import type { JlptLevel, PracticeQuestion, TargetForm, VocabularyItem } from "./types";

type ExamQuestionInput = {
  id: string;
  level: Extract<JlptLevel, "N1" | "N2" | "N3">;
  surface: string;
  reading: string;
  meaningZh: string;
  targetForm?: TargetForm;
  promptLabel: string;
  instructionZh: string;
  promptText: string;
  promptContextZh: string;
  expectedAnswer: string;
  options: string[];
  explanation: string;
};

export const examStyleQuestions: PracticeQuestion[] = [
  examQuestion({
    id: "n2-grammar-nitomonatte",
    level: "N2",
    surface: "に伴って",
    reading: "にともなって",
    meaningZh: "隨著、伴隨",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：選最符合前後關係的文法。",
    promptText: "産業の発展 ___、地域の雇用環境も大きく変化した。",
    promptContextZh: "隨著產業發展，地方的就業環境也大幅改變。",
    expectedAnswer: "に伴って",
    options: ["に伴って", "によると", "に限って", "に対して"],
    explanation: "「Aに伴ってB」表示 B 隨著 A 的變化一起發生。這裡是產業發展帶動雇用環境變化。"
  }),
  examQuestion({
    id: "n2-grammar-naikotoniwa",
    level: "N2",
    surface: "ないことには",
    reading: "ないことには",
    meaningZh: "若不...就無法...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意後句的「判斷できない」。",
    promptText: "実際に現場を見てみ ___、原因は判断できない。",
    promptContextZh: "沒有實際看現場，就無法判斷原因。",
    expectedAnswer: "ないことには",
    options: ["ないことには", "ないものなら", "ないどころか", "ない限りでは"],
    explanation: "「Vないことには、...ない」表示前項若不成立，後項就無法成立。後句的「できない」是線索。"
  }),
  examQuestion({
    id: "n2-grammar-womegutte",
    level: "N2",
    surface: "をめぐって",
    reading: "をめぐって",
    meaningZh: "圍繞、針對",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：判斷議論的主題。",
    promptText: "新しい評価制度の導入 ___、社内で意見が分かれている。",
    promptContextZh: "公司內部圍繞新評價制度的導入意見分歧。",
    expectedAnswer: "をめぐって",
    options: ["をめぐって", "をこめて", "を問わず", "をはじめ"],
    explanation: "「Aをめぐって」表示以 A 為中心產生議論、對立或問題。後面的「意見が分かれている」很典型。"
  }),
  examQuestion({
    id: "n2-grammar-kanenai",
    level: "N2",
    surface: "かねない",
    reading: "かねない",
    meaningZh: "有可能造成壞結果",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意負面結果的可能性。",
    promptText: "情報管理を怠れば、会社の信用を失い ___。",
    promptContextZh: "若疏忽資訊管理，可能失去公司信用。",
    expectedAnswer: "かねない",
    options: ["かねない", "きれない", "かけない", "がたい"],
    explanation: "「Vます形 + かねない」表示可能發生不好的結果。這裡的壞結果是「信用を失う」。"
  }),
  examQuestion({
    id: "n2-grammar-zaruwoenai",
    level: "N2",
    surface: "ざるを得ない",
    reading: "ざるをえない",
    meaningZh: "不得不",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：選被迫接受的表現。",
    promptText: "十分な資料がそろっていないため、結論を見送ら ___。",
    promptContextZh: "因為資料不足，不得不暫緩結論。",
    expectedAnswer: "ざるを得ない",
    options: ["ざるを得ない", "ないではいられない", "ずにはおかない", "かねない"],
    explanation: "「Vない形去ない + ざるを得ない」表示沒有其他選擇，只能那樣做。"
  }),
  examQuestion({
    id: "n2-grammar-nisakidatte",
    level: "N2",
    surface: "に先立って",
    reading: "にさきだって",
    meaningZh: "在...之前",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：判斷正式流程的前後順序。",
    promptText: "記者会見 ___、関係者に資料が配布された。",
    promptContextZh: "在記者會之前，資料已發給相關人士。",
    expectedAnswer: "に先立って",
    options: ["に先立って", "に応じて", "に反して", "に沿って"],
    explanation: "「Aに先立ってB」表示 B 在 A 之前先進行，常見於正式活動、發表、會議。"
  }),
  examQuestion({
    id: "n2-grammar-nimokakawarazu",
    level: "N2",
    surface: "にもかかわらず",
    reading: "にもかかわらず",
    meaningZh: "儘管、雖然",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意前後句的逆接。",
    promptText: "大雨 ___、説明会には多くの参加者が集まった。",
    promptContextZh: "儘管下大雨，說明會仍聚集了許多參加者。",
    expectedAnswer: "にもかかわらず",
    options: ["にもかかわらず", "にしたがって", "に限って", "にわたって"],
    explanation: "「AにもかかわらずB」表示 A 的情況下通常不會 B，但實際上卻 B。"
  }),
  examQuestion({
    id: "n2-text-ippoude",
    level: "N2",
    surface: "一方で",
    reading: "いっぽうで",
    meaningZh: "另一方面",
    promptLabel: "N2 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "電子申請は手続きの時間を短縮できる。___、高齢者には操作が難しいという声もある。",
    promptContextZh: "前句說優點，後句提出另一面向的問題。",
    expectedAnswer: "一方で",
    options: ["一方で", "そのため", "たとえば", "つまり"],
    explanation: "前後不是因果或換言，而是優點與課題的對比，所以用「一方で」。"
  }),
  examQuestion({
    id: "n2-order-yosoku-shigatai",
    level: "N2",
    surface: "しがたい",
    reading: "しがたい",
    meaningZh: "難以...",
    targetForm: "desiderative",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［専門家でさえ / 予測しがたい / ほど / 市場の変化が / 速い］",
    promptContextZh: "市場變化快到連專家都難以預測。",
    expectedAnswer: "専門家でさえ予測しがたいほど市場の変化が速い",
    options: [
      "専門家でさえ予測しがたいほど市場の変化が速い",
      "市場の変化が専門家でさえほど予測しがたい速い",
      "専門家ほど市場の変化が速いでさえ予測しがたい",
      "予測しがたい市場でさえ専門家の変化がほど速い"
    ],
    explanation: "「AほどB」表示程度；「専門家でさえ」放在「予測しがたい」前，強調連專家也難以預測。"
  }),
  examQuestion({
    id: "n2-order-zaruwoenai",
    level: "N2",
    surface: "ざるを得ない",
    reading: "ざるをえない",
    meaningZh: "不得不",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：注意「ため」造成的被迫選擇。",
    promptText: "［安全上の問題が / 見つかったため / 計画を / 変更せざるを得ない］",
    promptContextZh: "因為發現安全問題，不得不改變計畫。",
    expectedAnswer: "安全上の問題が見つかったため計画を変更せざるを得ない",
    options: [
      "安全上の問題が見つかったため計画を変更せざるを得ない",
      "計画を安全上の問題が変更せざるを得ない見つかったため",
      "見つかったため計画が安全上の問題を変更せざるを得ない",
      "安全上の問題を計画が見つかったため変更せざるを得ない"
    ],
    explanation: "原因句「安全上の問題が見つかったため」在前，後句接「計画を変更せざるを得ない」。"
  }),
  examQuestion({
    id: "n1-grammar-toaimatte",
    level: "N1",
    surface: "と相まって",
    reading: "とあいまって",
    meaningZh: "與...相互作用、加上...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選表示兩個因素相互作用的文法。",
    promptText: "独自の技術が丁寧な接客 ___、この店の評価を高めている。",
    promptContextZh: "獨家技術加上細緻接待，共同提高了店的評價。",
    expectedAnswer: "と相まって",
    options: ["と相まって", "に先立って", "を問わず", "に反して"],
    explanation: "「AがBと相まってC」表示 A 與 B 互相配合、共同造成 C。"
  }),
  examQuestion({
    id: "n1-grammar-yoginaku",
    level: "N1",
    surface: "を余儀なくされる",
    reading: "をよぎなくされる",
    meaningZh: "被迫...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選被外在因素迫使的表現。",
    promptText: "台風の影響で、主催者はイベントの中止 ___。",
    promptContextZh: "因颱風影響，主辦方被迫取消活動。",
    expectedAnswer: "を余儀なくされた",
    options: ["を余儀なくされた", "をものともせず", "にたえなかった", "に即していた"],
    explanation: "「Nを余儀なくされる」表示被外在情況逼得不得不做某事。這裡是被迫取消。"
  }),
  examQuestion({
    id: "n1-grammar-nakushitewa",
    level: "N1",
    surface: "なくしては",
    reading: "なくしては",
    meaningZh: "沒有...就不能...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：注意後句的否定判斷。",
    promptText: "住民の理解 ___、この計画を進めることはできない。",
    promptContextZh: "沒有居民理解，就無法推進這項計畫。",
    expectedAnswer: "なくしては",
    options: ["なくしては", "にしては", "からして", "をもって"],
    explanation: "「Nなくしては...ない」表示沒有 N 就無法成立。後句「できない」是重要線索。"
  }),
  examQuestion({
    id: "n1-grammar-nisokushite",
    level: "N1",
    surface: "に即して",
    reading: "にそくして",
    meaningZh: "依據、符合",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選符合實際情況的表現。",
    promptText: "現場の実情 ___、運用ルールを見直す必要がある。",
    promptContextZh: "需要依據現場實際情況重新檢討運用規則。",
    expectedAnswer: "に即して",
    options: ["に即して", "に至って", "にひきかえ", "を皮切りに"],
    explanation: "「Nに即して」表示依據 N、配合 N。這裡是依照現場實情調整規則。"
  }),
  examQuestion({
    id: "n1-grammar-mademonai",
    level: "N1",
    surface: "までもない",
    reading: "までもない",
    meaningZh: "沒必要到...程度",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：判斷「沒必要特地說明」。",
    promptText: "この結果が何を意味するかは、改めて説明する ___。",
    promptContextZh: "這個結果代表什麼，不用特別再說明。",
    expectedAnswer: "までもない",
    options: ["までもない", "にたえない", "にすぎない", "かいがない"],
    explanation: "「V辞書形 + までもない」表示沒有必要特地做某事。"
  }),
  examQuestion({
    id: "n1-grammar-beku",
    level: "N1",
    surface: "べく",
    reading: "べく",
    meaningZh: "為了...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選正式書面語的目的表現。",
    promptText: "原因を明らかにす ___、専門チームが設置された。",
    promptContextZh: "為了查明原因，成立了專門小組。",
    expectedAnswer: "べく",
    options: ["べく", "ものの", "ところを", "ばかりに"],
    explanation: "「V辞書形 + べく」是較正式的目的表現。注意「する」接「べく」常寫成「すべく」。"
  }),
  examQuestion({
    id: "n1-grammar-wokikkirini",
    level: "N1",
    surface: "を皮切りに",
    reading: "をかわきりに",
    meaningZh: "以...為開端",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選表示一連串活動開端的文法。",
    promptText: "東京での発表会 ___、全国各地で説明会が開かれる予定だ。",
    promptContextZh: "以東京發表會為開端，預計在全國各地舉辦說明會。",
    expectedAnswer: "を皮切りに",
    options: ["を皮切りに", "を余儀なく", "に至って", "にたえず"],
    explanation: "「Aを皮切りにB」表示以 A 為開端，之後 B 陸續展開。"
  }),
  examQuestion({
    id: "n1-grammar-toatte",
    level: "N1",
    surface: "とあって",
    reading: "とあって",
    meaningZh: "因為是...所以",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選說明特殊情況造成結果的文法。",
    promptText: "連休初日 ___、駅は朝から多くの旅行客で混雑していた。",
    promptContextZh: "因為是連假第一天，車站一早就擠滿旅客。",
    expectedAnswer: "とあって",
    options: ["とあって", "といえども", "ときたら", "とはいえ"],
    explanation: "「AとあってB」表示因為 A 這個特殊狀況，所以自然產生 B 的結果。"
  }),
  examQuestion({
    id: "n1-text-tadashi",
    level: "N1",
    surface: "ただし",
    reading: "ただし",
    meaningZh: "但是、但有條件",
    promptLabel: "N1 文章脈絡",
    instructionZh: "短文脈絡：選能補上限制條件的接續語。",
    promptText: "本制度は原則として全社員が利用できる。___、試用期間中の社員は対象外とする。",
    promptContextZh: "前句說原則，後句追加例外限制。",
    expectedAnswer: "ただし",
    options: ["ただし", "したがって", "それどころか", "ちなみに"],
    explanation: "後句不是結論、補充閒談或反駁，而是加上限制條件，所以用「ただし」。"
  }),
  examQuestion({
    id: "n1-order-nakushitewa",
    level: "N1",
    surface: "なくしては",
    reading: "なくしては",
    meaningZh: "沒有...就不能...",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：注意否定條件與後句否定的呼應。",
    promptText: "［長期的な視点 / なくしては / 持続的な成長は / 望めない］",
    promptContextZh: "沒有長期觀點，就無法期待持續成長。",
    expectedAnswer: "長期的な視点なくしては持続的な成長は望めない",
    options: [
      "長期的な視点なくしては持続的な成長は望めない",
      "持続的な成長はなくしては長期的な視点望めない",
      "長期的な視点は持続的な成長なくしては望めない",
      "望めない長期的な視点なくしては持続的な成長は"
    ],
    explanation: "「Nなくしては...ない」是一組，名詞「長期的な視点」要直接接「なくしては」。"
  }),
  examQuestion({
    id: "n1-order-wokikkirini",
    level: "N1",
    surface: "を皮切りに",
    reading: "をかわきりに",
    meaningZh: "以...為開端",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：注意開端與後續展開。",
    promptText: "［大阪での公演を / 皮切りに / 全国ツアーが / 始まった］",
    promptContextZh: "以大阪公演為開端，全國巡演開始。",
    expectedAnswer: "大阪での公演を皮切りに全国ツアーが始まった",
    options: [
      "大阪での公演を皮切りに全国ツアーが始まった",
      "全国ツアーを大阪での公演が皮切りに始まった",
      "大阪での公演が全国ツアーを始まった皮切りに",
      "皮切りに全国ツアーを大阪での公演が始まった"
    ],
    explanation: "「Aを皮切りにBが始まる」表示以 A 為第一步，B 接著展開。"
  }),
  examQuestion({
    id: "n3-grammar-yoninaru",
    level: "N3",
    surface: "ようになる",
    reading: "ようになる",
    meaningZh: "變得（能夠/習慣於）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：選表示「能力／習慣的轉變」的文法。",
    promptText: "毎日 練習したので、自転車に乗れる ___ なった。",
    promptContextZh: "每天練習，結果變得會騎自行車了。",
    expectedAnswer: "ように",
    options: ["ように", "ことに", "ために", "ようで"],
    explanation: "「Vる/可能形 + ようになる」表示「（從不會到會、從不做到做）變化的結果」。「ことになる」是外在的決定；「ために」表目的；「ようで」是「好像」。"
  }),
  examQuestion({
    id: "n3-grammar-kotonisuru",
    level: "N3",
    surface: "ことにする",
    reading: "ことにする",
    meaningZh: "決定（主動）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：注意是「我自己」的決定。",
    promptText: "体に悪いから、たばこをやめる ___ 。",
    promptContextZh: "對身體不好，我決定戒菸了。",
    expectedAnswer: "ことにした",
    options: ["ことにした", "ようにした", "ことになった", "ようになった"],
    explanation: "「Vる + ことにする」表示「自己的決定」。「ことになる」是外在情況/規定造成的結果；「ようにする」是「努力做到」。"
  }),
  examQuestion({
    id: "n3-grammar-tsumori",
    level: "N3",
    surface: "つもり",
    reading: "つもり",
    meaningZh: "打算",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：主觀打算。",
    promptText: "夏休みに国へ帰る ___ です。",
    promptContextZh: "暑假打算回國。",
    expectedAnswer: "つもり",
    options: ["つもり", "ばかり", "はず", "ところ"],
    explanation: "「Vる + つもり」表示主觀的打算。「ばかり」表示「剛剛...完」；「はず」表示客觀推測「應該」；「ところ」表動作階段。"
  }),
  examQuestion({
    id: "n3-grammar-bayokatta",
    level: "N3",
    surface: "ばよかった",
    reading: "ばよかった",
    meaningZh: "如果...就好了（後悔）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示對過去未做的事的後悔。",
    promptText: "雨に降られた。傘を持ってくれば ___ 。",
    promptContextZh: "被雨淋了，要是有帶傘就好了。",
    expectedAnswer: "よかった",
    options: ["よかった", "ほしかった", "いけなかった", "ならなかった"],
    explanation: "「Vば + よかった」表示對過去未做的事感到後悔。"
  }),
  examQuestion({
    id: "n3-grammar-tahougaii",
    level: "N3",
    surface: "たほうがいい",
    reading: "たほうがいい",
    meaningZh: "...比較好（建議）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：對對方的建議。",
    promptText: "熱がありますね。早く病院へ行った ___ 。",
    promptContextZh: "你發燒了呢，早點去醫院比較好。",
    expectedAnswer: "ほうがいい",
    options: ["ほうがいい", "ことがある", "つもりだ", "おかげだ"],
    explanation: "「Vた + ほうがいい」表示對對方的建議。"
  }),
  examQuestion({
    id: "n3-grammar-nakutehaikenai",
    level: "N3",
    surface: "なくてはいけない",
    reading: "なくてはいけない",
    meaningZh: "必須",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示義務。",
    promptText: "明日までにこのレポートを ___ いけない。",
    promptContextZh: "明天之前必須交這份報告。",
    expectedAnswer: "出さなくては",
    options: ["出さなくては", "出さなくても", "出さないで", "出すことが"],
    explanation: "「Vない形 + なくてはいけない」表示「必須做」的義務。「なくてもいい」相反，表示不需要做。"
  }),
  examQuestion({
    id: "n3-grammar-teshimau",
    level: "N3",
    surface: "てしまう",
    reading: "てしまう",
    meaningZh: "（不小心）做了",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示後悔／意外完成。",
    promptText: "大事な約束を忘れて ___ 、本当にすみません。",
    promptContextZh: "把重要的約定忘了，真的很抱歉。",
    expectedAnswer: "しまって",
    options: ["しまって", "おいて", "みて", "あって"],
    explanation: "「Vて + しまう」表示完成或表達遺憾／後悔。「ておく」表示為將來做準備；「てみる」表示嘗試。"
  }),
  examQuestion({
    id: "n3-grammar-teoku",
    level: "N3",
    surface: "ておく",
    reading: "ておく",
    meaningZh: "事先做好",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：為將來準備。",
    promptText: "明日の会議の前に、資料をコピーし ___ ます。",
    promptContextZh: "明天會議前先把資料影印起來。",
    expectedAnswer: "ておき",
    options: ["ておき", "てしまい", "てあり", "ていき"],
    explanation: "「Vて + おく」表示為將來做準備。「てある」是已被人放置的狀態；「てしまう」是完了／遺憾。"
  }),
  examQuestion({
    id: "n3-grammar-nagara",
    level: "N3",
    surface: "ながら",
    reading: "ながら",
    meaningZh: "一邊...一邊...",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：同一個人同時做兩件事。",
    promptText: "音楽を聞き ___ 、勉強するのが好きだ。",
    promptContextZh: "我喜歡邊聽音樂邊讀書。",
    expectedAnswer: "ながら",
    options: ["ながら", "あいだ", "うちに", "ばかり"],
    explanation: "「Vます形 + ながら」表示同一個人同時做兩件事。「あいだ」「うちに」是時間範圍／不同主語。"
  }),
  examQuestion({
    id: "n3-grammar-teirutokoro",
    level: "N3",
    surface: "ているところ",
    reading: "ているところ",
    meaningZh: "正在...中",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示動作正在進行的瞬間。",
    promptText: "今、ご飯を ___ ので、後で電話します。",
    promptContextZh: "現在正在吃飯，等等再打電話。",
    expectedAnswer: "食べているところな",
    options: ["食べているところな", "食べたところな", "食べたばかりな", "食べるところな"],
    explanation: "「Vている + ところだ」表示「動作正在進行中」；「Vたところだ」表示「剛剛做完」；「Vるところだ」是「正要做」；「Vたばかりだ」是「剛剛...不久」。"
  }),
  examQuestion({
    id: "n2-grammar-monono",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然...但...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：前後句子有逆接關係。",
    promptText: "ダイエットを始めた ___ 、なかなか体重が減らない。",
    promptContextZh: "雖然開始減肥了，但體重一直沒減少。",
    expectedAnswer: "ものの",
    options: ["ものの", "ことに", "ものを", "ように"],
    explanation: "「A ものの、B」表示「雖然 A，但是 B」，書面語逆接。「ものを」帶後悔語氣「明明可以...卻沒」。"
  }),
  examQuestion({
    id: "n2-grammar-karakoso",
    level: "N2",
    surface: "からこそ",
    reading: "からこそ",
    meaningZh: "正因為",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：強調唯一的理由。",
    promptText: "君のことを思っている ___ 、こんなに厳しく言うのだ。",
    promptContextZh: "正因為為了你著想，才這麼嚴格地說。",
    expectedAnswer: "からこそ",
    options: ["からこそ", "からといって", "からには", "からして"],
    explanation: "「A からこそ B」強調「正是因為 A」的唯一原因。「からといって」是「不能因為...就」；「からには」是「既然...就應該」。"
  }),
  examQuestion({
    id: "n2-grammar-niatatte",
    level: "N2",
    surface: "にあたって",
    reading: "にあたって",
    meaningZh: "在...之際",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「在某個重要關頭」。",
    promptText: "新しいプロジェクトを始める ___ 、関係者を集めて打ち合わせをした。",
    promptContextZh: "在開始新項目之際，召集了相關人員開會。",
    expectedAnswer: "にあたって",
    options: ["にあたって", "について", "に対して", "に従って"],
    explanation: "「Vる/N にあたって」用於正式場合，表示「在某重要時刻」。「について」是「關於」；「に対して」是「對於」；「に従って」是「隨著」。"
  }),
  examQuestion({
    id: "n2-grammar-nikanshite",
    level: "N2",
    surface: "に関して",
    reading: "にかんして",
    meaningZh: "關於",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：選正式的「關於」。",
    promptText: "この問題 ___ 、皆さんのご意見を伺いたい。",
    promptContextZh: "關於這個問題，想聽聽大家的意見。",
    expectedAnswer: "に関して",
    options: ["に関して", "に伴って", "に応じて", "に反して"],
    explanation: "「Nに関して」表示「關於 N」，較「について」正式。「に伴って」是「隨著」；「に応じて」是「依照」；「に反して」是「與...相反」。"
  }),
  examQuestion({
    id: "n2-grammar-nishitewa",
    level: "N2",
    surface: "にしては",
    reading: "にしては",
    meaningZh: "作為...來說（偏離預期）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意前後落差。",
    promptText: "彼は日本に来てまだ三か月 ___ 、日本語が上手だ。",
    promptContextZh: "他來日本才三個月，日語就講得很好。",
    expectedAnswer: "にしては",
    options: ["にしては", "にしても", "にしたら", "について"],
    explanation: "「N にしては」表示「以 N 來說（偏離預期）」。「にしても」是「即使...也」；「にしたら」是「站在 N 的立場」。"
  }),
  examQuestion({
    id: "n2-grammar-dokoroka",
    level: "N2",
    surface: "どころか",
    reading: "どころか",
    meaningZh: "別說...連...都...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示強烈否定／反向預期。",
    promptText: "宿題は終わる ___ 、まだ半分もやっていない。",
    promptContextZh: "別說作業沒寫完，連一半都還沒做。",
    expectedAnswer: "どころか",
    options: ["どころか", "ばかりか", "うえに", "に加えて"],
    explanation: "「A どころか B」表示「別說 A，連 B 都...」的強烈反向。「ばかりか」是「不只 A，B 也」(正向累加)；「うえに / に加えて」也是累加。"
  }),
  examQuestion({
    id: "n2-grammar-mai",
    level: "N2",
    surface: "まい",
    reading: "まい",
    meaningZh: "絕不（強烈否定意志）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：書面語的強烈否定意志。",
    promptText: "あんな店には二度と行く ___ と心に決めた。",
    promptContextZh: "我下定決心，再也不去那種店了。",
    expectedAnswer: "まい",
    options: ["まい", "ない", "なくて", "ぬ"]
,
    explanation: "「Vる + まい」(一類動詞辭書形；二類動詞「るまい / ようまい」)表示「絕對不做」的強烈決心，書面正式。「ぬ」是文語否定但無強烈意志。"
  }),
  examQuestion({
    id: "n2-grammar-bakarika",
    level: "N2",
    surface: "ばかりか",
    reading: "ばかりか",
    meaningZh: "不只...連...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：累加表現。",
    promptText: "彼は日本語 ___ 、中国語も韓国語も流暢に話せる。",
    promptContextZh: "他不只會說日語，連中文、韓文都很流利。",
    expectedAnswer: "ばかりか",
    options: ["ばかりか", "ばかりで", "ばかりに", "ばかりだ"],
    explanation: "「A ばかりか B」表示「不只 A，連 B 也」。「ばかりに」是「就因為...才」(負面結果)；「ばかりで」是「只...而已」。"
  }),
  examQuestion({
    id: "n2-grammar-monodakara",
    level: "N2",
    surface: "ものだから",
    reading: "ものだから",
    meaningZh: "因為...（辯解）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：辯解語氣的原因。",
    promptText: "外があまりにも寒かった ___ 、つい厚着をしてしまった。",
    promptContextZh: "因為外面實在太冷了，不知不覺就穿了很厚。",
    expectedAnswer: "ものだから",
    options: ["ものだから", "ものなら", "ものの", "ものか"],
    explanation: "「A ものだから B」用來解釋原因，常帶辯解語氣。「ものなら」表示假設；「ものの」是「雖然」；「ものか」是反問「怎麼可能」。"
  }),
  examQuestion({
    id: "n2-grammar-uede",
    level: "N2",
    surface: "うえで",
    reading: "うえで",
    meaningZh: "在...之後（再）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「先做某事再下一步」的正式表現。",
    promptText: "資料をよく読んだ ___ で、ご判断ください。",
    promptContextZh: "請仔細閱讀資料之後再判斷。",
    expectedAnswer: "うえ",
    options: ["うえ", "ばかり", "ところ", "そば"],
    explanation: "「Vた + うえで」表示「在 V 之後（再進入下一步）」，正式。「ばかり」是「剛剛」；「ところ」是「動作階段」；「そば」是「N 旁邊」。"
  }),
  examQuestion({
    id: "n1-grammar-nimomashite",
    level: "N1",
    surface: "にもまして",
    reading: "にもまして",
    meaningZh: "比...更...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「比預期/比過去更...」。",
    promptText: "今年は例年 ___ 多くの観光客がこの町を訪れている。",
    promptContextZh: "今年比往年湧入更多遊客造訪這座城市。",
    expectedAnswer: "にもまして",
    options: ["にもまして", "ともなく", "にあって", "を限りに"],
    explanation: "「N にもまして」表示「比 N 還更...」。「ともなく」是「無意間」；「にあって」是「處於 N 的情況」；「を限りに」是「以 N 為界」。"
  }),
  examQuestion({
    id: "n1-grammar-tobakarini",
    level: "N1",
    surface: "とばかりに",
    reading: "とばかりに",
    meaningZh: "彷彿在說...似的",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：戲劇化的表現。",
    promptText: "ベルが鳴ると、彼はもう待てない ___ 教室を飛び出した。",
    promptContextZh: "鈴聲一響，他彷彿再也等不及似的衝出教室。",
    expectedAnswer: "とばかりに",
    options: ["とばかりに", "とともに", "とあって", "といえども"],
    explanation: "「~とばかりに」表示「彷彿在說/做出...的姿態」，戲劇化描寫。「とともに」是「同時／隨著」；「とあって」是「因為是...所以」。"
  }),
  examQuestion({
    id: "n1-grammar-tomonareba",
    level: "N1",
    surface: "ともなれば",
    reading: "ともなれば",
    meaningZh: "一旦成為...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「達到某地位／階段時必然...」。",
    promptText: "管理職 ___ 、責任の重さも倍になる。",
    promptContextZh: "一旦成為管理階層，責任也加倍。",
    expectedAnswer: "ともなれば",
    options: ["ともなれば", "ともあれ", "ともなく", "ときたら"],
    explanation: "「N ともなれば」表示「達到 N 階段時，自然會...」。「ともあれ」是「無論如何」；「ともなく」是「無意間」；「ときたら」是「說到 N（負面評論）」。"
  }),
  examQuestion({
    id: "n1-grammar-deare",
    level: "N1",
    surface: "であれ",
    reading: "であれ",
    meaningZh: "無論是...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「無論 N 為何」。",
    promptText: "理由が何 ___ 、約束を破ることは許されない。",
    promptContextZh: "無論理由是什麼，違反約定都不可原諒。",
    expectedAnswer: "であれ",
    options: ["であれ", "にしては", "ながら", "といえども"],
    explanation: "「N であれ」表示「無論是 N」，正式書面。「といえども」是「即便是 N」(讓步)；「にしては」是「以 N 來說」(偏離)；「ながら」是「同時/雖然」。"
  }),
  examQuestion({
    id: "n1-grammar-tomoarou",
    level: "N1",
    surface: "ともあろう",
    reading: "ともあろう",
    meaningZh: "身為...卻...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：帶失望／批判語氣。",
    promptText: "教育者 ___ ものが、そんな不正を働くとは情けない。",
    promptContextZh: "身為教育者卻做出那種不正行為，實在可悲。",
    expectedAnswer: "ともあろう",
    options: ["ともあろう", "ともなれば", "ともなく", "ともあれ"],
    explanation: "「N ともあろうもの」表示「身為 N 這種身分的人卻...」，帶失望/批判語氣。"
  }),
  examQuestion({
    id: "n1-grammar-kitteno",
    level: "N1",
    surface: "きっての",
    reading: "きっての",
    meaningZh: "...當中數一數二的",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「N 中的第一／最頂尖」。",
    promptText: "彼はこの業界 ___ 名医として広く知られている。",
    promptContextZh: "他作為這個業界數一數二的名醫廣為人知。",
    expectedAnswer: "きっての",
    options: ["きっての", "あっての", "なくしての", "ながらの"],
    explanation: "「N + きっての」表示「N 中最為...」，正面評價。「あっての」是「有了 N 才...」；「なくしては」是「沒有 N 就不...」。"
  }),
  examQuestion({
    id: "n1-grammar-nagaranishite",
    level: "N1",
    surface: "ながらにして",
    reading: "ながらにして",
    meaningZh: "處於...就能...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：「不必離開某狀態就能...」。",
    promptText: "インターネットのおかげで、家に居 ___ 世界中のニュースが手に入る。",
    promptContextZh: "拜網路所賜，待在家就能取得全球資訊。",
    expectedAnswer: "ながらにして",
    options: ["ながらにして", "ながらも", "つつも", "つつあって"],
    explanation: "「居ながらにして」是固定表現，表示「不必離開（家／當下）就能...」。「ながらも」是「雖然」；「つつも」近似ながらも；「つつあって」是「持續...當中」。"
  }),
  examQuestion({
    id: "n1-grammar-nishite",
    level: "N1",
    surface: "にして",
    reading: "にして",
    meaningZh: "在...這個時刻／身分",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：強調達到某階段才...。",
    promptText: "あの傑作は彼が五十歳 ___ ようやく完成させたものだ。",
    promptContextZh: "那部傑作是他到了五十歲才終於完成的。",
    expectedAnswer: "にして",
    options: ["にして", "にあって", "ともなく", "ながらも"],
    explanation: "「N にして」表示「在 N 這個（年齡/階段/身分）時，才...」，較正式。「にあって」是「處於 N」；「ながらも」是「雖然」。"
  }),
  examQuestion({
    id: "n1-grammar-kagirida",
    level: "N1",
    surface: "限りだ",
    reading: "かぎりだ",
    meaningZh: "極為...（感情）",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：書面表達極致情感。",
    promptText: "家族と過ごせる時間が短くて、寂しい ___ だ。",
    promptContextZh: "能和家人共處的時間太短，非常寂寞。",
    expectedAnswer: "限り",
    options: ["限り", "極み", "次第", "気味"],
    explanation: "「い形容詞 + 限りだ」表示「至極...的感情」。「極み」常接名詞（贅沢の極み）；「次第」是「依照」；「気味」是「有點...的感覺」。"
  }),
  examQuestion({
    id: "n1-grammar-noitari",
    level: "N1",
    surface: "の至り",
    reading: "のいたり",
    meaningZh: "...之至（深感...）",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：用於致辭、書信的正式感情表達。",
    promptText: "皆様のご支援を賜り、感謝 ___ です。",
    promptContextZh: "承蒙各位的支持，深感感謝。",
    expectedAnswer: "の至り",
    options: ["の至り", "の極み", "の限り", "の余り"],
    explanation: "「N の至り」常用於 感謝・恐縮・光栄 等正式致辭。「の極み」也表示極致但多用「贅沢／疲労」等；「の限り」較少這種用法；「の余り」是「太過...而...」。"
  })
];

export function buildExamQuestionPool(level: JlptLevel | "all" = "all"): PracticeQuestion[] {
  if (level === "N1" || level === "N2" || level === "N3") {
    return examStyleQuestions.filter((question) => question.vocabulary.level === level);
  }

  return examStyleQuestions;
}

function examQuestion(input: ExamQuestionInput): PracticeQuestion {
  return {
    id: input.id,
    vocabulary: {
      id: input.id,
      surface: input.surface,
      reading: input.reading,
      meaningZh: input.meaningZh,
      partOfSpeech: "noun",
      group: null,
      lesson: null,
      tags: ["exam_style", input.level],
      examples: [{ japanese: input.promptText.replace("___", input.expectedAnswer), meaningZh: input.promptContextZh }],
      level: input.level
    },
    targetForm: input.targetForm ?? "reading",
    expectedAnswers: [input.expectedAnswer],
    explanation: input.explanation,
    promptLabel: input.promptLabel,
    promptText: input.promptText,
    promptContextZh: input.promptContextZh,
    instructionZh: input.instructionZh,
    options: input.options
  };
}
