import type { JlptLevel, PracticeQuestion, TargetForm, VocabularyItem } from "./types";

type ExamQuestionInput = {
  id: string;
  level: Extract<JlptLevel, "N1" | "N2" | "N3">;
  surface: string;
  reading: string;
  meaningZh: string;
  targetForm?: TargetForm;
  promptLabel: string;
  instructionZh: string;
  promptText: string;
  promptContextZh: string;
  expectedAnswer: string;
  options: string[];
  explanation: string;
  /**
   * Override the auto-generated example sentence. Needed for question types
   * (e.g. 用法 / 言い換え類義) where the prompt is an instruction or the
   * target phrase rather than a sentence with a blank.
   */
  exampleJapanese?: string;
  exampleMeaningZh?: string;
};

export const examStyleQuestions: PracticeQuestion[] = [
  examQuestion({
    id: "n2-grammar-nitomonatte",
    level: "N2",
    surface: "に伴って",
    reading: "にともなって",
    meaningZh: "隨著、伴隨",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：選最符合前後關係的文法。",
    promptText: "産業の発展 ___、地域の雇用環境も大きく変化した。",
    promptContextZh: "隨著產業發展，地方的就業環境也大幅改變。",
    expectedAnswer: "に伴って",
    options: ["に伴って", "によると", "に限って", "に対して"],
    explanation: "「Aに伴ってB」表示 B 隨著 A 的變化一起發生。這裡是產業發展帶動雇用環境變化。"
  }),
  examQuestion({
    id: "n2-grammar-naikotoniwa",
    level: "N2",
    surface: "ないことには",
    reading: "ないことには",
    meaningZh: "若不...就無法...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意後句的「判斷できない」。",
    promptText: "実際に現場を見てみ ___、原因は判断できない。",
    promptContextZh: "沒有實際看現場，就無法判斷原因。",
    expectedAnswer: "ないことには",
    options: ["ないことには", "ないものなら", "ないどころか", "ない限りでは"],
    explanation: "「Vないことには、...ない」表示前項若不成立，後項就無法成立。後句的「できない」是線索。"
  }),
  examQuestion({
    id: "n2-grammar-womegutte",
    level: "N2",
    surface: "をめぐって",
    reading: "をめぐって",
    meaningZh: "圍繞、針對",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：判斷議論的主題。",
    promptText: "新しい評価制度の導入 ___、社内で意見が分かれている。",
    promptContextZh: "公司內部圍繞新評價制度的導入意見分歧。",
    expectedAnswer: "をめぐって",
    options: ["をめぐって", "をこめて", "を問わず", "をはじめ"],
    explanation: "「Aをめぐって」表示以 A 為中心產生議論、對立或問題。後面的「意見が分かれている」很典型。"
  }),
  examQuestion({
    id: "n2-grammar-kanenai",
    level: "N2",
    surface: "かねない",
    reading: "かねない",
    meaningZh: "有可能造成壞結果",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意負面結果的可能性。",
    promptText: "情報管理を怠れば、会社の信用を失い ___。",
    promptContextZh: "若疏忽資訊管理，可能失去公司信用。",
    expectedAnswer: "かねない",
    options: ["かねない", "きれない", "かけない", "がたい"],
    explanation: "「Vます形 + かねない」表示可能發生不好的結果。這裡的壞結果是「信用を失う」。"
  }),
  examQuestion({
    id: "n2-grammar-zaruwoenai",
    level: "N2",
    surface: "ざるを得ない",
    reading: "ざるをえない",
    meaningZh: "不得不",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：選被迫接受的表現。",
    promptText: "十分な資料がそろっていないため、結論を見送ら ___。",
    promptContextZh: "因為資料不足，不得不暫緩結論。",
    expectedAnswer: "ざるを得ない",
    options: ["ざるを得ない", "ないではいられない", "ずにはおかない", "かねない"],
    explanation: "「Vない形去ない + ざるを得ない」表示沒有其他選擇，只能那樣做。"
  }),
  examQuestion({
    id: "n2-grammar-nisakidatte",
    level: "N2",
    surface: "に先立って",
    reading: "にさきだって",
    meaningZh: "在...之前",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：判斷正式流程的前後順序。",
    promptText: "記者会見 ___、関係者に資料が配布された。",
    promptContextZh: "在記者會之前，資料已發給相關人士。",
    expectedAnswer: "に先立って",
    options: ["に先立って", "に応じて", "に反して", "に沿って"],
    explanation: "「Aに先立ってB」表示 B 在 A 之前先進行，常見於正式活動、發表、會議。"
  }),
  examQuestion({
    id: "n2-grammar-nimokakawarazu",
    level: "N2",
    surface: "にもかかわらず",
    reading: "にもかかわらず",
    meaningZh: "儘管、雖然",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意前後句的逆接。",
    promptText: "大雨 ___、説明会には多くの参加者が集まった。",
    promptContextZh: "儘管下大雨，說明會仍聚集了許多參加者。",
    expectedAnswer: "にもかかわらず",
    options: ["にもかかわらず", "にしたがって", "に限って", "にわたって"],
    explanation: "「AにもかかわらずB」表示 A 的情況下通常不會 B，但實際上卻 B。"
  }),
  examQuestion({
    id: "n2-text-ippoude",
    level: "N2",
    surface: "一方で",
    reading: "いっぽうで",
    meaningZh: "另一方面",
    promptLabel: "N2 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "電子申請は手続きの時間を短縮できる。___、高齢者には操作が難しいという声もある。",
    promptContextZh: "前句說優點，後句提出另一面向的問題。",
    expectedAnswer: "一方で",
    options: ["一方で", "そのため", "たとえば", "つまり"],
    explanation: "前後不是因果或換言，而是優點與課題的對比，所以用「一方で」。"
  }),
  examQuestion({
    id: "n2-order-yosoku-shigatai",
    level: "N2",
    surface: "しがたい",
    reading: "しがたい",
    meaningZh: "難以...",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［専門家でさえ / 予測しがたい / ほど / 市場の変化が / 速い］",
    promptContextZh: "市場變化快到連專家都難以預測。",
    expectedAnswer: "専門家でさえ予測しがたいほど市場の変化が速い",
    options: [
      "専門家でさえ予測しがたいほど市場の変化が速い",
      "市場の変化が専門家でさえほど予測しがたい速い",
      "専門家ほど市場の変化が速いでさえ予測しがたい",
      "予測しがたい市場でさえ専門家の変化がほど速い"
    ],
    explanation: "「AほどB」表示程度；「専門家でさえ」放在「予測しがたい」前，強調連專家也難以預測。"
  }),
  examQuestion({
    id: "n2-order-zaruwoenai",
    level: "N2",
    surface: "ざるを得ない",
    reading: "ざるをえない",
    meaningZh: "不得不",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：注意「ため」造成的被迫選擇。",
    promptText: "［安全上の問題が / 見つかったため / 計画を / 変更せざるを得ない］",
    promptContextZh: "因為發現安全問題，不得不改變計畫。",
    expectedAnswer: "安全上の問題が見つかったため計画を変更せざるを得ない",
    options: [
      "安全上の問題が見つかったため計画を変更せざるを得ない",
      "計画を安全上の問題が変更せざるを得ない見つかったため",
      "見つかったため計画が安全上の問題を変更せざるを得ない",
      "安全上の問題を計画が見つかったため変更せざるを得ない"
    ],
    explanation: "原因句「安全上の問題が見つかったため」在前，後句接「計画を変更せざるを得ない」。"
  }),
  examQuestion({
    id: "n1-grammar-toaimatte",
    level: "N1",
    surface: "と相まって",
    reading: "とあいまって",
    meaningZh: "與...相互作用、加上...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選表示兩個因素相互作用的文法。",
    promptText: "独自の技術が丁寧な接客 ___、この店の評価を高めている。",
    promptContextZh: "獨家技術加上細緻接待，共同提高了店的評價。",
    expectedAnswer: "と相まって",
    options: ["と相まって", "に先立って", "を問わず", "に反して"],
    explanation: "「AがBと相まってC」表示 A 與 B 互相配合、共同造成 C。"
  }),
  examQuestion({
    id: "n1-grammar-yoginaku",
    level: "N1",
    surface: "を余儀なくされる",
    reading: "をよぎなくされる",
    meaningZh: "被迫...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選被外在因素迫使的表現。",
    promptText: "台風の影響で、主催者はイベントの中止 ___。",
    promptContextZh: "因颱風影響，主辦方被迫取消活動。",
    expectedAnswer: "を余儀なくされた",
    options: ["を余儀なくされた", "をものともせず", "にたえなかった", "に即していた"],
    explanation: "「Nを余儀なくされる」表示被外在情況逼得不得不做某事。這裡是被迫取消。"
  }),
  examQuestion({
    id: "n1-grammar-nakushitewa",
    level: "N1",
    surface: "なくしては",
    reading: "なくしては",
    meaningZh: "沒有...就不能...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：注意後句的否定判斷。",
    promptText: "住民の理解 ___、この計画を進めることはできない。",
    promptContextZh: "沒有居民理解，就無法推進這項計畫。",
    expectedAnswer: "なくしては",
    options: ["なくしては", "にしては", "からして", "をもって"],
    explanation: "「Nなくしては...ない」表示沒有 N 就無法成立。後句「できない」是重要線索。"
  }),
  examQuestion({
    id: "n1-grammar-nisokushite",
    level: "N1",
    surface: "に即して",
    reading: "にそくして",
    meaningZh: "依據、符合",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選符合實際情況的表現。",
    promptText: "現場の実情 ___、運用ルールを見直す必要がある。",
    promptContextZh: "需要依據現場實際情況重新檢討運用規則。",
    expectedAnswer: "に即して",
    options: ["に即して", "に至って", "にひきかえ", "を皮切りに"],
    explanation: "「Nに即して」表示依據 N、配合 N。這裡是依照現場實情調整規則。"
  }),
  examQuestion({
    id: "n1-grammar-mademonai",
    level: "N1",
    surface: "までもない",
    reading: "までもない",
    meaningZh: "沒必要到...程度",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：判斷「沒必要特地說明」。",
    promptText: "この結果が何を意味するかは、改めて説明する ___。",
    promptContextZh: "這個結果代表什麼，不用特別再說明。",
    expectedAnswer: "までもない",
    options: ["までもない", "にたえない", "にすぎない", "かいがない"],
    explanation: "「V辞書形 + までもない」表示沒有必要特地做某事。"
  }),
  examQuestion({
    id: "n1-grammar-beku",
    level: "N1",
    surface: "べく",
    reading: "べく",
    meaningZh: "為了...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選正式書面語的目的表現。",
    promptText: "原因を明らかにす ___、専門チームが設置された。",
    promptContextZh: "為了查明原因，成立了專門小組。",
    expectedAnswer: "べく",
    options: ["べく", "ものの", "ところを", "ばかりに"],
    explanation: "「V辞書形 + べく」是較正式的目的表現。注意「する」接「べく」常寫成「すべく」。"
  }),
  examQuestion({
    id: "n1-grammar-wokikkirini",
    level: "N1",
    surface: "を皮切りに",
    reading: "をかわきりに",
    meaningZh: "以...為開端",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選表示一連串活動開端的文法。",
    promptText: "東京での発表会 ___、全国各地で説明会が開かれる予定だ。",
    promptContextZh: "以東京發表會為開端，預計在全國各地舉辦說明會。",
    expectedAnswer: "を皮切りに",
    options: ["を皮切りに", "を余儀なく", "に至って", "にたえず"],
    explanation: "「Aを皮切りにB」表示以 A 為開端，之後 B 陸續展開。"
  }),
  examQuestion({
    id: "n1-grammar-toatte",
    level: "N1",
    surface: "とあって",
    reading: "とあって",
    meaningZh: "因為是...所以",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：選說明特殊情況造成結果的文法。",
    promptText: "連休初日 ___、駅は朝から多くの旅行客で混雑していた。",
    promptContextZh: "因為是連假第一天，車站一早就擠滿旅客。",
    expectedAnswer: "とあって",
    options: ["とあって", "といえども", "ときたら", "とはいえ"],
    explanation: "「AとあってB」表示因為 A 這個特殊狀況，所以自然產生 B 的結果。"
  }),
  examQuestion({
    id: "n1-text-tadashi",
    level: "N1",
    surface: "ただし",
    reading: "ただし",
    meaningZh: "但是、但有條件",
    promptLabel: "N1 文章脈絡",
    instructionZh: "短文脈絡：選能補上限制條件的接續語。",
    promptText: "本制度は原則として全社員が利用できる。___、試用期間中の社員は対象外とする。",
    promptContextZh: "前句說原則，後句追加例外限制。",
    expectedAnswer: "ただし",
    options: ["ただし", "したがって", "それどころか", "ちなみに"],
    explanation: "後句不是結論、補充閒談或反駁，而是加上限制條件，所以用「ただし」。"
  }),
  examQuestion({
    id: "n1-order-nakushitewa",
    level: "N1",
    surface: "なくしては",
    reading: "なくしては",
    meaningZh: "沒有...就不能...",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：注意否定條件與後句否定的呼應。",
    promptText: "［長期的な視点 / なくしては / 持続的な成長は / 望めない］",
    promptContextZh: "沒有長期觀點，就無法期待持續成長。",
    expectedAnswer: "長期的な視点なくしては持続的な成長は望めない",
    options: [
      "長期的な視点なくしては持続的な成長は望めない",
      "持続的な成長はなくしては長期的な視点望めない",
      "長期的な視点は持続的な成長なくしては望めない",
      "望めない長期的な視点なくしては持続的な成長は"
    ],
    explanation: "「Nなくしては...ない」是一組，名詞「長期的な視点」要直接接「なくしては」。"
  }),
  examQuestion({
    id: "n1-order-wokikkirini",
    level: "N1",
    surface: "を皮切りに",
    reading: "をかわきりに",
    meaningZh: "以...為開端",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：注意開端與後續展開。",
    promptText: "［大阪での公演を / 皮切りに / 全国ツアーが / 始まった］",
    promptContextZh: "以大阪公演為開端，全國巡演開始。",
    expectedAnswer: "大阪での公演を皮切りに全国ツアーが始まった",
    options: [
      "大阪での公演を皮切りに全国ツアーが始まった",
      "全国ツアーを大阪での公演が皮切りに始まった",
      "大阪での公演が全国ツアーを始まった皮切りに",
      "皮切りに全国ツアーを大阪での公演が始まった"
    ],
    explanation: "「Aを皮切りにBが始まる」表示以 A 為第一步，B 接著展開。"
  }),
  examQuestion({
    id: "n3-grammar-yoninaru",
    level: "N3",
    surface: "ようになる",
    reading: "ようになる",
    meaningZh: "變得（能夠/習慣於）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：選表示「能力／習慣的轉變」的文法。",
    promptText: "毎日 練習したので、自転車に乗れる ___ なった。",
    promptContextZh: "每天練習，結果變得會騎自行車了。",
    expectedAnswer: "ように",
    options: ["ように", "ことに", "ために", "ようで"],
    explanation: "「Vる/可能形 + ようになる」表示「（從不會到會、從不做到做）變化的結果」。「ことになる」是外在的決定；「ために」表目的；「ようで」是「好像」。"
  }),
  examQuestion({
    id: "n3-grammar-kotonisuru",
    level: "N3",
    surface: "ことにする",
    reading: "ことにする",
    meaningZh: "決定（主動）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：注意是「我自己」的決定。",
    promptText: "体に悪いから、たばこをやめる ___ 。",
    promptContextZh: "對身體不好，我決定戒菸了。",
    expectedAnswer: "ことにした",
    options: ["ことにした", "ようにした", "ことになった", "ようになった"],
    explanation: "「Vる + ことにする」表示「自己的決定」。「ことになる」是外在情況/規定造成的結果；「ようにする」是「努力做到」。"
  }),
  examQuestion({
    id: "n3-grammar-tsumori",
    level: "N3",
    surface: "つもり",
    reading: "つもり",
    meaningZh: "打算",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：主觀打算。",
    promptText: "夏休みに国へ帰る ___ です。",
    promptContextZh: "暑假打算回國。",
    expectedAnswer: "つもり",
    options: ["つもり", "ばかり", "はず", "ところ"],
    explanation: "「Vる + つもり」表示主觀的打算。「ばかり」表示「剛剛...完」；「はず」表示客觀推測「應該」；「ところ」表動作階段。"
  }),
  examQuestion({
    id: "n3-grammar-bayokatta",
    level: "N3",
    surface: "ばよかった",
    reading: "ばよかった",
    meaningZh: "如果...就好了（後悔）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示對過去未做的事的後悔。",
    promptText: "雨に降られた。傘を持ってくれば ___ 。",
    promptContextZh: "被雨淋了，要是有帶傘就好了。",
    expectedAnswer: "よかった",
    options: ["よかった", "ばかりだ", "つもりだ", "はずだ"],
    explanation: "「Vば + よかった」表示對過去未做的事感到後悔。其他三個都是常見的句末表現，但都需要不同的接續（「ばかりだ」「つもりだ」「はずだ」皆接 V辞書形/た形），不能直接接在 Vば 後面。"
  }),
  examQuestion({
    id: "n3-grammar-tahougaii",
    level: "N3",
    surface: "たほうがいい",
    reading: "たほうがいい",
    meaningZh: "...比較好（建議）",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：對對方的建議。",
    promptText: "熱がありますね。早く病院へ行った ___ 。",
    promptContextZh: "你發燒了呢，早點去醫院比較好。",
    expectedAnswer: "ほうがいい",
    options: ["ほうがいい", "ことがある", "つもりだ", "おかげだ"],
    explanation: "「Vた + ほうがいい」表示對對方的建議。"
  }),
  examQuestion({
    id: "n3-grammar-nakutehaikenai",
    level: "N3",
    surface: "なくてはいけない",
    reading: "なくてはいけない",
    meaningZh: "必須",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示義務。",
    promptText: "明日までにこのレポートを ___ いけない。",
    promptContextZh: "明天之前必須交這份報告。",
    expectedAnswer: "出さなくては",
    options: ["出さなくては", "出さなくても", "出さないで", "出すことが"],
    explanation: "「Vない形 + なくてはいけない」表示「必須做」的義務。「なくてもいい」相反，表示不需要做。"
  }),
  examQuestion({
    id: "n3-grammar-teshimau",
    level: "N3",
    surface: "てしまう",
    reading: "てしまう",
    meaningZh: "（不小心）做了",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示後悔／意外完成。",
    promptText: "大事な約束を忘れて ___ 、本当にすみません。",
    promptContextZh: "把重要的約定忘了，真的很抱歉。",
    expectedAnswer: "しまって",
    options: ["しまって", "おいて", "みて", "あって"],
    explanation: "「Vて + しまう」表示完成或表達遺憾／後悔。「ておく」表示為將來做準備；「てみる」表示嘗試。"
  }),
  examQuestion({
    id: "n3-grammar-teoku",
    level: "N3",
    surface: "ておく",
    reading: "ておく",
    meaningZh: "事先做好",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：為將來準備。",
    promptText: "明日の会議の前に、資料をコピーし ___ ます。",
    promptContextZh: "明天會議前先把資料影印起來。",
    expectedAnswer: "ておき",
    options: ["ておき", "てしまい", "てあり", "ていき"],
    explanation: "「Vて + おく」表示為將來做準備。「てある」是已被人放置的狀態；「てしまう」是完了／遺憾。"
  }),
  examQuestion({
    id: "n3-grammar-nagara",
    level: "N3",
    surface: "ながら",
    reading: "ながら",
    meaningZh: "一邊...一邊...",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：同一個人同時做兩件事。",
    promptText: "音楽を聞き ___ 、勉強するのが好きだ。",
    promptContextZh: "我喜歡邊聽音樂邊讀書。",
    expectedAnswer: "ながら",
    options: ["ながら", "あいだ", "うちに", "ばかり"],
    explanation: "「Vます形 + ながら」表示同一個人同時做兩件事。「あいだ」「うちに」是時間範圍／不同主語。"
  }),
  examQuestion({
    id: "n3-grammar-teirutokoro",
    level: "N3",
    surface: "ているところ",
    reading: "ているところ",
    meaningZh: "正在...中",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示動作正在進行的瞬間。",
    promptText: "今、ご飯を ___ ので、後で電話します。",
    promptContextZh: "現在正在吃飯，等等再打電話。",
    expectedAnswer: "食べているところな",
    options: ["食べているところな", "食べたところな", "食べたばかりな", "食べるところな"],
    explanation: "「Vている + ところだ」表示「動作正在進行中」；「Vたところだ」表示「剛剛做完」；「Vるところだ」是「正要做」；「Vたばかりだ」是「剛剛...不久」。"
  }),
  examQuestion({
    id: "n2-grammar-monono",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然...但...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：前後句子有逆接關係。",
    promptText: "ダイエットを始めた ___ 、なかなか体重が減らない。",
    promptContextZh: "雖然開始減肥了，但體重一直沒減少。",
    expectedAnswer: "ものの",
    options: ["ものの", "ことに", "ものを", "ように"],
    explanation: "「A ものの、B」表示「雖然 A，但是 B」，書面語逆接。「ものを」帶後悔語氣「明明可以...卻沒」。"
  }),
  examQuestion({
    id: "n2-grammar-karakoso",
    level: "N2",
    surface: "からこそ",
    reading: "からこそ",
    meaningZh: "正因為",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：強調唯一的理由。",
    promptText: "君のことを思っている ___ 、こんなに厳しく言うのだ。",
    promptContextZh: "正因為為了你著想，才這麼嚴格地說。",
    expectedAnswer: "からこそ",
    options: ["からこそ", "からといって", "からには", "からして"],
    explanation: "「A からこそ B」強調「正是因為 A」的唯一原因。「からといって」是「不能因為...就」；「からには」是「既然...就應該」。"
  }),
  examQuestion({
    id: "n2-grammar-niatatte",
    level: "N2",
    surface: "にあたって",
    reading: "にあたって",
    meaningZh: "在...之際",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「在某個重要關頭」。",
    promptText: "新しいプロジェクトを始める ___ 、関係者を集めて打ち合わせをした。",
    promptContextZh: "在開始新項目之際，召集了相關人員開會。",
    expectedAnswer: "にあたって",
    options: ["にあたって", "について", "に対して", "に従って"],
    explanation: "「Vる/N にあたって」用於正式場合，表示「在某重要時刻」。「について」是「關於」；「に対して」是「對於」；「に従って」是「隨著」。"
  }),
  examQuestion({
    id: "n2-grammar-nikanshite",
    level: "N2",
    surface: "に関して",
    reading: "にかんして",
    meaningZh: "關於",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：選正式的「關於」。",
    promptText: "この問題 ___ 、皆さんのご意見を伺いたい。",
    promptContextZh: "關於這個問題，想聽聽大家的意見。",
    expectedAnswer: "に関して",
    options: ["に関して", "に伴って", "に応じて", "に反して"],
    explanation: "「Nに関して」表示「關於 N」，較「について」正式。「に伴って」是「隨著」；「に応じて」是「依照」；「に反して」是「與...相反」。"
  }),
  examQuestion({
    id: "n2-grammar-nishitewa",
    level: "N2",
    surface: "にしては",
    reading: "にしては",
    meaningZh: "作為...來說（偏離預期）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意前後落差。",
    promptText: "彼は日本に来てまだ三か月 ___ 、日本語が上手だ。",
    promptContextZh: "他來日本才三個月，日語就講得很好。",
    expectedAnswer: "にしては",
    options: ["にしては", "にしても", "にしたら", "について"],
    explanation: "「N にしては」表示「以 N 來說（偏離預期）」。「にしても」是「即使...也」；「にしたら」是「站在 N 的立場」。"
  }),
  examQuestion({
    id: "n2-grammar-dokoroka",
    level: "N2",
    surface: "どころか",
    reading: "どころか",
    meaningZh: "別說...連...都...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示強烈否定／反向預期。",
    promptText: "宿題は終わる ___ 、まだ半分もやっていない。",
    promptContextZh: "別說作業沒寫完，連一半都還沒做。",
    expectedAnswer: "どころか",
    options: ["どころか", "ばかりか", "うえに", "に加えて"],
    explanation: "「A どころか B」表示「別說 A，連 B 都...」的強烈反向。「ばかりか」是「不只 A，B 也」(正向累加)；「うえに / に加えて」也是累加。"
  }),
  examQuestion({
    id: "n2-grammar-mai",
    level: "N2",
    surface: "まい",
    reading: "まい",
    meaningZh: "絕不（強烈否定意志）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：書面語的強烈否定意志。",
    promptText: "あんな店には二度と行く ___ と心に決めた。",
    promptContextZh: "我下定決心，再也不去那種店了。",
    expectedAnswer: "まい",
    options: ["まい", "ない", "なくて", "ぬ"]
,
    explanation: "「Vる + まい」(一類動詞辭書形；二類動詞「るまい / ようまい」)表示「絕對不做」的強烈決心，書面正式。「ぬ」是文語否定但無強烈意志。"
  }),
  examQuestion({
    id: "n2-grammar-bakarika",
    level: "N2",
    surface: "ばかりか",
    reading: "ばかりか",
    meaningZh: "不只...連...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：累加表現。",
    promptText: "彼は日本語 ___ 、中国語も韓国語も流暢に話せる。",
    promptContextZh: "他不只會說日語，連中文、韓文都很流利。",
    expectedAnswer: "ばかりか",
    options: ["ばかりか", "ばかりで", "ばかりに", "ばかりだ"],
    explanation: "「A ばかりか B」表示「不只 A，連 B 也」。「ばかりに」是「就因為...才」(負面結果)；「ばかりで」是「只...而已」。"
  }),
  examQuestion({
    id: "n2-grammar-monodakara",
    level: "N2",
    surface: "ものだから",
    reading: "ものだから",
    meaningZh: "因為...（辯解）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：辯解語氣的原因。",
    promptText: "外があまりにも寒かった ___ 、つい厚着をしてしまった。",
    promptContextZh: "因為外面實在太冷了，不知不覺就穿了很厚。",
    expectedAnswer: "ものだから",
    options: ["ものだから", "ものなら", "ものの", "ものか"],
    explanation: "「A ものだから B」用來解釋原因，常帶辯解語氣。「ものなら」表示假設；「ものの」是「雖然」；「ものか」是反問「怎麼可能」。"
  }),
  examQuestion({
    id: "n2-grammar-uede",
    level: "N2",
    surface: "うえで",
    reading: "うえで",
    meaningZh: "在...之後（再）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「先做某事再下一步」的正式表現。",
    promptText: "資料をよく読んだ ___ で、ご判断ください。",
    promptContextZh: "請仔細閱讀資料之後再判斷。",
    expectedAnswer: "うえ",
    options: ["うえ", "ばかり", "ところ", "そば"],
    explanation: "「Vた + うえで」表示「在 V 之後（再進入下一步）」，正式。「ばかり」是「剛剛」；「ところ」是「動作階段」；「そば」是「N 旁邊」。"
  }),
  examQuestion({
    id: "n1-grammar-nimomashite",
    level: "N1",
    surface: "にもまして",
    reading: "にもまして",
    meaningZh: "比...更...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「比預期/比過去更...」。",
    promptText: "今年は例年 ___ 多くの観光客がこの町を訪れている。",
    promptContextZh: "今年比往年湧入更多遊客造訪這座城市。",
    expectedAnswer: "にもまして",
    options: ["にもまして", "ともなく", "にあって", "を限りに"],
    explanation: "「N にもまして」表示「比 N 還更...」。「ともなく」是「無意間」；「にあって」是「處於 N 的情況」；「を限りに」是「以 N 為界」。"
  }),
  examQuestion({
    id: "n1-grammar-tobakarini",
    level: "N1",
    surface: "とばかりに",
    reading: "とばかりに",
    meaningZh: "彷彿在說...似的",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：戲劇化的表現。",
    promptText: "ベルが鳴ると、彼はもう待てない ___ 教室を飛び出した。",
    promptContextZh: "鈴聲一響，他彷彿再也等不及似的衝出教室。",
    expectedAnswer: "とばかりに",
    options: ["とばかりに", "とともに", "とあって", "といえども"],
    explanation: "「~とばかりに」表示「彷彿在說/做出...的姿態」，戲劇化描寫。「とともに」是「同時／隨著」；「とあって」是「因為是...所以」。"
  }),
  examQuestion({
    id: "n1-grammar-tomonareba",
    level: "N1",
    surface: "ともなれば",
    reading: "ともなれば",
    meaningZh: "一旦成為...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「達到某地位／階段時必然...」。",
    promptText: "管理職 ___ 、責任の重さも倍になる。",
    promptContextZh: "一旦成為管理階層，責任也加倍。",
    expectedAnswer: "ともなれば",
    options: ["ともなれば", "ともあれ", "ともなく", "ときたら"],
    explanation: "「N ともなれば」表示「達到 N 階段時，自然會...」。「ともあれ」是「無論如何」；「ともなく」是「無意間」；「ときたら」是「說到 N（負面評論）」。"
  }),
  examQuestion({
    id: "n1-grammar-deare",
    level: "N1",
    surface: "であれ",
    reading: "であれ",
    meaningZh: "無論是...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「無論 N 為何」。",
    promptText: "理由が何 ___ 、約束を破ることは許されない。",
    promptContextZh: "無論理由是什麼，違反約定都不可原諒。",
    expectedAnswer: "であれ",
    options: ["であれ", "にしては", "ながら", "といえども"],
    explanation: "「N であれ」表示「無論是 N」，正式書面。「といえども」是「即便是 N」(讓步)；「にしては」是「以 N 來說」(偏離)；「ながら」是「同時/雖然」。"
  }),
  examQuestion({
    id: "n1-grammar-tomoarou",
    level: "N1",
    surface: "ともあろう",
    reading: "ともあろう",
    meaningZh: "身為...卻...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：帶失望／批判語氣。",
    promptText: "教育者 ___ ものが、そんな不正を働くとは情けない。",
    promptContextZh: "身為教育者卻做出那種不正行為，實在可悲。",
    expectedAnswer: "ともあろう",
    options: ["ともあろう", "ともなれば", "ともなく", "ともあれ"],
    explanation: "「N ともあろうもの」表示「身為 N 這種身分的人卻...」，帶失望/批判語氣。"
  }),
  examQuestion({
    id: "n1-grammar-kitteno",
    level: "N1",
    surface: "きっての",
    reading: "きっての",
    meaningZh: "...當中數一數二的",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「N 中的第一／最頂尖」。",
    promptText: "彼はこの業界 ___ 名医として広く知られている。",
    promptContextZh: "他作為這個業界數一數二的名醫廣為人知。",
    expectedAnswer: "きっての",
    options: ["きっての", "あっての", "なくしての", "ながらの"],
    explanation: "「N + きっての」=「N 當中數一數二的」（正面肯定 N 中最頂尖）。「あっての」是「有了 N 才有的（依存關係）」；「なくしての」是「沒有 N 而成立的」（此處語意不通）；「ながらの」是「自帶 N 屬性的、N 風的」。"
  }),
  examQuestion({
    id: "n1-grammar-nagaranishite",
    level: "N1",
    surface: "ながらにして",
    reading: "ながらにして",
    meaningZh: "處於...就能...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：「不必離開某狀態就能...」。",
    promptText: "インターネットのおかげで、家に居 ___ 世界中のニュースが手に入る。",
    promptContextZh: "拜網路所賜，待在家就能取得全球資訊。",
    expectedAnswer: "ながらにして",
    options: ["ながらにして", "ながらも", "つつも", "つつあって"],
    explanation: "「居ながらにして」是固定表現，表示「不必離開（家／當下）就能...」。「ながらも」是「雖然」；「つつも」近似ながらも；「つつあって」是「持續...當中」。"
  }),
  examQuestion({
    id: "n1-grammar-nishite",
    level: "N1",
    surface: "にして",
    reading: "にして",
    meaningZh: "在...這個時刻／身分",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：強調達到某階段才...。",
    promptText: "あの傑作は彼が五十歳 ___ ようやく完成させたものだ。",
    promptContextZh: "那部傑作是他到了五十歲才終於完成的。",
    expectedAnswer: "にして",
    options: ["にして", "にあって", "ともなく", "ながらも"],
    explanation: "「N にして」表示「在 N 這個（年齡/階段/身分）時，才...」，較正式。「にあって」是「處於 N」；「ながらも」是「雖然」。"
  }),
  examQuestion({
    id: "n1-grammar-kagirida",
    level: "N1",
    surface: "限りだ",
    reading: "かぎりだ",
    meaningZh: "極為...（感情）",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：書面表達極致情感。",
    promptText: "家族と過ごせる時間が短くて、寂しい ___ だ。",
    promptContextZh: "能和家人共處的時間太短，非常寂寞。",
    expectedAnswer: "限り",
    options: ["限り", "極み", "次第", "気味"],
    explanation: "「い形容詞 + 限りだ」表示「至極...的感情」。「極み」常接名詞（贅沢の極み）；「次第」是「依照」；「気味」是「有點...的感覺」。"
  }),
  examQuestion({
    id: "n1-grammar-noitari",
    level: "N1",
    surface: "の至り",
    reading: "のいたり",
    meaningZh: "...之至（深感...）",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：用於致辭、書信的正式感情表達。",
    promptText: "皆様のご支援を賜り、感謝 ___ です。",
    promptContextZh: "承蒙各位的支持，深感感謝。",
    expectedAnswer: "の至り",
    options: ["の至り", "の極み", "の限り", "の余り"],
    explanation: "「N の至り」常用於 感謝・恐縮・光栄 等正式致辭。「の極み」也表示極致但多用「贅沢／疲労」等；「の限り」較少這種用法；「の余り」是「太過...而...」。"
  }),
  examQuestion({
    id: "n3-grammar-nikui",
    level: "N3",
    surface: "にくい",
    reading: "にくい",
    meaningZh: "難以...",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示某動作做起來費力。",
    promptText: "字が小さすぎて、とても ___ ですね。",
    promptContextZh: "字太小，很難讀呢。",
    expectedAnswer: "読みにくい",
    options: ["読みにくい", "読みやすい", "読みたい", "読めない"],
    explanation: "「Vます形 + にくい」表示動作做起來費力、困難。「やすい」相反，是「容易做」；「たい」是希望；「読めない」是「無法讀」(指能力上不行)，但這裡的問題不是能力而是條件造成不易讀，所以「にくい」最自然。"
  }),
  examQuestion({
    id: "n3-grammar-yasui",
    level: "N3",
    surface: "やすい",
    reading: "やすい",
    meaningZh: "容易做、好做",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：強調操作上順手。",
    promptText: "このペンは持ち ___ 、長い時間書いても疲れない。",
    promptContextZh: "這支筆很好握，長時間寫也不會累。",
    expectedAnswer: "やすくて",
    options: ["やすくて", "にくくて", "がちで", "そうで"],
    explanation: "「Vます形 + やすい」表示「容易做、好操作」。「にくい」是相反；「がち」是「容易發生（負面）」；「そう」是「看起來像」。"
  }),
  examQuestion({
    id: "n3-grammar-tagaru",
    level: "N3",
    surface: "たがる",
    reading: "たがる",
    meaningZh: "（第三人稱）想要做",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：描述他人的欲望。",
    promptText: "妹は 体調が 悪いのに、病院に ___ 。",
    promptContextZh: "妹妹身體不舒服，卻不想去醫院。",
    expectedAnswer: "行きたがらない",
    options: ["行きたがらない", "行きたくない", "行かなさそう", "行かないらしい"],
    explanation: "「Vます形 + たがる（否定：たがらない）」表示「第三人稱（自己以外的人）想／不想做某事」。「Vたい／たくない」是「自己」的願望（第一人稱）；「Vそう」是「看起來會...」（觀察推測）；「Vらしい」是「聽說會...」（傳聞）。本句主語「妹」是第三人稱，必須用「行きたがらない」。"
  }),
  examQuestion({
    id: "n3-grammar-youtosuru",
    level: "N3",
    surface: "ようとする",
    reading: "ようとする",
    meaningZh: "正要、試圖",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：動作即將發生卻被打斷。",
    promptText: "家を出 ___ としたとき、電話が鳴った。",
    promptContextZh: "正要出門時，電話響了。",
    expectedAnswer: "よう",
    options: ["よう", "る", "て", "た"],
    explanation: "「動詞意向形 + とする」表示「正要做某動作（卻被打斷或注意到別事）」。「Vるとする」是另一個意思「假定...」；「Vてとする」「Vたとする」皆不通。"
  }),
  examQuestion({
    id: "n3-grammar-rashii-typical",
    level: "N3",
    surface: "らしい",
    reading: "らしい",
    meaningZh: "（典型的）像...的樣子",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表「符合該身分的典型」。",
    promptText: "あの人は男 ___ ことを よく 言うね。",
    promptContextZh: "那個人常常說很有男子氣概的話呢。",
    expectedAnswer: "らしい",
    options: ["らしい", "そうな", "ような", "みたいな"],
    explanation: "「N + らしい」此處的意思是「具有 N 應有的特質」，是典型而非傳聞。「ような」「みたいな」表示「像 N」(外表相似)；「そうな」是「看起來」。"
  }),
  examQuestion({
    id: "n3-grammar-taritari",
    level: "N3",
    surface: "たり〜たり",
    reading: "たり〜たり",
    meaningZh: "做...做...",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：列舉動作。",
    promptText: "休みの日は本を読んだり、___ して過ごす。",
    promptContextZh: "假日會做做看書、散步之類的事情。",
    expectedAnswer: "散歩したり",
    options: ["散歩したり", "散歩しても", "散歩する", "散歩しながら"],
    explanation: "「Vたり、Vたりする」表示列舉幾個動作（不限這些）。「ても」是讓步；「ながら」是「同時」。"
  }),
  examQuestion({
    id: "n3-grammar-tamama",
    level: "N3",
    surface: "たまま",
    reading: "たまま",
    meaningZh: "保持...的狀態",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表「狀態未變」。",
    promptText: "靴を 履いた ___ 、部屋に 上がらないで ください。",
    promptContextZh: "請不要穿著鞋子上房間。",
    expectedAnswer: "まま",
    options: ["まま", "あと", "なり", "ところ"],
    explanation: "「Vた + まま」表示「保持該動作的狀態」沒有改變。「あと」是「之後」；「なり」是「一...就」(N1)；「ところ」是「動作階段」。"
  }),
  examQuestion({
    id: "n3-grammar-baruhodo",
    level: "N3",
    surface: "ば〜ほど",
    reading: "ば〜ほど",
    meaningZh: "越...越...",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：比例變化。",
    promptText: "日本語は 練習すれば ___ 上手になる。",
    promptContextZh: "日語越練習就會越好。",
    expectedAnswer: "するほど",
    options: ["するほど", "したほど", "するばかり", "するまで"],
    explanation: "「Vば + Vほど」表示「越...越...」，前後動詞要一致。「したほど」過去式不通；「するばかり」是「越來越」(單向)；「するまで」是「直到...為止」。"
  }),
  examQuestion({
    id: "n3-grammar-noni",
    level: "N3",
    surface: "のに",
    reading: "のに",
    meaningZh: "雖然...卻...",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：表示意外的結果。",
    promptText: "あんなに 頑張って 勉強した ___ 、試験に 落ちて しまった。",
    promptContextZh: "那麼努力地讀書了，卻還是考砸了。",
    expectedAnswer: "のに",
    options: ["のに", "ので", "ように", "うちに"],
    explanation: "「Vた/イ形容詞 + のに」表示「明明...卻...」的逆接。「ので」是順接因果；「ように」是「為了/像」；「うちに」是「趁著」。"
  }),
  examQuestion({
    id: "n3-grammar-nara-topic",
    level: "N3",
    surface: "なら",
    reading: "なら",
    meaningZh: "如果是...的話",
    promptLabel: "N3 文法形式選擇",
    instructionZh: "句中填空：對方話題的回應。",
    promptText: "日本語の 文法の こと ___ 、田中先生に 聞いた ほうが いい。",
    promptContextZh: "如果是日語文法的事，去問田中老師比較好。",
    expectedAnswer: "なら",
    options: ["なら", "ば", "と", "たら"],
    explanation: "「N + なら」用於承接對方話題並提建議（「如果說到 N 的話」）。「ば」「と」「たら」是條件句，但接續或語感不太相同 — N + ば不通；N + と/たら 需要動詞句。"
  }),
  examQuestion({
    id: "n2-grammar-nimotozuite",
    level: "N2",
    surface: "にもとづいて",
    reading: "にもとづいて",
    meaningZh: "依據、根據",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「以 N 為依據」。",
    promptText: "アンケートの 結果 ___ 、新しい サービスが 設計された。",
    promptContextZh: "依據問卷調查的結果設計了新服務。",
    expectedAnswer: "にもとづいて",
    options: ["にもとづいて", "にあたって", "に関して", "に対して"],
    explanation: "「N にもとづいて」表示「以 N 為根據/依據」。「にあたって」是「在...之際」；「に関して」是「關於」；「に対して」是「對於」。"
  }),
  examQuestion({
    id: "n2-grammar-nisuginai",
    level: "N2",
    surface: "にすぎない",
    reading: "にすぎない",
    meaningZh: "只不過是",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「不過如此」的縮小語氣。",
    promptText: "これは あくまでも 個人的な 意見 ___ 、決定では ありません。",
    promptContextZh: "這只不過是個人意見，並不是決定。",
    expectedAnswer: "にすぎず",
    options: ["にすぎず", "にちがいなく", "にきまっており", "にほかならず"],
    explanation: "「N にすぎない」表示「不過是 N 而已」。「にちがいない」是「一定是」；「にきまっている」是「肯定」；「にほかならない」是「正是」 — 三個都是肯定加強，與「にすぎない」的縮小相反。"
  }),
  examQuestion({
    id: "n2-grammar-tsutsuaru",
    level: "N2",
    surface: "つつある",
    reading: "つつある",
    meaningZh: "正在逐漸...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：書面語的「正逐步發生」。",
    promptText: "地球の 平均気温は 徐々に 上昇し ___ 。",
    promptContextZh: "地球的平均氣溫正在逐漸上升。",
    expectedAnswer: "つつある",
    options: ["つつある", "かけている", "ながら", "ばかりだ"],
    explanation: "「Vます形 + つつある」表示「正在持續/逐步 V」，書面正式。「かけている」是「做到一半」；「ばかりだ」是「越來越」；「ながら」是「同時」。"
  }),
  examQuestion({
    id: "n2-grammar-dokorodewanai",
    level: "N2",
    surface: "どころではない",
    reading: "どころではない",
    meaningZh: "哪有空...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示根本沒餘力做某事。",
    promptText: "明日 試験だから、テレビを 見ている ___ 。",
    promptContextZh: "明天就要考試了，哪有空看電視。",
    expectedAnswer: "どころではない",
    options: ["どころではない", "わけがない", "ものではない", "にちがいない"],
    explanation: "「V ている + どころではない」表示「沒餘力做 V」。「わけがない」是「不可能」；「ものではない」是「不該做」；「にちがいない」是「一定」。"
  }),
  examQuestion({
    id: "n2-grammar-ueni",
    level: "N2",
    surface: "うえに",
    reading: "うえに",
    meaningZh: "而且，加上",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：累加同方向的事項。",
    promptText: "彼は 仕事が できる ___ 、人柄も いい。",
    promptContextZh: "他工作能力強，而且人品也好。",
    expectedAnswer: "うえに",
    options: ["うえに", "うえで", "うえは", "うえも"],
    explanation: "「A うえに B」表示 A 之外還加上同方向的 B。「うえで」是「在 A 之後再 B」；「うえは」是「既然 A 就應 B」；「うえも」不存在。"
  }),
  examQuestion({
    id: "n2-grammar-bakarini",
    level: "N2",
    surface: "ばかりに",
    reading: "ばかりに",
    meaningZh: "就因為...（壞結果）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：對負面結果的歸因。",
    promptText: "甘い 物を 食べすぎた ___ 、虫歯に なって しまった。",
    promptContextZh: "就因為甜食吃太多，蛀牙了。",
    expectedAnswer: "ばかりに",
    options: ["ばかりに", "おかげで", "ものだから", "からといって"],
    explanation: "「A ばかりに B」表示「就因為 A 才導致負面 B」。「おかげで」是正面結果；「ものだから」是辯解語氣；「からといって」是「不能因為...就」。"
  }),
  examQuestion({
    id: "n2-grammar-uchiha",
    level: "N2",
    surface: "うちは",
    reading: "うちは",
    meaningZh: "在...的時候",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「在某狀態持續期間」。",
    promptText: "若い ___ は、いろいろな ことに 挑戦した ほうが いい。",
    promptContextZh: "趁年輕的時候，多挑戰各種事情比較好。",
    expectedAnswer: "うち",
    options: ["うち", "あいだ", "なか", "うえ"],
    explanation: "「N/V + うちは」強調「在某狀態還持續時，趁機做」。「あいだ」也是「期間」但較中性；「なか」是「之中」；「うえ」是「之上/之後」。"
  }),
  examQuestion({
    id: "n2-grammar-nishiro",
    level: "N2",
    surface: "にしろ",
    reading: "にしろ",
    meaningZh: "無論...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示「無論何種情況都...」。",
    promptText: "どんな 仕事 ___ 、最後まで 責任を 持つべきだ。",
    promptContextZh: "無論什麼樣的工作，都應該負責到底。",
    expectedAnswer: "にしろ",
    options: ["にしろ", "にしては", "については", "によって"],
    explanation: "「N にしろ」表示「即使是 N，也...」的讓步。「にしては」是「以 N 來說（偏離預期）」；「については」是「關於 N」；「によって」是「依照」。"
  }),
  examQuestion({
    id: "n2-grammar-kotoda",
    level: "N2",
    surface: "ことだ",
    reading: "ことだ",
    meaningZh: "應該...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：給對方的忠告／建議。",
    promptText: "健康の ためには、毎日 運動する ___ 。",
    promptContextZh: "為了健康，每天運動是該做的事。",
    expectedAnswer: "ことだ",
    options: ["ことだ", "ものだ", "ためだ", "ところだ"],
    explanation: "「Vる + ことだ」是給特定對象的「應該做」的建議。「ものだ」是普遍真理/常理；「ためだ」是「為了...」；「ところだ」是動作階段。"
  }),
  examQuestion({
    id: "n2-grammar-monoda",
    level: "N2",
    surface: "ものだ",
    reading: "ものだ",
    meaningZh: "本來就...（普遍真理）",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示眾所周知的道理。",
    promptText: "人間は 誰でも いつかは 年を 取る ___ 。",
    promptContextZh: "人都會有變老的一天。",
    expectedAnswer: "ものだ",
    options: ["ものだ", "ことだ", "はずだ", "わけだ"],
    explanation: "「Vる + ものだ」表示「本來就是...」的普遍真理。「ことだ」是針對對象的忠告；「はずだ」是「應該（推測）」；「わけだ」是「原來如此」的歸結。"
  }),
  examQuestion({
    id: "n1-grammar-niatte",
    level: "N1",
    surface: "にあって",
    reading: "にあって",
    meaningZh: "處於...的情況下",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「身處特定時代或環境」。",
    promptText: "この 不景気 ___ 、企業は 大きな 変革を 求められて いる。",
    promptContextZh: "處於這個不景氣的時代，企業被要求做出重大變革。",
    expectedAnswer: "にあって",
    options: ["にあって", "にあたって", "によって", "にしたら"],
    explanation: "「N にあって」用於正式書面，表示「處於 N 的時代/狀況」。「にあたって」是「在 N 之際（行動前）」；「によって」是「依照/由於」；「にしたら」是「就 N 來看」。"
  }),
  examQuestion({
    id: "n1-grammar-towaie",
    level: "N1",
    surface: "とはいえ",
    reading: "とはいえ",
    meaningZh: "雖說如此",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：書面語的讓步。",
    promptText: "もう 春に なった ___ 、まだ 朝晩は 冷え込む。",
    promptContextZh: "雖說已經入春，但早晚還是很冷。",
    expectedAnswer: "とはいえ",
    options: ["とはいえ", "と思いきや", "とともに", "とあって"],
    explanation: "「~とはいえ」是書面語的讓步，「雖說...但...」。「と思いきや」是「以為...卻不料...」；「とともに」是「同時/隨著」；「とあって」是「因為是...所以」。"
  }),
  examQuestion({
    id: "n1-grammar-monowo",
    level: "N1",
    surface: "ものを",
    reading: "ものを",
    meaningZh: "明明可以...卻...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：帶後悔／責備語氣的逆接。",
    promptText: "早く 言って くれれば 手伝った ___ 、なぜ 黙って いたんですか。",
    promptContextZh: "你早點說的話我就幫忙了，為什麼一直不講？",
    expectedAnswer: "ものを",
    options: ["ものを", "ものの", "ものなら", "ものだから"],
    explanation: "「~ものを」帶後悔/責備語氣，「明明可以...卻沒...」。「ものの」是純粹的「雖然...但...」；「ものなら」是假設「如果可以...的話」；「ものだから」是辯解原因。"
  }),
  examQuestion({
    id: "n1-grammar-kato-omouto",
    level: "N1",
    surface: "かと思うと",
    reading: "かとおもうと",
    meaningZh: "剛...就...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示兩件事接連發生。",
    promptText: "雨が 止んだ ___ 、また 激しく 降り始めた。",
    promptContextZh: "雨剛停，又開始大下了起來。",
    expectedAnswer: "かと思うと",
    options: ["かと思うと", "と思いきや", "ばかりに", "きり"],
    explanation: "「Vた + かと思うと」表示「剛剛...就立刻...」，兩件事緊接發生。「と思いきや」是「以為 A 卻是 B」(預期落空)；「ばかりに」是「就因為」；「きり」是「自從...再也沒...」。"
  }),
  examQuestion({
    id: "n1-grammar-kotodashi",
    level: "N1",
    surface: "ことだし",
    reading: "ことだし",
    meaningZh: "既然...就...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：根據既有事實做出判斷。",
    promptText: "もう 遅い ___ 、今日は この へんで お開きに しましょう。",
    promptContextZh: "既然已經很晚了，今天就到這裡結束吧。",
    expectedAnswer: "ことだし",
    options: ["ことだし", "ことから", "ところで", "だけあって"],
    explanation: "「A ことだし B」根據事實 A 提出建議 B，較婉轉。「ことから」是「從 A 可知 B」(推論)；「ところで」是「即使...也」；「だけあって」是「不愧是」。"
  }),
  examQuestion({
    id: "n1-grammar-aroukotoka",
    level: "N1",
    surface: "あろうことか",
    reading: "あろうことか",
    meaningZh: "怎麼會...！",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：對意外負面事件表達驚訝。",
    promptText: "___ 、彼は 大事な 会議中に 居眠りしてしまった。",
    promptContextZh: "竟然，他在重要的會議中睡著了。",
    expectedAnswer: "あろうことか",
    options: ["あろうことか", "あろうとも", "ともあれ", "もしかすると"],
    explanation: "「あろうことか」放句首，表示「想不到竟然...！」對意外負面事件的驚訝。「あろうとも」是「無論發生什麼」；「ともあれ」是「總之」；「もしかすると」是「也許」。"
  }),
  examQuestion({
    id: "n1-grammar-youmononara",
    level: "N1",
    surface: "ようものなら",
    reading: "ようものなら",
    meaningZh: "萬一...的話就糟了",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：假設後接嚴重後果。",
    promptText: "ここで 失敗 ___ 、すべての 努力が 水の泡だ。",
    promptContextZh: "在這裡萬一失敗，所有的努力就全白費了。",
    expectedAnswer: "しようものなら",
    options: ["しようものなら", "するものなら", "すれば", "したからには"],
    explanation: "「V意向形 + ものなら」表示「萬一這樣做的話，會發生嚴重後果」。「するものなら」少用且語氣較弱；「すれば」是中性條件；「からには」是「既然...就一定」。"
  }),
  examQuestion({
    id: "n1-grammar-zunihaokanai",
    level: "N1",
    surface: "ずにはおかない",
    reading: "ずにはおかない",
    meaningZh: "勢必、絕對會",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：自然發生／不得不引起。",
    promptText: "あの ニュースは 世間を 驚かせ ___ だろう。",
    promptContextZh: "那則新聞勢必會震驚社會吧。",
    expectedAnswer: "ずにはおかない",
    options: ["ずにはおかない", "ざるを得ない", "てはならない", "にすぎない"],
    explanation: "「V未然形 + ずにはおかない」表示「自然會引起／勢必」。「ざるを得ない」是主體被迫做(「不得不」)；「てはならない」是「不可以」(禁止)；「にすぎない」是「只不過是」。"
  }),
  examQuestion({
    id: "n1-grammar-kiri-since",
    level: "N1",
    surface: "きり",
    reading: "きり",
    meaningZh: "自從...以後再也沒...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示「最後一次後就沒再...」。",
    promptText: "高校を 卒業した ___ 、彼とは 一度も 会って いない。",
    promptContextZh: "自從高中畢業之後，就再也沒見過他了。",
    expectedAnswer: "きり",
    options: ["きり", "まま", "ばかり", "だけ"],
    explanation: "「Vた + きり〜ない」表示「自從那次 V 之後就再也沒...」。「まま」是「保持狀態」；「ばかり」是「剛剛/只」；「だけ」是「只」。"
  }),
  examQuestion({
    id: "n1-grammar-tokorowo",
    level: "N1",
    surface: "ところを",
    reading: "ところを",
    meaningZh: "在...的時候，承蒙...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：尊敬語體常用，表體諒對方狀況。",
    promptText: "お忙しい ___ 、わざわざ お越し いただき ありがとうございます。",
    promptContextZh: "百忙之中還勞煩您專程過來，非常感謝。",
    expectedAnswer: "ところを",
    options: ["ところを", "ところで", "ところに", "ところまで"],
    explanation: "「お/Vている + ところを」是禮貌語體中表示「打擾／體諒對方狀況」。「ところで」是「即使...也」；「ところに/へ」是「正當...時」；「ところまで」是「到 N 為止」。"
  }),

  // -- N1 言い換え類義 (synonym / paraphrase) ----------------------------------
  examQuestion({
    id: "n1-syn-yamuwoezu",
    level: "N1",
    surface: "やむを得ず",
    reading: "やむをえず",
    meaningZh: "不得已、迫於無奈",
    promptLabel: "N1 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "その 計画は 「やむを得ず」 中止された。",
    promptContextZh: "那個計畫不得已被迫中止。",
    expectedAnswer: "仕方なく",
    options: ["仕方なく", "思わず", "何とか", "急いで"],
    explanation: "「やむを得ず」= 無法選擇而被迫 ≒「仕方なく」。「思わず」是「不自覺、反射性」（沒經思考）；「何とか」是「設法、勉強撐過」（強調過程努力）；「急いで」是「匆忙地」（強調速度）。皆與「被迫的不情願」差一點。"
  }),
  examQuestion({
    id: "n1-syn-kotogotoku",
    level: "N1",
    surface: "ことごとく",
    reading: "ことごとく",
    meaningZh: "全部、無一例外",
    promptLabel: "N1 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼の 提案は 「ことごとく」 反対された。",
    promptContextZh: "他的提案無一例外地都遭到反對。",
    expectedAnswer: "すべて",
    options: ["すべて", "ほとんど", "強く", "次々と"],
    explanation: "「ことごとく」= 一個不剩、全部 ≒「すべて」。「ほとんど」是「幾乎」（仍留有例外）；「強く」是強烈；「次々と」是接連不斷（強調連續而非全數）。"
  }),
  examQuestion({
    id: "n1-syn-omune",
    level: "N1",
    surface: "おおむね",
    reading: "おおむね",
    meaningZh: "大致上、大略",
    promptLabel: "N1 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "試験の 結果は 「おおむね」 予想通りだった。",
    promptContextZh: "考試結果大致上跟預想的一樣。",
    expectedAnswer: "だいたい",
    options: ["だいたい", "ちょうど", "結局", "かなり"],
    explanation: "「おおむね」= 大致上、整體看來 ≒「だいたい」。「ちょうど」是「剛好（精確一致）」；「結局」是「結果是、終究」（強調最後）；「かなり」是「相當（程度大）」。皆與「整體上接近」之意有別。"
  }),
  examQuestion({
    id: "n1-syn-tegakete",
    level: "N1",
    surface: "手がけて",
    reading: "てがけて",
    meaningZh: "親自負責、操刀",
    promptLabel: "N1 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼は 新しい プロジェクトを 「手がけて」 いる。",
    promptContextZh: "他親自負責新的專案。",
    expectedAnswer: "担当して",
    options: ["担当して", "検討して", "計画して", "観察して"],
    explanation: "「手がける」= 親自著手、實際操刀 ≒「担当する」。「検討する」是「研議、討論」（決策前階段）；「計画する」是「規劃」（執行前階段）；「観察する」是「觀察」（旁觀，未動手）。皆未到「親手執行」的程度。"
  }),
  examQuestion({
    id: "n1-syn-tegowai",
    level: "N1",
    surface: "手強い",
    reading: "てごわい",
    meaningZh: "難對付的、強勁的",
    promptLabel: "N1 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "今回の 対戦相手は かなり 「手強い」 と評判だ。",
    promptContextZh: "據說這次的對手相當難對付。",
    expectedAnswer: "強くて 倒しにくい",
    options: ["強くて 倒しにくい", "経験豊富で 戦い 慣れて いる", "礼儀正しく 親しみやすい"],
    explanation: "「手強い」= 對手實力強、難以擊敗 ≒「強くて倒しにくい」。「経験豊富で戦い慣れている」是「經驗多、上場熟練」（雖然手強的對手常常如此，但定義是強度而非經驗）；「礼儀正しく親しみやすい」是「禮貌親切」（屬於個性層面，與對戰實力無關）。"
  }),

  // -- N1 用法 (word usage) ----------------------------------------------------
  examQuestion({
    id: "n1-usage-hossoku",
    level: "N1",
    surface: "発足",
    reading: "ほっそく",
    meaningZh: "（組織、機構）成立、啟動",
    promptLabel: "N1 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「発足」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「發足」用於組織、機構正式成立、啟動。",
    expectedAnswer: "来月から、新しい 委員会が 発足する 予定だ。",
    exampleJapanese: "来月から、新しい 委員会が 発足する 予定だ。",
    exampleMeaningZh: "下個月起新委員會將正式成立。",
    options: [
      "来月から、新しい 委員会が 発足する 予定だ。",
      "桜の 季節が 今年は 早めに 発足した。",
      "怒りが 発足して、彼は 大声で 叫んだ。",
      "新型の 携帯電話が 来週 発足する。"
    ],
    explanation: "「発足」專指組織、團體、制度的「成立／啟動」，主語必須是組織類名詞。季節用「始まる」，怒り用「爆発する」，商品上市用「発売される」。"
  }),
  examQuestion({
    id: "n1-usage-tegakeru",
    level: "N1",
    surface: "手がける",
    reading: "てがける",
    meaningZh: "親自著手、操刀",
    promptLabel: "N1 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「手がける」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「手がける」用於親自負責、操刀某項工作、事業。",
    expectedAnswer: "彼は これまでに 多くの 著名な 建築物を 手がけて きた。",
    exampleJapanese: "彼は これまでに 多くの 著名な 建築物を 手がけて きた。",
    exampleMeaningZh: "他至今操刀過許多著名建築。",
    options: [
      "彼は これまでに 多くの 著名な 建築物を 手がけて きた。",
      "弟は 階段で 転んで 手を 手がけて しまった。",
      "雨が 強かったので、傘を 手がけて 外出した。",
      "兄は 大学入試を 手がけて 見事 合格した。"
    ],
    explanation: "「手がける」是「親自著手某項工作／作品」，對象常是創作、事業、案件。受傷用「怪我する」，攜帶物品用「持つ」，參加考試用「受ける」。"
  }),
  examQuestion({
    id: "n1-usage-miotosu",
    level: "N1",
    surface: "見落とす",
    reading: "みおとす",
    meaningZh: "看漏、疏忽未察覺",
    promptLabel: "N1 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「見落とす」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「見落とす」是「應該注意到的東西卻沒看到」。",
    expectedAnswer: "校正で 細かい 誤字を いくつか 見落として しまった。",
    exampleJapanese: "校正で 細かい 誤字を いくつか 見落として しまった。",
    exampleMeaningZh: "校稿時把幾個小錯字看漏了。",
    options: [
      "校正で 細かい 誤字を いくつか 見落として しまった。",
      "山の 頂上から 街全体を 見落として 写真を 撮った。",
      "彼は 約束の 時間を 見落として、家を 出なかった。",
      "テストで 計算問題を すべて 見落として 答えた。"
    ],
    explanation: "「見落とす」= 應留意卻沒看到（多用於文件、誤字、徵兆）。從山上望街用「見下ろす」，忘記約定時間用「忘れる」，把題目跳過用「飛ばす」。"
  }),
  examQuestion({
    id: "n1-usage-uchiawaseru",
    level: "N1",
    surface: "打ち合わせる",
    reading: "うちあわせる",
    meaningZh: "事前協商、開協調會",
    promptLabel: "N1 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「打ち合わせる」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「打ち合わせる」是事前討論、協調工作細節。",
    expectedAnswer: "来週の 会議の 議題に ついて、課長と 打ち合わせた。",
    exampleJapanese: "来週の 会議の 議題に ついて、課長と 打ち合わせた。",
    exampleMeaningZh: "我跟課長協商了下週會議的議題。",
    options: [
      "来週の 会議の 議題に ついて、課長と 打ち合わせた。",
      "二人は 目を 打ち合わせて、互いに 微笑んだ。",
      "兄弟は 仲が悪く、よく 打ち合わせて 喧嘩する。",
      "釘を 板に 打ち合わせて、棚を 作った。"
    ],
    explanation: "「打ち合わせる」是工作上的「事前協商」。彼此對望用「見合わせる」，吵架用「言い争う／喧嘩する」，把釘子打進去用「打ち付ける／打ち込む」。"
  }),

  // -- N1 文脈規定 (vocab cloze) ----------------------------------------------
  examQuestion({
    id: "n1-vocab-hakkaku",
    level: "N1",
    surface: "発覚",
    reading: "はっかく",
    meaningZh: "（壞事）東窗事發、被揭發",
    promptLabel: "N1 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "大規模な 不正経理が 監査で ___ し、社長が 辞任した。",
    promptContextZh: "大規模做假帳被審計揭發，社長因此辭職。",
    expectedAnswer: "発覚",
    options: ["発覚", "発明", "発生", "発達"],
    explanation: "「発覚」專指「壞事被揭發出來」。「発明」是發明；「発生」是發生（中性）；「発達」是發展、進化。"
  }),
  examQuestion({
    id: "n1-vocab-okotaru",
    level: "N1",
    surface: "怠る",
    reading: "おこたる",
    meaningZh: "懈怠、疏於",
    promptLabel: "N1 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "機械の 点検を ___ ば、大きな 事故に つながりかねない。",
    promptContextZh: "如果疏於機械檢查，可能釀成大事故。",
    expectedAnswer: "怠れ",
    options: ["怠れ", "軽んじれ", "急げ"],
    explanation: "「怠る」= 應做的事敷衍不認真做（最直接導致疏失）。「軽んじる」是「輕視」（態度上不重視，但動作仍可能在做）；「急ぐ」是「匆忙趕進度」（同樣可能釀事故，但問題在於速度而非態度）。"
  }),
  examQuestion({
    id: "n1-vocab-shinogu",
    level: "N1",
    surface: "しのぐ",
    reading: "しのぐ",
    meaningZh: "凌駕、超越；勉強撐過",
    promptLabel: "N1 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "新人の 彼女は、ベテランを ___ 売上を 記録した。",
    promptContextZh: "她身為新人，卻創下凌駕資深員工的業績。",
    expectedAnswer: "しのぐ",
    options: ["しのぐ", "防ぐ", "招く", "守る"],
    explanation: "「しのぐ」= 凌駕、勝過（A をしのぐ B）。「防ぐ」是防止；「招く」是招致；「守る」是守護。只有「しのぐ」搭配「ベテランを〜売上」自然。"
  }),
  examQuestion({
    id: "n1-vocab-shincho",
    level: "N1",
    surface: "慎重",
    reading: "しんちょう",
    meaningZh: "慎重",
    promptLabel: "N1 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "投資の 判断は ___ に 行わなければ ならない。",
    promptContextZh: "投資判斷必須慎重進行。",
    expectedAnswer: "慎重",
    options: ["慎重", "厳重", "重大", "重要"],
    explanation: "「慎重」= 行為謹慎、不躁進。「厳重」是嚴密（多用於警備、抗議）；「重大」是嚴重（事件本身）；「重要」是重要（價值高）。本句強調「行動方式」，要用「慎重」。"
  }),
  examQuestion({
    id: "n1-vocab-taemanai",
    level: "N1",
    surface: "絶え間ない",
    reading: "たえまない",
    meaningZh: "持續不斷的、不間斷的",
    promptLabel: "N1 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "彼女は ___ 努力で 一流の バイオリニストに なった。",
    promptContextZh: "她憑藉不間斷的努力成為一流的小提琴家。",
    expectedAnswer: "絶え間ない",
    options: ["絶え間ない", "限りない", "果てしない", "やむをえない"],
    explanation: "「絶え間ない」= 中間沒有停頓、連續不斷（強調無間隔）。「限りない」是無止盡（強調無上限）；「果てしない」是無邊無際（多用於空間）；「やむをえない」是不得已。語境是「持續努力」最契合。"
  }),

  // -- N2 言い換え類義 ---------------------------------------------------------
  examQuestion({
    id: "n2-syn-osoraku",
    level: "N2",
    surface: "おそらく",
    reading: "おそらく",
    meaningZh: "（書面語）大概、恐怕",
    promptLabel: "N2 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼は 「おそらく」 もう 来ない だろう。",
    promptContextZh: "他大概不會再來了吧。",
    expectedAnswer: "たぶん",
    options: ["たぶん", "きっと", "どうやら", "もしかして"],
    explanation: "「おそらく」≒「たぶん」（推測，把握中等）。「きっと」是「一定（信心高）」；「どうやら」是「看起來、似乎」（觀察推斷）；「もしかして」是「莫非、是不是」（懷疑語氣，信心低）。差別在於把握程度與語感。"
  }),
  examQuestion({
    id: "n2-syn-shocchu",
    level: "N2",
    surface: "しょっちゅう",
    reading: "しょっちゅう",
    meaningZh: "常常、動不動就",
    promptLabel: "N2 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼女は 「しょっちゅう」 遅刻する。",
    promptContextZh: "她常常遲到。",
    expectedAnswer: "頻繁に",
    options: ["頻繁に", "たまに", "ときどき", "いつも"],
    explanation: "「しょっちゅう」≒「頻繁に」（高頻率、屢屢）。「たまに」是「偶爾」（頻率低）；「ときどき」是「有時候」（頻率中等）；「いつも」是「總是、每次」（頻率最高，必發生）。要從頻率刻度上挑「高頻但非總是」的詞。"
  }),
  examQuestion({
    id: "n2-syn-sokkuri",
    level: "N2",
    surface: "そっくり",
    reading: "そっくり",
    meaningZh: "一模一樣、極相似",
    promptLabel: "N2 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "双子の 兄弟は 顔が 「そっくり」 だ。",
    promptContextZh: "雙胞胎兄弟臉長得一模一樣。",
    expectedAnswer: "よく 似ている",
    options: ["よく 似ている", "やや 似ている", "雰囲気が 似ている"],
    explanation: "「そっくり」= 高度相似、幾乎一模一樣 ≒「よく似ている」。「やや似ている」是「有點像」（程度太弱）；「雰囲気が似ている」是「氛圍接近」（不到外貌一模一樣）。"
  }),
  examQuestion({
    id: "n2-syn-gakkari",
    level: "N2",
    surface: "がっかり",
    reading: "がっかり",
    meaningZh: "失望、沮喪",
    promptLabel: "N2 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "試験に 落ちて、彼は 「がっかり」 した。",
    promptContextZh: "因為考試沒過，他很失望。",
    expectedAnswer: "失望",
    options: ["失望", "後悔", "戸惑い", "悲しみ"],
    explanation: "「がっかりする」≒「失望する」（期待落空的失落感）。「後悔」是事後悔不當初（責備自己）；「戸惑い」是不知所措、困惑；「悲しみ」是悲傷。雖然都是負面情緒，唯有「失望」精準對應「期待沒實現」。"
  }),
  examQuestion({
    id: "n2-syn-wazawaza",
    level: "N2",
    surface: "わざわざ",
    reading: "わざわざ",
    meaningZh: "（為了 X）特地、特意",
    promptLabel: "N2 類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "雨の中、「わざわざ」 来て くれて ありがとう。",
    promptContextZh: "下雨還特地過來，謝謝你。",
    expectedAnswer: "特別に",
    options: ["特別に", "ついでに", "急いで"],
    explanation: "「わざわざ」= 為了某事特地花費心力（即使不便也來）≒「特別に」。「ついでに」是「順便」（剛好順手就做，與「特地」精神相反）；「急いで」是「匆忙地」（強調速度而非用心）。"
  }),

  // -- N2 用法 -----------------------------------------------------------------
  examQuestion({
    id: "n2-usage-habuku",
    level: "N2",
    surface: "省く",
    reading: "はぶく",
    meaningZh: "省略、刪去",
    promptLabel: "N2 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「省く」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「省く」用於省略、刪除多餘的部分。",
    expectedAnswer: "説明を 簡単に するため、専門用語を 省いた。",
    exampleJapanese: "説明を 簡単に するため、専門用語を 省いた。",
    exampleMeaningZh: "為了讓說明簡單，省略了專業術語。",
    options: [
      "説明を 簡単に するため、専門用語を 省いた。",
      "時間を 省くため、急いで 食事を した。",
      "彼は 約束を 省いて、来なかった。",
      "試験で 問題を 全部 省いて、白紙で 出した。"
    ],
    explanation: "「省く」= 省略不必要的部分（語句、步驟）。節省時間用「節約する／短縮する」，違反約定用「破る」，跳過題目用「飛ばす」。"
  }),
  examQuestion({
    id: "n2-usage-motomeru",
    level: "N2",
    surface: "求める",
    reading: "もとめる",
    meaningZh: "請求、徵求",
    promptLabel: "N2 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「求める」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「求める」是向人請求、要求某事物。",
    expectedAnswer: "判断に 迷ったので、上司に 助言を 求めた。",
    exampleJapanese: "判断に 迷ったので、上司に 助言を 求めた。",
    exampleMeaningZh: "因為拿不定主意，所以向上司請求建議。",
    options: [
      "判断に 迷ったので、上司に 助言を 求めた。",
      "旅行先で、おいしい レストランを 求めて 歩き回った。",
      "雨に 求められて、傘を 開いた。",
      "落し物の 鍵を 部屋中 求めて 探した。"
    ],
    explanation: "「求める」= 向他人請求（助言、協力、回答等抽象事物）。實際找東西要用「探す」；被雨淋要用「降られる」；尋找遺失物用「探す」。"
  }),
  examQuestion({
    id: "n2-usage-kotowaru",
    level: "N2",
    surface: "断る",
    reading: "ことわる",
    meaningZh: "拒絕、回絕",
    promptLabel: "N2 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「断る」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「断る」是拒絕邀請、要求。",
    expectedAnswer: "急な 誘いだったので、丁寧に 断った。",
    exampleJapanese: "急な 誘いだったので、丁寧に 断った。",
    exampleMeaningZh: "因為是突然的邀約，所以禮貌地拒絕了。",
    options: [
      "急な 誘いだったので、丁寧に 断った。",
      "強い 雨に 断られて、外出を やめた。",
      "兄に 断られた 服を 弟が 着て 出かけた。",
      "道路工事で 断られた ため、迂回した。"
    ],
    explanation: "「断る」= 拒絕邀請、請求等。被雨阻擋用「降られる」；衣服「不要的」用「着なくなった／お下がり」；道路因施工不通用「通れない／通行止め」。"
  }),
  examQuestion({
    id: "n2-usage-osamaru",
    level: "N2",
    surface: "収まる",
    reading: "おさまる",
    meaningZh: "（容納地）放得進去；平息",
    promptLabel: "N2 詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「収まる」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「収まる」是東西容納於空間內，或情緒、騷動平息。",
    expectedAnswer: "大量の 荷物が なんとか この 箱に 収まった。",
    exampleJapanese: "大量の 荷物が なんとか この 箱に 収まった。",
    exampleMeaningZh: "大量行李勉強塞進這個箱子。",
    options: [
      "大量の 荷物が なんとか この 箱に 収まった。",
      "風邪が 収まって、薬を 飲んだ。",
      "彼の 怒りは 収まって、激しく 怒鳴った。",
      "夕食が 収まって、お腹が 空いて きた。"
    ],
    explanation: "「収まる」= 容納於某範圍內，或事態、情緒平息。但 B、C、D 在語意上自相矛盾（先平息又生病／先平息又生氣／吃飽又餓）。"
  }),

  // -- N2 文脈規定 -------------------------------------------------------------
  examQuestion({
    id: "n2-vocab-boshu",
    level: "N2",
    surface: "募集",
    reading: "ぼしゅう",
    meaningZh: "招募、徵求",
    promptLabel: "N2 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "来月の イベントで 手伝う ボランティアを ___ している。",
    promptContextZh: "正在募集下個月幫忙活動的志工。",
    expectedAnswer: "募集",
    options: ["募集", "招待", "採用", "入会"],
    explanation: "「募集」= 公開招募（人員、作品）。「招待」是邀請特定對象；「採用」是錄取後雇用；「入会」是（自己）入會（不能對外行動）。"
  }),
  examQuestion({
    id: "n2-vocab-taio",
    level: "N2",
    surface: "対応",
    reading: "たいおう",
    meaningZh: "因應、處理",
    promptLabel: "N2 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "顧客からの 苦情に 迅速に ___ する 必要が ある。",
    promptContextZh: "對於客戶投訴必須迅速處理。",
    expectedAnswer: "対応",
    options: ["対応", "対面", "対立", "対象"],
    explanation: "「対応」= 處理、應對（外部情況）。「対面」是面對面；「対立」是對立、衝突；「対象」是對象、目標。"
  }),
  examQuestion({
    id: "n2-vocab-omoitsuki",
    level: "N2",
    surface: "思いつき",
    reading: "おもいつき",
    meaningZh: "靈光一閃、隨興點子",
    promptLabel: "N2 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "彼の 行動は いつも 単なる ___ で、計画性が ない。",
    promptContextZh: "他的行動總是憑一時想到的點子，毫無計畫性。",
    expectedAnswer: "思いつき",
    options: ["思いつき", "思い込み", "思い出", "思いやり"],
    explanation: "「思いつき」= 突然想到的點子（多帶輕率語感）。「思い込み」是先入為主／一廂情願；「思い出」是回憶；「思いやり」是體貼。"
  }),
  examQuestion({
    id: "n2-vocab-tekisetsu",
    level: "N2",
    surface: "適切",
    reading: "てきせつ",
    meaningZh: "妥當、合適",
    promptLabel: "N2 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "面接では ___ な 言葉遣いを 心がけて ください。",
    promptContextZh: "面試時請留意使用合適的措辭。",
    expectedAnswer: "適切",
    options: ["適切", "適度", "適応", "適合"],
    explanation: "「適切」= 妥當、恰當（用於行為、判斷、措辭）。「適度」是程度適中（運動量等）；「適応」是適應（環境）；「適合」是符合（規格、條件）。"
  }),
  examQuestion({
    id: "n2-vocab-torikumu",
    level: "N2",
    surface: "取り組む",
    reading: "とりくむ",
    meaningZh: "（認真）著手處理",
    promptLabel: "N2 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "全社一丸と なって、環境問題に ___ いる。",
    promptContextZh: "全公司同心協力，正著手處理環境問題。",
    expectedAnswer: "取り組んで",
    options: ["取り組んで", "取り上げて", "取り消して", "取り入れて"],
    explanation: "「取り組む」= 認真投入處理（課題、問題）。「取り上げる」是「拿起／提及」；「取り消す」是「取消」；「取り入れる」是「導入、採納」。"
  }),

  // -- N3 文脈規定 (light sprinkle) -------------------------------------------
  examQuestion({
    id: "n3-vocab-tazuneru",
    level: "N3",
    surface: "訪ねる",
    reading: "たずねる",
    meaningZh: "拜訪",
    promptLabel: "N3 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "夏休みに、田舎の 祖父母を ___ 行きました。",
    promptContextZh: "暑假時去鄉下拜訪了祖父母。",
    expectedAnswer: "訪ねて",
    options: ["訪ねて", "探して", "集めて", "求めて"],
    explanation: "「訪ねる」= 拜訪（人）。「探す」是「找」；「集める」是「收集」；「求める」是「請求」，都不適用於「拜訪親人」。"
  }),
  examQuestion({
    id: "n3-vocab-katazukeru",
    level: "N3",
    surface: "片付ける",
    reading: "かたづける",
    meaningZh: "整理、收拾",
    promptLabel: "N3 詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "食事の あと、皿を ___ から、テレビを 見ます。",
    promptContextZh: "用完餐後收拾完餐盤再看電視。",
    expectedAnswer: "片付けて",
    options: ["片付けて", "並べて", "壊して", "預けて"],
    explanation: "「片付ける」= 整理收拾。「並べる」是「擺好」（用餐前才做）；「壊す」是「弄壞」；「預ける」是「寄放」。"
  }),

  // -- N2 文章脈絡 (paragraph context / connectives) --------------------------
  examQuestion({
    id: "n2-text-sonoue",
    level: "N2",
    surface: "そのうえ",
    reading: "そのうえ",
    meaningZh: "再加上、而且",
    promptLabel: "N2 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "このレストランは料金が手頃だ。___、味も本格的で評判がいい。",
    promptContextZh: "前句說價格便宜，後句疊加另一個優點：味道也好。",
    expectedAnswer: "そのうえ",
    options: ["そのうえ", "それにしても", "そのため", "つまり"],
    explanation: "前後同方向、後句再加一個優點，用「そのうえ」（再加上）。「それにしても」帶意外語氣；「そのため」是因果；「つまり」是換言之。"
  }),
  examQuestion({
    id: "n2-text-tokoroga",
    level: "N2",
    surface: "ところが",
    reading: "ところが",
    meaningZh: "（出乎意料）然而",
    promptLabel: "N2 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "出発前は天気予報も晴れだった。___、現地に着くと急に雨が降り出した。",
    promptContextZh: "原本預期晴天，結果到現場卻突然下雨。",
    expectedAnswer: "ところが",
    options: ["ところが", "そして", "それで", "なお"],
    explanation: "「ところが」表示「結果與預期相反、出乎意料」。「そして」是並列；「それで」是因果；「なお」是補述。"
  }),
  examQuestion({
    id: "n2-text-soredemo",
    level: "N2",
    surface: "それでも",
    reading: "それでも",
    meaningZh: "儘管如此、就算這樣",
    promptLabel: "N2 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "何度も練習を重ねた。___、本番では失敗してしまった。",
    promptContextZh: "雖然付出努力，本場仍然失敗。",
    expectedAnswer: "それでも",
    options: ["それでも", "だから", "すなわち", "そこで"],
    explanation: "「それでも」承認前句事實，但後句結果不如預期（讓步＋逆接）。「だから」是因果；「すなわち」是換言；「そこで」是「於是採取行動」。"
  }),

  // -- N1 文章脈絡 ------------------------------------------------------------
  examQuestion({
    id: "n1-text-nimokakawarazu",
    level: "N1",
    surface: "にもかかわらず",
    reading: "にもかかわらず",
    meaningZh: "儘管...仍然...",
    promptLabel: "N1 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "事前に何度も確認した。___、当日になって計画に不備があると分かった。",
    promptContextZh: "事前再三確認，當天卻發現計畫有瑕疵。",
    expectedAnswer: "にもかかわらず",
    options: ["にもかかわらず", "それどころか", "もっとも", "すなわち"],
    explanation: "「(...)にもかかわらず」表示「儘管 A 卻 B」（強烈逆接）。「それどころか」是「不僅如此甚至更...」；「もっとも」是補加限制條件；「すなわち」是換言。"
  }),
  examQuestion({
    id: "n1-text-mottomo",
    level: "N1",
    surface: "もっとも",
    reading: "もっとも",
    meaningZh: "話雖如此、不過",
    promptLabel: "N1 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "この機能は非常に便利だ。___、使いこなすには多少の慣れが必要だ。",
    promptContextZh: "承認便利，但接著補充一個附帶條件。",
    expectedAnswer: "もっとも",
    options: ["もっとも", "それゆえ", "なお", "ひいては"],
    explanation: "「もっとも」承認前句後追加例外或限制條件（≒ ただし）。「それゆえ」是因果（形式語）；「なお」是補充；「ひいては」是「進而、由此延伸」。"
  }),
  examQuestion({
    id: "n1-text-kaette",
    level: "N1",
    surface: "かえって",
    reading: "かえって",
    meaningZh: "反而",
    promptLabel: "N1 文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "彼を励まそうと声をかけた。___、本人を傷つけてしまった。",
    promptContextZh: "出於好意鼓勵，結果反而傷害了對方。",
    expectedAnswer: "かえって",
    options: ["かえって", "したがって", "それゆえ", "なお"],
    explanation: "「かえって」表示「結果與意圖／預期相反」。「したがって」「それゆえ」都是因果（順方向），與本句的「反向結果」不符；「なお」是補述。"
  }),

  // -- N2 文の組み立て (sentence assembly) -----------------------------------
  examQuestion({
    id: "n2-order-bakarika",
    level: "N2",
    surface: "ばかりか",
    reading: "ばかりか",
    meaningZh: "不只...還...",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［この店は / 料理がおいしい / 値段も手頃だ / ばかりか］",
    promptContextZh: "這家店不只料理好吃，價錢也合理。",
    expectedAnswer: "この店は料理がおいしいばかりか値段も手頃だ",
    options: [
      "この店は料理がおいしいばかりか値段も手頃だ",
      "ばかりかこの店は料理がおいしい値段も手頃だ",
      "この店はばかりか料理がおいしい値段も手頃だ",
      "値段も手頃だこの店は料理がおいしいばかりか"
    ],
    explanation: "「AばかりかB」是並列疊加：A 是已知優點，B 補充另一優點。「料理がおいしい」直接接「ばかりか」，後接「値段も手頃だ」；「ばかりか」不能放句首或緊跟「は」之後。"
  }),
  examQuestion({
    id: "n2-order-shidai",
    level: "N2",
    surface: "次第",
    reading: "しだい",
    meaningZh: "一...就...",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［結果が / 出次第 / 連絡を / します］",
    promptContextZh: "結果一出來就馬上聯絡您。",
    expectedAnswer: "結果が出次第連絡をします",
    options: [
      "結果が出次第連絡をします",
      "出次第結果が連絡をします",
      "連絡をします結果が出次第",
      "結果が連絡を出次第します"
    ],
    explanation: "「Vます形/N + 次第」=「一...就...」，前句條件、後句動作。「結果が出る」加「次第」後接後句「連絡をします」。「出次第」不能置於句首，「次第」也不能與其前面動詞分離。"
  }),
  examQuestion({
    id: "n2-order-nishitagatte",
    level: "N2",
    surface: "にしたがって",
    reading: "にしたがって",
    meaningZh: "隨著...",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［科学技術の発展 / 生活が / にしたがって / 便利になった］",
    promptContextZh: "隨著科技發展，生活變得便利。",
    expectedAnswer: "科学技術の発展にしたがって生活が便利になった",
    options: [
      "科学技術の発展にしたがって生活が便利になった",
      "にしたがって科学技術の発展生活が便利になった",
      "便利になった生活が科学技術の発展にしたがって",
      "生活がにしたがって科学技術の発展便利になった"
    ],
    explanation: "「Nにしたがって」表示伴隨變化，N 是變化來源、後句是隨之發生的變化。「科学技術の発展」直接接「にしたがって」，句尾以「便利になった」收。"
  }),
  examQuestion({
    id: "n2-order-tsutsuaru",
    level: "N2",
    surface: "つつある",
    reading: "つつある",
    meaningZh: "正在...中",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［日本社会は / 急速に / 高齢化し / つつある］",
    promptContextZh: "日本社會正快速地高齡化。",
    expectedAnswer: "日本社会は急速に高齢化しつつある",
    options: [
      "日本社会は急速に高齢化しつつある",
      "つつある日本社会は急速に高齢化し",
      "高齢化し日本社会は急速につつある",
      "急速に日本社会はつつある高齢化し"
    ],
    explanation: "「Vます形 + つつある」表示動作正在進行的階段。「高齢化し」直接接「つつある」收尾；副詞「急速に」修飾整個過程，置於主語之後動詞之前。"
  }),
  examQuestion({
    id: "n2-order-monono",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然...但...",
    promptLabel: "N2 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［免許は / 持っている / ものの / 運転には自信がない］",
    promptContextZh: "雖然有駕照，但對開車沒自信。",
    expectedAnswer: "免許は持っているものの運転には自信がない",
    options: [
      "免許は持っているものの運転には自信がない",
      "ものの免許は持っている運転には自信がない",
      "運転には自信がない免許は持っているものの",
      "免許はものの持っている運転には自信がない"
    ],
    explanation: "「Vている + ものの」是逆接連接，A ものの B = 「雖然 A 但 B」。「持っている」後直接接「ものの」，後接逆接句「運転には自信がない」。"
  }),

  // -- N1 文の組み立て --------------------------------------------------------
  examQuestion({
    id: "n1-order-tagasaigo",
    level: "N1",
    surface: "たが最後",
    reading: "たがさいご",
    meaningZh: "一旦...就...（無法挽回）",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［借金を / したが最後 / 取り戻すのは / 困難だ］",
    promptContextZh: "一旦借了錢，要回收就很困難。",
    expectedAnswer: "借金をしたが最後取り戻すのは困難だ",
    options: [
      "借金をしたが最後取り戻すのは困難だ",
      "困難だ借金をしたが最後取り戻すのは",
      "したが最後借金を取り戻すのは困難だ",
      "取り戻すのは借金をしたが最後困難だ"
    ],
    explanation: "「Vたが最後」表示「一旦...就再也無法挽回」，後句必為負面結果。「借金をした」直接接「が最後」，後接結論「取り戻すのは困難だ」。"
  }),
  examQuestion({
    id: "n1-order-yoganai",
    level: "N1",
    surface: "ようがない",
    reading: "ようがない",
    meaningZh: "無從...、無法...",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［連絡先が / わからないので / 彼女に / 知らせようがない］",
    promptContextZh: "不知道聯絡方式，沒辦法通知她。",
    expectedAnswer: "連絡先がわからないので彼女に知らせようがない",
    options: [
      "連絡先がわからないので彼女に知らせようがない",
      "わからないので彼女に連絡先が知らせようがない",
      "知らせようがない連絡先がわからないので彼女に",
      "彼女に知らせようがない連絡先がわからないので"
    ],
    explanation: "「Vます形 + ようがない」表示「客觀條件不允許做某動作」。先說原因「連絡先がわからないので」，再接結果「彼女に知らせようがない」；「彼女に」要與動詞「知らせる」緊鄰。"
  }),
  examQuestion({
    id: "n1-order-tatokorode",
    level: "N1",
    surface: "たところで",
    reading: "たところで",
    meaningZh: "就算...也...",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［今さら / 後悔した / ところで / 結果は変わらない］",
    promptContextZh: "事到如今後悔也改變不了結果。",
    expectedAnswer: "今さら後悔したところで結果は変わらない",
    options: [
      "今さら後悔したところで結果は変わらない",
      "後悔した今さらところで結果は変わらない",
      "ところで今さら後悔した結果は変わらない",
      "結果は変わらない今さら後悔したところで"
    ],
    explanation: "「Vた + ところで」表示「即使做了 V 也沒用」，後句必為否定／無效結果。副詞「今さら」放句首加強語氣，「後悔した」緊鄰「ところで」。"
  }),
  examQuestion({
    id: "n1-order-nisuginai",
    level: "N1",
    surface: "にすぎない",
    reading: "にすぎない",
    meaningZh: "不過是...",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［これは / 一部の意見 / にすぎず / 全体を反映する / ものではない］",
    promptContextZh: "這只不過是部分意見，並不能代表整體。",
    expectedAnswer: "これは一部の意見にすぎず全体を反映するものではない",
    options: [
      "これは一部の意見にすぎず全体を反映するものではない",
      "にすぎずこれは一部の意見全体を反映するものではない",
      "全体を反映するこれは一部の意見にすぎずものではない",
      "ものではないこれは一部の意見にすぎず全体を反映する"
    ],
    explanation: "「Nにすぎない」是「只不過是 N」。連用中止形「にすぎず」接後句「全体を反映するものではない」。先點出「これは一部の意見」這個小範圍，再否定全體性。"
  }),
  examQuestion({
    id: "n1-order-tewa",
    level: "N1",
    surface: "ては",
    reading: "ては",
    meaningZh: "...了又...",
    promptLabel: "N1 語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［単語を / 覚えては / 忘れての / 繰り返しだ］",
    promptContextZh: "單字記了又忘、忘了又記，一直在重複。",
    expectedAnswer: "単語を覚えては忘れての繰り返しだ",
    options: [
      "単語を覚えては忘れての繰り返しだ",
      "繰り返しだ単語を覚えては忘れての",
      "忘れての単語を覚えては繰り返しだ",
      "単語を忘れての覚えては繰り返しだ"
    ],
    explanation: "「Vては Vての繰り返し」是固定表達：兩個動詞交替循環。「単語を」是受詞，緊接「覚えては」；接著「忘れての」修飾結尾的「繰り返しだ」。"
  }),

  // -- N2 文法形式選擇 (additional patterns) -----------------------------------
  examQuestion({
    id: "n2-grammar-dakeatte",
    level: "N2",
    surface: "だけあって",
    reading: "だけあって",
    meaningZh: "不愧是、正符合身分",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：句意是「正符合身分／地位的優點」。",
    promptText: "彼は十年も日本に住んでいる ___ 、日本語が非常に流暢だ。",
    promptContextZh: "他在日本住了十年，難怪日語非常流利。",
    expectedAnswer: "だけあって",
    options: ["だけあって", "ばかりに", "からこそ", "ところで"],
    explanation: "「Nだけあって」表「不愧是 N、與 N 的條件相符的優點」。「ばかりに」是「正因為...才（壞結果）」；「からこそ」是強調原因；「ところで」是「即使...也」。"
  }),
  examQuestion({
    id: "n2-grammar-kotokara",
    level: "N2",
    surface: "ことから",
    reading: "ことから",
    meaningZh: "從...這個事實",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：依事實做推斷。",
    promptText: "現場に指紋が残っていた ___ 、犯人が特定された。",
    promptContextZh: "從現場留有指紋這個事實，鎖定了犯人。",
    expectedAnswer: "ことから",
    options: ["ことから", "ものだから", "ものの", "ばかりに"],
    explanation: "「Vた + ことから」表「以前面事實為依據而判斷／斷定」（客觀推理）。「ものだから」是個人辯解的因果；「ものの」是逆接；「ばかりに」是「正因為...才導致壞結果」。"
  }),
  examQuestion({
    id: "n2-grammar-tokoroni",
    level: "N2",
    surface: "ところに",
    reading: "ところに",
    meaningZh: "正當...的時候",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：注意「正在...時被打斷」。",
    promptText: "夕食を作っている ___ 、母から電話がかかってきた。",
    promptContextZh: "正在做晚餐時，媽媽打電話來了。",
    expectedAnswer: "ところに",
    options: ["ところに", "ところで", "ところを", "ところまで"],
    explanation: "「Vている + ところに」表「正在做某事時，發生／介入了某事」。「ところで」是「即使...也」；「ところを」是「正在...被...」（多接被動／敬語）；「ところまで」是「到 N 為止」。"
  }),
  examQuestion({
    id: "n2-grammar-tabini",
    level: "N2",
    surface: "たびに",
    reading: "たびに",
    meaningZh: "每次...就...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：每次發生 A 就會發生 B。",
    promptText: "この曲を聴く ___ 、学生時代を思い出す。",
    promptContextZh: "每次聽到這首曲子就會想起學生時代。",
    expectedAnswer: "たびに",
    options: ["たびに", "おりに", "さいに", "とともに"],
    explanation: "「Vる + たびに」表「每當 V 就...」（強調反覆對應）。「おりに／さいに」是「在...的特定場合」（單次事件）；「とともに」是「隨著／同時」。"
  }),
  examQuestion({
    id: "n2-grammar-kagiri",
    level: "N2",
    surface: "限り",
    reading: "かぎり",
    meaningZh: "就...範圍而言、只要...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：表示某觀察／能力的範圍。",
    promptText: "私が知る ___ 、彼はとても誠実な人だ。",
    promptContextZh: "就我所知，他是個非常誠實的人。",
    expectedAnswer: "限り",
    options: ["限り", "以上", "あいだ", "あげく"],
    explanation: "「Vる + 限り」表「在 V 的範圍／限度內」（多用於 evidential：以個人所知斷言）。「以上」是「既然」（理由）；「あいだ」是時間期間；「あげく」是「（負面）最終結果」。"
  }),
  examQuestion({
    id: "n2-grammar-amari",
    level: "N2",
    surface: "あまり",
    reading: "あまり",
    meaningZh: "過於...而...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：過度的原因造成負面結果。",
    promptText: "試合に勝ちたいと思う ___ 、力が入りすぎてしまった。",
    promptContextZh: "因為太想贏比賽，反而過度用力。",
    expectedAnswer: "あまり",
    options: ["あまり", "ばかり", "あげく", "あまりの"],
    explanation: "「Vる + あまり」表「因過度 V 而導致（負面）結果」。「ばかり」是「只／剛剛」；「あげく」是「費盡心思之後（負面）」；「あまりの」需接名詞（あまりの暑さに〜）。"
  }),
  examQuestion({
    id: "n2-grammar-nikawatte",
    level: "N2",
    surface: "にかわって",
    reading: "にかわって",
    meaningZh: "代替...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：代替本應做某事的人。",
    promptText: "病気で休んだ田中さん ___ 、私が会議に出席した。",
    promptContextZh: "我代替因病請假的田中先生出席會議。",
    expectedAnswer: "にかわって",
    options: ["にかわって", "について", "において", "にあたって"],
    explanation: "「Nにかわって」表「代替 N」（前者本應做某事，由他人代行）。「について」是「關於」；「において」是「在...（場合）」；「にあたって」是「在...的關鍵時刻」。"
  }),
  examQuestion({
    id: "n2-grammar-ijoha",
    level: "N2",
    surface: "以上",
    reading: "いじょう",
    meaningZh: "既然...就...",
    promptLabel: "N2 文法形式選擇",
    instructionZh: "句中填空：承擔責任的語氣。",
    promptText: "試合に出場する ___ 、優勝を目指すしかない。",
    promptContextZh: "既然要參賽，就只能以奪冠為目標。",
    expectedAnswer: "以上",
    options: ["以上", "あげく", "ばかり", "ものの"],
    explanation: "「Vる/Vた + 以上（は）」表「既然 V，就有相應的責任」（強烈責任語氣）。「あげく」是「（費盡心思後的）負面結果」；「ばかり」是「只」；「ものの」是逆接。"
  }),

  // -- N1 文法形式選擇 (additional patterns) -----------------------------------
  examQuestion({
    id: "n1-grammar-bakoso",
    level: "N1",
    surface: "ばこそ",
    reading: "ばこそ",
    meaningZh: "正是因為...才...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：強調肯定原因，後句必為正面結果。",
    promptText: "プロ意識 ___ 、つらいトレーニングにも耐えられるのだ。",
    promptContextZh: "正因為有專業意識，才能忍受嚴酷訓練。",
    expectedAnswer: "があればこそ",
    options: ["があればこそ", "があるからして", "があるにあっては", "があるとはいえ"],
    explanation: "「Vば + こそ」表「正是因為...才（達成正面結果）」（強烈肯定原因）。「からして」是「光看一點便能斷言」；「にあっては」是「在...的處境中」；「とはいえ」是逆接。"
  }),
  examQuestion({
    id: "n1-grammar-taritomo",
    level: "N1",
    surface: "たりとも",
    reading: "たりとも",
    meaningZh: "即使一個...也（不）...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：最小單位＋否定，強烈禁止。",
    promptText: "国境警備では、一瞬 ___ 油断は許されない。",
    promptContextZh: "在邊境警備上，連一秒鐘的鬆懈都不被允許。",
    expectedAnswer: "たりとも",
    options: ["たりとも", "にして", "ぐらいで", "ながら"],
    explanation: "「N（最小單位）+ たりとも + 否定」=「即使一個 N 也不容...」（強烈否定）。「にして」是「在...時／作為...」；「ぐらいで」是「大約這個程度」；「ながら」是「邊...邊...／雖然...」，皆與「最小單位＋強烈否定」的語感不合。"
  }),
  examQuestion({
    id: "n1-grammar-nihikikae",
    level: "N1",
    surface: "にひきかえ",
    reading: "にひきかえ",
    meaningZh: "與...相反",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：兩方對比成反差。",
    promptText: "兄は積極的なの ___ 、弟は内気で人見知りだ。",
    promptContextZh: "哥哥很積極，相對地弟弟內向怕生。",
    expectedAnswer: "にひきかえ",
    options: ["にひきかえ", "にもまして", "にくわえて", "にもとづいて"],
    explanation: "「Nにひきかえ」表「與 N 形成對比（鮮明反差）」。「にもまして」是「比...更加」（程度更高）；「にくわえて」是「再加上」（疊加）；「にもとづいて」是「基於」。"
  }),
  examQuestion({
    id: "n1-grammar-dewaarumaishi",
    level: "N1",
    surface: "ではあるまいし",
    reading: "ではあるまいし",
    meaningZh: "又不是...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：訓誡或自嘲語氣。",
    promptText: "子供 ___ 、そのくらいの計算は自分でできるはずだ。",
    promptContextZh: "又不是小孩子，這種程度的計算應該自己會算。",
    expectedAnswer: "ではあるまいし",
    options: ["ではあるまいし", "ではあるまい", "ではないまでも", "でなくとも"],
    explanation: "「Nではあるまいし」=「又不是 N，所以...（應該／不應該...）」（責備語氣）。「ではあるまい」單獨用是「大概不是」；「ではないまでも」是「即使不到...也」；「でなくとも」是「即使不是...也」。"
  }),
  examQuestion({
    id: "n1-grammar-gahayaika",
    level: "N1",
    surface: "が早いか",
    reading: "がはやいか",
    meaningZh: "一...就立刻...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：強調幾乎同時、立刻的反應。",
    promptText: "子供たちは家に帰る ___ 、ランドセルを放り出して遊びに行った。",
    promptContextZh: "孩子們一回家，就立刻丟下書包出去玩。",
    expectedAnswer: "が早いか",
    options: ["が早いか", "がてら", "ながらに", "とともに"],
    explanation: "「Vる + が早いか」表「A 完成的瞬間 B 立刻發生」（書面語）。「がてら」是「順便」；「ながらに」是「保持原狀的狀態」；「とともに」是「隨著／同時」。"
  }),
  examQuestion({
    id: "n1-grammar-tarumono",
    level: "N1",
    surface: "たるもの",
    reading: "たるもの",
    meaningZh: "身為...就應當...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：對身分／角色的應然要求。",
    promptText: "教師 ___ 、生徒の手本とならねばならない。",
    promptContextZh: "身為教師，必須成為學生的榜樣。",
    expectedAnswer: "たるもの",
    options: ["たるもの", "であれば", "ともなれば", "ともあろう"],
    explanation: "「N + たるもの」=「作為 N 這樣身分的人，應當...」（古典文體，強調應然）。「であれば」是「如果是 N」（條件）；「ともなれば」是「一旦成為 N」；「ともあろう」是「身為堂堂的 N（怎能...）」（後接非議）。"
  }),
  examQuestion({
    id: "n1-grammar-wohete",
    level: "N1",
    surface: "を経て",
    reading: "をへて",
    meaningZh: "經過...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：經過某過程／時間後達成結果。",
    promptText: "5年に及ぶ厳しい交渉 ___ 、ようやく合意に達した。",
    promptContextZh: "經過長達五年的嚴峻談判，終於達成共識。",
    expectedAnswer: "を経て",
    options: ["を経て", "を通して", "において", "にあたって"],
    explanation: "「Nを経て」表「經過 N（過程／時間／地點）後達到後續結果」。「を通して」是「貫穿整個 N（強調範圍）」；「において」是「在...（場合）」；「にあたって」是「在...的關鍵時刻」。"
  }),
  examQuestion({
    id: "n1-grammar-nikatakunai",
    level: "N1",
    surface: "にかたくない",
    reading: "にかたくない",
    meaningZh: "不難...",
    promptLabel: "N1 文法形式選擇",
    instructionZh: "句中填空：表示推測或想像並不困難（書面語）。",
    promptText: "突然の解雇通告を受けた彼の心境は、想像 ___ 。",
    promptContextZh: "他突然收到解雇通知的心情，不難想像。",
    expectedAnswer: "にかたくない",
    options: ["にかたくない", "にちがいない", "にすぎない", "にあらず"],
    explanation: "「N（多為察知／推測類動詞名詞化）+ にかたくない」=「不難 V」（書面語、評論常用）。「にちがいない」是「一定是」；「にすぎない」是「只不過是」；「にあらず」是「不是」（古典否定）。"
  }),

  // -- N2 漢字読み (kanji reading) ---------------------------------------------
  examQuestion({
    id: "n2-read-kaizen",
    level: "N2",
    surface: "改善",
    reading: "かいぜん",
    meaningZh: "改善",
    promptLabel: "N2 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "業務の流れを徹底的に「改善」する必要がある。",
    promptContextZh: "必須徹底改善業務流程。",
    expectedAnswer: "かいぜん",
    exampleJapanese: "業務の流れを徹底的に改善する必要がある。",
    exampleMeaningZh: "必須徹底改善業務流程。",
    options: ["かいぜん", "かいせん", "がいぜん", "こうぜん"],
    explanation: "「改」音讀「かい」，「善」音讀「ぜん」→ かいぜん。「かいせん」是「回線／改選」（清濁混淆）；「がいぜん」是「蓋然」（首字濁音化）；「こうぜん」是「公然」（首字錯讀）。"
  }),
  examQuestion({
    id: "n2-read-kentou",
    level: "N2",
    surface: "検討",
    reading: "けんとう",
    meaningZh: "檢討、研議",
    promptLabel: "N2 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "提案の内容を慎重に「検討」します。",
    promptContextZh: "我們會慎重研議提案內容。",
    expectedAnswer: "けんとう",
    exampleJapanese: "提案の内容を慎重に検討します。",
    exampleMeaningZh: "我們會慎重研議提案內容。",
    options: ["けんとう", "けんどう", "げんとう", "けんと"],
    explanation: "「検」音讀「けん」，「討」音讀「とう」→ けんとう。「けんどう」是「剣道」（次字濁音）；「げんとう」是「幻灯」（首字濁音）；「けんと」是缺長音（長音脫落）。"
  }),
  examQuestion({
    id: "n2-read-osaeru",
    level: "N2",
    surface: "抑える",
    reading: "おさえる",
    meaningZh: "壓抑、抑制",
    promptLabel: "N2 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "怒りを「抑える」のは大変な努力が必要だ。",
    promptContextZh: "壓抑怒氣需要極大的努力。",
    expectedAnswer: "おさえる",
    exampleJapanese: "怒りを抑えるのは大変な努力が必要だ。",
    exampleMeaningZh: "壓抑怒氣需要極大的努力。",
    options: ["おさえる", "おしえる", "つかえる", "おそえる"],
    explanation: "「抑」訓讀「おさ-える」→ おさえる。「おしえる」是「教える」（同形不同字混淆）；「つかえる」是「仕える／使える」；「おそえる」是錯誤的母音變體（無此單字）。"
  }),
  examQuestion({
    id: "n2-read-awateru",
    level: "N2",
    surface: "慌てる",
    reading: "あわてる",
    meaningZh: "慌張、驚慌",
    promptLabel: "N2 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "予期せぬ事態にも「慌てる」ことなく対応した。",
    promptContextZh: "面對突發狀況也不慌不忙地應對。",
    expectedAnswer: "あわてる",
    exampleJapanese: "予期せぬ事態にも慌てることなく対応した。",
    exampleMeaningZh: "面對突發狀況也不慌不忙地應對。",
    options: ["あわてる", "あばれる", "あおてる", "あつてる"],
    explanation: "「慌」訓讀「あわ-てる」→ あわてる。「あばれる」是「暴れる」（同義場景但字不同）；「あおてる」「あつてる」是無對應字的擬音陷阱。"
  }),
  examQuestion({
    id: "n2-read-magirawashii",
    level: "N2",
    surface: "紛らわしい",
    reading: "まぎらわしい",
    meaningZh: "容易混淆的",
    promptLabel: "N2 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この二つの表現は意味が「紛らわしい」。",
    promptContextZh: "這兩個表達意思容易搞混。",
    expectedAnswer: "まぎらわしい",
    exampleJapanese: "この二つの表現は意味が紛らわしい。",
    exampleMeaningZh: "這兩個表達意思容易搞混。",
    options: ["まぎらわしい", "まきらわしい", "まずらわしい", "みぎらわしい"],
    explanation: "「紛」訓讀「まぎ-らわしい」→ まぎらわしい。「まきらわしい」是清濁混淆；「まずらわしい」是子音錯誤；「みぎらわしい」是首音母音錯誤。"
  }),
  examQuestion({
    id: "n2-read-shousai",
    level: "N2",
    surface: "詳細",
    reading: "しょうさい",
    meaningZh: "詳細、詳情",
    promptLabel: "N2 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "事件の「詳細」については明日発表される。",
    promptContextZh: "事件詳情明天會公布。",
    expectedAnswer: "しょうさい",
    exampleJapanese: "事件の詳細については明日発表される。",
    exampleMeaningZh: "事件詳情明天會公布。",
    options: ["しょうさい", "しょさい", "しゅうさい", "しょうざい"],
    explanation: "「詳」音讀「しょう」，「細」音讀「さい」→ しょうさい。「しょさい」是「書斎」（長音脫落 → 撞到另一個詞）；「しゅうさい」是「秀才」（拗音換成 ゅう）；「しょうざい」是「商材」（次字濁音）。"
  }),

  // -- N1 漢字読み -------------------------------------------------------------
  examQuestion({
    id: "n1-read-kencho",
    level: "N1",
    surface: "顕著",
    reading: "けんちょ",
    meaningZh: "顯著",
    promptLabel: "N1 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "近年、環境問題の影響は「顕著」に現れている。",
    promptContextZh: "近年來環境問題的影響顯而易見。",
    expectedAnswer: "けんちょ",
    exampleJapanese: "近年、環境問題の影響は顕著に現れている。",
    exampleMeaningZh: "近年來環境問題的影響顯而易見。",
    options: ["けんちょ", "けんしょ", "げんちょ", "けんちょう"],
    explanation: "「顕」音讀「けん」，「著」音讀「ちょ」→ けんちょ。「けんしょ」是清濁混淆；「げんちょ」是首字濁音；「けんちょう」是多餘的長音（撞到「県庁」）。"
  }),
  examQuestion({
    id: "n1-read-suikou",
    level: "N1",
    surface: "遂行",
    reading: "すいこう",
    meaningZh: "執行、完成",
    promptLabel: "N1 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "与えられた任務を確実に「遂行」する。",
    promptContextZh: "確實執行所受託付的任務。",
    expectedAnswer: "すいこう",
    exampleJapanese: "与えられた任務を確実に遂行する。",
    exampleMeaningZh: "確實執行所受託付的任務。",
    options: ["すいこう", "ついこう", "ずいこう", "すいぎょう"],
    explanation: "「遂」音讀「すい」，「行」音讀「こう」→ すいこう。「ついこう」是首字子音錯誤；「ずいこう」是「随行」（濁音化）；「すいぎょう」是「行」誤讀為「ぎょう」（修行 しゅぎょう 的類推）。"
  }),
  examQuestion({
    id: "n1-read-dakyou",
    level: "N1",
    surface: "妥協",
    reading: "だきょう",
    meaningZh: "妥協",
    promptLabel: "N1 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この問題で安易な「妥協」はできない。",
    promptContextZh: "在這個問題上不能輕易妥協。",
    expectedAnswer: "だきょう",
    exampleJapanese: "この問題で安易な妥協はできない。",
    exampleMeaningZh: "在這個問題上不能輕易妥協。",
    options: ["だきょう", "たきょう", "だこう", "だぎょう"],
    explanation: "「妥」音讀「だ」，「協」音讀「きょう」→ だきょう。「たきょう」是清濁混淆；「だこう」是「蛇行」（次字錯讀）；「だぎょう」是次字濁音化。"
  }),
  examQuestion({
    id: "n1-read-anmoku",
    level: "N1",
    surface: "暗黙",
    reading: "あんもく",
    meaningZh: "默契、不言明",
    promptLabel: "N1 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "チーム内には「暗黙」のルールがある。",
    promptContextZh: "團隊內存在默契性的規則。",
    expectedAnswer: "あんもく",
    exampleJapanese: "チーム内には暗黙のルールがある。",
    exampleMeaningZh: "團隊內存在默契性的規則。",
    options: ["あんもく", "あんぼく", "あんしょう", "あんめい"],
    explanation: "「暗」音讀「あん」，「黙」音讀「もく」→ あんもく。「あんぼく」是次字濁音；「あんしょう」是「暗証／暗唱」（次字錯讀）；「あんめい」是「暗冥」類錯讀。"
  }),
  examQuestion({
    id: "n1-read-todokooru",
    level: "N1",
    surface: "滞る",
    reading: "とどこおる",
    meaningZh: "停滯、拖延",
    promptLabel: "N1 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "作業の進行が予定より「滞って」いる。",
    promptContextZh: "工作進度比預定還要拖延。",
    expectedAnswer: "とどこおって",
    exampleJapanese: "作業の進行が予定より滞っている。",
    exampleMeaningZh: "工作進度比預定還要拖延。",
    options: ["とどこおって", "とどまって", "とどろいて", "たくおって"],
    explanation: "「滞」訓讀「とどこお-る」→ とどこおって。「とどまって」是「留まる／止まる」（同字根 とど- 但不同字）；「とどろいて」是「轟いて」（同字根，意為轟鳴）；「たくおって」是無對應字的擬音陷阱。"
  }),
  examQuestion({
    id: "n1-read-tsuchikau",
    level: "N1",
    surface: "培う",
    reading: "つちかう",
    meaningZh: "培養（能力、素養）",
    promptLabel: "N1 漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "豊かな感性を「培う」教育を目指している。",
    promptContextZh: "致力於培養豐富感性的教育。",
    expectedAnswer: "つちかう",
    exampleJapanese: "豊かな感性を培う教育を目指している。",
    exampleMeaningZh: "致力於培養豐富感性的教育。",
    options: ["つちかう", "ばいかう", "つちこう", "つくろう"],
    explanation: "「培」訓讀「つちか-う」→ つちかう。「ばいかう」是把訓讀換成音讀「ばい」的陷阱；「つちこう」是次音節母音錯誤；「つくろう」是「繕う」（修補，不同字）。"
  })
];

export function buildExamQuestionPool(level: JlptLevel | "all" = "all"): PracticeQuestion[] {
  if (level === "N1" || level === "N2" || level === "N3") {
    return examStyleQuestions.filter((question) => question.vocabulary.level === level);
  }

  return examStyleQuestions;
}

function examQuestion(input: ExamQuestionInput): PracticeQuestion {
  return {
    id: input.id,
    vocabulary: {
      id: input.id,
      surface: input.surface,
      reading: input.reading,
      meaningZh: input.meaningZh,
      partOfSpeech: "noun",
      group: null,
      lesson: null,
      tags: ["exam_style", input.level],
      examples: [
        {
          japanese: input.exampleJapanese ?? input.promptText.replace("___", input.expectedAnswer),
          meaningZh: input.exampleMeaningZh ?? input.promptContextZh
        }
      ],
      level: input.level
    },
    targetForm: input.targetForm ?? "reading",
    expectedAnswers: [input.expectedAnswer],
    explanation: input.explanation,
    promptLabel: input.promptLabel,
    promptText: input.promptText,
    promptContextZh: input.promptContextZh,
    instructionZh: input.instructionZh,
    options: input.options
  };
}
