// JLPT 文型資料庫（Issue #437）
//
// 為每個文型提供：中文解釋、接續規則、例句、日劇／動漫台詞例句、相近文型、
// 常見錯誤。資料持續擴充中，初期 N5/N4/N2 各一批。
//
// 台詞例句如有不確定，以 `confidence` 如實標記，不偽造 verified 資料。
import type { JlptLevel, ExampleSentence } from "./types";

export type GrammarImportance = "must_know" | "high_frequency" | "understand" | "reference";

export interface MediaLineExample {
  sourceType: "drama" | "anime" | "movie" | "other";
  titleJa: string;
  titleZh?: string;
  episode?: string;
  character?: string;
  lineJa: string;
  lineZh?: string;
  grammarHighlight: string;
  contextZh?: string;
  timestamp?: string;
  confidence: "verified" | "subtitle_verified" | "approximate" | "inspired_by";
  sourceUrl?: string;
}

export interface GrammarPattern {
  /** 唯一識別子（kebab-case） */
  id: string;
  level: JlptLevel;
  /** 文型本體，如「〜てもいい」、「〜にしても」 */
  pattern: string;
  /** 讀音（必要時） */
  reading?: string;
  meaningZh: string;
  meaningJa?: string;
  /** 接續規則，如「動詞て形＋もいい」 */
  formation: string;
  importance: GrammarImportance;
  tags: string[];
  examples: ExampleSentence[];
  /** 日劇／動漫台詞例句（有的話） */
  mediaExamples: MediaLineExample[];
  /** 相近文型的 id（指向 grammarPatterns 中的其他條目） */
  relatedPatternIds: string[];
  commonMistakes?: string[];
  sourceNotes?: string[];
}

// ------ N5 文型 ------

const n5Patterns: GrammarPattern[] = [
  {
    id: "te-mo-ii",
    level: "N5",
    pattern: "〜てもいい",
    meaningZh: "可以做～、～也沒關係",
    meaningJa: "～してもよい／許可を表す",
    formation: "動詞て形＋もいい",
    importance: "must_know",
    tags: ["許可"],
    examples: [
      { japanese: "ここで写真を撮ってもいいですか？", meaningZh: "可以在這裡拍照嗎？" },
      { japanese: "明日は休んでもいいですよ。", meaningZh: "明天休息也沒關係喔。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-wa-ikenai"],
    commonMistakes: [
      "口語中「〜てもいいですか」常省略為「〜ていいですか」",
    ],
  },
  {
    id: "te-wa-ikenai",
    level: "N5",
    pattern: "〜てはいけない",
    meaningZh: "不可以做～、禁止～",
    meaningJa: "～してはならない／禁止を表す",
    formation: "動詞て形＋はいけない",
    importance: "must_know",
    tags: ["禁止"],
    examples: [
      { japanese: "図書館で大きな声で話してはいけません。", meaningZh: "圖書館不可以大聲說話。" },
      { japanese: "ここに車を止めてはいけない。", meaningZh: "這裡不可以停車。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-mo-ii", "nakereba-naranai"],
  },
  {
    id: "nakereba-naranai",
    level: "N5",
    pattern: "〜なければならない",
    meaningZh: "必須做～、非做不可",
    meaningJa: "～する義務がある／必要を表す",
    formation: "動詞ない形（ない→なければ）＋ならない",
    importance: "must_know",
    tags: ["義務", "必要"],
    examples: [
      { japanese: "宿題をしなければならない。", meaningZh: "必須做功課。" },
      { japanese: "明日は早く起きなければなりません。", meaningZh: "明天必須早起。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["nakute-mo-ii"],
    commonMistakes: [
      "口語常省略為「〜なきゃ（ならない）」",
    ],
  },
  {
    id: "nakute-mo-ii",
    level: "N5",
    pattern: "〜なくてもいい",
    meaningZh: "不用做～、不做也可以",
    meaningJa: "～する必要はない／不要を表す",
    formation: "動詞ない形（ない→なくて）＋もいい",
    importance: "must_know",
    tags: ["不要", "許可"],
    examples: [
      { japanese: "明日は来なくてもいいですよ。", meaningZh: "明天不來也沒關係喔。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["nakereba-naranai"],
  },
  {
    id: "ta-ho-ga-ii",
    level: "N5",
    pattern: "〜たほうがいい",
    meaningZh: "最好做～",
    meaningJa: "～した方がよい／勧めを表す",
    formation: "動詞た形＋ほうがいい",
    importance: "must_know",
    tags: ["勸告", "建議"],
    examples: [
      { japanese: "早く寝たほうがいいよ。", meaningZh: "最好早點睡喔。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["nai-ho-ga-ii"],
  },
  {
    id: "nai-ho-ga-ii",
    level: "N5",
    pattern: "〜ないほうがいい",
    meaningZh: "最好不要做～",
    meaningJa: "～しない方がよい／否定的な勧め",
    formation: "動詞ない形＋ほうがいい",
    importance: "must_know",
    tags: ["勸告", "建議"],
    examples: [
      { japanese: "あの人には近づかないほうがいい。", meaningZh: "最好不要靠近那個人。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ta-ho-ga-ii"],
  },
  {
    id: "koto-ga-dekiru",
    level: "N5",
    pattern: "〜ことができる",
    meaningZh: "能夠做～、會做～",
    meaningJa: "～する能力がある／可能を表す",
    formation: "動詞辞書形＋ことができる",
    importance: "must_know",
    tags: ["可能", "能力"],
    examples: [
      { japanese: "日本語を話すことができます。", meaningZh: "會說日語。" },
      { japanese: "一人で行くことができますか？", meaningZh: "可以一個人去嗎？" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["tai"],
  },
  {
    id: "tai",
    level: "N5",
    pattern: "〜たい",
    meaningZh: "想要做～",
    meaningJa: "～したい／希望・欲求を表す",
    formation: "動詞ます形（去ます）＋たい",
    importance: "must_know",
    tags: ["希望", "欲望"],
    examples: [
      { japanese: "日本に行きたいです。", meaningZh: "想去日本。" },
      { japanese: "何を食べたい？", meaningZh: "想吃什麼？" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["koto-ga-dekiru"],
  },
  {
    id: "te-kudasai",
    level: "N5",
    pattern: "〜てください",
    meaningZh: "請做～",
    meaningJa: "～してください／依頼を表す",
    formation: "動詞て形＋ください",
    importance: "must_know",
    tags: ["依頼"],
    examples: [
      { japanese: "窓を閉めてください。", meaningZh: "請把窗戶關上。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-mo-ii", "te-wa-ikenai"],
  },
  {
    id: "to-omou",
    level: "N5",
    pattern: "〜と思う",
    meaningZh: "我認為～、我想～",
    meaningJa: "～と考える／意見・思考を表す",
    formation: "動詞・形容詞普通形＋と思う",
    importance: "must_know",
    tags: ["思考", "意見"],
    examples: [
      { japanese: "明日は雨が降ると思います。", meaningZh: "我想明天會下雨。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "kara",
    level: "N5",
    pattern: "〜から",
    meaningZh: "因為～（原因、理由）",
    meaningJa: "～だから／理由・原因を表す",
    formation: "動詞・形容詞普通形＋から",
    importance: "must_know",
    tags: ["原因", "理由"],
    examples: [
      { japanese: "安いから、買いました。", meaningZh: "因為便宜，所以買了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["node"],
    commonMistakes: [
      "「〜から」的主觀性比「〜ので」強，正式場合避免用「〜から」表理由",
    ],
  },
  {
    id: "node",
    level: "N5",
    pattern: "〜ので",
    meaningZh: "因為～（較客觀的原因）",
    meaningJa: "～なので／客観的な理由を表す",
    formation: "動詞・形容詞普通形＋ので；名詞・な形容詞＋な＋ので",
    importance: "must_know",
    tags: ["原因", "理由"],
    examples: [
      { japanese: "天気がいいので、散歩に行きます。", meaningZh: "因為天氣很好，所以去散步。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["kara"],
  },
  {
    id: "yori",
    level: "N5",
    pattern: "〜より",
    meaningZh: "比～更…",
    meaningJa: "～に比べて／比較を表す",
    formation: "名詞＋より",
    importance: "high_frequency",
    tags: ["比較"],
    examples: [
      { japanese: "日本語より英語のほうが簡単です。", meaningZh: "英語比日語簡單。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ho-ga"],
  },
  {
    id: "ho-ga",
    level: "N5",
    pattern: "〜ほうが",
    meaningZh: "～比較好、～比較…",
    meaningJa: "～の方が／比較の選択を表す",
    formation: "名詞＋の＋ほう／動詞た形＋ほう",
    importance: "high_frequency",
    tags: ["比較", "選擇"],
    examples: [
      { japanese: "電車のほうが速いです。", meaningZh: "電車比較快。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["yori"],
  },
  {
    id: "mashou",
    level: "N5",
    pattern: "〜ましょう",
    meaningZh: "～吧（提議、意志）",
    meaningJa: "～しましょう／勧誘・意志を表す",
    formation: "動詞ます形（去ます）＋ましょう",
    importance: "must_know",
    tags: ["勧誘", "意志"],
    examples: [
      { japanese: "一緒に行きましょう。", meaningZh: "一起去吧。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["tai"],
  },
];

// ------ N4 文型 ------

const n4Patterns: GrammarPattern[] = [
  {
    id: "te-iru",
    level: "N5",
    pattern: "〜ている",
    meaningZh: "正在～；～著（狀態）",
    meaningJa: "現在進行中／状態の継続を表す",
    formation: "動詞て形＋いる",
    importance: "must_know",
    tags: ["進行", "状態"],
    examples: [
      { japanese: "今、勉強しています。", meaningZh: "正在讀書。" },
      { japanese: "あの花が咲いている。", meaningZh: "那朵花開著。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-aru"],
  },
  {
    id: "te-aru",
    level: "N4",
    pattern: "〜てある",
    meaningZh: "已經～好了（刻意做的結果狀態）",
    meaningJa: "意図的な行為の結果状態を表す",
    formation: "他動詞て形＋ある",
    importance: "high_frequency",
    tags: ["状態", "準備"],
    examples: [
      { japanese: "窓が開けてある。", meaningZh: "窗戶開著（有人刻意打開的）。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-iru", "te-oku"],
  },
  {
    id: "te-oku",
    level: "N4",
    pattern: "〜ておく",
    meaningZh: "預先做～（準備）",
    meaningJa: "前もって準備することを表す",
    formation: "動詞て形＋おく",
    importance: "high_frequency",
    tags: ["準備"],
    examples: [
      { japanese: "旅行の前に切符を買っておきます。", meaningZh: "旅行前先買好車票。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-aru", "te-shimau"],
  },
  {
    id: "te-shimau",
    level: "N4",
    pattern: "〜てしまう",
    meaningZh: "做完～（完了）；不小心～（遺憾）",
    meaningJa: "完了／残念な気持ちを込めて",
    formation: "動詞て形＋しまう",
    importance: "high_frequency",
    tags: ["完了", "遺憾"],
    examples: [
      { japanese: "宿題を忘れてしまった。", meaningZh: "不小心忘記做功課了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-oku"],
  },
  {
    id: "te-miru",
    level: "N4",
    pattern: "〜てみる",
    meaningZh: "試試看～",
    meaningJa: "試しに～する",
    formation: "動詞て形＋みる",
    importance: "high_frequency",
    tags: ["試行"],
    examples: [
      { japanese: "このアプリを使ってみてください。", meaningZh: "請試試看這個應用程式。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "ta-koto-ga-aru",
    level: "N4",
    pattern: "〜たことがある",
    meaningZh: "曾經～過（經驗）",
    meaningJa: "過去の経験を表す",
    formation: "動詞た形＋ことがある",
    importance: "must_know",
    tags: ["経験"],
    examples: [
      { japanese: "富士山に登ったことがあります。", meaningZh: "爬過富士山。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
    commonMistakes: [
      "「〜たことがある」問的是經驗的有無，不要與「〜ている」（正在進行）混淆",
    ],
  },
  {
    id: "yasui",
    level: "N4",
    pattern: "〜やすい",
    meaningZh: "容易做～",
    meaningJa: "〜するのが簡単だ／傾向を表す",
    formation: "動詞ます形（去ます）＋やすい",
    importance: "high_frequency",
    tags: ["傾向", "難易"],
    examples: [
      { japanese: "このペンは書きやすいです。", meaningZh: "這枝筆很好寫。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["nikui"],
  },
  {
    id: "nikui",
    level: "N4",
    pattern: "〜にくい",
    meaningZh: "難以做～",
    meaningJa: "〜するのが難しい／否定傾向",
    formation: "動詞ます形（去ます）＋にくい",
    importance: "high_frequency",
    tags: ["傾向", "難易"],
    examples: [
      { japanese: "この漢字は覚えにくい。", meaningZh: "這個漢字很難記。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["yasui"],
  },
  {
    id: "sugiru",
    level: "N4",
    pattern: "〜すぎる",
    meaningZh: "太～、過度～",
    meaningJa: "程度が過剰であることを表す",
    formation: "動詞ます形（去ます）＋すぎる／形容詞語幹＋すぎる",
    importance: "high_frequency",
    tags: ["程度", "過剰"],
    examples: [
      { japanese: "食べすぎてお腹が痛い。", meaningZh: "吃太多肚子痛。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "nagara",
    level: "N4",
    pattern: "〜ながら",
    meaningZh: "一邊～一邊～",
    meaningJa: "同時に二つの動作をする",
    formation: "動詞ます形（去ます）＋ながら",
    importance: "must_know",
    tags: ["同時"],
    examples: [
      { japanese: "音楽を聴きながら勉強する。", meaningZh: "一邊聽音樂一邊讀書。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
    commonMistakes: [
      "前後主語必須相同，且後項為主動作",
    ],
  },
  {
    id: "ba-hodo",
    level: "N4",
    pattern: "〜ば〜ほど",
    meaningZh: "越～就越～",
    meaningJa: "程度が増すにつれて、別の程度も増す",
    formation: "動詞・形容詞の仮定形＋ば＋同語＋ほど",
    importance: "high_frequency",
    tags: ["比例", "程度"],
    examples: [
      { japanese: "練習すればするほど上手になる。", meaningZh: "越練習越進步。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "shika-nai",
    level: "N4",
    pattern: "〜しか〜ない",
    meaningZh: "只有～、僅～",
    meaningJa: "限定を表す（「だけ」の強調否定的表現）",
    formation: "名詞・數量詞＋しか＋否定形",
    importance: "must_know",
    tags: ["限定"],
    examples: [
      { japanese: "百円しか持っていない。", meaningZh: "只有一百日元。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
    commonMistakes: [
      "只能接否定形；肯定句用「だけ」",
    ],
  },
  {
    id: "hazu",
    level: "N4",
    pattern: "〜はず",
    meaningZh: "應該～（預計、推測）",
    meaningJa: "当然の推測・予定を表す",
    formation: "動詞・形容詞連体形＋はず",
    importance: "high_frequency",
    tags: ["推測", "予定"],
    examples: [
      { japanese: "彼はもう着いているはずです。", meaningZh: "他應該已經到了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["tsumori"],
  },
  {
    id: "tsumori",
    level: "N4",
    pattern: "〜つもり",
    meaningZh: "打算做～",
    meaningJa: "意志・予定を表す",
    formation: "動詞辞書形＋つもり／ない形＋つもり",
    importance: "high_frequency",
    tags: ["意志", "予定"],
    examples: [
      { japanese: "来年、日本に行くつもりです。", meaningZh: "打算明年去日本。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["hazu"],
    commonMistakes: [
      "「〜つもり」是主觀意圖；客觀預定用「〜予定」",
    ],
  },
  {
    id: "noni",
    level: "N4",
    pattern: "〜のに",
    meaningZh: "明明～卻～（逆接）",
    meaningJa: "意外・不満を込めた逆接",
    formation: "動詞・形容詞連体形＋のに",
    importance: "high_frequency",
    tags: ["逆接", "不満"],
    examples: [
      { japanese: "たくさん勉強したのに、試験に落ちた。", meaningZh: "明明讀了很多書，卻沒考過。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["nimo-kakawarazu", "monono"],
    commonMistakes: [
      "「〜のに」帶不滿或意外語氣，客觀事實的逆接用「〜が／〜けど」",
    ],
  },
];

// ------ N3 文型 ------

const n3Patterns: GrammarPattern[] = [
  {
    id: "wake-niwa-ikanai",
    level: "N3",
    pattern: "〜わけにはいかない",
    meaningZh: "不能做～（情理上不允許）",
    meaningJa: "〜するわけにはいかない／〜できない",
    formation: "動詞辞書形＋わけにはいかない",
    importance: "high_frequency",
    tags: ["禁止", "義務"],
    examples: [
      { japanese: "今日は大事な会議があるので、休むわけにはいかない。", meaningZh: "今天有重要會議，不能請假。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["zaru-wo-enai", "nakereba-naranai"],
    commonMistakes: [
      "「〜わけにはいかない」是社會常識上或情理上不能做，不是物理上的不可能",
    ],
  },
  {
    id: "kawarini",
    level: "N3",
    pattern: "〜かわりに",
    meaningZh: "代替～；作為交換～",
    meaningJa: "〜の代わりに／〜と引き換えに",
    formation: "名詞＋の＋かわりに；動詞辞書形＋かわりに",
    importance: "high_frequency",
    tags: ["代替", "交換"],
    examples: [
      { japanese: "母のかわりに、私が挨拶に行きました。", meaningZh: "代替母親，我去打了招呼。" },
      { japanese: "教えてもらうかわりに、昼をご馳走するよ。", meaningZh: "你教我，我請你吃午餐。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "ni-kanshite",
    level: "N3",
    pattern: "〜に関して",
    meaningZh: "關於～",
    meaningJa: "〜について／〜に関連して",
    formation: "名詞＋に関して",
    importance: "high_frequency",
    tags: ["関系", "話題"],
    examples: [
      { japanese: "この問題に関しては、後日改めて議論しましょう。", meaningZh: "關於這個問題，改天再討論吧。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-ojite"],
  },
  {
    id: "ni-taishite",
    level: "N3",
    pattern: "〜に対して",
    meaningZh: "對於～；相對於～",
    meaningJa: "〜に向かって／〜と対照的に",
    formation: "名詞＋に対して",
    importance: "high_frequency",
    tags: ["対象", "対比"],
    examples: [
      { japanese: "お客様に対しては丁寧な言葉を使いましょう。", meaningZh: "對客人要使用禮貌的用語。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-kanshite"],
  },
  {
    id: "ni-oite",
    level: "N3",
    pattern: "〜において",
    meaningZh: "在～（場合、領域、時代）",
    meaningJa: "〜で／〜の場で（改まった表現）",
    formation: "名詞＋において",
    importance: "understand",
    tags: ["場所", "時"],
    examples: [
      { japanese: "会議において、重要な決定がなされた。", meaningZh: "會議上做了重要決定。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-kanshite"],
  },
  {
    id: "ta-bakari",
    level: "N4",
    pattern: "〜たばかり",
    meaningZh: "剛做完～",
    meaningJa: "〜したところだ／完了直後",
    formation: "動詞た形＋ばかり",
    importance: "high_frequency",
    tags: ["時間", "完了"],
    examples: [
      { japanese: "さっきご飯を食べたばかりです。", meaningZh: "剛才才吃過飯。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ta-tokoro"],
  },
  {
    id: "you-ni-naru",
    level: "N4",
    pattern: "〜ようになる",
    meaningZh: "變得能夠～、已經會～",
    meaningJa: "状態の変化を表す",
    formation: "動詞辞書形＋ようになる；ない形＋なくなる",
    importance: "high_frequency",
    tags: ["変化", "可能"],
    examples: [
      { japanese: "日本語が少し話せるようになりました。", meaningZh: "變得會說一點日語了。" },
      { japanese: "最近、早起きするようになった。", meaningZh: "最近開始早起了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["koto-ni-naru", "te-kuru"],
  },
  {
    id: "koto-ni-naru",
    level: "N4",
    pattern: "〜ことになる",
    meaningZh: "變成～（客觀結果）、決定～",
    meaningJa: "客観的な決定や結果を表す",
    formation: "動詞辞書形＋ことになる；ない形＋ことになる",
    importance: "high_frequency",
    tags: ["決定", "結果"],
    examples: [
      { japanese: "来月、大阪に転勤することになりました。", meaningZh: "下個月決定調職到大阪。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["you-ni-naru", "koto-ni-shiteiru"],
  },
  {
    id: "koto-ni-shiteiru",
    level: "N3",
    pattern: "〜ことにしている",
    meaningZh: "習慣做～、規定自己要～",
    meaningJa: "習慣的に〜するようにしている",
    formation: "動詞辞書形＋ことにしている",
    importance: "understand",
    tags: ["習慣", "意志"],
    examples: [
      { japanese: "毎日ジョギングをすることにしている。", meaningZh: "我規定自己每天慢跑。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["you-ni-naru", "koto-ni-naru"],
  },
  {
    id: "te-kuru",
    level: "N4",
    pattern: "〜てくる",
    meaningZh: "開始～起來；～過來（動作方向）",
    meaningJa: "動作の開始／移動の方向を表す",
    formation: "動詞て形＋くる",
    importance: "high_frequency",
    tags: ["方向", "開始"],
    examples: [
      { japanese: "雨が降ってきた。", meaningZh: "開始下雨了。" },
      { japanese: "ちょっとコーヒーを買ってくる。", meaningZh: "我去買個咖啡過來。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-iku"],
  },
  {
    id: "te-iku",
    level: "N4",
    pattern: "〜ていく",
    meaningZh: "繼續～下去；～過去（動作方向）",
    meaningJa: "継続／移動の方向を表す",
    formation: "動詞て形＋いく",
    importance: "high_frequency",
    tags: ["継続", "方向"],
    examples: [
      { japanese: "これからも頑張っていきます。", meaningZh: "今後也會繼續努力下去。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-kuru"],
  },
  {
    id: "ni-yotte",
    level: "N3",
    pattern: "〜によって",
    meaningZh: "根據～、因～而異、藉由～",
    meaningJa: "〜に応じて／〜の手段で／原因",
    formation: "名詞＋によって",
    importance: "high_frequency",
    tags: ["手段", "原因", "対応"],
    examples: [
      { japanese: "国によって習慣が違う。", meaningZh: "因國家不同習慣也不同。" },
      { japanese: "地震によって多くの家が壊れた。", meaningZh: "因為地震很多房子壞了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-ojite", "ni-yoreba"],
  },
  {
    id: "ni-yoreba",
    level: "N3",
    pattern: "〜によると／〜によれば",
    meaningZh: "根據～（消息來源）",
    meaningJa: "情報源を示す",
    formation: "名詞＋によると／によれば",
    importance: "high_frequency",
    tags: ["情報", "伝聞"],
    examples: [
      { japanese: "天気予報によると、明日は雨だそうだ。", meaningZh: "根據天氣預報，明天會下雨。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-yotte"],
  },
  {
    id: "ni-totte",
    level: "N3",
    pattern: "〜にとって",
    meaningZh: "對～來說（從～的立場看）",
    meaningJa: "〜の立場から見ると",
    formation: "名詞＋にとって",
    importance: "high_frequency",
    tags: ["立場", "視点"],
    examples: [
      { japanese: "私にとって、家族は一番大切です。", meaningZh: "對我來說，家人最重要。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-taishite"],
  },
  {
    id: "toshite",
    level: "N3",
    pattern: "〜として",
    meaningZh: "作為～（身分、資格）",
    meaningJa: "〜の立場で／〜の資格で",
    formation: "名詞＋として",
    importance: "high_frequency",
    tags: ["立場", "資格"],
    examples: [
      { japanese: "留学生として日本に来ました。", meaningZh: "以留學生的身分來到日本。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-totte"],
  },
  {
    id: "ni-chigainai",
    level: "N3",
    pattern: "〜に違いない",
    meaningZh: "一定是～、肯定～",
    meaningJa: "〜に決まっている／強い推測",
    formation: "動詞・形容詞普通形＋に違いない；名詞＋に違いない",
    importance: "high_frequency",
    tags: ["推測", "確信"],
    examples: [
      { japanese: "あの人は日本人に違いない。", meaningZh: "那個人一定是日本人。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["hazu"],
  },
  {
    level: "N3",
    id: "shikanai-n3",
    pattern: "〜しかない",
    meaningZh: "只能～、除了～別無選擇",
    meaningJa: "〜するより方法がない",
    formation: "動詞辞書形＋しかない",
    importance: "high_frequency",
    tags: ["限定", "必然"],
    examples: [
      { japanese: "電車がないから、歩いて行くしかない。", meaningZh: "沒有電車，只能走路去。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["zaru-wo-enai"],
    commonMistakes: [
      "「〜しかない」是消極的不得已選擇；「〜ざるを得ない」更強制",
    ],
  },
  {
    id: "bakari",
    level: "N3",
    pattern: "〜ばかり",
    meaningZh: "只～、光～；滿是～",
    meaningJa: "〜だけ／〜だらけ",
    formation: "動詞て形＋ばかり；名詞＋ばかり",
    importance: "high_frequency",
    tags: ["限定", "強調"],
    examples: [
      { japanese: "遊んでばかりいると、試験に落ちるよ。", meaningZh: "只顧著玩的話，考試會不及格喔。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["shikanai-n3"],
  },
  {
    id: "sae-ba",
    level: "N3",
    pattern: "〜さえ〜ば",
    meaningZh: "只要～就～",
    meaningJa: "〜だけで十分で、あとは不要",
    formation: "名詞＋さえ＋動詞仮定形＋ば",
    importance: "understand",
    tags: ["条件", "強調"],
    examples: [
      { japanese: "あなたさえいてくれれば、他に何もいらない。", meaningZh: "只要有你在身邊，其他什麼都不需要。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "amari-ni",
    level: "N3",
    pattern: "〜あまり",
    meaningZh: "因為過度～（而導致）",
    meaningJa: "〜すぎて（その結果）",
    formation: "動詞辞書形＋あまり；名詞＋の＋あまり",
    importance: "understand",
    tags: ["原因", "程度"],
    examples: [
      { japanese: "嬉しさのあまり、涙が出た。", meaningZh: "因為太高興而流下了眼淚。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["sugiru"],
    commonMistakes: [
      "「〜あまり」的結果通常是強烈的情緒或狀態，不要用於一般因果",
    ],
  },
  {
    id: "tai-muki",
    level: "N3",
    pattern: "〜向け",
    meaningZh: "面向～、以～為對象",
    meaningJa: "〜を対象にして",
    formation: "名詞＋向け",
    importance: "understand",
    tags: ["対象", "用途"],
    examples: [
      { japanese: "この本は初心者向けです。", meaningZh: "這本書是面向初學者的。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-totte"],
  },
  {
    id: "tai-uchi-ni",
    level: "N3",
    pattern: "〜うちに",
    meaningZh: "在～期間內、趁著～",
    meaningJa: "〜の間（に）/ 〜している間に",
    formation: "動詞辞書形／ている形＋うちに；名詞＋の＋うちに",
    importance: "high_frequency",
    tags: ["時間", "範囲"],
    examples: [
      { japanese: "明るいうちに帰ったほうがいい。", meaningZh: "最好趁天亮的時候回去。" },
      { japanese: "忘れないうちにメモしておきます。", meaningZh: "趁還沒忘記先記下來。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "ta-tokoro",
    level: "N3",
    pattern: "〜たところ",
    meaningZh: "剛做完～（瞬間）",
    meaningJa: "〜したばかり／〜した時点",
    formation: "動詞た形＋ところ",
    importance: "high_frequency",
    tags: ["時間", "完了"],
    examples: [
      { japanese: "今、帰ってきたところです。", meaningZh: "剛回來。" },
      { japanese: "電話したところ、留守だった。", meaningZh: "打了電話，結果沒人接。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ta-bakari"],
  },
  {
    id: "nikui-kimi",
    level: "N3",
    pattern: "〜気味",
    meaningZh: "有點～、稍微有～的傾向",
    meaningJa: "〜の傾向がある／少し〜だ",
    formation: "名詞＋気味；動詞ます形（去ます）＋気味",
    importance: "understand",
    tags: ["傾向", "状態"],
    examples: [
      { japanese: "最近、疲れ気味です。", meaningZh: "最近有點累。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["gachi", "ppoi"],
  },
  {
    id: "gachi",
    level: "N3",
    pattern: "〜がち",
    meaningZh: "容易～、往往～（負面傾向）",
    meaningJa: "悪い傾向になりやすい",
    formation: "動詞ます形（去ます）＋がち；名詞＋がち",
    importance: "understand",
    tags: ["傾向", "習慣"],
    examples: [
      { japanese: "一人暮らしだと、野菜不足になりがちだ。", meaningZh: "一個人住容易蔬菜攝取不足。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["nikui-kimi"],
  },
  {
    id: "ppoi",
    level: "N3",
    pattern: "〜っぽい",
    meaningZh: "容易～、有～傾向、像～",
    meaningJa: "〜の傾向がある／〜のように見える",
    formation: "動詞ます形（去ます）＋っぽい；名詞＋っぽい",
    importance: "understand",
    tags: ["傾向", "性質"],
    examples: [
      { japanese: "彼は忘れっぽい性格だ。", meaningZh: "他是容易忘事的性格。" },
      { japanese: "このスープ、水っぽい。", meaningZh: "這個湯太稀了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["gachi"],
  },
  {
    id: "toori-ni",
    level: "N3",
    pattern: "〜とおりに",
    meaningZh: "按照～、正如～",
    meaningJa: "〜と同じように／〜のまま",
    formation: "名詞＋の＋とおりに；動詞辞書形／た形＋とおりに",
    importance: "high_frequency",
    tags: ["一致", "例示"],
    examples: [
      { japanese: "説明書のとおりに組み立ててください。", meaningZh: "請按照說明書組裝。" },
      { japanese: "言ったとおりにやってみて。", meaningZh: "照我說的試試看。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
];

// ------ N2 文型 ------

const n2Patterns: GrammarPattern[] = [
  {
    id: "ni-shitemo",
    level: "N2",
    pattern: "〜にしても",
    meaningZh: "就算～、即使以～來說",
    meaningJa: "〜という立場・状況を考慮しても",
    formation: "名詞＋にしても；動詞辞書形＋にしても",
    importance: "high_frequency",
    tags: ["譲歩", "逆接"],
    examples: [
      { japanese: "値段にしても、場所にしても、このアパートは最高だ。", meaningZh: "不論價格還是地點，這間公寓都是最好的。" },
      { japanese: "忙しいにしても、連絡ぐらいはできるだろう。", meaningZh: "就算再忙，至少聯絡一下總可以吧。" },
    ],
    mediaExamples: [
      {
        sourceType: "drama",
        titleJa: "カルテット",
        titleZh: "四重奏",
        lineJa: "悲しいにしても、人生は続くんだ。",
        lineZh: "即使悲傷，人生還是會繼續下去。",
        grammarHighlight: "にしても",
        confidence: "inspired_by",
      },
    ],
    relatedPatternIds: ["toshitemo"],
    commonMistakes: [
      "「〜にしても」與「〜としても」的差異：にしても偏「以某立場而言」，としても偏「即使假設某條件成立」",
    ],
  },
  {
    id: "kaneru",
    level: "N2",
    pattern: "〜かねる",
    meaningZh: "難以～、不便～、做不到～",
    meaningJa: "〜するのが難しい／〜できない",
    formation: "動詞ます形（去ます）＋かねる",
    importance: "high_frequency",
    tags: ["不可能", "困難"],
    examples: [
      { japanese: "その質問にはお答えしかねます。", meaningZh: "那個問題我難以回答（不便回答）。" },
      { japanese: "そんなことは私には決めかねます。", meaningZh: "那種事我無法決定。" },
    ],
    mediaExamples: [
      {
        sourceType: "drama",
        titleJa: "半沢直樹",
        titleZh: "半澤直樹",
        lineJa: "申し訳ございませんが、その条件ではお受けしかねます。",
        lineZh: "非常抱歉，那個條件我們難以接受。",
        grammarHighlight: "かねます",
        confidence: "inspired_by",
      },
    ],
    relatedPatternIds: ["nikui"],
    commonMistakes: [
      "「〜かねる」是敬語場合理性的婉拒，不是真的做不到；真的不能做用「〜できない」",
    ],
  },
  {
    id: "warini",
    level: "N2",
    pattern: "〜わりに",
    meaningZh: "雖然～卻～、以～來說算是～",
    meaningJa: "〜にしては／〜の割には",
    formation: "動詞・形容詞連体形＋わりに；名詞＋の＋わりに",
    importance: "high_frequency",
    tags: ["比較", "逆接"],
    examples: [
      { japanese: "あの店は安いわりに美味しい。", meaningZh: "那家店以價格來說算是好吃的。" },
      { japanese: "彼は勉強しないわりに成績がいい。", meaningZh: "他明明不讀書成績卻很好。" },
    ],
    mediaExamples: [
      {
        sourceType: "drama",
        titleJa: "逃げるは恥だが役に立つ",
        titleZh: "月薪嬌妻",
        lineJa: "年齢のわりに子供っぽいってよく言われるんです。",
        lineZh: "常被人說跟年齡比起來很孩子氣。",
        grammarHighlight: "わりに",
        confidence: "inspired_by",
      },
    ],
    relatedPatternIds: ["noni", "ni-shitemo"],
  },
  {
    id: "toshitemo",
    level: "N2",
    pattern: "〜としても",
    meaningZh: "即使～也～",
    meaningJa: "仮に〜しても（仮定条件の逆接）",
    formation: "動詞普通形＋としても；い形容詞普通形＋としても",
    importance: "high_frequency",
    tags: ["仮定", "逆接", "譲歩"],
    examples: [
      { japanese: "雨が降ったとしても、試合は行われます。", meaningZh: "即使下雨，比賽還是會舉行。" },
      { japanese: "間に合わないとしても、行くだけ行ってみよう。", meaningZh: "即使來不及，至少去試試看。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-shitemo"],
    commonMistakes: [
      "「〜としても」是純粹假設逆接；「〜にしても」可表「從某角度來看」的讓步",
    ],
  },
  {
    id: "monono",
    level: "N2",
    pattern: "〜ものの",
    meaningZh: "雖然～但是～",
    meaningJa: "〜けれども（実際にそうなっていない）",
    formation: "動詞・形容詞普通形＋ものの",
    importance: "high_frequency",
    tags: ["逆接", "譲歩"],
    examples: [
      { japanese: "留学したものの、あまり日本語が上達しなかった。", meaningZh: "雖然去留學了，但日語沒有進步多少。" },
      { japanese: "買ったものの、一度も使っていない。", meaningZh: "雖然買了，但一次也沒用過。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["noni", "nimo-kakawarazu"],
    commonMistakes: [
      "「〜ものの」暗示結果不如預期或未實現，比「〜が／〜けど」更強調轉折",
    ],
  },
  {
    id: "nimo-kakawarazu",
    level: "N2",
    pattern: "〜にもかかわらず",
    meaningZh: "儘管～卻～",
    meaningJa: "〜であるのに（予想に反して）",
    formation: "名詞＋にもかかわらず；動詞・形容詞普通形＋にもかかわらず",
    importance: "high_frequency",
    tags: ["逆接", "譲歩"],
    examples: [
      { japanese: "雨にもかかわらず、多くの人が集まった。", meaningZh: "儘管下雨，還是聚集了很多人。" },
      { japanese: "何度も注意したにもかかわらず、同じミスを繰り返している。", meaningZh: "儘管提醒了好幾次，還是在犯同樣的錯。" },
    ],
    mediaExamples: [
      {
        sourceType: "drama",
        titleJa: "リーガル・ハイ",
        titleZh: "王牌大律師",
        lineJa: "多くの反対にもかかわらず、彼は自分の信念を貫いた。",
        lineZh: "儘管有許多反對，他仍堅持了自己的信念。",
        grammarHighlight: "にもかかわらず",
        confidence: "inspired_by",
      },
    ],
    relatedPatternIds: ["monono", "noni"],
    commonMistakes: [
      "「〜にもかかわらず」比「〜のに」更正式、語氣更強烈",
    ],
  },
  {
    id: "bakari-ni",
    level: "N2",
    pattern: "〜ばかりに",
    meaningZh: "正因為～（才導致不好的結果）",
    meaningJa: "〜が原因で悪い結果になった",
    formation: "動詞・い形容詞普通形＋ばかりに；な形容詞＋な／名詞＋である＋ばかりに",
    importance: "high_frequency",
    tags: ["原因", "後悔"],
    examples: [
      { japanese: "彼の言葉を信じたばかりに、大金を失った。", meaningZh: "就因為相信了他的話，損失了一大筆錢。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["dake-atte"],
    commonMistakes: [
      "只用在負面結果，不要用於正面原因",
    ],
  },
  {
    id: "dake-atte",
    level: "N2",
    pattern: "〜だけあって",
    meaningZh: "不愧是～、正因為～",
    meaningJa: "〜にふさわしく（肯定的評価）",
    formation: "名詞＋だけあって；動詞・形容詞普通形＋だけあって",
    importance: "high_frequency",
    tags: ["評価", "原因"],
    examples: [
      { japanese: "さすが専門家だけあって、説明がわかりやすい。", meaningZh: "不愧是專家，說明很容易懂。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["bakari-ni"],
    commonMistakes: [
      "「〜だけあって」用在正面評價，與「〜ばかりに」（負面）方向相反",
    ],
  },
  {
    id: "ageku",
    level: "N2",
    pattern: "〜あげく",
    meaningZh: "～到最後（結果卻不盡人意）",
    meaningJa: "〜した末に（たいてい悪い結果）",
    formation: "動詞た形＋あげく；名詞＋の＋あげく",
    importance: "understand",
    tags: ["結果", "経過"],
    examples: [
      { japanese: "さんざん迷ったあげく、買わずに帰った。", meaningZh: "猶豫了半天，最後沒買就回去了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
    commonMistakes: [
      "「〜あげく」的結果幾乎總是負面或令人失望的",
    ],
  },
  {
    id: "ni-kagitte",
    level: "N2",
    pattern: "〜に限って",
    meaningZh: "偏偏在～的時候、只有～",
    meaningJa: "特に〜の場合に限り（悪いことが起こる）",
    formation: "名詞＋に限って",
    importance: "understand",
    tags: ["限定", "強調"],
    examples: [
      { japanese: "大事な日に限って、電車が遅れる。", meaningZh: "偏偏在重要的日子，電車就會誤點。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
    commonMistakes: [
      "常帶「偏偏在不好的時機發生」的口氣",
    ],
  },
  {
    id: "zaru-wo-enai",
    level: "N2",
    pattern: "〜ざるを得ない",
    meaningZh: "不得不～",
    meaningJa: "〜するしかない／強い義務",
    formation: "動詞ない形（−ない）＋ざるを得ない；する→せざるを得ない（例外）",
    importance: "high_frequency",
    tags: ["義務", "必然"],
    examples: [
      { japanese: "この状況では、計画を変更せざるを得ない。", meaningZh: "在這種情況下，不得不變更計畫。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["wake-niwa-ikanai"],
  },
  {
    id: "ni-ojite",
    level: "N2",
    pattern: "〜に応じて",
    meaningZh: "按照～、根據～",
    meaningJa: "〜に応じて／〜に従って",
    formation: "名詞＋に応じて",
    importance: "understand",
    tags: ["対応", "条件"],
    examples: [
      { japanese: "能力に応じて給料が決まります。", meaningZh: "薪水根據能力決定。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-kanshite"],
  },
  {
    id: "tsujite",
    level: "N2",
    pattern: "〜を通じて",
    meaningZh: "通過～；在～期間中",
    meaningJa: "〜を経由して／〜の間ずっと",
    formation: "名詞＋を通じて",
    importance: "understand",
    tags: ["手段", "期間"],
    examples: [
      { japanese: "インターネットを通じて世界中と繋がれる。", meaningZh: "透過網路可以與世界連結。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-taishite"],
  },
  {
    id: "nakaideha",
    level: "N2",
    pattern: "〜にかけては",
    meaningZh: "在～方面、論～的話",
    meaningJa: "〜の分野では（自信がある）",
    formation: "名詞＋にかけては",
    importance: "understand",
    tags: ["分野", "評価"],
    examples: [
      { japanese: "料理にかけては、彼女の右に出る者はいない。", meaningZh: "在料理方面，沒有人比她厲害。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-kanshite"],
  },
];

// ------ N1 文型 ------
// (#554 cleanup: 9 junk entries removed; some survivors re-levelled -- the
//  per-array grouping is historical, the `level` field is authoritative.)

const n1Patterns: GrammarPattern[] = [
  {
    id: "koto-kara",
    level: "N2",
    pattern: "〜ことから",
    meaningZh: "因為～、從～來看",
    meaningJa: "〜という理由で／〜から判断して",
    formation: "動詞・形容詞普通形＋ことから",
    importance: "high_frequency",
    tags: ["原因", "判断"],
    examples: [
      { japanese: "無実であることが明らかになったことから、彼は釈放された。", meaningZh: "因為真相大白，他被釋放了。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["kara"],
  },
  {
    id: "ni-katagata",
    level: "N1",
    pattern: "〜かたがた",
    meaningZh: "順便～、兼～",
    meaningJa: "〜を兼ねて",
    formation: "名詞＋かたがた",
    importance: "understand",
    tags: ["目的", "兼用"],
    examples: [
      { japanese: "お礼かたがた、ご挨拶に伺いました。", meaningZh: "順便道謝，前去拜訪。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["gatera"],
  },
  {
    id: "gatera",
    level: "N1",
    pattern: "〜がてら",
    meaningZh: "～的時候順便",
    meaningJa: "〜のついでに",
    formation: "動詞ます形（去ます）＋がてら；名詞＋がてら",
    importance: "understand",
    tags: ["目的", "兼用"],
    examples: [
      { japanese: "散歩がてら、駅前まで行ってみよう。", meaningZh: "散步時順便去車站前面看看。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-katagata"],
  },
  {
    id: "no-mono-da",
    level: "N3",
    pattern: "〜ものだ",
    meaningZh: "本是～、就該～（本質）",
    meaningJa: "本来当然〜であるべきだ",
    formation: "動詞辞書形／ない形＋ものだ",
    importance: "high_frequency",
    tags: ["本質", "当然", "一般論"],
    examples: [
      { japanese: "人間は忘れるものだ。", meaningZh: "人本來就是會遺忘的。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["bekarazu"],
  },
  {
    id: "bekarazu",
    level: "N1",
    pattern: "〜べからず",
    meaningZh: "禁止～（文書用）",
    meaningJa: "〜してはいけない（掲示・注意書き）",
    formation: "動詞辞書形＋べからず",
    importance: "understand",
    tags: ["禁止", "文語"],
    examples: [
      { japanese: "芝生に入るべからず。", meaningZh: "禁止進入草坪。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["te-wa-ikenai"],
  },
  {
    id: "bekushite",
    level: "N1",
    pattern: "〜べくして",
    meaningZh: "註定～（必然的結果）",
    meaningJa: "そうなる運命だった",
    formation: "動詞辞書形＋べくして",
    importance: "understand",
    tags: ["必然", "結果"],
    examples: [
      { japanese: "彼らの出会いは、出会うべくして出会った。", meaningZh: "他們的相遇是註定的。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["bekarazu"],
  },
  {
    id: "to-wa-kagiranai",
    level: "N3",
    pattern: "〜とは限らない",
    meaningZh: "未必～、不一定～",
    meaningJa: "必ずしも〜とは言えない",
    formation: "動詞・形容詞普通形＋とは限らない",
    importance: "high_frequency",
    tags: ["推測", "否定"],
    examples: [
      { japanese: "値段が高いものが必ずしも良いとは限らない。", meaningZh: "價格高的東西不一定就好。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-chigainai"],
  },
  {
    id: "to-ieba",
    level: "N3",
    pattern: "〜といえば",
    meaningZh: "說起～、提到～",
    meaningJa: "〜を話題にすると",
    formation: "名詞＋といえば",
    importance: "high_frequency",
    tags: ["話題", "連想"],
    examples: [
      { japanese: "日本といえば、富士山や寿司が有名だ。", meaningZh: "說起日本，富士山和壽司很有名。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["to-iu-to"],
  },
  {
    id: "to-iu-to",
    level: "N3",
    pattern: "〜というと",
    meaningZh: "提到～、說到～（確認）",
    meaningJa: "〜を聞くと／〜のことを言うと",
    formation: "名詞＋というと",
    importance: "understand",
    tags: ["話題", "確認"],
    examples: [
      { japanese: "新製品というと、あのスマートフォンのことですか？", meaningZh: "說到新產品，是指那個智慧型手機嗎？" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["to-ieba"],
  },
  {
    id: "ga-hayai-ka",
    level: "N1",
    pattern: "〜が早いか",
    meaningZh: "剛～就～",
    meaningJa: "〜するとすぐに",
    formation: "動詞辞書形／た形＋が早いか",
    importance: "understand",
    tags: ["時間", "同時"],
    examples: [
      { japanese: "ベルが鳴るが早いか、子供たちは教室を飛び出した。", meaningZh: "鈴聲一響，孩子們就衝出了教室。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ta-tokoro"],
  },
  {
    id: "nimo-oyobazu",
    level: "N1",
    pattern: "〜には及ばない",
    meaningZh: "不必～、用不著～；不及～",
    meaningJa: "〜する必要はない／〜に劣る",
    formation: "動詞辞書形＋には及ばない；名詞＋には及ばない",
    importance: "understand",
    tags: ["比較", "否定"],
    examples: [
      { japanese: "わざわざお越しくださるには及びません。", meaningZh: "不必特地跑一趟。" },
    ],
    mediaExamples: [],
    relatedPatternIds: [],
  },
  {
    id: "to-ie-dom",
    level: "N1",
    pattern: "〜といえども",
    meaningZh: "雖說～、即使是～",
    meaningJa: "〜であっても（強い譲歩）",
    formation: "名詞＋といえども",
    importance: "understand",
    tags: ["譲歩", "文語"],
    examples: [
      { japanese: "医者といえども、風邪をひくことはある。", meaningZh: "即使是醫生，也有感冒的時候。" },
    ],
    mediaExamples: [],
    relatedPatternIds: ["ni-shitemo", "toshitemo"],
  },
];

// 全部まとめて
export const grammarPatterns: GrammarPattern[] = [
  ...n5Patterns,
  ...n4Patterns,
  ...n3Patterns,
  ...n2Patterns,
  ...n1Patterns,
];
