import type { PracticeQuestion } from "../../types";
import { examQuestion } from "../helpers";

export const n2Items: PracticeQuestion[] = [
  examQuestion({
    id: "n2-grammar-nitomonatte",
    level: "N2",
    surface: "に伴って",
    reading: "にともなって",
    meaningZh: "隨著、伴隨",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "産業の発展 ___、地域の雇用環境も大きく変化した。",
    promptContextZh: "隨著產業發展，地方的就業環境也大幅改變。",
    hintZh: "產業發展與地方就業環境的關聯。",
    expectedAnswer: "に伴って",
    options: ["に伴って", "によると", "に限って", "に対して"],
    explanation: "「Aに伴ってB」表示 B 隨著 A 的變化一起發生。這裡是產業發展帶動雇用環境變化。"
  }),
  examQuestion({
    id: "n2-grammar-naikotoniwa",
    level: "N2",
    surface: "ないことには",
    reading: "ないことには",
    meaningZh: "若不...就無法...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "実際に現場を見てみ ___、原因は判断できない。",
    promptContextZh: "沒有實際看現場，就無法判斷原因。",
    hintZh: "判斷原因時對現場觀察的必要性。",
    expectedAnswer: "ないことには",
    options: ["ないことには", "ない限り", "なくしては", "なしには"],
    explanation: "四個都帶有「若沒...就...」的精神，但細節不同：「ないことには〜ない」強調「必須先實際做 V，否則...」；「ない限り〜ない」強調「在 V 沒成立的範圍內」（持續狀態）；「なくしては〜ない」是「沒有 N 就不...」（要求 N 是名詞）；「なしには」也是「沒有 N...就不」（要求 N 是名詞）。本句的「見てみ」是 Vて+みる 的連用，必須選「ないことには」對應動詞句。"
  }),
  examQuestion({
    id: "n2-grammar-womegutte",
    level: "N2",
    surface: "をめぐって",
    reading: "をめぐって",
    meaningZh: "圍繞、針對",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新しい評価制度の導入 ___、社内で意見が分かれている。",
    promptContextZh: "公司內部圍繞新評價制度的導入意見分歧。",
    hintZh: "公司導入新評價制度後出現的議論。",
    expectedAnswer: "をめぐって",
    options: ["をめぐって", "をこめて", "を問わず", "をはじめ"],
    explanation: "「Aをめぐって」表示以 A 為中心產生議論、對立或問題。後面的「意見が分かれている」很典型。"
  }),
  examQuestion({
    id: "n2-grammar-kanenai",
    level: "N2",
    surface: "かねない",
    reading: "かねない",
    meaningZh: "有可能造成壞結果",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "情報管理を怠れば、会社の信用を失い ___。",
    promptContextZh: "若疏忽資訊管理，可能失去公司信用。",
    hintZh: "資訊管理疏忽對公司信用的影響。",
    expectedAnswer: "かねない",
    options: ["かねない", "がたい", "そうだ", "うる"],
    explanation: "「Vます形 + かねない」=「有可能發生（壞結果）」。其餘三個都能接 Vます形：「がたい」是「（人主觀上）難以...」；「そうだ」（樣態）是「看起來會...」（觀察推測，正負皆可）；「うる」是「有可能...」（中性可能性，常用於正面或客觀）。本句強調「會釀成負面結果」，唯有「かねない」精準。"
  }),
  examQuestion({
    id: "n2-grammar-zaruwoenai",
    level: "N2",
    surface: "ざるを得ない",
    reading: "ざるをえない",
    meaningZh: "不得不",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "十分な資料がそろっていないため、結論を見送ら ___。",
    promptContextZh: "因為資料不足，不得不暫緩結論。",
    hintZh: "資料不足時對結論的處理。",
    expectedAnswer: "ざるを得ない",
    options: ["ざるを得ない", "ないではいられない", "ずにはおかない", "かねない"],
    explanation: "「Vない形去ない + ざるを得ない」表示沒有其他選擇，只能那樣做。"
  }),
  examQuestion({
    id: "n2-grammar-nisakidatte",
    level: "N2",
    surface: "に先立って",
    reading: "にさきだって",
    meaningZh: "在...之前",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "記者会見 ___、関係者に資料が配布された。",
    promptContextZh: "在記者會之前，資料已發給相關人士。",
    hintZh: "記者會與資料發放的時間關係。",
    expectedAnswer: "に先立って",
    options: ["に先立って", "に応じて", "に反して", "に沿って"],
    explanation: "「Aに先立ってB」表示 B 在 A 之前先進行，常見於正式活動、發表、會議。"
  }),
  examQuestion({
    id: "n2-grammar-nimokakawarazu",
    level: "N2",
    surface: "にもかかわらず",
    reading: "にもかかわらず",
    meaningZh: "儘管、雖然",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "大雨 ___、説明会には多くの参加者が集まった。",
    promptContextZh: "儘管下大雨，說明會仍聚集了許多參加者。",
    hintZh: "大雨天氣與說明會出席狀況。",
    expectedAnswer: "にもかかわらず",
    options: ["にもかかわらず", "を問わず", "のもかまわず", "のせいで"],
    explanation: "「Nにもかかわらず」表示「儘管 N（普遍會阻止），結果卻仍 B」。「Nを問わず」是「不論 N 為何」（多用於範圍中性，如年齢を問わず）；「Nのもかまわず」是「不顧 N」（強調自我中心地不在乎）；「Nのせいで」是「因為 N（負面原因）」（順因果，方向相反）。本句下大雨仍聚集人潮，是強烈逆接，要用「にもかかわらず」。"
  }),
  examQuestion({
    id: "n2-text-ippoude",
    level: "N2",
    surface: "一方で",
    reading: "いっぽうで",
    meaningZh: "另一方面",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "電子申請は手続きの時間を短縮できる。___、高齢者には操作が難しいという声もある。",
    promptContextZh: "前句說優點，後句提出另一面向的問題。",
    expectedAnswer: "一方で",
    options: ["一方で", "とはいえ", "もっとも", "それに対して"],
    explanation: "四個都帶逆接／補述語氣，差別在語感：「一方で」是平衡並列兩個面向（優點 vs 課題）；「とはいえ」是承認前句之後的讓步（雖然...但...）；「もっとも」是補加例外或限制；「それに対して」是強烈直接的對比。本句一邊講優點、另一邊講困擾，最自然的是「一方で」。"
  }),
  examQuestion({
    id: "n2-order-yosoku-shigatai",
    level: "N2",
    surface: "しがたい",
    reading: "しがたい",
    meaningZh: "難以...",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［専門家でさえ / 予測しがたい / ほど / 市場の変化が / 速い］",
    promptContextZh: "市場變化快到連專家都難以預測。",
    expectedAnswer: "専門家でさえ予測しがたいほど市場の変化が速い",
    options: [
      "専門家でさえ予測しがたいほど市場の変化が速い",
      "市場の変化が専門家でさえほど予測しがたい速い",
      "専門家ほど市場の変化が速いでさえ予測しがたい",
      "予測しがたい市場でさえ専門家の変化がほど速い"
    ],
    explanation: "「AほどB」表示程度；「専門家でさえ」放在「予測しがたい」前，強調連專家也難以預測。"
  }),
  examQuestion({
    id: "n2-order-zaruwoenai",
    level: "N2",
    surface: "ざるを得ない",
    reading: "ざるをえない",
    meaningZh: "不得不",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［安全上の問題が / 見つかったため / 計画を / 変更せざるを得ない］",
    promptContextZh: "因為發現安全問題，不得不改變計畫。",
    expectedAnswer: "安全上の問題が見つかったため計画を変更せざるを得ない",
    options: [
      "安全上の問題が見つかったため計画を変更せざるを得ない",
      "計画を安全上の問題が変更せざるを得ない見つかったため",
      "見つかったため計画が安全上の問題を変更せざるを得ない",
      "安全上の問題を計画が見つかったため変更せざるを得ない"
    ],
    explanation: "原因句「安全上の問題が見つかったため」在前，後句接「計画を変更せざるを得ない」。"
  }),
  examQuestion({
    id: "n2-grammar-monono",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然...但...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "ダイエットを始めた ___ 、なかなか体重が減らない。",
    promptContextZh: "雖然開始減肥了，但體重一直沒減少。",
    hintZh: "開始減肥後體重的變化。",
    expectedAnswer: "ものの",
    options: ["ものの", "ことに", "ものを", "ように"],
    explanation: "「A ものの、B」表示「雖然 A，但是 B」，書面語逆接。「ものを」帶後悔語氣「明明可以...卻沒」。"
  }),
  examQuestion({
    id: "n2-grammar-karakoso",
    level: "N2",
    surface: "からこそ",
    reading: "からこそ",
    meaningZh: "正因為",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "君のことを思っている ___ 、こんなに厳しく言うのだ。",
    promptContextZh: "正因為為了你著想，才這麼嚴格地說。",
    hintZh: "對對方的關心與嚴厲態度的關係。",
    expectedAnswer: "からこそ",
    options: ["からこそ", "からといって", "からには", "からして"],
    explanation: "「A からこそ B」強調「正是因為 A」的唯一原因。「からといって」是「不能因為...就」；「からには」是「既然...就應該」。"
  }),
  examQuestion({
    id: "n2-grammar-niatatte",
    level: "N2",
    surface: "にあたって",
    reading: "にあたって",
    meaningZh: "在...之際",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新しいプロジェクトを始める ___ 、関係者を集めて打ち合わせをした。",
    promptContextZh: "在開始新項目之際，召集了相關人員開會。",
    hintZh: "啟動新項目時的準備工作。",
    expectedAnswer: "にあたって",
    options: ["にあたって", "について", "に対して", "に従って"],
    explanation: "「Vる/N にあたって」用於正式場合，表示「在某重要時刻」。「について」是「關於」；「に対して」是「對於」；「に従って」是「隨著」。"
  }),
  examQuestion({
    id: "n2-grammar-nikanshite",
    level: "N2",
    surface: "に関して",
    reading: "にかんして",
    meaningZh: "關於",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この問題 ___ 、皆さんのご意見を伺いたい。",
    promptContextZh: "關於這個問題，想聽聽大家的意見。",
    hintZh: "就某問題向大家徵詢意見。",
    expectedAnswer: "に関して",
    options: ["に関して", "に伴って", "に応じて", "に反して"],
    explanation: "「Nに関して」表示「關於 N」，較「について」正式。「に伴って」是「隨著」；「に応じて」是「依照」；「に反して」是「與...相反」。"
  }),
  examQuestion({
    id: "n2-grammar-nishitewa",
    level: "N2",
    surface: "にしては",
    reading: "にしては",
    meaningZh: "作為...來說（偏離預期）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は日本に来てまだ三か月 ___ 、日本語が上手だ。",
    promptContextZh: "他來日本才三個月，日語就講得很好。",
    hintZh: "他來日本的時間與日語能力的關係。",
    expectedAnswer: "にしては",
    options: ["にしては", "にしても", "にしたら", "について"],
    explanation: "「N にしては」表示「以 N 來說（偏離預期）」。「にしても」是「即使...也」；「にしたら」是「站在 N 的立場」。"
  }),
  examQuestion({
    id: "n2-grammar-dokoroka",
    level: "N2",
    surface: "どころか",
    reading: "どころか",
    meaningZh: "別說...連...都...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "宿題は終わる ___ 、まだ半分もやっていない。",
    promptContextZh: "別說作業沒寫完，連一半都還沒做。",
    expectedAnswer: "どころか",
    options: ["どころか", "ばかりか", "うえに", "に加えて"],
    explanation: "「A どころか B」表示「別說 A，連 B 都...」的強烈反向。「ばかりか」是「不只 A，B 也」(正向累加)；「うえに / に加えて」也是累加。"
  }),
  examQuestion({
    id: "n2-grammar-mai",
    level: "N2",
    surface: "まい",
    reading: "まい",
    meaningZh: "絕不（強烈否定意志）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あんな店には二度と行く ___ と心に決めた。",
    promptContextZh: "我下定決心，再也不去那種店了。",
    expectedAnswer: "まい",
    options: ["まい", "ない", "なくて", "ぬ"]
,
    explanation: "「Vる + まい」(一類動詞辭書形；二類動詞「るまい / ようまい」)表示「絕對不做」的強烈決心，書面正式。「ぬ」是文語否定但無強烈意志。"
  }),
  examQuestion({
    id: "n2-grammar-bakarika",
    level: "N2",
    surface: "ばかりか",
    reading: "ばかりか",
    meaningZh: "不只...連...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は日本語 ___ 、中国語も韓国語も流暢に話せる。",
    promptContextZh: "他不只會說日語，連中文、韓文都很流利。",
    expectedAnswer: "ばかりか",
    options: ["ばかりか", "ばかりで", "ばかりに", "ばかりだ"],
    explanation: "「A ばかりか B」表示「不只 A，連 B 也」。「ばかりに」是「就因為...才」(負面結果)；「ばかりで」是「只...而已」。"
  }),
  examQuestion({
    id: "n2-grammar-monodakara",
    level: "N2",
    surface: "ものだから",
    reading: "ものだから",
    meaningZh: "因為...（辯解）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "外があまりにも寒かった ___ 、つい厚着をしてしまった。",
    promptContextZh: "因為外面實在太冷了，不知不覺就穿了很厚。",
    expectedAnswer: "ものだから",
    options: ["ものだから", "ものなら", "ものの", "ものか"],
    explanation: "「A ものだから B」用來解釋原因，常帶辯解語氣。「ものなら」表示假設；「ものの」是「雖然」；「ものか」是反問「怎麼可能」。"
  }),
  examQuestion({
    id: "n2-grammar-uede",
    level: "N2",
    surface: "うえで",
    reading: "うえで",
    meaningZh: "在...之後（再）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "資料をよく読んだ ___ で、ご判断ください。",
    promptContextZh: "請仔細閱讀資料之後再判斷。",
    expectedAnswer: "うえ",
    options: ["うえ", "ばかり", "ところ", "そば"],
    explanation: "「Vた + うえで」表示「在 V 之後（再進入下一步）」，正式。「ばかり」是「剛剛」；「ところ」是「動作階段」；「そば」是「N 旁邊」。"
  }),
  examQuestion({
    id: "n2-grammar-nimotozuite",
    level: "N2",
    surface: "にもとづいて",
    reading: "にもとづいて",
    meaningZh: "依據、根據",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "アンケートの 結果 ___ 、新しい サービスが 設計された。",
    promptContextZh: "依據問卷調查的結果設計了新服務。",
    expectedAnswer: "にもとづいて",
    options: ["にもとづいて", "にあたって", "に関して", "に対して"],
    explanation: "「N にもとづいて」表示「以 N 為根據/依據」。「にあたって」是「在...之際」；「に関して」是「關於」；「に対して」是「對於」。"
  }),
  examQuestion({
    id: "n2-grammar-nisuginai",
    level: "N2",
    surface: "にすぎない",
    reading: "にすぎない",
    meaningZh: "只不過是",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "これは あくまでも 個人的な 意見 ___ 、決定では ありません。",
    promptContextZh: "這只不過是個人意見，並不是決定。",
    expectedAnswer: "にすぎず",
    options: ["にすぎず", "にちがいなく", "にきまっており", "にほかならず"],
    explanation: "「N にすぎない」表示「不過是 N 而已」。「にちがいない」是「一定是」；「にきまっている」是「肯定」；「にほかならない」是「正是」 — 三個都是肯定加強，與「にすぎない」的縮小相反。"
  }),
  examQuestion({
    id: "n2-grammar-tsutsuaru",
    level: "N2",
    surface: "つつある",
    reading: "つつある",
    meaningZh: "正在逐漸...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "地球の 平均気温は 徐々に 上昇し ___ 。",
    promptContextZh: "地球的平均氣溫正在逐漸上升。",
    expectedAnswer: "つつある",
    options: ["つつある", "かけている", "ながら", "ばかりだ"],
    explanation: "「Vます形 + つつある」表示「正在持續/逐步 V」，書面正式。「かけている」是「做到一半」；「ばかりだ」是「越來越」；「ながら」是「同時」。"
  }),
  examQuestion({
    id: "n2-grammar-dokorodewanai",
    level: "N2",
    surface: "どころではない",
    reading: "どころではない",
    meaningZh: "哪有空...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "明日 試験だから、テレビを 見ている ___ 。",
    promptContextZh: "明天就要考試了，哪有空看電視。",
    expectedAnswer: "どころではない",
    options: ["どころではない", "わけがない", "ものではない", "にちがいない"],
    explanation: "「V ている + どころではない」表示「沒餘力做 V」。「わけがない」是「不可能」；「ものではない」是「不該做」；「にちがいない」是「一定」。"
  }),
  examQuestion({
    id: "n2-grammar-ueni",
    level: "N2",
    surface: "うえに",
    reading: "うえに",
    meaningZh: "而且，加上",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は 仕事が できる ___ 、人柄も いい。",
    promptContextZh: "他工作能力強，而且人品也好。",
    expectedAnswer: "うえに",
    options: ["うえに", "うえで", "うえは", "うえも"],
    explanation: "「A うえに B」表示 A 之外還加上同方向的 B。「うえで」是「在 A 之後再 B」；「うえは」是「既然 A 就應 B」；「うえも」不存在。"
  }),
  examQuestion({
    id: "n2-grammar-bakarini",
    level: "N2",
    surface: "ばかりに",
    reading: "ばかりに",
    meaningZh: "就因為...（壞結果）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "甘い 物を 食べすぎた ___ 、虫歯に なって しまった。",
    promptContextZh: "就因為甜食吃太多，蛀牙了。",
    expectedAnswer: "ばかりに",
    options: ["ばかりに", "おかげで", "ものの", "からといって"],
    explanation: "「A ばかりに B」表示「就因為 A 才導致負面 B」，本句「就因為甜食吃太多才蛀牙」。「おかげで」引出正面結果（蛀牙負面，不合）；「ものの」是「雖然…但…」的逆接（與因果方向相反）；「からといって」是「不能因為…就…」。三者都不表此負面因果，唯「ばかりに」成立。"
  }),
  examQuestion({
    id: "n2-grammar-uchiha",
    level: "N2",
    surface: "うちは",
    reading: "うちは",
    meaningZh: "在...的時候",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "若い ___ は、いろいろな ことに 挑戦した ほうが いい。",
    promptContextZh: "趁年輕的時候，多挑戰各種事情比較好。",
    expectedAnswer: "うち",
    options: ["うち", "あいだ", "なか", "うえ"],
    explanation: "「N/V + うちは」強調「在某狀態還持續時，趁機做」。「あいだ」也是「期間」但較中性；「なか」是「之中」；「うえ」是「之上/之後」。"
  }),
  examQuestion({
    id: "n2-grammar-nishiro",
    level: "N2",
    surface: "にしろ",
    reading: "にしろ",
    meaningZh: "無論...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "どんな 仕事 ___ 、最後まで 責任を 持つべきだ。",
    promptContextZh: "無論什麼樣的工作，都應該負責到底。",
    expectedAnswer: "にしろ",
    options: ["にしろ", "にしては", "については", "によって"],
    explanation: "「N にしろ」表示「即使是 N，也...」的讓步。「にしては」是「以 N 來說（偏離預期）」；「については」是「關於 N」；「によって」是「依照」。"
  }),
  examQuestion({
    id: "n2-grammar-kotoda",
    level: "N2",
    surface: "ことだ",
    reading: "ことだ",
    meaningZh: "應該...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "健康の ためには、毎日 運動する ___ 。",
    promptContextZh: "為了健康，每天運動是該做的事。",
    expectedAnswer: "ことだ",
    options: ["ことだ", "ものだ", "ためだ", "ところだ"],
    explanation: "「Vる + ことだ」是給特定對象的「應該做」的建議。「ものだ」是普遍真理/常理；「ためだ」是「為了...」；「ところだ」是動作階段。"
  }),
  examQuestion({
    id: "n2-grammar-monoda",
    level: "N2",
    surface: "ものだ",
    reading: "ものだ",
    meaningZh: "本來就...（普遍真理）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "人間は 誰でも いつかは 年を 取る ___ 。",
    promptContextZh: "人都會有變老的一天。",
    expectedAnswer: "ものだ",
    options: ["ものだ", "ことだ", "はずだ", "わけだ"],
    explanation: "「Vる + ものだ」表示「本來就是...」的普遍真理。「ことだ」是針對對象的忠告；「はずだ」是「應該（推測）」；「わけだ」是「原來如此」的歸結。"
  }),
  // -- N2 言い換え類義 ---------------------------------------------------------
  examQuestion({
    id: "n2-syn-osoraku",
    level: "N2",
    surface: "おそらく",
    reading: "おそらく",
    meaningZh: "（書面語）大概、恐怕",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼は 「おそらく」 もう 来ない だろう。",
    promptContextZh: "他大概不會再來了吧。",
    expectedAnswer: "たぶん",
    options: ["たぶん", "きっと", "もしかして", "必ず"],
    explanation: "「おそらく」≒「たぶん」（推測，把握中等）。「きっと」是「一定（信心高、近乎肯定）」；「もしかして」是「莫非（信心低、帶懷疑）」；「必ず」是「必定（100%、無推測語氣）」。四者沿確定程度排列，唯「たぶん」與「おそらく」同為中等推測。"
  }),
  examQuestion({
    id: "n2-syn-shocchu",
    level: "N2",
    surface: "しょっちゅう",
    reading: "しょっちゅう",
    meaningZh: "常常、動不動就",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼女は 「しょっちゅう」 遅刻する。",
    promptContextZh: "她常常遲到。",
    expectedAnswer: "頻繁に",
    options: ["頻繁に", "たまに", "ときどき", "いつも"],
    explanation: "「しょっちゅう」≒「頻繁に」（高頻率、屢屢）。「たまに」是「偶爾」（頻率低）；「ときどき」是「有時候」（頻率中等）；「いつも」是「總是、每次」（頻率最高，必發生）。要從頻率刻度上挑「高頻但非總是」的詞。"
  }),
  examQuestion({
    id: "n2-syn-sokkuri",
    level: "N2",
    surface: "そっくり",
    reading: "そっくり",
    meaningZh: "一模一樣、極相似",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "双子の 兄弟は 顔が 「そっくり」 だ。",
    promptContextZh: "雙胞胎兄弟臉長得一模一樣。",
    expectedAnswer: "よく 似ている",
    options: ["よく 似ている", "やや 似ている", "雰囲気が 似ている"],
    explanation: "「そっくり」= 高度相似、幾乎一模一樣 ≒「よく似ている」。「やや似ている」是「有點像」（程度太弱）；「雰囲気が似ている」是「氛圍接近」（不到外貌一模一樣）。"
  }),
  examQuestion({
    id: "n2-syn-gakkari",
    level: "N2",
    surface: "がっかり",
    reading: "がっかり",
    meaningZh: "失望、沮喪",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "試験に 落ちて、彼は 「がっかり」 した。",
    promptContextZh: "因為考試沒過，他很失望。",
    expectedAnswer: "失望",
    options: ["失望", "後悔", "戸惑い", "悲しみ"],
    explanation: "「がっかりする」≒「失望する」（期待落空的失落感）。「後悔」是事後悔不當初（責備自己）；「戸惑い」是不知所措、困惑；「悲しみ」是悲傷。雖然都是負面情緒，唯有「失望」精準對應「期待沒實現」。"
  }),
  examQuestion({
    id: "n2-syn-wazawaza",
    level: "N2",
    surface: "わざわざ",
    reading: "わざわざ",
    meaningZh: "（為了 X）特地、特意",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "雨の中、「わざわざ」 来て くれて ありがとう。",
    promptContextZh: "下雨還特地過來，謝謝你。",
    expectedAnswer: "特別に",
    options: ["特別に", "ついでに", "急いで"],
    explanation: "「わざわざ」= 為了某事特地花費心力（即使不便也來）≒「特別に」。「ついでに」是「順便」（剛好順手就做，與「特地」精神相反）；「急いで」是「匆忙地」（強調速度而非用心）。"
  }),
  // -- N2 用法 -----------------------------------------------------------------
  examQuestion({
    id: "n2-usage-habuku",
    level: "N2",
    surface: "省く",
    reading: "はぶく",
    meaningZh: "省略、刪去",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「省く」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「省く」用於省略、刪除多餘的部分。",
    expectedAnswer: "説明を 簡単に するため、専門用語を 省いた。",
    exampleJapanese: "説明を 簡単に するため、専門用語を 省いた。",
    exampleMeaningZh: "為了讓說明簡單，省略了專業術語。",
    options: [
      "説明を 簡単に するため、専門用語を 省いた。",
      "時間を 省くため、急いで 食事を した。",
      "彼は 約束を 省いて、来なかった。",
      "試験で 問題を 全部 省いて、白紙で 出した。"
    ],
    explanation: "「省く」= 省略不必要的部分（語句、步驟）。節省時間用「節約する／短縮する」，違反約定用「破る」，跳過題目用「飛ばす」。"
  }),
  examQuestion({
    id: "n2-usage-motomeru",
    level: "N2",
    surface: "求める",
    reading: "もとめる",
    meaningZh: "請求、徵求",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「求める」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「求める」是向人請求、要求某事物。",
    expectedAnswer: "判断に 迷ったので、上司に 助言を 求めた。",
    exampleJapanese: "判断に 迷ったので、上司に 助言を 求めた。",
    exampleMeaningZh: "因為拿不定主意，所以向上司請求建議。",
    options: [
      "判断に 迷ったので、上司に 助言を 求めた。",
      "なくした 指輪を 一日中 求めた。",
      "雨に 求められて、傘を 開いた。",
      "落し物の 鍵を 部屋中 求めて 探した。"
    ],
    explanation: "「求める」= 向他人請求（助言、協力、回答等抽象事物）。弄丟的具體物品（指輪・鍵）要用「探す」；被雨淋要用「降られる」。"
  }),
  examQuestion({
    id: "n2-usage-kotowaru",
    level: "N2",
    surface: "断る",
    reading: "ことわる",
    meaningZh: "拒絕、回絕",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「断る」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「断る」是拒絕邀請、要求。",
    expectedAnswer: "急な 誘いだったので、丁寧に 断った。",
    exampleJapanese: "急な 誘いだったので、丁寧に 断った。",
    exampleMeaningZh: "因為是突然的邀約，所以禮貌地拒絕了。",
    options: [
      "急な 誘いだったので、丁寧に 断った。",
      "強い 雨に 断られて、外出を やめた。",
      "兄に 断られた 服を 弟が 着て 出かけた。",
      "道路工事で 断られた ため、迂回した。"
    ],
    explanation: "「断る」= 拒絕邀請、請求等。被雨阻擋用「降られる」；衣服「不要的」用「着なくなった／お下がり」；道路因施工不通用「通れない／通行止め」。"
  }),
  examQuestion({
    id: "n2-usage-osamaru",
    level: "N2",
    surface: "収まる",
    reading: "おさまる",
    meaningZh: "（容納地）放得進去；平息",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の 文の うち、「収まる」の 使い方が 最も 適切なものは どれか。",
    promptContextZh: "「収まる」是東西容納於空間內，或情緒、騷動平息。",
    expectedAnswer: "大量の 荷物が なんとか この 箱に 収まった。",
    exampleJapanese: "大量の 荷物が なんとか この 箱に 収まった。",
    exampleMeaningZh: "大量行李勉強塞進這個箱子。",
    options: [
      "大量の 荷物が なんとか この 箱に 収まった。",
      "風邪が 収まって、薬を 飲んだ。",
      "彼の 怒りは 収まって、激しく 怒鳴った。",
      "夕食が 収まって、お腹が 空いて きた。"
    ],
    explanation: "「収まる」= 容納於某範圍內，或事態、情緒平息。但 B、C、D 在語意上自相矛盾（先平息又生病／先平息又生氣／吃飽又餓）。"
  }),
  // -- N2 文脈規定 -------------------------------------------------------------
  examQuestion({
    id: "n2-vocab-boshu",
    level: "N2",
    surface: "募集",
    reading: "ぼしゅう",
    meaningZh: "招募、徵求",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "来月の イベントで 手伝う ボランティアを ___ している。",
    promptContextZh: "正在募集下個月幫忙活動的志工。",
    expectedAnswer: "募集",
    options: ["募集", "招待", "採用", "入会"],
    explanation: "「募集」= 公開招募（人員、作品）。「招待」是邀請特定對象；「採用」是錄取後雇用；「入会」是（自己）入會（不能對外行動）。"
  }),
  examQuestion({
    id: "n2-vocab-taio",
    level: "N2",
    surface: "対応",
    reading: "たいおう",
    meaningZh: "因應、處理",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "顧客からの 苦情に 迅速に ___ する 必要が ある。",
    promptContextZh: "對於客戶投訴必須迅速處理。",
    expectedAnswer: "対応",
    options: ["対応", "対面", "対立", "対象"],
    explanation: "「対応」= 處理、應對（外部情況）。「対面」是面對面；「対立」是對立、衝突；「対象」是對象、目標。"
  }),
  examQuestion({
    id: "n2-vocab-omoitsuki",
    level: "N2",
    surface: "思いつき",
    reading: "おもいつき",
    meaningZh: "靈光一閃、隨興點子",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "彼の 行動は いつも 単なる ___ で、計画性が ない。",
    promptContextZh: "他的行動總是憑一時想到的點子，毫無計畫性。",
    expectedAnswer: "思いつき",
    options: ["思いつき", "思い込み", "思い出", "思いやり"],
    explanation: "「思いつき」= 突然想到的點子（多帶輕率語感）。「思い込み」是先入為主／一廂情願；「思い出」是回憶；「思いやり」是體貼。"
  }),
  examQuestion({
    id: "n2-vocab-tekisetsu",
    level: "N2",
    surface: "適切",
    reading: "てきせつ",
    meaningZh: "妥當、合適",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "面接では ___ な 言葉遣いを 心がけて ください。",
    promptContextZh: "面試時請留意使用合適的措辭。",
    expectedAnswer: "適切",
    options: ["適切", "適度", "適応", "適合"],
    explanation: "「適切」= 妥當、恰當（用於行為、判斷、措辭）。「適度」是程度適中（運動量等）；「適応」是適應（環境）；「適合」是符合（規格、條件）。"
  }),
  examQuestion({
    id: "n2-vocab-torikumu",
    level: "N2",
    surface: "取り組む",
    reading: "とりくむ",
    meaningZh: "（認真）著手處理",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "全社一丸と なって、環境問題に ___ いる。",
    promptContextZh: "全公司同心協力，正著手處理環境問題。",
    expectedAnswer: "取り組んで",
    options: ["取り組んで", "取り上げて", "取り消して", "取り入れて"],
    explanation: "「取り組む」= 認真投入處理（課題、問題）。「取り上げる」是「拿起／提及」；「取り消す」是「取消」；「取り入れる」是「導入、採納」。"
  }),
  // -- N2 文章脈絡 (paragraph context / connectives) --------------------------
  examQuestion({
    id: "n2-text-sonoue",
    level: "N2",
    surface: "そのうえ",
    reading: "そのうえ",
    meaningZh: "再加上、而且",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "このレストランは料金が手頃だ。___、味も本格的で評判がいい。",
    promptContextZh: "前句說價格便宜，後句疊加另一個優點：味道也好。",
    expectedAnswer: "そのうえ",
    options: ["そのうえ", "それにしても", "そのため", "つまり"],
    explanation: "前後同方向、後句再加一個優點，用「そのうえ」（再加上）。「それにしても」帶意外語氣；「そのため」是因果；「つまり」是換言之。"
  }),
  examQuestion({
    id: "n2-text-tokoroga",
    level: "N2",
    surface: "ところが",
    reading: "ところが",
    meaningZh: "（出乎意料）然而",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "出発前は天気予報も晴れだった。___、現地に着くと急に雨が降り出した。",
    promptContextZh: "原本預期晴天，結果到現場卻突然下雨。",
    expectedAnswer: "ところが",
    options: ["ところが", "そして", "それで", "なお"],
    explanation: "「ところが」表示「結果與預期相反、出乎意料」。「そして」是並列；「それで」是因果；「なお」是補述。"
  }),
  examQuestion({
    id: "n2-text-soredemo",
    level: "N2",
    surface: "それでも",
    reading: "それでも",
    meaningZh: "儘管如此、就算這樣",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "何度も練習を重ねた。___、本番では失敗してしまった。",
    promptContextZh: "雖然付出努力，本場仍然失敗。",
    expectedAnswer: "それでも",
    options: ["それでも", "だから", "すなわち", "そこで"],
    explanation: "「それでも」承認前句事實，但後句結果不如預期（讓步＋逆接）。「だから」是因果；「すなわち」是換言；「そこで」是「於是採取行動」。"
  }),
  // -- N2 文の組み立て (sentence assembly) -----------------------------------
  examQuestion({
    id: "n2-order-bakarika",
    level: "N2",
    surface: "ばかりか",
    reading: "ばかりか",
    meaningZh: "不只...還...",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［この店は / 料理がおいしい / 値段も手頃だ / ばかりか］",
    promptContextZh: "這家店不只料理好吃，價錢也合理。",
    expectedAnswer: "この店は料理がおいしいばかりか値段も手頃だ",
    options: [
      "この店は料理がおいしいばかりか値段も手頃だ",
      "ばかりかこの店は料理がおいしい値段も手頃だ",
      "この店はばかりか料理がおいしい値段も手頃だ",
      "値段も手頃だこの店は料理がおいしいばかりか"
    ],
    explanation: "「AばかりかB」是並列疊加：A 是已知優點，B 補充另一優點。「料理がおいしい」直接接「ばかりか」，後接「値段も手頃だ」；「ばかりか」不能放句首或緊跟「は」之後。"
  }),
  examQuestion({
    id: "n2-order-shidai",
    level: "N2",
    surface: "次第",
    reading: "しだい",
    meaningZh: "一...就...",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［結果が / 出次第 / 連絡を / します］",
    promptContextZh: "結果一出來就馬上聯絡您。",
    expectedAnswer: "結果が出次第連絡をします",
    options: [
      "結果が出次第連絡をします",
      "出次第結果が連絡をします",
      "連絡をします結果が出次第",
      "結果が連絡を出次第します"
    ],
    explanation: "「Vます形/N + 次第」=「一...就...」，前句條件、後句動作。「結果が出る」加「次第」後接後句「連絡をします」。「出次第」不能置於句首，「次第」也不能與其前面動詞分離。"
  }),
  examQuestion({
    id: "n2-order-nishitagatte",
    level: "N2",
    surface: "にしたがって",
    reading: "にしたがって",
    meaningZh: "隨著...",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［科学技術の発展 / 生活が / にしたがって / 便利になった］",
    promptContextZh: "隨著科技發展，生活變得便利。",
    expectedAnswer: "科学技術の発展にしたがって生活が便利になった",
    options: [
      "科学技術の発展にしたがって生活が便利になった",
      "にしたがって科学技術の発展生活が便利になった",
      "便利になった生活が科学技術の発展にしたがって",
      "生活がにしたがって科学技術の発展便利になった"
    ],
    explanation: "「Nにしたがって」表示伴隨變化，N 是變化來源、後句是隨之發生的變化。「科学技術の発展」直接接「にしたがって」，句尾以「便利になった」收。"
  }),
  examQuestion({
    id: "n2-order-tsutsuaru",
    level: "N2",
    surface: "つつある",
    reading: "つつある",
    meaningZh: "正在...中",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［日本社会は / 急速に / 高齢化し / つつある］",
    promptContextZh: "日本社會正快速地高齡化。",
    expectedAnswer: "日本社会は急速に高齢化しつつある",
    options: [
      "日本社会は急速に高齢化しつつある",
      "つつある日本社会は急速に高齢化し",
      "高齢化し日本社会は急速につつある",
      "急速に日本社会はつつある高齢化し"
    ],
    explanation: "「Vます形 + つつある」表示動作正在進行的階段。「高齢化し」直接接「つつある」收尾；副詞「急速に」修飾整個過程，置於主語之後動詞之前。"
  }),
  examQuestion({
    id: "n2-order-monono",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然...但...",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［免許は / 持っている / ものの / 運転には自信がない］",
    promptContextZh: "雖然有駕照，但對開車沒自信。",
    expectedAnswer: "免許は持っているものの運転には自信がない",
    options: [
      "免許は持っているものの運転には自信がない",
      "ものの免許は持っている運転には自信がない",
      "運転には自信がない免許は持っているものの",
      "免許はものの持っている運転には自信がない"
    ],
    explanation: "「Vている + ものの」是逆接連接，A ものの B = 「雖然 A 但 B」。「持っている」後直接接「ものの」，後接逆接句「運転には自信がない」。"
  }),
  // -- N2 文法形式選擇 (additional patterns) -----------------------------------
  examQuestion({
    id: "n2-grammar-dakeatte",
    level: "N2",
    surface: "だけあって",
    reading: "だけあって",
    meaningZh: "不愧是、正符合身分",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は十年も日本に住んでいる ___ 、日本語が非常に流暢だ。",
    promptContextZh: "他在日本住了十年，難怪日語非常流利。",
    expectedAnswer: "だけあって",
    options: ["だけあって", "ばかりに", "どころか", "ところで"],
    explanation: "「Vだけあって」表「不愧是…、與條件相符的好結果」，本句「住了十年，難怪日語流暢」。「ばかりに」是「正因…才（壞結果）」（流暢是好結果，不合）；「どころか」是「豈止…（反而相反）」（接續與語意都不合）；「ところで」是「即使…也」。三者都不表此相符的好結果，唯「だけあって」成立。"
  }),
  examQuestion({
    id: "n2-grammar-kotokara",
    level: "N2",
    surface: "ことから",
    reading: "ことから",
    meaningZh: "從...這個事實",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "現場に指紋が残っていた ___ 、犯人が特定された。",
    promptContextZh: "從現場留有指紋這個事實，鎖定了犯人。",
    expectedAnswer: "ことから",
    options: ["ことから", "ものだから", "ものの", "ばかりに"],
    explanation: "「Vた + ことから」表「以前面事實為依據而判斷／斷定」（客觀推理）。「ものだから」是個人辯解的因果；「ものの」是逆接；「ばかりに」是「正因為...才導致壞結果」。"
  }),
  examQuestion({
    id: "n2-grammar-tokoroni",
    level: "N2",
    surface: "ところに",
    reading: "ところに",
    meaningZh: "正當...的時候",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "夕食を作っている ___ 、母から電話がかかってきた。",
    promptContextZh: "正在做晚餐時，媽媽打電話來了。",
    expectedAnswer: "ところに",
    options: ["ところに", "ところで", "ところを", "ところまで"],
    explanation: "「Vている + ところに」表「正在做某事時，發生／介入了某事」。「ところで」是「即使...也」；「ところを」是「正在...被...」（多接被動／敬語）；「ところまで」是「到 N 為止」。"
  }),
  examQuestion({
    id: "n2-grammar-tabini",
    level: "N2",
    surface: "たびに",
    reading: "たびに",
    meaningZh: "每次...就...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この曲を聴く ___ 、学生時代を思い出す。",
    promptContextZh: "每次聽到這首曲子就會想起學生時代。",
    expectedAnswer: "たびに",
    options: ["たびに", "おりに", "さいに", "とともに"],
    explanation: "「Vる + たびに」表「每當 V 就...」（強調反覆對應）。「おりに／さいに」是「在...的特定場合」（單次事件）；「とともに」是「隨著／同時」。"
  }),
  examQuestion({
    id: "n2-grammar-kagiri",
    level: "N2",
    surface: "限り",
    reading: "かぎり",
    meaningZh: "就...範圍而言、只要...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "私が知る ___ 、彼はとても誠実な人だ。",
    promptContextZh: "就我所知，他是個非常誠實的人。",
    expectedAnswer: "限り",
    options: ["限り", "以上", "あいだ", "あげく"],
    explanation: "「Vる + 限り」表「在 V 的範圍／限度內」（多用於 evidential：以個人所知斷言）。「以上」是「既然」（理由）；「あいだ」是時間期間；「あげく」是「（負面）最終結果」。"
  }),
  examQuestion({
    id: "n2-grammar-amari",
    level: "N2",
    surface: "あまり",
    reading: "あまり",
    meaningZh: "過於...而...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "試合に勝ちたいと思う ___ 、力が入りすぎてしまった。",
    promptContextZh: "因為太想贏比賽，反而過度用力。",
    expectedAnswer: "あまり",
    options: ["あまり", "ばかり", "あげく", "あまりの"],
    explanation: "「Vる + あまり」表「因過度 V 而導致（負面）結果」。「ばかり」是「只／剛剛」；「あげく」是「費盡心思之後（負面）」；「あまりの」需接名詞（あまりの暑さに〜）。"
  }),
  examQuestion({
    id: "n2-grammar-nikawatte",
    level: "N2",
    surface: "にかわって",
    reading: "にかわって",
    meaningZh: "代替...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "病気で休んだ田中さん ___ 、私が会議に出席した。",
    promptContextZh: "我代替因病請假的田中先生出席會議。",
    expectedAnswer: "にかわって",
    options: ["にかわって", "について", "において", "にあたって"],
    explanation: "「Nにかわって」表「代替 N」（前者本應做某事，由他人代行）。「について」是「關於」；「において」是「在...（場合）」；「にあたって」是「在...的關鍵時刻」。"
  }),
  examQuestion({
    id: "n2-grammar-ijoha",
    level: "N2",
    surface: "以上",
    reading: "いじょう",
    meaningZh: "既然...就...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "試合に出場する ___ 、優勝を目指すしかない。",
    promptContextZh: "既然要參賽，就只能以奪冠為目標。",
    expectedAnswer: "以上",
    options: ["以上", "あげく", "ばかり", "ものの"],
    explanation: "「Vる/Vた + 以上（は）」表「既然 V，就有相應的責任」（強烈責任語氣）。「あげく」是「（費盡心思後的）負面結果」；「ばかり」是「只」；「ものの」是逆接。"
  }),
  // -- N2 漢字読み (kanji reading) ---------------------------------------------
  examQuestion({
    id: "n2-read-kaizen",
    level: "N2",
    surface: "改善",
    reading: "かいぜん",
    meaningZh: "改善",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "業務の流れを徹底的に「改善」する必要がある。",
    promptContextZh: "必須徹底改善業務流程。",
    expectedAnswer: "かいぜん",
    exampleJapanese: "業務の流れを徹底的に改善する必要がある。",
    exampleMeaningZh: "必須徹底改善業務流程。",
    options: ["かいぜん", "かいせん", "がいぜん", "こうぜん"],
    explanation: "「改」音讀「かい」，「善」音讀「ぜん」→ かいぜん。「かいせん」是「回線／改選」（清濁混淆）；「がいぜん」是「蓋然」（首字濁音化）；「こうぜん」是「公然」（首字錯讀）。"
  }),
  examQuestion({
    id: "n2-read-kentou",
    level: "N2",
    surface: "検討",
    reading: "けんとう",
    meaningZh: "檢討、研議",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "提案の内容を慎重に「検討」します。",
    promptContextZh: "我們會慎重研議提案內容。",
    expectedAnswer: "けんとう",
    exampleJapanese: "提案の内容を慎重に検討します。",
    exampleMeaningZh: "我們會慎重研議提案內容。",
    options: ["けんとう", "けんどう", "げんとう", "けんと"],
    explanation: "「検」音讀「けん」，「討」音讀「とう」→ けんとう。「けんどう」是「剣道」（次字濁音）；「げんとう」是「幻灯」（首字濁音）；「けんと」是缺長音（長音脫落）。"
  }),
  examQuestion({
    id: "n2-read-osaeru",
    level: "N2",
    surface: "抑える",
    reading: "おさえる",
    meaningZh: "壓抑、抑制",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "怒りを「抑える」のは大変な努力が必要だ。",
    promptContextZh: "壓抑怒氣需要極大的努力。",
    expectedAnswer: "おさえる",
    exampleJapanese: "怒りを抑えるのは大変な努力が必要だ。",
    exampleMeaningZh: "壓抑怒氣需要極大的努力。",
    options: ["おさえる", "おしえる", "つかえる", "おそえる"],
    explanation: "「抑」訓讀「おさ-える」→ おさえる。「おしえる」是「教える」（同形不同字混淆）；「つかえる」是「仕える／使える」；「おそえる」是錯誤的母音變體（無此單字）。"
  }),
  examQuestion({
    id: "n2-read-awateru",
    level: "N2",
    surface: "慌てる",
    reading: "あわてる",
    meaningZh: "慌張、驚慌",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "予期せぬ事態にも「慌てる」ことなく対応した。",
    promptContextZh: "面對突發狀況也不慌不忙地應對。",
    expectedAnswer: "あわてる",
    exampleJapanese: "予期せぬ事態にも慌てることなく対応した。",
    exampleMeaningZh: "面對突發狀況也不慌不忙地應對。",
    options: ["あわてる", "あばれる", "あおてる", "あつてる"],
    explanation: "「慌」訓讀「あわ-てる」→ あわてる。「あばれる」是「暴れる」（同義場景但字不同）；「あおてる」「あつてる」是無對應字的擬音陷阱。"
  }),
  examQuestion({
    id: "n2-read-magirawashii",
    level: "N2",
    surface: "紛らわしい",
    reading: "まぎらわしい",
    meaningZh: "容易混淆的",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この二つの表現は意味が「紛らわしい」。",
    promptContextZh: "這兩個表達意思容易搞混。",
    expectedAnswer: "まぎらわしい",
    exampleJapanese: "この二つの表現は意味が紛らわしい。",
    exampleMeaningZh: "這兩個表達意思容易搞混。",
    options: ["まぎらわしい", "まきらわしい", "まずらわしい", "みぎらわしい"],
    explanation: "「紛」訓讀「まぎ-らわしい」→ まぎらわしい。「まきらわしい」是清濁混淆；「まずらわしい」是子音錯誤；「みぎらわしい」是首音母音錯誤。"
  }),
  examQuestion({
    id: "n2-read-shousai",
    level: "N2",
    surface: "詳細",
    reading: "しょうさい",
    meaningZh: "詳細、詳情",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "事件の「詳細」については明日発表される。",
    promptContextZh: "事件詳情明天會公布。",
    expectedAnswer: "しょうさい",
    exampleJapanese: "事件の詳細については明日発表される。",
    exampleMeaningZh: "事件詳情明天會公布。",
    options: ["しょうさい", "しょさい", "しゅうさい", "しょうざい"],
    explanation: "「詳」音讀「しょう」，「細」音讀「さい」→ しょうさい。「しょさい」是「書斎」（長音脫落 → 撞到另一個詞）；「しゅうさい」是「秀才」（拗音換成 ゅう）；「しょうざい」是「商材」（次字濁音）。"
  }),
  examQuestion({
    id: "n2-grammar-seide",
    level: "N2",
    surface: "せいで",
    reading: "せいで",
    meaningZh: "都怪（負面原因）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "朝寝坊した ___、大事な会議に遅刻してしまった。",
    promptContextZh: "都怪睡過頭，重要的會議遲到了。",
    hintZh: "睡過頭和開會遲到的前後關連。",
    expectedAnswer: "せいで",
    options: ["せいで","おかげで","かわりに","からには"],
    explanation: "「〜せいで」把不好的結果歸咎於前項原因。「おかげで」是正面的「多虧」（本句是壞結果，不合）；「かわりに」是「代替／相對地」；「からには」是「既然…就」。本句要怪睡過頭導致遲到，唯有「せいで」。"
  }),
  examQuestion({
    id: "n2-grammar-kuseni",
    level: "N2",
    surface: "くせに",
    reading: "くせに",
    meaningZh: "明明卻（帶責備）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は本当は知っている ___、何も知らないふりをしている。",
    promptContextZh: "他明明知道，卻裝作什麼都不知道。",
    hintZh: "他其實知情，表面上的反應。",
    expectedAnswer: "くせに",
    options: ["くせに","おかげで","とおりに","かぎり"],
    explanation: "「〜くせに」是帶責備、不滿的「明明…卻」，前後同一主語。「おかげで」正面；「とおりに」是「按照」；「かぎり」是「只要／限度」。本句責備他裝傻，故「くせに」最合。與中性的「のに」相比，「くせに」語氣更帶輕蔑。"
  }),
  examQuestion({
    id: "n2-grammar-warini",
    level: "N2",
    surface: "わりに",
    reading: "わりに",
    meaningZh: "相對於意外地",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この店は値段が高い ___、味はそれほどでもない。",
    promptContextZh: "這家店價格雖高，味道卻沒那麼好（不成比例）。",
    hintZh: "價格與實際味道之間的落差。",
    expectedAnswer: "わりに",
    options: ["わりに","とおりに","うえに","ばかりに"],
    explanation: "「〜わりに」表示「就…的程度而言，結果與預期不成比例」。「とおりに」是「正如」；「うえに」是「不僅…而且…（追加同向）」（本句是反差，不合）；「ばかりに」是「就因為…造成壞結果」。本句價格高但味道不相稱，唯有「わりに」。"
  }),
  examQuestion({
    id: "n2-grammar-nitaishite",
    level: "N2",
    surface: "に対して",
    reading: "にたいして",
    meaningZh: "對於／相對比",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "兄が社交的なの ___、弟は内向的だ。",
    promptContextZh: "相對於哥哥很善於社交，弟弟則很內向。",
    hintZh: "兄弟兩人個性的並列比較。",
    expectedAnswer: "に対して",
    options: ["に対して","について","にとって","において"],
    explanation: "「〜に対して」在此表「對比」（A 相對於 B）。「について」是「關於（主題）」；「にとって」是「對…來說（立場）」；「において」是「在…場合/方面」。本句是哥哥 vs 弟弟的對比，故「に対して」。注意「に対して」另有「對某對象做動作」之意，靠語境分辨。"
  }),
  examQuestion({
    id: "n2-grammar-niyotte",
    level: "N2",
    surface: "によって",
    reading: "によって",
    meaningZh: "依而不同／透過",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "考え方は人 ___ さまざまだ。",
    promptContextZh: "想法因人而異，各有不同。",
    hintZh: "不同的人在想法上的差異。",
    expectedAnswer: "によって",
    options: ["によって","について","にかけて","にわたって"],
    explanation: "「〜によって」在此表「依…而各有不同」，常配「さまざま／違う／異なる」。「について」是「關於」；「にかけて」是「從…到…（範圍/時間）」；「にわたって」是「歷經…整個範圍」。本句「因人而異」是「によって」典型用法。"
  }),
  examQuestion({
    id: "n2-grammar-nichigainai",
    level: "N2",
    surface: "に違いない",
    reading: "にちがいない",
    meaningZh: "一定是（推測）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "電気が消えているから、彼はもう寝た ___。",
    promptContextZh: "燈關著，他一定已經睡了。",
    hintZh: "從關燈這個線索做出的判斷。",
    expectedAnswer: "に違いない",
    options: ["に違いない","わけがない","おそれがある","とは限らない"],
    explanation: "「〜に違いない」是「(根據根據)一定是…」的強推測。「わけがない」是「不可能」（相反）；「おそれがある」是「有…的危險」；「とは限らない」是「未必」。本句由關燈推斷「一定睡了」，唯有「に違いない」。"
  }),
  examQuestion({
    id: "n2-grammar-nioujite",
    level: "N2",
    surface: "に応じて",
    reading: "におうじて",
    meaningZh: "依而相應調整",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "収入 ___、税金の額も変わる。",
    promptContextZh: "稅金的金額會隨著收入而相應改變。",
    hintZh: "收入高低與要繳稅金之間的連動。",
    expectedAnswer: "に応じて",
    options: ["に応じて","において","に際して","をめぐって"],
    explanation: "「〜に応じて」是「配合…的變化而相應地（調整）」，前項常為可變的量（收入、能力、狀況）。「において」是「在…場合」；「に際して」是「在…之際」；「をめぐって」是「圍繞…（議論）」。本句稅額隨收入連動，故「に応じて」。"
  }),
  examQuestion({
    id: "n2-grammar-nisotte",
    level: "N2",
    surface: "に沿って",
    reading: "にそって",
    meaningZh: "沿著／按照方針",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "会社の方針 ___、計画を立て直した。",
    promptContextZh: "按照公司的方針，重新擬定了計畫。",
    hintZh: "公司既定方針與計畫之間的依循關係。",
    expectedAnswer: "に沿って",
    options: ["に沿って","に反して","をこめて","にかけて"],
    explanation: "「〜に沿って」是「順著（方針/期待/河川）」不偏離。「に反して」是「與…相反」（正相反）；「をこめて」是「滿懷（心意）」；「にかけて」是「從…到…」。本句依循公司方針，故「に沿って」。"
  }),
  examQuestion({
    id: "n2-grammar-nioite",
    level: "N2",
    surface: "において",
    reading: "において",
    meaningZh: "在場合／在方面",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "今日の会議は第一会議室 ___ 行われます。",
    promptContextZh: "今天的會議將在第一會議室舉行。",
    hintZh: "會議進行的場所說明。",
    expectedAnswer: "において",
    options: ["において","にとって","によって","に対して"],
    explanation: "「〜において」是書面的「在（某場所／時代／領域）」。「にとって」是「對…來說」；「によって」是「依／透過」；「に対して」是「對於／對比」。本句指出會議場所，故「において」。口語可用「で」，書面正式用「において」。"
  }),
  examQuestion({
    id: "n2-grammar-wohajime",
    level: "N2",
    surface: "をはじめ",
    reading: "をはじめ",
    meaningZh: "以為首及其他",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この動物園にはパンダ ___、さまざまな動物がいる。",
    promptContextZh: "這座動物園以熊貓為首，還有各式各樣的動物。",
    hintZh: "熊貓與園內其他動物的舉例關係。",
    expectedAnswer: "をはじめ",
    options: ["をはじめ","をこめて","を中心に","はもちろん"],
    explanation: "「N をはじめ(として)」是「以最具代表性的 N 為首，還有其他同類」。「をこめて」是「滿懷」；「を中心に」是「以…為中心」（強調核心而非舉例代表）；「はもちろん」是「…自不待言」需接「も」呼應。本句舉熊貓為代表再帶出其他，故「をはじめ」。"
  }),
  examQuestion({
    id: "n2-grammar-wotsuujite",
    level: "N2",
    surface: "を通じて",
    reading: "をつうじて",
    meaningZh: "透過／在整個期間",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "インターネット ___、世界中の人と交流できる。",
    promptContextZh: "透過網路，可以和世界各地的人交流。",
    hintZh: "網路作為與各地交流的手段。",
    expectedAnswer: "を通じて",
    options: ["を通じて","に応じて","をめぐって","にわたって"],
    explanation: "「〜を通じて」表「以…為媒介/手段」或「在整個期間一直」。「に応じて」是「依…相應」；「をめぐって」是「圍繞…議論」；「にわたって」是「歷經整個範圍」。本句網路是交流的手段，故「を通じて」。"
  }),
  examQuestion({
    id: "n2-grammar-womotoni",
    level: "N2",
    surface: "をもとに",
    reading: "をもとに",
    meaningZh: "以為依據",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "アンケートの結果 ___、新商品を開発した。",
    promptContextZh: "以問卷的結果為依據，開發了新商品。",
    hintZh: "問卷結果與新商品開發之間的根據關係。",
    expectedAnswer: "をもとに",
    options: ["をもとに","をめぐって","に応じて","に沿って"],
    explanation: "「〜をもとに(して)」是「以…為素材/根據」。「をめぐって」是「圍繞…」；「に応じて」是「依…相應調整」；「に沿って」是「順著方針」（沿著既定方向，非「以…為素材」）。本句以問卷為素材開發商品，故「をもとに」。"
  }),
  examQuestion({
    id: "n2-grammar-tototan",
    level: "N2",
    surface: "たとたん",
    reading: "たとたん",
    meaningZh: "一就在那瞬間",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "立ち上がっ ___、めまいがした。",
    promptContextZh: "一站起來，那一瞬間就頭暈了。",
    hintZh: "站起身那一刻身體出現的反應。",
    expectedAnswer: "たとたん",
    options: ["たとたん","たうえで","たところで","たばかり"],
    explanation: "「Vた + とたん(に)」是「就在 V 的那一瞬間，意外地發生後項」，後項多為說話者未預期、不可控的事。「たうえで」是「在做完…之後再…」（有計畫的順序）；「たところで」是「即使…也…」（讓步）；「たばかり」是「才剛…」（時間近）。本句站起瞬間突然暈眩，故「たとたん」。"
  }),
  examQuestion({
    id: "n2-grammar-tatokoro",
    level: "N2",
    surface: "たところ",
    reading: "たところ",
    meaningZh: "一結果發現",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "店に問い合わせ ___、すでに売り切れだった。",
    promptContextZh: "向店家詢問之後，結果發現已經賣完了。",
    hintZh: "向店家詢問後得到的回覆狀況。",
    expectedAnswer: "たところ",
    options: ["たところ","たとたん","たすえに","たかぎり"],
    explanation: "「Vた + ところ」是「做了 V 之後，(契機性地)發現/得到某結果」，偏書面、中性。「たとたん」強調「同一瞬間」且後項意外；「たすえに」是「歷經…最終」；「たかぎり」非固定句型。本句詢問後得知售罄，是「契機→發現」，故「たところ」。"
  }),
  examQuestion({
    id: "n2-grammar-ippouda",
    level: "N2",
    surface: "一方だ",
    reading: "いっぽうだ",
    meaningZh: "不斷單向發展",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "物価は上がる ___ 、生活は苦しくなる ___ 。",
    promptContextZh: "物價持續往上漲，（另一方面）生活也越來越辛苦。",
    hintZh: "兩個子句分別描述同時並進、且持續惡化的兩種趨勢。",
    expectedAnswer: "一方で / 一方だ",
    options: ["一方で / 一方だ", "ところで / ところだ", "次第で / 次第だ", "まま / ままだ"],
    explanation: "「Vる一方で、〜Vる一方だ」用「一方で」連接對比的另一面、句尾「一方だ」表單向持續發展（多為惡化）。本句「物價持續上漲（一方で），生活越來越苦（一方だ）」。「ところで／ところだ」是「正要／剛…」的時點；「次第で／次第だ」是「取決於／原委」；「まま／ままだ」是「保持原狀」，三組接續或語意都不合，唯「一方で / 一方だ」成立。"
  }),
  examQuestion({
    id: "n2-grammar-hanmen",
    level: "N2",
    surface: "反面",
    reading: "はんめん",
    meaningZh: "另一面相反",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この仕事は給料がいい ___、責任も重い。",
    promptContextZh: "這份工作薪水好，但另一方面責任也很重。",
    hintZh: "同一份工作的好處與代價並陳。",
    expectedAnswer: "反面",
    options: ["反面","うえに","あまり","ばかりに"],
    explanation: "「〜反面」是「同一事物有正反兩面」，前後對比。「うえに」是「不僅…而且…（同向追加）」（本句是正反對比，不合）；「あまり」是「由於太…（程度因果）」；「ばかりに」是「就因為…(壞結果)」。本句薪水好但責任重，是一體兩面，故「反面」。"
  }),
  examQuestion({
    id: "n2-grammar-ueha",
    level: "N2",
    surface: "上は",
    reading: "うえは",
    meaningZh: "既然就應當",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "引き受けた ___、最後まで責任を持ってやり遂げる。",
    promptContextZh: "既然接下了，就要負責到底完成它。",
    hintZh: "接下任務之後該有的覺悟。",
    expectedAnswer: "上は",
    options: ["上は","うちに","あげく","ところ"],
    explanation: "「Vた + 上は」是「既然已經…，理所當然就要/必須…」，後句常配決心或義務。「うちに」是「趁…的時候」；「あげく」是「…的結果(負面)」；「ところ」是「正在/契機」。本句既然接了就負責到底，故「上は」。與「以上(は)」近義，可互換。"
  }),
  examQuestion({
    id: "n2-grammar-shidai",
    level: "N2",
    surface: "次第",
    reading: "しだい",
    meaningZh: "一就立刻（書面）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "詳細が決まり ___、改めてご連絡いたします。",
    promptContextZh: "細節一確定，會再另行與您聯繫。",
    hintZh: "細節確定後接下來的聯繫安排。",
    expectedAnswer: "次第",
    options: ["次第","とたん","うちに","まま"],
    explanation: "「Vます stem + 次第」是「一…就立刻…」的書面、商務用法，後項是說話者意志（連絡する／お知らせする 等）。「とたん」也是「一…就…」但後項多為意外、不可控的事，且接 Vた；本句空格前是「決まり」(ます stem) 且後項是禮貌的意志行為，故「次第」。「うちに」是「趁…」；「まま」是「保持…狀態」。"
  }),
  examQuestion({
    id: "n2-grammar-nikaketewa",
    level: "N2",
    surface: "にかけては",
    reading: "にかけては",
    meaningZh: "在方面最拿手",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "料理の腕 ___、彼の右に出る者はいない。",
    promptContextZh: "在廚藝這方面，沒有人比得上他。",
    hintZh: "他在做菜這項能力上的地位。",
    expectedAnswer: "にかけては",
    options: ["にかけては","において","にとって","に関して"],
    explanation: "「N にかけては」是「論…(某能力/領域)的話，(某人)最厲害」，後句必為正面、稱讚。「において」是中性的「在…方面」(無稱讚義)；「にとって」是「對…來說」；「に関して」是「關於」。本句後句是「無人能及」的稱讚，故「にかけては」。"
  }),
  examQuestion({
    id: "n2-grammar-kake",
    level: "N2",
    surface: "かけ",
    reading: "かけ",
    meaningZh: "做到一半",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "読み ___ の本が机の上に置いてある。",
    promptContextZh: "讀到一半的書放在桌上。",
    hintZh: "桌上那本書目前的閱讀狀態。",
    expectedAnswer: "かけ",
    options: ["かけ","きり","がち","ぎみ"],
    explanation: "「Vます stem + かけ(の)」是「做到一半、還沒做完」。「きり」是「就…再也(沒)…」；「がち」是「容易/常常…(傾向)」；「ぎみ」是「略有…的感覺」。本句書讀到一半，故「かけ」。注意「かける」也可當動詞「開始做」，這裡是名詞化的中途狀態。"
  }),
  examQuestion({
    id: "n2-grammar-kirenai",
    level: "N2",
    surface: "きれない",
    reading: "きれない",
    meaningZh: "做不完／無法完全",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "料理が多すぎて、とても食べ ___。",
    promptContextZh: "菜太多了，實在吃不完。",
    hintZh: "菜量太多時對於吃光的可能性。",
    expectedAnswer: "きれない",
    options: ["きれない","がたい","かねない","ようがない"],
    explanation: "「Vます stem + きれない」是「(數量/程度太大)無法做完、做盡」。「がたい」是「(心理上)難以…」(如「信じがたい」)；「かねない」是「有可能(發生壞事)」；「ようがない」是「想做也沒方法」(本句是量太多吃不完，不是沒方法)。本句菜多到吃不完(數量)，故「きれない」。反義「きる」=徹底做完。"
  }),
  examQuestion({
    id: "n2-grammar-nuku",
    level: "N2",
    surface: "ぬく",
    reading: "ぬく",
    meaningZh: "堅持到底做完",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "苦しかったが、最後まで走り ___。",
    promptContextZh: "雖然很痛苦，但堅持跑到了最後。",
    hintZh: "在痛苦中對於這場跑步的完成方式。",
    expectedAnswer: "ぬく",
    options: ["ぬく","きる","かける","だす"],
    explanation: "「Vます stem + ぬく」是「克服困難、堅持到最後做完」，強調過程的艱辛與毅力。「きる」也是「完全做完」但偏「分量上做盡」、不強調克服困難；本句有「苦しかったが(雖然痛苦)」的奮鬥語感，故「ぬく」更貼。「かける」是「做到一半」；「だす」是「開始…起來」。"
  }),
  examQuestion({
    id: "n2-grammar-gachi",
    level: "N2",
    surface: "がち",
    reading: "がち",
    meaningZh: "容易往往（傾向）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "冬は寒くて、家にこもり ___ になる。",
    promptContextZh: "冬天很冷，往往容易窩在家裡。",
    hintZh: "天冷時對於外出意願的變化。",
    expectedAnswer: "がち",
    options: ["がち","ぎみ","っぽい","かけ"],
    explanation: "「Vます stem / N + がち」是「容易、往往(發生不太好的傾向)」。「ぎみ」是「略微帶有…的感覺」(程度輕)；「っぽい」是「帶有…性質/像…」；「かけ」是「做到一半」。本句天冷常窩家裡是傾向，故「がち」。「病気がち」「遅れがち」等為常見搭配。"
  }),
  examQuestion({
    id: "n2-grammar-gimi",
    level: "N2",
    surface: "気味",
    reading: "ぎみ",
    meaningZh: "略有的感覺",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "少し風邪 ___ なので、今日は早く帰ります。",
    promptContextZh: "有點感冒的感覺，所以今天早點回去。",
    hintZh: "身體目前不太舒服的輕微狀態。",
    expectedAnswer: "気味",
    options: ["気味","がち","だらけ","向き"],
    explanation: "「N / Vます stem + 気味」是「略微有…的傾向/感覺」(程度輕微)。「がち」是「常常、容易(發生)」(頻率傾向)；「だらけ」是「滿是…」；「向き」是「適合…」。本句「有點感冒」是輕微狀態，故「気味」。「太り気味」「疲れ気味」常見。"
  }),
  examQuestion({
    id: "n2-grammar-darake",
    level: "N2",
    surface: "だらけ",
    reading: "だらけ",
    meaningZh: "滿是（負面）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "子供は泥 ___ になって、元気に遊んでいる。",
    promptContextZh: "小孩弄得滿身是泥，精神十足地玩著。",
    hintZh: "小孩玩耍後全身的狀態。",
    expectedAnswer: "だらけ",
    options: ["だらけ","気味","がち","ばかり"],
    explanation: "「N + だらけ」是「(到處)滿是…」，多為負面、髒亂或數量多到困擾(泥・傷・間違い・借金)。「気味」是「略有…感覺」；「がち」是「常常…」；「ばかり」是「淨是、只有」(語感較中性，且常指單一事物反覆)。本句滿身是泥，故「だらけ」。"
  }),
  examQuestion({
    id: "n2-grammar-ppoi",
    level: "N2",
    surface: "っぽい",
    reading: "っぽい",
    meaningZh: "帶有像（性質）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は最近、怒り ___ 性格になった気がする。",
    promptContextZh: "感覺他最近變得有點易怒的性格。",
    hintZh: "對他近來性格變化的觀察。",
    expectedAnswer: "っぽい",
    options: ["っぽい","気味","がち","らしい"],
    explanation: "「N / Vます stem + っぽい」是「帶有…的性質、容易…、像…」(口語，常帶評價)。「気味」是「略有…感覺」；「がち」是「容易/常常(某行為)」；「らしい」是「像…該有的樣子」或「聽說」。本句指性格特質「易怒」，故「っぽい」。「怒りっぽい」「子供っぽい」「忘れっぽい」常見。"
  }),
  examQuestion({
    id: "n2-grammar-wakenihaikanai",
    level: "N2",
    surface: "わけにはいかない",
    reading: "わけにはいかない",
    meaningZh: "(情理上)不能",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "明日は大事な試験だから、休む ___。",
    promptContextZh: "明天有重要的考試，所以不能請假。",
    hintZh: "明天有考試時對於請假的考量。",
    expectedAnswer: "わけにはいかない",
    options: ["わけにはいかない","わけがない","ものではない","ことはない"],
    explanation: "「Vる + わけにはいかない」是「(基於情理、義務、心理)不能那樣做」。「わけがない」是「不可能(會)」(否定可能性)；「ものではない」是「不應該(道德常理)」；「ことはない」是「不必」。本句因考試而「不能請假」(情理上)，故「わけにはいかない」。"
  }),
  examQuestion({
    id: "n2-grammar-wakeganai",
    level: "N2",
    surface: "わけがない",
    reading: "わけがない",
    meaningZh: "不可能會",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あんなに練習したのだから、失敗する ___。",
    promptContextZh: "都練習得那麼勤了，不可能會失敗。",
    hintZh: "大量練習之後對失敗可能性的判斷。",
    expectedAnswer: "わけがない",
    options: ["わけがない","わけにはいかない","ほかない","までもない"],
    explanation: "「Vる + わけがない」是「(從道理推斷)絕不可能…」。「わけにはいかない」是「(情理上)不能…」；「ほかない」是「只能…」；「までもない」是「沒必要…」。本句由「練得那麼勤」推斷「不可能失敗」，故「わけがない」。"
  }),
  examQuestion({
    id: "n2-grammar-kotohanai",
    level: "N2",
    surface: "ことはない",
    reading: "ことはない",
    meaningZh: "沒必要用不著",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "まだ時間があるから、そんなに急ぐ ___。",
    promptContextZh: "還有時間，用不著那麼著急。",
    hintZh: "時間還夠時對於趕時間的看法。",
    expectedAnswer: "ことはない",
    options: ["ことはない","ものではない","わけがない","どころではない"],
    explanation: "「Vる + ことはない」是「沒必要…、用不著…」，常用於安慰或勸告。「ものではない」是「不應該(道德)」；「わけがない」是「不可能」；「どころではない」是「哪有心思…(根本不是…的時候)」。本句時間還夠、勸對方不必急，故「ことはない」。"
  }),
  examQuestion({
    id: "n2-grammar-nihokanaranai-genin",
    level: "N2",
    surface: "にほかならない",
    reading: "にほかならない",
    meaningZh: "正是、無非是",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "今回の混乱の原因は、事前の確認不足 ___。",
    promptContextZh: "這次混亂的原因正是事前確認不足。",
    hintZh: "說明造成混亂的核心原因。",
    expectedAnswer: "にほかならない",
    options: ["にほかならない","にすぎない","に相違ない","とは限らない"],
    explanation: "「Nにほかならない」表示正是 N、無非是 N。「にすぎない」是只不過；「に相違ない」是確信推測；「とは限らない」是否定必然。本句要斷定原因，選「にほかならない」。"
  }),
  examQuestion({
    id: "n2-grammar-nitomonatte-denshi",
    level: "N2",
    surface: "に伴って",
    reading: "にともなって",
    meaningZh: "伴隨、隨著",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "電子契約の普及 ___、社内の承認手続きも見直された。",
    promptContextZh: "隨著電子契約普及，公司內部的核准流程也被重新檢討。",
    hintZh: "電子契約普及後，公司內部流程的調整。",
    expectedAnswer: "に伴って",
    options: ["に伴って","にしたがって","に沿って","に応じて"],
    explanation: "「Nに伴って」表示某變化連帶帶來另一變化。「にしたがって」偏依照規則或漸進變化；「に沿って」是依照方針；「に応じて」是依條件調整。本句是普及造成流程跟著變動，最自然是「に伴って」。"
  }),
  examQuestion({
    id: "n2-grammar-nioujite-kenshu",
    level: "N2",
    surface: "に応じて",
    reading: "におうじて",
    meaningZh: "依照、根據不同情況",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "申込者の経験年数 ___、研修内容を三段階に分けている。",
    promptContextZh: "依申請者的經驗年數，將研修內容分成三個階段。",
    hintZh: "研修內容依參加者條件而調整。",
    expectedAnswer: "に応じて",
    options: ["に応じて","に沿って","に基づいて","に伴って"],
    explanation: "「Nに応じて」表示內容會配合 N 的差異而變化。「に沿って」是依方針；「に基づいて」是以資料或規則為根據；「に伴って」是伴隨變化。本句重點是按經驗年數分級，選「に応じて」。"
  }),
  examQuestion({
    id: "n2-grammar-womegutte-shineki",
    level: "N2",
    surface: "をめぐって",
    reading: "をめぐって",
    meaningZh: "圍繞、針對",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新駅の建設計画 ___、住民の間で賛否が分かれている。",
    promptContextZh: "居民之間圍繞新車站建設計畫意見分歧。",
    hintZh: "居民對新車站建設計畫有不同看法。",
    expectedAnswer: "をめぐって",
    options: ["をめぐって","について","に関して","を通じて"],
    explanation: "「Nをめぐって」常用於議論、対立、問題が起こる場合。「について」「に関して」只是一般「關於」，少了對立語感；「を通じて」是透過媒介或期間。本句有「賛否が分かれている」，最自然是「をめぐって」。"
  }),
  examQuestion({
    id: "n2-grammar-monono-seido",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然、但是",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新しい勤怠システムは導入された ___、現場ではまだ操作ミスが多い。",
    promptContextZh: "新的出勤系統雖然已導入，但現場仍有很多操作錯誤。",
    hintZh: "制度導入後，現場仍有實際運用問題。",
    expectedAnswer: "ものの",
    options: ["ものの","一方で","反面","に対して"],
    explanation: "「Vたものの」表示前項成立，但結果沒有如預期順利。「一方で」「反面」偏兩面並列；「に対して」是對比不同對象。本句是導入後仍未順利，選「ものの」。"
  }),
  examQuestion({
    id: "n2-grammar-nishitewa-kikakusho",
    level: "N2",
    surface: "にしては",
    reading: "にしては",
    meaningZh: "以...來說",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "入社一年目 ___、彼の企画書はかなり完成度が高い。",
    promptContextZh: "以入社第一年來說，他的企劃書完成度相當高。",
    hintZh: "評價一份企劃書時，把入社年資納入判斷。",
    expectedAnswer: "にしては",
    options: ["にしては","わりに","くせに","ものの"],
    explanation: "「Nにしては」表示以某身分、條件或標準來看，結果超出預期。「わりに」也可表示相對評價，但較口語且不如本句的基準明確；「くせに」帶責備；「ものの」是讓步。本句以「入社一年目」為基準評價，選「にしては」。"
  }),
  examQuestion({
    id: "n2-grammar-bakarini-kakunin",
    level: "N2",
    surface: "ばかりに",
    reading: "ばかりに",
    meaningZh: "只因為...就造成壞結果",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "確認を一度怠った ___、納品全体が遅れることになった。",
    promptContextZh: "只因一次疏忽確認，就導致整個交貨延誤。",
    hintZh: "一次確認疏忽造成後續交期問題。",
    expectedAnswer: "ばかりに",
    options: ["ばかりに","せいで","ことから","おかげで"],
    explanation: "「Vたばかりに」強調因為一個看似小的原因造成遺憾結果。「せいで」只是一般負面原因，沒有「小因大果」的惋惜語感；「ことから」是判斷依據或原因；「おかげで」通常是正面原因。本句有「一度」與大範圍延誤，選「ばかりに」。"
  }),
  examQuestion({
    id: "n2-grammar-tokoroni-shusei",
    level: "N2",
    surface: "ところに",
    reading: "ところに",
    meaningZh: "正當...時",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "ちょうど報告書を印刷しようとしていた ___、部長から修正の指示が入った。",
    promptContextZh: "正要印報告書時，部長提出了修改指示。",
    hintZh: "報告書印刷前，主管提出新的指示。",
    expectedAnswer: "ところに",
    options: ["ところに","最中に","折に","次第"],
    explanation: "「Vようとしていたところに」表示正要做某事時，另一事插進來。「最中に」偏「正在進行中」；「折に」是「時機、機會」較鄭重；「次第」是「一…就…」。本句是正要印刷時被打斷，選「ところに」。"
  }),
  examQuestion({
    id: "n2-grammar-wakeniha-yakusoku",
    level: "N2",
    surface: "わけにはいかない",
    reading: "わけにはいかない",
    meaningZh: "不能那樣做",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "取引先との約束がある以上、こちらの都合だけで日程を変える ___。",
    promptContextZh: "既然已經和客戶約好，就不能只因我方方便而更改日程。",
    hintZh: "已和外部對象約定後，日程調整受到限制。",
    expectedAnswer: "わけにはいかない",
    options: ["わけにはいかない","わけがない","ことはない","はずがない"],
    explanation: "「Vるわけにはいかない」表示因社會、道義或責任上的理由不能做。「わけがない」「はずがない」是否定可能性；「ことはない」是不必做。本句是約定造成不能任意改期，選「わけにはいかない」。"
  }),
  examQuestion({
    id: "n2-grammar-tsutsuaru-shinsei",
    level: "N2",
    surface: "つつある",
    reading: "つつある",
    meaningZh: "正在逐漸...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "紙の申請書は、オンライン手続きへと徐々に置き換えられ ___。",
    promptContextZh: "紙本申請書正逐漸被線上手續取代。",
    hintZh: "紙本與線上申請方式的轉換。",
    expectedAnswer: "つつある",
    options: ["つつある","ているところだ","一方だ","ばかりだ"],
    explanation: "「Vます形 + つつある」表示變化正在逐步進行。「ているところだ」偏「正在做某動作」；「一方だ」多表示單方向加劇；「ばかりだ」多接惡化。本句有「徐々に」的漸進變化，選「つつある」。"
  }),
  examQuestion({
    id: "text-ippoude-online",
    level: "N2",
    surface: "一方で",
    reading: "いっぽうで",
    meaningZh: "另一方面",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "オンライン授業は、通学時間を減らせる点で学生の負担を軽くする。録画を見直せるため、復習もしやすい。___、学生同士が偶然に話す機会は生まれにくい。",
    promptContextZh: "線上課有便利的一面，但學生之間偶然交流的機會較少。",
    hintZh: "便利性後接另一面向的問題。",
    expectedAnswer: "一方で",
    options: ["一方で","したがって","それにしても","なお"],
    explanation: "「一方で」對照同一主題的另一面。「したがって」是順接結論；「それにしても」是承認後的評價語氣；「なお」是補充，不形成明確對照。"
  }),
  examQuestion({
    id: "text-shitagatte-yosan",
    level: "N2",
    surface: "したがって",
    reading: "したがって",
    meaningZh: "因此",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "今年度の予算は、当初の見込みを下回ることが確実となった。新規事業に充てられる資金も限られている。___、各部署には計画の優先順位を見直してもらう必要がある。",
    promptContextZh: "因預算低於預期且新事業資金有限，因此需要各部門重新檢討計畫優先順序。",
    hintZh: "前面的條件導向後面的管理判斷。",
    expectedAnswer: "したがって",
    options: ["したがって","ところが","もっとも","その一方で"],
    explanation: "「したがって」表示由前文條件自然導出的結論。「ところが」是反轉；「もっとも」是補充限制；「その一方で」是對照另一面。"
  }),
  examQuestion({
    id: "text-nao-password",
    level: "N2",
    surface: "なお",
    reading: "なお",
    meaningZh: "此外、另外",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "会場では無料のWi-Fiをご利用いただけます。接続が不安定な場合は、近くのスタッフまでお声がけください。___、パスワードは当日受付でお渡しする資料に記載されています。",
    promptContextZh: "說明會場 Wi-Fi 與協助方式後，補充密碼位置。",
    hintZh: "服務說明後補充另一個實務資訊。",
    expectedAnswer: "なお",
    options: ["なお","ところが","それにもかかわらず","そのため"],
    explanation: "「なお」用於公告或說明中的補充資訊。「ところが」是轉折；「それにもかかわらず」是逆接；「そのため」是原因結果。"
  }),
  examQuestion({
    id: "n2-grammar-wotoiwazu-boshu",
    level: "N2",
    surface: "を問わず",
    reading: "をとわず",
    meaningZh: "不論、不問",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "経験の有無 ___、この研修にはどなたでも申し込めます。",
    promptContextZh: "不論是否有經驗，任何人都可以報名這項研修。",
    hintZh: "研修報名條件與經驗有無的關係。",
    expectedAnswer: "を問わず",
    options: ["を問わず","をはじめ","を通じて","をもとに"],
    explanation: "「Nを問わず」表示不以 N 的差異作為限制。「をはじめ」是列舉起點；「を通じて」是透過或整段期間；「をもとに」是以資料或事實為基礎。"
  }),
  examQuestion({
    id: "n2-grammar-nikagirazu-shimin",
    level: "N2",
    surface: "に限らず",
    reading: "にかぎらず",
    meaningZh: "不限於...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "学生 ___、社会人にもこの図書館の利用を広げる方針だ。",
    promptContextZh: "方針是不只學生，也把圖書館使用對象擴大到社會人士。",
    hintZh: "圖書館使用對象的擴大。",
    expectedAnswer: "に限らず",
    options: ["に限らず","に限って","に限り","に応じて"],
    explanation: "「Aに限らずBも」表示不限於 A，B 也包含在內。「に限って」是偏偏／唯有；「に限り」是限定條件；「に応じて」是依照差異調整。"
  }),
  examQuestion({
    id: "n2-grammar-kaneru-kojinjoho",
    level: "N2",
    surface: "かねる",
    reading: "かねる",
    meaningZh: "難以、無法",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "個人情報に関わるため、その件についてはお答え ___。",
    promptContextZh: "因為涉及個人資料，關於那件事無法回答。",
    hintZh: "客服或窗口對敏感資訊的回覆方式。",
    expectedAnswer: "しかねます",
    options: ["しかねます","しかねません","しきれます","しております"],
    explanation: "「Vます形 + かねる」是正式語氣的「難以／無法」，常用於婉拒，「お答えしかねます」是客服固定說法。「しかねません」是「可能會做出（不利之事）」的危險可能；「しきれます」是「做得完」；「しております」是「正在／已（謙讓）」與「無法回答」語意相反。唯「しかねます」表婉拒。"
  }),
  examQuestion({
    id: "n2-grammar-wokeikini-ryugaku",
    level: "N2",
    surface: "を契機に",
    reading: "をけいきに",
    meaningZh: "以...為契機",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "短期留学 ___、彼は日本語教育に強い関心を持つようになった。",
    promptContextZh: "以短期留學為契機，他開始對日語教育產生強烈興趣。",
    hintZh: "某次經驗成為後續興趣形成的轉折點。",
    expectedAnswer: "を契機に",
    options: ["を契機に","をめぐって","を問わず","を通じて"],
    explanation: "「Nを契機に」表示 N 成為後續變化的觸發點。「をめぐって」是圍繞爭議或議題；「を問わず」是不論；「を通じて」是透過手段或期間。"
  }),
  examQuestion({
    id: "n2-order-naikotoniwa-genba",
    level: "N2",
    surface: "ないことには",
    reading: "ないことには",
    meaningZh: "若不...就無法...",
    promptLabel: "語順組合",
    instructionZh: "語順組合：選語法正確且語意自然的句子。",
    promptText: "［現場の状況を / 確認しないことには / 原因を / 判断できない］",
    promptContextZh: "若不確認現場狀況，就無法判斷原因。",
    hintZh: "判斷前需要完成的確認動作。",
    expectedAnswer: "現場の状況を確認しないことには原因を判断できない",
    options: ["現場の状況を確認しないことには原因を判断できない","原因を確認しないことには現場の状況を判断できない","確認しないことには現場の状況を原因を判断できない","現場の状況を判断できない原因を確認しないことには"],
    explanation: "「Vないことには〜できない」是必要條件。先形成「現場の状況を確認しないことには」，再接無法做的判斷「原因を判断できない」。"
  }),
  examQuestion({
    id: "n2-grammar-monono-kaikei-cdx",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然…但是",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新しい会計システムは導入された ___ 、現場ではまだ紙の伝票を併用している。",
    promptContextZh: "雖然導入了新的會計系統，但現場仍同時併用紙本傳票。",
    hintZh: "新系統上線後，現場實際的作業方式。",
    expectedAnswer: "ものの",
    options: ["ものの", "からには", "ばかりに", "に先立って"],
    explanation: "「Aものの、B」表示既成事實 A 與預期相反的 B（書面語）。本句「系統雖已導入，現場卻仍用紙本」正是這種落差。「からには」是「既然…就應當…」（後接義務／決心）；「ばかりに」是「就因為…才招致壞結果」（強調單一負面原因）；「に先立って」是「在…之前」（時間先後）。三者都無法銜接「已導入卻仍併用」的轉折。"
  }),
  examQuestion({
    id: "n2-grammar-monono-setsumei-cdx",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然…但是",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "説明は一通り受けた ___ 、専門用語が多く、内容を十分に理解できなかった。",
    promptContextZh: "雖然大致聽過了說明，但專業術語太多，沒能充分理解內容。",
    hintZh: "聽完說明後，對內容的掌握程度。",
    expectedAnswer: "ものの",
    options: ["ものの", "ことから", "に応じて", "ばかりか"],
    explanation: "「Aものの、B」表示「A 雖成立，結果卻不如預期」。本句「聽過說明，卻沒能理解」即此逆接。「ことから」是「從 A 這件事可推知 B」（推論根據）；「に応じて」是「依照 A 相應地…」；「ばかりか」是「不僅 A，連 B 也…」（遞進添加）。三者方向皆與「聽了卻沒懂」的轉折不符。"
  }),
  examQuestion({
    id: "n2-grammar-kake-mail-cdx",
    level: "N2",
    surface: "かけ",
    reading: "かけ",
    meaningZh: "做到一半",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "メールを書き ___ で席を外したため、下書きのまま送信されていなかった。",
    promptContextZh: "因為郵件寫到一半就離開了座位，所以一直停在草稿狀態沒送出。",
    hintZh: "離開座位時，那封郵件處於什麼狀態。",
    expectedAnswer: "かけ",
    options: ["かけ", "終え", "直し", "抜き"],
    explanation: "「Vます stem + かけ(で／の)」表示「做到一半、尚未完成」，本句郵件寫到一半即停。「書き終え」是「寫完」（與「下書きのまま」矛盾）；「書き直し」是「重寫」；「書き抜き」是「摘錄」。語境是「中途未完成」，只有「かけ」成立。"
  }),
  examQuestion({
    id: "n2-grammar-gachi-shokuji-cdx",
    level: "N2",
    surface: "がち",
    reading: "がち",
    meaningZh: "容易、往往（傾向）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "忙しい時期は、食事を抜き ___ になるので、意識して休憩を取るようにしている。",
    promptContextZh: "忙碌的時期容易省略用餐，所以會刻意提醒自己休息。",
    hintZh: "工作忙碌時，用餐方面常出現的情況。",
    expectedAnswer: "がち",
    options: ["がち", "だらけ", "まみれ", "っぱなし"],
    explanation: "「Vます stem / N + がち」表示「容易、往往（發生不太理想的傾向）」，本句「忙起來常省略吃飯」即此頻率傾向。「だらけ」是「滿是…（負面之物）」（如「傷だらけ」）；「まみれ」是「沾滿…（液體／粉塵）」（如「泥まみれ」）；「っぱなし」是「一直保持…的狀態／放著不管」。只有「がち」表達「常常如此」的傾向。"
  }),
  examQuestion({
    id: "n2-grammar-nimotozuite-shanaikitei-cdx",
    level: "N2",
    surface: "にもとづいて",
    reading: "にもとづいて",
    meaningZh: "依據、根據",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "今回の処分は、社内規定 ___ 厳正に決定されたものだ。",
    promptContextZh: "這次的處分，是依據公司內部規定嚴正決定的。",
    hintZh: "做出這次處分時所依循的準則。",
    expectedAnswer: "にもとづいて",
    options: ["にもとづいて", "にかこつけて", "に反して", "をめぐって"],
    explanation: "「N + にもとづいて」表示「以 N 為根據／準則」，本句「依規定做出處分」即此。「にかこつけて」是「假借…為藉口」（負面）；「に反して」是「與…相反」；「をめぐって」是「圍繞…（爭論）」。處分以規定為依據，唯有「にもとづいて」。"
  }),
  examQuestion({
    id: "n2-grammar-nimotozuite-data-cdx",
    level: "N2",
    surface: "にもとづいて",
    reading: "にもとづいて",
    meaningZh: "依據、根據",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "調査で得られた客観的なデータ ___ 、改善案をまとめた。",
    promptContextZh: "根據調查所得的客觀數據，彙整出了改善方案。",
    hintZh: "彙整改善方案時所憑藉的東西。",
    expectedAnswer: "にもとづいて",
    options: ["にもとづいて", "に応じて", "に先立って", "に限って"],
    explanation: "「N + にもとづいて」表示「以 N 為根據」，本句「依客觀數據彙整方案」即此。「に応じて」是「依…相應變化／調整」（需有可對應的變數，如「収入に応じて」）；「に先立って」是「在…之前」（時間先後）；「に限って」是「偏偏只有…／唯獨…」。以數據為根據，唯有「にもとづいて」最自然。"
  }),
  examQuestion({
    id: "n2-grammar-womotoni-taiken-cdx",
    level: "N2",
    surface: "をもとに",
    reading: "をもとに",
    meaningZh: "以…為依據／素材",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "祖父の戦争体験 ___ 、一本の短編小説を書いた。",
    promptContextZh: "以祖父的戰爭經歷為題材，寫了一篇短篇小說。",
    hintZh: "寫這篇短篇小說時，取材自什麼。",
    expectedAnswer: "をもとに",
    options: ["をもとに", "に反して", "に応じて", "を問わず"],
    explanation: "「N + をもとに(して)」表示「以 N 為素材／藍本（再創作出別的東西）」，本句「取材祖父經歷寫小說」即此。「に反して」是「與…相反」；「に応じて」是「依…相應調整」；「を問わず」是「不論…（都一樣）」。創作的取材來源，唯有「をもとに」。"
  }),
  examQuestion({
    id: "n2-grammar-womotoni-shashin-cdx",
    level: "N2",
    surface: "をもとに",
    reading: "をもとに",
    meaningZh: "以…為依據／素材",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "古い町並みの写真 ___ 、当時の駅前の様子を模型で再現した。",
    promptContextZh: "以舊街景的照片為依據，用模型重現了當時車站前的樣貌。",
    hintZh: "重現車站前舊貌時，是參照什麼做出來的。",
    expectedAnswer: "をもとに",
    options: ["をもとに", "にかこつけて", "にいたって", "にあるまじき"],
    explanation: "「N + をもとに」表示「以 N 為依據／藍本」，本句「依舊照片重現車站樣貌」即此。「にかこつけて」是「假借…為藉口」；「にいたって」是「到了…地步才…」；「にあるまじき」是「身為…不該有的」。以照片為製作依據，唯有「をもとに」。"
  }),
  examQuestion({
    id: "n2-vocab-katayotte-cdx",
    level: "N2",
    surface: "偏って",
    reading: "かたよって",
    meaningZh: "偏向、不均衡",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "栄養が「偏って」いると、体調を崩しやすくなる。",
    promptContextZh: "營養一旦失衡，就容易把身體搞壞。",
    expectedAnswer: "かたよって",
    exampleJapanese: "栄養が偏っていると、体調を崩しやすくなる。",
    exampleMeaningZh: "營養一旦失衡，就容易把身體搞壞。",
    options: ["かたよって", "かたまって", "へだたって", "かたどって"],
    explanation: "「偏」訓讀「かたよ-る」→ て形「かたよって」。「かたまって」是「固まって」（凝固、聚成一塊，訓讀相近但不同字）；「へだたって」是「隔たって」（相隔、有距離，不同字）；「かたどって」是「象って／模って」（仿照外形，發音近似的陷阱）。表「營養失衡」的「偏って」讀作 かたよって。"
  }),
  examQuestion({
    id: "n2-vocab-taemanai-shien-cdx",
    level: "N2",
    surface: "絶え間ない",
    reading: "たえまない",
    meaningZh: "持續不斷的、不間斷的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "災害発生後、被災地には全国から ___ 支援が寄せられた。",
    promptContextZh: "災害發生後，全國各地源源不絕地送來對災區的援助。",
    hintZh: "災後全國對災區提供援助的方式。",
    expectedAnswer: "絶え間ない",
    options: ["絶え間ない", "限りない", "重大な", "適切な"],
    explanation: "「絶え間ない」表示「中間沒有停頓、接連不斷」，本句「援助源源不絕地送來」即此。「限りない」是「無止盡的」（強調無上限，不強調無間斷）；「重大な」是「重大的」（事態嚴重）；「適切な」是「適切的」（恰當）。修飾「持續湧入的援助」，唯有「絶え間ない」。"
  }),
  examQuestion({
    id: "n2-vocab-taemanai-hihan-cdx",
    level: "N2",
    surface: "絶え間ない",
    reading: "たえまない",
    meaningZh: "持續不斷的、不間斷的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "SNS上では、その企業の対応をめぐって ___ 批判が続いている。",
    promptContextZh: "在社群媒體上，圍繞該企業的應對，接連不斷的批評持續不止。",
    hintZh: "社群上針對該企業應對的批評呈現什麼狀態。",
    expectedAnswer: "絶え間ない",
    options: ["絶え間ない", "わずかな", "穏やかな", "的確な"],
    explanation: "「絶え間ない」表示「接連不斷、毫無停歇」，本句後接「批判が続いている」正強調批評持續不止。「わずかな」是「些微的」（與「持續不止」矛盾）；「穏やかな」是「平穩的」（語感相反）；「的確な」是「準確的」。修飾「不停歇的批評」，唯有「絶え間ない」。"
  }),
  examQuestion({
    id: "reinforce-yomi-magirawashii-2",
    level: "N2",
    surface: "紛らわしい",
    reading: "まぎらわしい",
    meaningZh: "容易混淆的",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "説明書の図が「紛らわしく」、初心者には組み立て手順が分かりにくい。",
    promptContextZh: "說明書的圖示容易讓人搞混，新手不易看懂組裝步驟。",
    expectedAnswer: "まぎらわしく",
    exampleJapanese: "説明書の図が紛らわしく、初心者には組み立て手順が分かりにくい。",
    exampleMeaningZh: "說明書的圖示容易讓人搞混，新手不易看懂組裝步驟。",
    options: ["まぎらわしく", "まじらわしく", "まぎれわしく", "まぐらわしく"],
    explanation: "「紛」訓讀「まぎ-らわしい」，連用形「紛らわしく」→ まぎらわしく。「まじらわしく」是「ぎ→じ」的子音錯誤；「まぎれわしく」是把語幹誤拆成「紛れ（まぎれ）」；「まぐらわしく」是「ぎ→ぐ」的母音錯誤。"
  }),
  examQuestion({
    id: "reinforce-grammar-tatokoro-1",
    level: "N2",
    surface: "たところ",
    reading: "たところ",
    meaningZh: "一結果發現",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "念のためメーカーに問い合わせ ___ 、その部品はすでに生産終了になっていることが分かった。",
    promptContextZh: "為求保險向廠商詢問後，得知那項零件已經停產了。",
    hintZh: "向廠商詢問之後所掌握到的情況。",
    expectedAnswer: "たところ",
    options: ["たところ", "たとたん", "たばかりに", "たうえで"],
    explanation: "「Vた + ところ」表示做了某動作後（契機性地）得知新事實，偏書面、中性。「たとたん」強調「同一瞬間」且後項突發；「たばかりに」是「就因為...才導致（不良後果）」；「たうえで」是「在...之後再...」（前提步驟）。本句詢問後得知停產，是「契機→發現」，選「たところ」。"
  }),
  examQuestion({
    id: "reinforce-grammar-tatokoro-2",
    level: "N2",
    surface: "たところ",
    reading: "たところ",
    meaningZh: "一結果發現",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "過去の記録を調べ ___ 、同じような不具合が三年前にも起きていた。",
    promptContextZh: "調閱過去的紀錄後，發現三年前也曾發生過類似的故障。",
    hintZh: "調閱過往紀錄之後所查明的事實。",
    expectedAnswer: "たところ",
    options: ["たところ", "たところで", "たとたん", "た末に"],
    explanation: "「調べたところ」表示調查後查明的客觀事實，焦點在結果與發現。「たところで」是「即使...也（無濟於事）」（逆接假定）；「たとたん」是「一...的瞬間」（突發同時）；「た末に」是「歷經...最終」（強調過程）。本句是調查後的發現，選「たところ」。"
  }),
  examQuestion({
    id: "reinforce-v2-yomi-katayoru-2",
    level: "N2",
    surface: "偏る",
    reading: "かたよる",
    meaningZh: "偏向、不公平",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "「偏った」情報だけをもとに判断すると、結論を誤るおそれがある。",
    promptContextZh: "若只憑偏頗的資訊作判斷，恐怕會導出錯誤的結論。",
    expectedAnswer: "かたよった",
    exampleJapanese: "偏った情報だけをもとに判断すると、結論を誤るおそれがある。",
    exampleMeaningZh: "若只憑偏頗的資訊作判斷，恐怕會導出錯誤的結論。",
    options: ["かたよった", "かたむいた", "へだたった", "かたまった"],
    explanation: "「偏」訓讀「かたよ-る」，た形「偏った」→ かたよった，指資訊或想法失衡、不公正。「かたむいた」是「傾いた」（傾斜，近義字但不同字）；「へだたった」是「隔たった」（相隔）；「かたまった」是「固まった」（凝固，訓讀相近的陷阱）。"
  }),
  examQuestion({
    id: "reinforce-v2-grammar-tatokoro-1",
    level: "N2",
    surface: "たところ",
    reading: "たところ",
    meaningZh: "一結果發現",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "念のため契約書を確認し ___ 、更新には代表者の署名が必要だと分かった。",
    promptContextZh: "為求保險確認契約書後，得知續約需要代表人的簽名。",
    hintZh: "確認契約書之後所查明的條件。",
    expectedAnswer: "たところ",
    options: ["たところ", "たとたん", "たばかりに", "たところで"],
    explanation: "「Vた + ところ」表示做了某動作後查明的新事實，焦點在結果與發現。「たとたん」強調同一瞬間且後項突發；「たばかりに」是「就因為...才導致（不良後果）」；「たところで」是「即使...也（無濟於事）」（逆接假定）。本句確認後得知須簽名，選「たところ」。"
  }),
  examQuestion({
    id: "reinforce-adv-nimokakawarazu",
    level: "N2",
    surface: "にもかかわらず",
    reading: "にもかかわらず",
    meaningZh: "儘管…仍然…",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "今回の説明会は、全部署に三週間前から繰り返し周知していた。___、当日の出席率は半数にも届かなかった。",
    promptContextZh: "這次說明會三週前就向全部門再三宣導，儘管如此，當天出席率卻連半數都不到。",
    hintZh: "充分宣導之後，當天實際出席的狀況。",
    expectedAnswer: "にもかかわらず",
    options: ["にもかかわらず", "それを受けて", "したがって", "それゆえ"],
    explanation: "前句「再三宣導」按常理應帶來高出席率，後句卻是「出席率不到半數」，屬強烈逆接，用「にもかかわらず」。「それを受けて」是「承接前項而採取下一步」（順接發展）；「したがって」「それゆえ」都是「因此」（順接因果），三者方向皆與本句的反差結果相反，故唯有「にもかかわらず」成立。"
  }),
  examQuestion({
    id: "reinforce-adv-naikotoniwa",
    level: "N2",
    surface: "ないことには",
    reading: "ないことには",
    meaningZh: "若不先…就無法…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "カタログの数値だけでは判断できない。実際に試作機を動かしてみ ___ 、量産に向くかどうかは結論を出せない。",
    promptContextZh: "光看型錄數據無法判斷，不先實際讓試作機運轉看看，就無法對是否適合量產下結論。",
    hintZh: "在替量產與否下結論之前，必須先完成的步驟。",
    expectedAnswer: "ないことには",
    options: ["ないことには", "までもなく", "どころか", "ともなしに"],
    explanation: "「Vないことには〜ない」表示「不先實際做 V，後項就無法成立」，本句後接「結論を出せない」正是這個必要條件結構。「までもなく」是「用不著…（不必特地做）」，語意相反；「どころか」是「別說…反而…」（反轉遞進）；「ともなしに」是「無意間…」。三者接於「動かしてみ」後皆不成立，唯「ないことには」對應否定後項。"
  }),
  examQuestion({
    id: "reinforce-adv-bakarini",
    level: "N2",
    surface: "ばかりに",
    reading: "ばかりに",
    meaningZh: "只因…（小失誤釀大禍而後悔）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "つい余計な一言を口にした ___ 、まとまりかけていた商談がこじれてしまった。",
    promptContextZh: "只因不小心多說了一句話，原本就快談成的生意就此鬧僵了。",
    hintZh: "多說一句話，與快談成的生意最後結果之間的關係。",
    expectedAnswer: "ばかりに",
    options: ["ばかりに", "だけに", "ばかりか", "からには"],
    explanation: "「Vたばかりに」強調「只因一個看似不大的失誤，就釀成令人懊悔的壞結果」，本句「多一句話→生意鬧僵」正是此惋惜語感。「だけに」是「正因…程度更…」（需程度／情緒加倍對比，此處無）；「ばかりか」是「不僅…還…」（遞進添加，非因果）；「からには」是「既然…就應當…」（前提→義務）。三者皆不表此小因大果的後悔，唯「ばかりに」成立。"
  }),
  examQuestion({
    id: "reinforce-adv-gachi",
    level: "N2",
    surface: "がち",
    reading: "がち",
    meaningZh: "往往容易…（負面傾向）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "経験が浅いうちは、慣れた作業ほど確認を省き ___ になるので注意したい。",
    promptContextZh: "經驗尚淺時，越是熟練的作業反而往往容易省略確認，這點要當心。",
    hintZh: "資歷尚淺的人面對熟練作業時，在確認方面常出現的傾向。",
    expectedAnswer: "がち",
    options: ["がち", "かけ", "だらけ", "ずくめ"],
    explanation: "「Vます形 / N + がち」表示「往往、容易（出現不太理想的傾向）」，本句「越熟練越常省略確認」正是這種習慣性傾向。「かけ」是「做到一半」（如「やりかけ」）；「だらけ」是「滿是…（負面之物）」（如「傷だらけ」，接名詞表充斥）；「ずくめ」是「清一色、淨是…」（如「いいことずくめ」）。三者皆非「頻繁傾向」，唯「がち」吻合。"
  }),
  examQuestion({
    id: "reinforce-adv-bayokatta",
    level: "N2",
    surface: "ばよかった",
    reading: "ばよかった",
    meaningZh: "早知道…就好了（悔恨）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "こんなに大きな問題になる前に、もっと早く上司に相談しておけ ___ と悔やんでいる。",
    promptContextZh: "正懊悔著，早該在演變成這麼大的問題之前，更早向主管報告才對。",
    hintZh: "在事情鬧大之後，對當初處理時機的反省。",
    expectedAnswer: "ばよかった",
    options: ["ばよかった", "ばきりがない", "たらきりがない", "ばすむ"],
    explanation: "「Vば + よかった」表示「對過去沒做（或沒早做）的事感到悔恨」，本句「早知道就更早報告」正是此義，且與句末「悔やんでいる」呼應。「ばきりがない」「たらきりがない」是「一旦…就沒完沒了」（如「数えればきりがない」），語意不合；「ばすむ」是「只要…就能了事」。表過去未行動的悔恨唯「ばよかった」吻合。"
  }),
  examQuestion({
    id: "reinforce-adv-younishita",
    level: "N2",
    surface: "ようにする",
    reading: "ようにする",
    meaningZh: "（持續努力／養成習慣去）做到…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "人に決められたわけではないが、ミスを減らすため、自分で意識して退社前には必ず翌日の予定を見直す ___。",
    promptContextZh: "並不是有人規定，而是為了減少失誤，我自己有意識地做到下班前一定重看隔天的行程。",
    hintZh: "強調並非他人規定，而是自己有意識地長期維持的習慣動作。",
    expectedAnswer: "ようにしている",
    options: ["ようにしている", "ようになっている", "ことになっている", "ところだった"],
    explanation: "「Vる + ようにしている」表示「（靠自身努力、有意識地）養成並持續維持某習慣」，本句以「自分で意識して」點明是自我要求，正是此義。「ようになっている」是「（自然而然）變成如此的狀態」，但「自分で意識して」強調刻意維持，與自然形成相斥；「ことになっている」是「（依規定／安排）成為…」，而句首「人に決められたわけではない」已明確排除外部規定；「ところだった」是「差點…／正要…」（時間點，語意不合）。唯「ようにしている」吻合。"
  }),
  examQuestion({
    id: "issue79-grammar-kaneru-membership",
    level: "N2",
    surface: "かねる",
    reading: "かねる",
    meaningZh: "難以、無法（婉拒）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "安全上の理由から、期限の切れた会員証での入場は ___。",
    promptContextZh: "基於安全上的理由，恕難允許持過期會員證入場。",
    hintZh: "基於規定，婉轉表示不能接受某種做法。",
    expectedAnswer: "認めかねます",
    options: ["認めかねます", "認めきれます", "認めつつあります", "認めっぱなしです"],
    explanation: "「Vます形＋かねる」表示難以、不能做某事，常用於正式婉拒。本句是基於安全規定不能允許使用過期會員證入場。「認めきれます」是能完全認可（語意相反）；「認めつつあります」是正在逐漸承認；「認めっぱなしです」是放著一直認可，皆不符合婉拒語境，唯「認めかねます」成立。"
  }),
  examQuestion({
    id: "issue79-grammar-uchiwa-student",
    level: "N2",
    surface: "うちは",
    reading: "うちは",
    meaningZh: "在...的時候、趁...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "学生でいる ___、できるだけ多くの本を読んでおきたい。",
    promptContextZh: "趁還是學生的時候，想盡量多讀一些書。",
    hintZh: "某身份或狀態持續期間內想先完成的事。",
    expectedAnswer: "うちは",
    options: ["うちは", "ところで", "たびに", "ものの"],
    explanation: "「〜うちは」表示在某狀態持續期間內（趁著還…）。本句是趁還是學生時想多讀書。「ところで」轉換話題；「たびに」表示每次；「ものの」表示雖然…但是，皆不表示狀態持續期間，唯「うちは」成立。"
  }),
  examQuestion({
    id: "issue79-grammar-nikakawarazu-keiken",
    level: "N2",
    surface: "にかかわらず",
    reading: "にかかわらず",
    meaningZh: "不論...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "経験の有無 ___、希望者は全員研修に参加できます。",
    promptContextZh: "不論有沒有經驗，凡是有意願者全員都能參加研修。",
    hintZh: "不以某條件作為限制。",
    expectedAnswer: "にかかわらず",
    options: ["にかかわらず", "によると", "に対して", "に沿って"],
    explanation: "「Nにかかわらず」表示不論某條件如何結果都一樣。本句是無論有無經驗都能參加研修。「によると」表示根據消息來源；「に対して」表示對…；「に沿って」表示依照方針或規則，皆不表示無條件，唯「にかかわらず」成立。"
  }),
  examQuestion({
    id: "issue79-context-shitagatte-buhin",
    level: "N2",
    surface: "したがって",
    reading: "したがって",
    meaningZh: "因此",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "この部品は熱に弱く、80度を超える環境では性能が落ちる。___、高温の場所で使う機械には採用しないことにした。",
    promptContextZh: "這個零件不耐熱，在超過 80 度的環境下性能會下降；因此決定不採用於高溫場所使用的機械。",
    hintZh: "前句的事實導出後句的判斷。",
    expectedAnswer: "したがって",
    options: ["したがって", "もっとも", "ところが", "たとえば"],
    explanation: "「したがって」表示根據前述理由導出結論。本句由「高溫下性能下降」推出「不採用於高溫設備」。「もっとも」是補充但書；「ところが」是逆接；「たとえば」是舉例，皆不形成因果結論，唯「したがって」成立。"
  }),
  examQuestion({
    id: "issue79-context-shitagatte-kaijou",
    level: "N2",
    surface: "したがって",
    reading: "したがって",
    meaningZh: "因此",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "応募者が定員を大きく超えたため、会場の席数を増やす必要が出てきた。___、説明会は予定より大きいホールで行う。",
    promptContextZh: "報名人數大幅超過名額，必須增加會場座位；因此說明會將改在比原訂更大的會場舉行。",
    hintZh: "前面的狀況直接造成後面的安排。",
    expectedAnswer: "したがって",
    options: ["したがって", "それでも", "一方で", "ちなみに"],
    explanation: "前句是報名人數超過名額、需要增加座位，後句是改用較大會場，兩者為原因與結論，故「したがって」最自然。「それでも」是逆接；「一方で」是對比並列；「ちなみに」是補充旁枝資訊，皆不符合，唯「したがって」成立。"
  }),
  examQuestion({
    id: "reinforce-ageku-lost-station",
    level: "N2",
    surface: "あげく",
    reading: "あげく",
    meaningZh: "…的結果（多為不理想結局）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "道に迷って一時間歩き回った ___、最初にいた駅前に戻ってきてしまった。",
    promptContextZh: "迷路走了一個小時，結果又回到了一開始的車站前。",
    hintZh: "在長時間折騰之後最終落得的下場。",
    expectedAnswer: "あげく",
    options: ["あげく", "うちに", "ところを", "となれば"],
    explanation: "「Vたあげく」表示經過一番折騰之後，最後得到（多半不理想的）結果，本句是走了一小時又繞回原處。「うちに」要接持續狀態（如「歩いているうちに」），接「歩き回った」た形不自然；「ところを」表示『正當某狀況時（被打擾／被看見）』；「となれば」是假設條件『一旦變成…的話』，三者都不符合『折騰一番後的結果』語感，唯「あげく」成立。"
  }),
  examQuestion({
    id: "n2-grammar-nihanshite-yosou",
    level: "N2",
    surface: "に反して",
    reading: "にはんして",
    meaningZh: "與...相反、出乎...之外",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "売れ行きは、担当者の予想 ___、発売初日から非常に好調だった。",
    promptContextZh: "銷量出乎負責人預料，從上市首日起就非常暢銷。",
    hintZh: "負責人原本的預估與實際銷售結果之間的落差。",
    expectedAnswer: "に反して",
    options: ["に反して", "に応じて", "に沿って", "をめぐって"],
    explanation: "「Nに反して」表示結果與預想、期待、規定相反。本句銷量超出負責人預期，正是「與預想相反」。「に応じて」是「視 N 而調整」（相應配合）；「に沿って」是「順著 N（方針/期待）」（不偏離，若選此則應如預想，與「好調」矛盾）；「をめぐって」是「圍繞 N（議論）」。唯「に反して」吻合。"
  }),
  examQuestion({
    id: "n2-grammar-nikurabete-rain",
    level: "N2",
    surface: "に比べて",
    reading: "にくらべて",
    meaningZh: "與...相比",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "去年 ___、今年は雨の日がかなり多い。",
    promptContextZh: "和去年相比，今年的雨天相當多。",
    hintZh: "把今年的雨天天數放在去年這個基準上看。",
    expectedAnswer: "に比べて",
    options: ["に比べて", "に加えて", "に対して", "によると"],
    explanation: "「Nに比べて」表示以 N 為基準做比較。本句拿今年與去年相比。「に加えて」是「除 N 之外再加上」（添加，非比較）；「に対して」是「對於 N／與 N 對比（對象並列）」（多用於對立的兩方，而非同一指標的前後比較）；「によると」是「根據 N（消息來源）」。唯「に比べて」吻合兩年雨量多寡的比較。"
  }),
  examQuestion({
    id: "n2-grammar-nitsurete-temperature",
    level: "N2",
    surface: "につれて",
    reading: "につれて",
    meaningZh: "隨著...（而逐漸）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "気温が上がる ___、アイスクリームの売り上げも伸びてきた。",
    promptContextZh: "隨著氣溫上升，冰淇淋的銷量也跟著增加。",
    hintZh: "氣溫變化與冰淇淋銷量之間的連動方向。",
    expectedAnswer: "につれて",
    options: ["につれて", "に反して", "に関して", "に限って"],
    explanation: "「Vる/Nにつれて」表示前項變化時，後項也隨之逐漸變化（連動的漸變）。本句氣溫上升、銷量也跟著上升。「に反して」是「與...相反」；「に関して」是「關於...」；「に限って」是「偏偏／唯獨...」。唯「につれて」吻合「越...越...」的連動關係。"
  }),
  examQuestion({
    id: "n2-grammar-tatoe-hantai",
    level: "N2",
    surface: "たとえ",
    reading: "たとえ",
    meaningZh: "即使、就算",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "___ 周囲に反対されても、自分で決めた道を進みたい。",
    promptContextZh: "即使被周遭反對，也想走自己決定的路。",
    hintZh: "句尾的「ても」提示前面應該是哪一種假設讓步副詞。",
    expectedAnswer: "たとえ",
    options: ["たとえ", "むしろ", "いわば", "せめて"],
    explanation: "「たとえ〜ても」呼應使用，表示「即使（發生極端情況）也...」的假設讓步。本句與句尾「反対されても」搭配。「むしろ」是「寧可、反倒」；「いわば」是「可謂、好比」；「せめて」是「至少」。三者都不與「ても」呼應，唯「たとえ」吻合。"
  }),
  examQuestion({
    id: "n2-grammar-karatoitte-cheap",
    level: "N2",
    surface: "からといって",
    reading: "からといって",
    meaningZh: "不能因為...就...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "いくら値段が安い ___、すぐ壊れる商品を買うべきではない。",
    promptContextZh: "再怎麼便宜，也不該買馬上就壞的商品。",
    hintZh: "便宜這個理由與「不該買」這個結論之間的關係。",
    expectedAnswer: "からといって",
    options: ["からといって", "だけに", "ものなら", "にしては"],
    explanation: "「Aからといって（Bない）」表示「不能僅因為 A 就（斷定/做）B」，後句常為否定。本句呼應「いくら」與「買うべきではない」，否定「便宜＝該買」的推論。「だけに」是「正因為...（所以更...）」（順接強調）；「ものなら」是「若能...的話」（假設）；「にしては」是「以...而言（卻）」（與預期落差）。唯「からといって」吻合。"
  }),
  examQuestion({
    id: "n2-vocab-futan-transport",
    level: "N2",
    surface: "負担",
    reading: "ふたん",
    meaningZh: "負擔",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "交通費の ___ を減らすため、会社は定期券代を補助することにした。",
    promptContextZh: "為了減輕交通費的負擔，公司決定補助月票費用。",
    hintZh: "公司補助月票，是想減輕員工在交通費上承受的什麼。",
    expectedAnswer: "負担",
    options: ["負担", "不満", "不足", "負け"],
    explanation: "「負担」= 經濟或心理上承受的負擔。本句「減輕交通費的負擔」最自然。「不満」是「不滿」（情緒）；「不足」是「不足、短缺」（數量不夠，與「補助分擔費用」方向不符）；「負け」是「輸、敗」。唯「負担」吻合。"
  }),
  examQuestion({
    id: "n2-vocab-eikyou-typhoon",
    level: "N2",
    surface: "影響",
    reading: "えいきょう",
    meaningZh: "影響",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "台風の ___ で、午後の便はすべて欠航になった。",
    promptContextZh: "受颱風影響，下午的班機全部停飛。",
    hintZh: "颱風造成班機停飛，這是颱風帶來的什麼。",
    expectedAnswer: "影響",
    options: ["影響", "印象", "効果", "関心"],
    explanation: "「影響」= 對他事造成的作用（中性，可正可負）。本句颱風導致停飛，是負面波及。「印象」是「印象」（感受）；「効果」是「效果」（多指正面成效）；「関心」是「關心、興趣」。唯「影響」吻合「Nの影響で（因 N 的影響而...）」這個固定搭配。"
  }),
  examQuestion({
    id: "n2-vocab-tetsuduki-address",
    level: "N2",
    surface: "手続き",
    reading: "てつづき",
    meaningZh: "手續、程序",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "引っ越し後、市役所で住所変更の ___ をした。",
    promptContextZh: "搬家後，在市公所辦了變更住址的手續。",
    hintZh: "在市公所變更住址時，依規定要一步步辦完的事。",
    expectedAnswer: "手続き",
    options: ["手続き", "手伝い", "受付", "申込"],
    explanation: "「手続き」= 為辦理某事所需的一連串正式程序，「住所変更の手続き」是固定搭配。「手伝い」是「幫忙」；「受付」是「受理（櫃台/動作）」（指地點或接待，不接「の___をした」自然）；「申込」是「報名、申請」（多用於課程/活動，住址變更不用申込）。唯「手続き」吻合。"
  }),
  examQuestion({
    id: "n2-vocab-setsuyaku-electricity",
    level: "N2",
    surface: "節約",
    reading: "せつやく",
    meaningZh: "節約、節省",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "電気代を ___ するため、使っていない部屋の照明は消している。",
    promptContextZh: "為了節省電費，沒在使用的房間都把燈關掉。",
    hintZh: "關掉沒在用的燈，是為了在電費上做什麼。",
    expectedAnswer: "節約",
    options: ["節約", "節目", "約束", "予約"],
    explanation: "「節約」= 節省（金錢、資源）。本句關燈是為節省電費。「節目」是「段落、節骨眼」（時間/事物的關鍵點）；「約束」是「約定」；「予約」是「預約」。唯「節約」吻合「電気代を節約する」。"
  }),
  examQuestion({
    id: "n2-kanji-joukyou",
    level: "N2",
    surface: "状況",
    reading: "じょうきょう",
    meaningZh: "狀況、情況",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "現在の「状況」を詳しく説明してください。",
    promptContextZh: "請詳細說明目前的狀況。",
    expectedAnswer: "じょうきょう",
    options: ["じょうきょう", "しょうきょう", "じょうこう", "じょきょう"],
    explanation: "「状」音讀「じょう」，「況」音讀「きょう」→ じょうきょう。「しょうきょう」是首字清濁混淆（じょう→しょう）；「じょうこう」是次字長音/拗音脫落（きょう→こう，撞「条項」）；「じょきょう」是首字長音脫落（じょう→じょ）。",
    exampleJapanese: "現在の状況を詳しく説明してください。",
    exampleMeaningZh: "請詳細說明目前的狀況。"
  }),
  examQuestion({
    id: "n2-kanji-shikyuu",
    level: "N2",
    surface: "支給",
    reading: "しきゅう",
    meaningZh: "支付、發給",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "交通費は来月まとめて「支給」される。",
    promptContextZh: "交通費下個月會一併發放。",
    expectedAnswer: "しきゅう",
    options: ["しきゅう", "じきゅう", "しきょう", "しきゅ"],
    explanation: "「支」音讀「し」，「給」音讀「きゅう」→ しきゅう。「じきゅう」是首字濁音（し→じ，撞「時給/自給」）；「しきょう」是次字拗音誤（きゅう→きょう）；「しきゅ」是長音脫落（きゅう→きゅ）。",
    exampleJapanese: "交通費は来月まとめて支給される。",
    exampleMeaningZh: "交通費下個月會一併發放。"
  }),
  examQuestion({
    id: "n2-kanji-kisoku",
    level: "N2",
    surface: "規則",
    reading: "きそく",
    meaningZh: "規則、規定",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "会社の「規則」を守って行動してください。",
    promptContextZh: "請遵守公司的規則行動。",
    expectedAnswer: "きそく",
    options: ["きそく", "ぎそく", "きぞく", "きさい"],
    explanation: "「規」音讀「き」，「則」音讀「そく」→ きそく。「ぎそく」是首字濁音（き→ぎ，撞「義足」）；「きぞく」是次字濁音（そく→ぞく，撞「貴族」）；「きさい」是次字誤讀（そく→さい，撞「記載」）。",
    exampleJapanese: "会社の規則を守って行動してください。",
    exampleMeaningZh: "請遵守公司的規則行動。"
  }),
  examQuestion({
    id: "reinforce-stubborn-nagaramomo-young",
    level: "N2",
    surface: "ながらも",
    reading: "ながらも",
    meaningZh: "儘管如此仍然",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "経験は浅い ___ 、彼は落ち着いて顧客の苦情に対応した。",
    promptContextZh: "雖然經驗尚淺，他仍冷靜地處理了顧客的客訴。",
    hintZh: "條件不利，但表現卻超出預期。",
    expectedAnswer: "ながらも",
    options: ["ながらも", "からには", "だけに", "にかけて"],
    explanation: "「Vます形/イ形/Nながらも」表示「有前項事實，後項卻仍成立」的逆接。本句經驗淺，卻仍冷靜應對客訴，故選「ながらも」。「からには」是「既然…就」；「だけに」是「正因為…才」；「にかけて」表時間範圍或擅長領域，接續與語意皆不合。"
  }),
  examQuestion({
    id: "reinforce-stubborn-uewa-contract",
    level: "N2",
    surface: "上は",
    reading: "うえは",
    meaningZh: "做了就應當",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "契約書に署名した ___ 、条件を守る責任がある。",
    promptContextZh: "簽署了合約之後，就有遵守條件的責任。",
    hintZh: "做出某項承諾後，必須擔起隨之而來的責任。",
    expectedAnswer: "上は",
    options: ["上は", "うえで", "うえに", "うちは"],
    explanation: "「Vた＋上は」表示「既做了前項，理所當然就要承擔後項的義務或覺悟」。本句簽了約就要守條件，故選「上は」。「うえで」是「在…之後／在…方面」偏中性程序；「うえに」是「加上、而且」的累加；「うちは」是「在…期間」，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-torikumu-traffic",
    level: "N2",
    surface: "取り組む",
    reading: "とりくむ",
    meaningZh: "認真投入、著手處理",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "市は、駅前の混雑を減らすため、交通問題に本格的に ___ ことにした。",
    promptContextZh: "市政府為減少站前壅塞，決定正式著手處理交通問題。",
    hintZh: "為解決課題而持續努力的動作。",
    expectedAnswer: "取り組む",
    options: ["取り組む", "取り込む", "取り替える", "取り消す"],
    explanation: "「取り組む」表示認真投入、致力於某問題或課題。「問題に取り組む」是固定搭配。「取り込む」是拿進來/吸收；「取り替える」是更換；「取り消す」是取消，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-oomune-synonym",
    level: "N2",
    surface: "おおむね",
    reading: "おおむね",
    meaningZh: "大致、大體上",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "新しい計画は、「おおむね」順調に進んでいる。",
    promptContextZh: "新計畫大致上進行得很順利。",
    hintZh: "選出語意最接近的說法。",
    expectedAnswer: "だいたい",
    options: ["だいたい", "完全に", "少しずつ", "急に"],
    explanation: "「おおむね」表示大致、大體上，最接近「だいたい」。「完全に」是完全；「少しずつ」是逐漸；「急に」是突然，皆不合。",
    exampleJapanese: "新しい計画は、おおむね順調に進んでいる。",
    exampleMeaningZh: "新計畫大致上進行得很順利。"
  }),
  examQuestion({
    id: "reinforce-round2-amari-presentation",
    level: "N2",
    surface: "あまり",
    reading: "あまり",
    meaningZh: "由於過度…而…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "発表の直前、緊張の ___ 声が震えてしまった。",
    promptContextZh: "發表前一刻，因為太緊張而聲音發抖。",
    hintZh: "因情緒過於強烈而引發身體反應。",
    expectedAnswer: "あまり",
    options: ["あまり", "末に", "たびに", "かぎり"],
    explanation: "「Nのあまり」表示由於某種感情或狀態過強而產生後果。本句是因過度緊張而聲音發抖。「末に」是經過一番過程後；「たびに」每次；「かぎり」限度/只要，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-womegutte-station",
    level: "N2",
    surface: "をめぐって",
    reading: "をめぐって",
    meaningZh: "圍繞、針對",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新駅の建設計画 ___、住民の間で意見が分かれている。",
    promptContextZh: "圍繞新車站的建設計畫，居民之間意見分歧。",
    hintZh: "以某議題為中心引發討論或對立。",
    expectedAnswer: "をめぐって",
    options: ["をめぐって", "に沿って", "に応じて", "を通じて"],
    explanation: "「Nをめぐって」表示圍繞某議題發生討論、對立或問題。本句是圍繞新站建設計畫意見分歧。「に沿って」按照；「に応じて」依照；「を通じて」透過/整個期間，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-mononara-return",
    level: "N2",
    surface: "ものなら",
    reading: "ものなら",
    meaningZh: "如果能…的話（難實現的假設）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "戻れる ___、入社したばかりの自分に忠告したい。",
    promptContextZh: "如果回得去的話，真想提醒剛進公司的自己。",
    hintZh: "假設一個現實中很難達成的願望。",
    expectedAnswer: "ものなら",
    options: ["ものなら", "ものの", "ものだから", "ものを"],
    explanation: "「V可能形＋ものなら」表示如果能做到某個實際上很難的事。本句是如果能回到過去，就想提醒剛入社的自己。「ものの」雖然；「ものだから」原因辯解；「ものを」明明卻，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-monono-system",
    level: "N2",
    surface: "ものの",
    reading: "ものの",
    meaningZh: "雖然…但…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新しい制度を導入した ___、現場ではまだ使い方が十分に理解されていない。",
    promptContextZh: "雖然導入了新制度，但現場還沒充分理解使用方法。",
    hintZh: "承認前項屬實，但後項仍有不足。",
    expectedAnswer: "ものの",
    options: ["ものの", "ものなら", "ものだから", "ものを"],
    explanation: "「〜ものの」表示雖然前項成立，但後項仍有相反或不充分之處。本句是雖導入制度，但現場尚未理解。「ものなら」假設；「ものだから」原因；「ものを」遺憾/責備，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-tadashi-member",
    level: "N2",
    surface: "ただし",
    reading: "ただし",
    meaningZh: "但是、附帶條件",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "会員登録は無料です。___、一部の機能を利用するには本人確認が必要です。",
    promptContextZh: "會員註冊免費。但是，使用部分功能需要本人身分驗證。",
    hintZh: "在前句說明後補上限制或例外。",
    expectedAnswer: "ただし",
    options: ["ただし", "したがって", "つまり", "一方で"],
    explanation: "「ただし」用於在前述內容上追加條件、例外或限制。本句在「免費註冊」的說明後，補上需本人驗證的條件。「したがって」是「因此」；「つまり」是「換言之」；「一方で」是「另一方面」，皆不合。"
  }),
  examQuestion({
    id: "reinforce-round2-kanji-joukyou",
    level: "N2",
    surface: "状況",
    reading: "じょうきょう",
    meaningZh: "狀況、情況",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "現場の「状況」を確認してから判断しましょう。",
    promptContextZh: "先確認現場的狀況再判斷吧。",
    expectedAnswer: "じょうきょう",
    options: ["じょうきょう", "しょうきょう", "じょうこう", "じょうぎょう"],
    explanation: "「状況」讀作「じょうきょう」。「しょうきょう」是語頭清濁誤讀；「じょうこう」是漏掉後半拗音的誤讀；「じょうぎょう」是後半清濁與讀音的混淆。",
    exampleJapanese: "現場の状況を確認してから判断しましょう。",
    exampleMeaningZh: "先確認現場的狀況再判斷吧。"
  }),
  examQuestion({
    id: "reinforce-round2-ageku-cancel",
    level: "N2",
    surface: "あげく",
    reading: "あげく",
    meaningZh: "到頭來落得…（多為不理想結局）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "何度も会議を重ねた ___、結局その計画は中止になった。",
    promptContextZh: "開了好幾次會，到頭來那項計畫還是喊停了。",
    hintZh: "經過再三折騰，最後演變成不樂見的下場。",
    expectedAnswer: "あげく",
    options: ["あげく", "うちに", "ところに", "かと思うと"],
    explanation: "「Vたあげく」表示經過一番過程後，最後得到多半不理想的結果。本句是多次開會後，最後計畫仍中止。「うちに」期間/趁著；「ところに」正當時；「かと思うと」剛…就，皆不合。"
  })
];
