import type { PracticeQuestion } from "../../types";
import { examQuestion } from "../helpers";

export const n3Items: PracticeQuestion[] = [
  examQuestion({
    id: "n3-grammar-yoninaru",
    level: "N3",
    surface: "ようになる",
    reading: "ようになる",
    meaningZh: "變得（能夠/習慣於）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "毎日 練習したので、自転車に乗れる ___ なった。",
    promptContextZh: "每天練習，結果變得會騎自行車了。",
    hintZh: "每天練習自行車的結果。",
    expectedAnswer: "ように",
    options: ["ように", "ことに", "ために", "ようで"],
    explanation: "「Vる/可能形 + ようになる」表示「（從不會到會、從不做到做）變化的結果」。「ことになる」是外在的決定；「ために」表目的；「ようで」是「好像」。"
  }),
  examQuestion({
    id: "n3-grammar-kotonisuru",
    level: "N3",
    surface: "ことにする",
    reading: "ことにする",
    meaningZh: "決定（主動）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "体に悪いから、たばこをやめる ___ 。",
    promptContextZh: "對身體不好，我決定戒菸了。",
    hintZh: "因身體考量對抽菸的處理。",
    expectedAnswer: "ことにした",
    options: ["ことにした", "ようにした", "ことになった", "ようになった"],
    explanation: "「Vる + ことにする」表示「自己的決定」。「ことになる」是外在情況/規定造成的結果；「ようにする」是「努力做到」。"
  }),
  examQuestion({
    id: "n3-grammar-tsumori",
    level: "N3",
    surface: "つもり",
    reading: "つもり",
    meaningZh: "打算",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "夏休みに国へ帰る ___ です。",
    promptContextZh: "暑假打算回國。",
    hintZh: "暑假的安排。",
    expectedAnswer: "つもり",
    options: ["つもり", "ばかり", "はず", "ところ"],
    explanation: "「Vる + つもり」表示主觀的打算。「ばかり」表示「剛剛...完」；「はず」表示客觀推測「應該」；「ところ」表動作階段。"
  }),
  examQuestion({
    id: "n3-grammar-bayokatta",
    level: "N3",
    surface: "ばよかった",
    reading: "ばよかった",
    meaningZh: "如果...就好了（後悔）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "雨に降られた。傘を持ってくれば ___ 。",
    promptContextZh: "被雨淋了，要是有帶傘就好了。",
    hintZh: "被雨淋濕後對帶傘的反思。",
    expectedAnswer: "よかった",
    options: ["よかった", "ばかりだ", "つもりだ", "はずだ"],
    explanation: "「Vば + よかった」表示對過去未做的事感到後悔。其他三個都是常見的句末表現，但都需要不同的接續（「ばかりだ」「つもりだ」「はずだ」皆接 V辞書形/た形），不能直接接在 Vば 後面。"
  }),
  examQuestion({
    id: "n3-grammar-tahougaii",
    level: "N3",
    surface: "たほうがいい",
    reading: "たほうがいい",
    meaningZh: "...比較好（建議）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "熱がありますね。早く病院へ行った ___ 。",
    promptContextZh: "你發燒了呢，早點去醫院比較好。",
    hintZh: "發燒時對就醫安排的判斷。",
    expectedAnswer: "ほうがいい",
    options: ["ほうがいい", "ことがある", "つもりだ", "おかげだ"],
    explanation: "「Vた + ほうがいい」表示對對方的建議。"
  }),
  examQuestion({
    id: "n3-grammar-nakutehaikenai",
    level: "N3",
    surface: "なくてはいけない",
    reading: "なくてはいけない",
    meaningZh: "必須",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "明日までにこのレポートを ___ いけない。",
    promptContextZh: "明天之前必須交這份報告。",
    hintZh: "明天前報告交件的安排。",
    expectedAnswer: "出さなくては",
    options: ["出さなくては", "出さなくても", "出さないで", "出すことが"],
    explanation: "「Vない形 + なくてはいけない」表示「必須做」的義務。「なくてもいい」相反，表示不需要做。"
  }),
  examQuestion({
    id: "n3-grammar-teshimau",
    level: "N3",
    surface: "てしまう",
    reading: "てしまう",
    meaningZh: "（不小心）做了",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "大事な約束を忘れて ___ 、本当にすみません。",
    promptContextZh: "把重要的約定忘了，真的很抱歉。",
    hintZh: "對忘記重要約定的回應。",
    expectedAnswer: "しまって",
    options: ["しまって", "おいて", "みて", "あって"],
    explanation: "「Vて + しまう」表示完成或表達遺憾／後悔。「ておく」表示為將來做準備；「てみる」表示嘗試。"
  }),
  examQuestion({
    id: "n3-grammar-teoku",
    level: "N3",
    surface: "ておく",
    reading: "ておく",
    meaningZh: "事先做好",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "明日の会議の前に、資料をコピーし ___ ます。",
    promptContextZh: "明天會議前先把資料影印起來。",
    hintZh: "會議前對資料的安排。",
    expectedAnswer: "ておき",
    options: ["ておき", "てしまい", "てあり", "ていき"],
    explanation: "「Vて + おく」表示為將來做準備。「てある」是已被人放置的狀態；「てしまう」是完了／遺憾。"
  }),
  examQuestion({
    id: "n3-grammar-nagara",
    level: "N3",
    surface: "ながら",
    reading: "ながら",
    meaningZh: "一邊...一邊...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "音楽を聞き ___ 、勉強するのが好きだ。",
    promptContextZh: "我喜歡邊聽音樂邊讀書。",
    hintZh: "聽音樂與讀書的習慣。",
    expectedAnswer: "ながら",
    options: ["ながら", "あいだ", "うちに", "ばかり"],
    explanation: "「Vます形 + ながら」表示同一個人同時做兩件事。「あいだ」「うちに」是時間範圍／不同主語。"
  }),
  examQuestion({
    id: "n3-grammar-teirutokoro",
    level: "N3",
    surface: "ているところ",
    reading: "ているところ",
    meaningZh: "正在...中",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "今、ご飯を ___ ので、後で電話します。",
    promptContextZh: "現在正在吃飯，等等再打電話。",
    hintZh: "用餐時間中對於來電的回應。",
    expectedAnswer: "食べているところな",
    options: ["食べているところな", "食べたところな", "食べたばかりな", "食べるところな"],
    explanation: "「Vている + ところだ」表示「動作正在進行中」；「Vたところだ」表示「剛剛做完」；「Vるところだ」是「正要做」；「Vたばかりだ」是「剛剛...不久」。"
  }),
  examQuestion({
    id: "n3-grammar-nikui",
    level: "N3",
    surface: "にくい",
    reading: "にくい",
    meaningZh: "難以...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "字が小さすぎて、とても ___ ですね。",
    promptContextZh: "字太小，很難讀呢。",
    expectedAnswer: "読みにくい",
    options: ["読みにくい", "読みやすい", "読みたい", "読めない"],
    explanation: "「Vます形 + にくい」表示動作做起來費力、困難。「やすい」相反，是「容易做」；「たい」是希望；「読めない」是「無法讀」(指能力上不行)，但這裡的問題不是能力而是條件造成不易讀，所以「にくい」最自然。"
  }),
  examQuestion({
    id: "n3-grammar-yasui",
    level: "N3",
    surface: "やすい",
    reading: "やすい",
    meaningZh: "容易做、好做",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "このペンは持ち ___ 、長い時間書いても疲れない。",
    promptContextZh: "這支筆很好握，長時間寫也不會累。",
    expectedAnswer: "やすくて",
    options: ["やすくて", "にくくて", "がちで", "そうで"],
    explanation: "「Vます形 + やすい」表示「容易做、好操作」。「にくい」是相反；「がち」是「容易發生（負面）」；「そう」是「看起來像」。"
  }),
  examQuestion({
    id: "n3-grammar-tagaru",
    level: "N3",
    surface: "たがる",
    reading: "たがる",
    meaningZh: "（第三人稱）想要做",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "妹は 体調が 悪いのに、病院に ___ 。",
    promptContextZh: "妹妹身體不舒服，卻不想去醫院。",
    expectedAnswer: "行きたがらない",
    options: ["行きたがらない", "行きたくない", "行かなさそう", "行かないらしい"],
    explanation: "「Vます形 + たがる（否定：たがらない）」表示「第三人稱（自己以外的人）想／不想做某事」。「Vたい／たくない」是「自己」的願望（第一人稱）；「Vそう」是「看起來會...」（觀察推測）；「Vらしい」是「聽說會...」（傳聞）。本句主語「妹」是第三人稱，必須用「行きたがらない」。"
  }),
  examQuestion({
    id: "n3-grammar-youtosuru",
    level: "N3",
    surface: "ようとする",
    reading: "ようとする",
    meaningZh: "正要、試圖",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "家を出 ___ としたとき、電話が鳴った。",
    promptContextZh: "正要出門時，電話響了。",
    expectedAnswer: "よう",
    options: ["よう", "る", "て", "た"],
    explanation: "「動詞意向形 + とする」表示「正要做某動作（卻被打斷或注意到別事）」。「Vるとする」是另一個意思「假定...」；「Vてとする」「Vたとする」皆不通。"
  }),
  examQuestion({
    id: "n3-grammar-rashii-typical",
    level: "N3",
    surface: "らしい",
    reading: "らしい",
    meaningZh: "（典型的）像...的樣子",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あの人は男 ___ ことを よく 言うね。",
    promptContextZh: "那個人常常說很有男子氣概的話呢。",
    expectedAnswer: "らしい",
    options: ["らしい", "そうな", "ような", "みたいな"],
    explanation: "「N + らしい」此處的意思是「具有 N 應有的特質」，是典型而非傳聞。「ような」「みたいな」表示「像 N」(外表相似)；「そうな」是「看起來」。"
  }),
  examQuestion({
    id: "n3-grammar-taritari",
    level: "N3",
    surface: "たり〜たり",
    reading: "たり〜たり",
    meaningZh: "做...做...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "休みの日は本を読んだり、___ して過ごす。",
    promptContextZh: "假日會做做看書、散步之類的事情。",
    expectedAnswer: "散歩したり",
    options: ["散歩したり", "散歩しても", "散歩する", "散歩しながら"],
    explanation: "「Vたり、Vたりする」表示列舉幾個動作（不限這些）。「ても」是讓步；「ながら」是「同時」。"
  }),
  examQuestion({
    id: "n3-grammar-tamama",
    level: "N3",
    surface: "たまま",
    reading: "たまま",
    meaningZh: "保持...的狀態",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "靴を 履いた ___ 、部屋に 上がらないで ください。",
    promptContextZh: "請不要穿著鞋子上房間。",
    expectedAnswer: "まま",
    options: ["まま", "あと", "なり", "ところ"],
    explanation: "「Vた + まま」表示「保持該動作的狀態」沒有改變。「あと」是「之後」；「なり」是「一...就」(N1)；「ところ」是「動作階段」。"
  }),
  examQuestion({
    id: "n3-grammar-baruhodo",
    level: "N3",
    surface: "ば〜ほど",
    reading: "ば〜ほど",
    meaningZh: "越...越...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "日本語は 練習すれば ___ 上手になる。",
    promptContextZh: "日語越練習就會越好。",
    expectedAnswer: "するほど",
    options: ["するほど", "したほど", "するばかり", "するまで"],
    explanation: "「Vば + Vほど」表示「越...越...」，前後動詞要一致。「したほど」過去式不通；「するばかり」是「越來越」(單向)；「するまで」是「直到...為止」。"
  }),
  examQuestion({
    id: "n3-grammar-noni",
    level: "N3",
    surface: "のに",
    reading: "のに",
    meaningZh: "雖然...卻...",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あんなに 頑張って 勉強した ___ 、試験に 落ちて しまった。",
    promptContextZh: "那麼努力地讀書了，卻還是考砸了。",
    expectedAnswer: "のに",
    options: ["のに", "ので", "ように", "うちに"],
    explanation: "「Vた/イ形容詞 + のに」表示「明明...卻...」的逆接。「ので」是順接因果；「ように」是「為了/像」；「うちに」是「趁著」。"
  }),
  examQuestion({
    id: "n3-grammar-nara-topic",
    level: "N3",
    surface: "なら",
    reading: "なら",
    meaningZh: "如果是...的話",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "日本語の 文法の こと ___ 、田中先生に 聞いた ほうが いい。",
    promptContextZh: "如果是日語文法的事，去問田中老師比較好。",
    expectedAnswer: "なら",
    options: ["なら", "ば", "と", "たら"],
    explanation: "「N + なら」用於承接對方話題並提建議（「如果說到 N 的話」）。「ば」「と」「たら」是條件句，但接續或語感不太相同 — N + ば不通；N + と/たら 需要動詞句。"
  }),
  // -- N3 文脈規定 (light sprinkle) -------------------------------------------
  examQuestion({
    id: "n3-vocab-tazuneru",
    level: "N3",
    surface: "訪ねる",
    reading: "たずねる",
    meaningZh: "拜訪",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "夏休みに、田舎の 祖父母を ___ 行きました。",
    promptContextZh: "暑假時去鄉下拜訪了祖父母。",
    expectedAnswer: "訪ねて",
    options: ["訪ねて", "探して", "集めて", "求めて"],
    explanation: "「訪ねる」= 拜訪（人）。「探す」是「找」；「集める」是「收集」；「求める」是「請求」，都不適用於「拜訪親人」。"
  }),
  examQuestion({
    id: "n3-vocab-katazukeru",
    level: "N3",
    surface: "片付ける",
    reading: "かたづける",
    meaningZh: "整理、收拾",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "食事の あと、皿を ___ から、テレビを 見ます。",
    promptContextZh: "用完餐後收拾完餐盤再看電視。",
    expectedAnswer: "片付けて",
    options: ["片付けて", "並べて", "壊して", "預けて"],
    explanation: "「片付ける」= 整理收拾。「並べる」是「擺好」（用餐前才做）；「壊す」是「弄壞」；「預ける」是「寄放」。"
  }),
  examQuestion({
    id: "n3-grammar-noni-kusuri",
    level: "N3",
    surface: "のに",
    reading: "のに",
    meaningZh: "明明…卻…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "薬を飲んだ ___ 、ちっとも熱が下がらない。",
    promptContextZh: "明明吃了藥，燒卻一點也沒退。",
    hintZh: "吃藥之後與退燒情況之間的落差。",
    expectedAnswer: "のに",
    options: ["のに", "ので", "から", "なら"],
    explanation: "「のに」表示「明明…卻…」的逆接與不滿，本句「吃了藥卻完全不退燒」即此。「ので」「から」都是「因為」，會變成「因為吃了藥所以不退燒」的邏輯矛盾；「なら」是「如果…的話」。唯「のに」成立。"
  }),
  examQuestion({
    id: "n3-grammar-ba-hodo-hon",
    level: "N3",
    surface: "ば〜ほど",
    reading: "ば〜ほど",
    meaningZh: "越…越…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この本は、読め ___ 読むほど面白くなる。",
    promptContextZh: "這本書越讀越有趣。",
    hintZh: "閱讀次數與有趣程度的連動。",
    expectedAnswer: "ば",
    options: ["ば", "たら", "と", "なら"],
    explanation: "「Vば〜Vるほど」是固定句型，表示「越…越…」，本句「越讀越有趣」。空格須填「ば」才能與後面的「ほど」構成此句型。「たら」「と」「なら」都無法組成此慣用形。唯「ば」成立。"
  }),
  examQuestion({
    id: "n3-grammar-tameni-shourai",
    level: "N3",
    surface: "ために",
    reading: "ために",
    meaningZh: "為了…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "将来の ___ に、毎月少しずつお金を貯めている。",
    promptContextZh: "為了將來，每個月一點一點地存錢。",
    hintZh: "每個月存錢時所著眼的方向。",
    expectedAnswer: "ために",
    options: ["ために", "ように", "とおりに", "かわりに"],
    explanation: "「Nのために」表示目的「為了…」，本句「為了將來而存錢」。「ように」表目的時要接動詞（如「貯めるように」），不接「将来の」；「とおりに」是「按照…」；「かわりに」是「代替…」。唯「ために」與「将来の」搭配成立。"
  }),
  examQuestion({
    id: "n3-grammar-soutai-ame",
    level: "N3",
    surface: "そうだ（様態）",
    reading: "そうだ",
    meaningZh: "看起來就要…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "空が急に暗くなってきた。今にも雨が降り ___ だ。",
    promptContextZh: "天空突然暗了下來，眼看就要下雨了。",
    hintZh: "從天色判斷接下來的天氣徵兆。",
    expectedAnswer: "そう",
    options: ["そう", "らしい", "みたい", "よう"],
    explanation: "「Vます stem＋そうだ」是樣態用法「看起來就要…」，本句「眼看就要下雨」。樣態「そう」直接接ます形「降り」；而「らしい／みたい／よう」要接辭書形（降るらしい等），無法接「降り」。唯「そう」在此接續成立。"
  }),
  examQuestion({
    id: "n3-grammar-hazu-touchaku",
    level: "N3",
    surface: "はず",
    reading: "はず",
    meaningZh: "照理應該…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "彼は朝早く家を出たから、今ごろもう会社に着いている ___ だ。",
    promptContextZh: "他一大早就出門了，現在照理應該已經到公司了。",
    hintZh: "依出門時間推測他此刻的狀況。",
    expectedAnswer: "はず",
    options: ["はず", "つもり", "らしい", "ながら"],
    explanation: "「はずだ」表示根據理由做出的合理推斷「照理應該…」，本句「一早出門，現在應該已到公司」。「つもりだ」是主觀打算／自以為，不用於對狀態的客觀推斷；「らしい」「ながら」在「___だ」的框架下不成立（らしいだ／ながらだ 不通）。唯「はず」成立。"
  }),
  examQuestion({
    id: "n3-grammar-saseru-yasai",
    level: "N3",
    surface: "させる",
    reading: "させる",
    meaningZh: "讓／使（某人）做",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "母は健康のために、子どもに毎日野菜を食べ ___ 。",
    promptContextZh: "媽媽為了健康，每天讓孩子吃蔬菜。",
    hintZh: "媽媽針對孩子吃蔬菜這件事所採取的做法。",
    expectedAnswer: "させる",
    options: ["させる", "られる", "させられる", "たがる"],
    explanation: "「使役 させる」表示「讓／使某人做…」，本句「媽媽讓孩子吃蔬菜」。「られる」是被動／可能（媽媽被吃？媽媽能吃？皆不合）；「させられる」是使役被動（被迫吃，與「子どもに」不合）；「たがる」是想做。唯「させる」與「子どもに…食べ」成立。"
  }),
  examQuestion({
    id: "n3-grammar-tokoroda-deru",
    level: "N3",
    surface: "ところだ",
    reading: "ところだ",
    meaningZh: "正要…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "「もしもし、今どこ？」「ごめん、ちょうど今、家を出る ___ だ。」",
    promptContextZh: "「喂，你現在在哪？」「抱歉，剛好現在正要出門。」",
    hintZh: "說話當下，出門這個動作所處的階段。",
    expectedAnswer: "ところ",
    options: ["ところ", "とき", "あいだ", "まま"],
    explanation: "「Vる＋ところだ」表示「正要…」即將進行，本句「正準備要出門」。「とき」是「…的時候」；「あいだ」是「…期間」；「まま」是「保持…狀態」。在「ちょうど今、家を出る___だ」中，唯「ところ」表「即將」成立。"
  }),
  examQuestion({
    id: "n3-vocab-nakanaka-tokenai",
    level: "N3",
    surface: "なかなか",
    reading: "なかなか",
    meaningZh: "（不）容易、怎麼也（不）",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この問題はとても難しくて、 ___ 解けない。",
    promptContextZh: "這道題目非常難，怎麼也解不開。",
    hintZh: "解這道題目的順利程度。",
    expectedAnswer: "なかなか",
    options: ["なかなか", "せっかく", "わざわざ", "たまたま"],
    explanation: "「なかなか＋否定」表示「（怎麼也）不容易…」，本句「題目太難，怎麼也解不開」。「せっかく」是「特意、難得」；「わざわざ」是「特地」；「たまたま」是「碰巧」。三者都不與「解けない」構成「不易」之意，唯「なかなか」成立。"
  }),
  examQuestion({
    id: "n3-vocab-shimekiri-maniawanai",
    level: "N3",
    surface: "締め切り",
    reading: "しめきり",
    meaningZh: "截止期限",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "急いだが、レポートの ___ に間に合わなかった。",
    promptContextZh: "雖然趕了，還是沒能趕上報告的截止期限。",
    hintZh: "報告沒能趕上的那個時間點。",
    expectedAnswer: "締め切り",
    options: ["締め切り", "待ち合わせ", "受付", "募集"],
    explanation: "「締め切り」是「截止期限」，本句「沒趕上報告的截止期限」。「待ち合わせ」是「碰面（之約）」；「受付」是「櫃台、報到」；「募集」是「招募」。與「レポートの…に間に合わなかった」搭配，唯「締め切り」成立。"
  }),
  examQuestion({
    id: "n3-vocab-niau-shatsu",
    level: "N3",
    surface: "似合う",
    reading: "にあう",
    meaningZh: "相襯、合適",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "その青いシャツ、君によく ___ ね。",
    promptContextZh: "那件藍襯衫很適合你呢。",
    hintZh: "藍襯衫穿在對方身上的效果。",
    expectedAnswer: "似合う",
    options: ["似合う", "間に合う", "付き合う", "似ている"],
    explanation: "「似合う」是「相襯、適合」，本句「那件藍襯衫很適合你」。「間に合う」是「來得及」；「付き合う」是「交往、陪同」；「似ている」是「相像」（近形陷阱，但「シャツが君に似ている」不通）。唯「似合う」成立。"
  }),
  examQuestion({
    id: "n3-vocab-nareru-shigoto",
    level: "N3",
    surface: "慣れる",
    reading: "なれる",
    meaningZh: "習慣、適應",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "新しい仕事に ___ まで、少し時間がかかった。",
    promptContextZh: "直到適應新工作，花了一點時間。",
    hintZh: "對新工作從陌生到上手的過程。",
    expectedAnswer: "慣れる",
    options: ["慣れる", "慣らす", "困る", "飽きる"],
    explanation: "「慣れる」是「習慣、適應」，本句「直到適應新工作花了點時間」。「慣らす」是「使習慣（他動）」，與「仕事に」自動詞語境不合；「困る」是「為難」；「飽きる」是「厭倦」。唯「慣れる」成立。"
  }),
  examQuestion({
    id: "n3-vocab-azukeru-inu",
    level: "N3",
    surface: "預ける",
    reading: "あずける",
    meaningZh: "託放、寄放",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "旅行の間、犬をペットホテルに ___ ことにした。",
    promptContextZh: "決定旅行期間把狗寄放在寵物旅館。",
    hintZh: "旅行期間對於狗的安排方向。",
    expectedAnswer: "預ける",
    options: ["預ける", "預かる", "借りる", "育てる"],
    explanation: "「預ける」是「（把東西）託放給對方保管」，本句「把狗寄放在寵物旅館」。「預かる」方向相反，是「（替對方）保管」；「借りる」是「借入」；「育てる」是「養育」（場所用「で」、且旅行期間暫時安置與長期養育語意不符）。主語把狗暫時交給旅館託管，唯「預ける」成立。"
  }),
  examQuestion({
    id: "n3-vocab-tashikameru-jikan",
    level: "N3",
    surface: "確かめる",
    reading: "たしかめる",
    meaningZh: "確認、查清",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "出発する前に、電車の時間をもう一度 ___ 。",
    promptContextZh: "出發之前，再確認一次電車的時間。",
    hintZh: "出發前針對電車時間做的動作。",
    expectedAnswer: "確かめる",
    options: ["確かめる", "見つける", "比べる", "決める"],
    explanation: "「確かめる」是「確認、查清」，本句「出發前再確認一次電車時間」。「見つける」是「找到」；「比べる」是「比較」；「決める」是「決定」。與「もう一度…時間を」搭配，唯「確かめる」成立。"
  }),
  examQuestion({
    id: "n3-vocab-sekkaku-ryouri",
    level: "N3",
    surface: "せっかく",
    reading: "せっかく",
    meaningZh: "特意、難得",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: " ___ 作った料理なのに、誰も食べてくれなかった。",
    promptContextZh: "特意做的菜，卻沒有人吃。",
    hintZh: "對於做了菜卻沒人吃的心情。",
    expectedAnswer: "せっかく",
    options: ["せっかく", "わざと", "たまたま", "なかなか"],
    explanation: "「せっかく」表示「特意、難得（卻白費）」，本句「特意做的菜卻沒人吃」帶惋惜。「わざと」是「故意」；「たまたま」是「碰巧」；「なかなか」是「（不）容易」。與「作った料理なのに誰も食べてくれなかった」的惋惜語感相配，唯「せっかく」成立。"
  }),
  examQuestion({
    id: "n3-vocab-medatsu-hitogomi",
    level: "N3",
    surface: "目立つ",
    reading: "めだつ",
    meaningZh: "顯眼、突出",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "彼女は赤い服を着ているので、人混みの中でもよく ___ 。",
    promptContextZh: "她穿著紅色衣服，在人群中也很顯眼。",
    hintZh: "她在人群中的醒目程度。",
    expectedAnswer: "目立つ",
    options: ["目立つ", "似合う", "目指す", "見つかる"],
    explanation: "「目立つ」是「顯眼、突出」，本句「她穿紅衣服，在人群中也很顯眼」。「似合う」是「相襯」；「目指す」是「以…為目標」；「見つかる」是「被找到」。與「人混みの中でも」搭配表醒目，唯「目立つ」成立。"
  }),
  examQuestion({
    id: "n3-vocab-matomeru-iken",
    level: "N3",
    surface: "まとめる",
    reading: "まとめる",
    meaningZh: "整合、歸納",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "司会者は、参加者のいろいろな意見を一つに ___ 。",
    promptContextZh: "主持人把與會者各式各樣的意見整合為一。",
    hintZh: "主持人對眾多意見的處理方式。",
    expectedAnswer: "まとめた",
    options: ["まとめた", "集めた", "並べた", "分けた"],
    explanation: "「まとめる」是「整合、歸納成一個」，本句「把與會者的意見整合為一」。「集める」是「收集（多個）」，與「一つに」不合；「並べる」是「排列」；「分ける」是「分開」。與「一つに」搭配表合而為一，唯「まとめた」成立。"
  }),
  examQuestion({
    id: "n3-vocab-kotowaru-zangyou",
    level: "N3",
    surface: "断る",
    reading: "ことわる",
    meaningZh: "拒絕、回絕",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "残業を頼まれたが、用事があるので ___ 。",
    promptContextZh: "雖然被請求加班，但因為有事所以回絕了。",
    hintZh: "面對加班請求所做的回應。",
    expectedAnswer: "断った",
    options: ["断った", "謝った", "頼んだ", "許した"],
    explanation: "「断る」是「拒絕、回絕」，本句「被請求加班，但因有事而回絕」。「謝る」是「道歉」；「頼む」是「拜託」；「許す」是「原諒」。與「用事があるので」的轉折相配，唯「断った」成立。"
  }),
  examQuestion({
    id: "n3-kanji-tsugou",
    level: "N3",
    surface: "都合",
    reading: "つごう",
    meaningZh: "情況、方便與否",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "今日はちょっと「都合」が悪いので、また今度にしてください。",
    promptContextZh: "今天有點不方便，請改約下次。",
    expectedAnswer: "つごう",
    options: ["つごう", "とごう", "つこう", "とこう"],
    explanation: "「都」在此讀「つ」、「合」濁化讀「ごう」，故「都合」＝つごう（情況、方便與否）。「とごう」誤把「都」讀成「と」；「つこう」漏掉「合」的濁音；「とこう」兩處都錯。",
    exampleJapanese: "今日はちょっと都合が悪いので、また今度にしてください。",
    exampleMeaningZh: "今天有點不方便，請改約下次。"
  }),
  examQuestion({
    id: "n3-kanji-kufuu",
    level: "N3",
    surface: "工夫",
    reading: "くふう",
    meaningZh: "設法、巧思",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "問題を解決するために、いろいろな「工夫」をした。",
    promptContextZh: "為了解決問題，下了各種工夫。",
    expectedAnswer: "くふう",
    options: ["くふう", "こうふう", "くぶう", "こうぶう"],
    explanation: "「工」讀短音「く」、「夫」讀「ふ」（不濁化），故「工夫」＝くふう（設法、巧思）。「こうふう」誤把「工」讀成長音「こう」；「くぶう」把「夫」誤濁成「ぶ」；「こうぶう」兩處都錯。",
    exampleJapanese: "問題を解決するために、いろいろな工夫をした。",
    exampleMeaningZh: "為了解決問題，下了各種工夫。"
  }),
  examQuestion({
    id: "n3-kanji-housou",
    level: "N3",
    surface: "放送",
    reading: "ほうそう",
    meaningZh: "播送、廣播",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "台風の最新情報がテレビで「放送」された。",
    promptContextZh: "颱風的最新資訊在電視上播送了。",
    expectedAnswer: "ほうそう",
    options: ["ほうそう", "ぼうそう", "ほそう", "ほうぞう"],
    explanation: "「放」讀長音「ほう」、「送」讀「そう」，故「放送」＝ほうそう（播送）。「ぼうそう」把「放」誤濁成「ぼう」（會變成「暴走」）；「ほそう」漏掉長音；「ほうぞう」把「送」誤濁成「ぞう」。",
    exampleJapanese: "台風の最新情報がテレビで放送された。",
    exampleMeaningZh: "颱風的最新資訊在電視上播送了。"
  }),
  examQuestion({
    id: "n3-kanji-keiken",
    level: "N3",
    surface: "経験",
    reading: "けいけん",
    meaningZh: "經驗",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "海外で働いた「経験」が、今の仕事に役立っている。",
    promptContextZh: "在海外工作的經驗，對現在的工作很有幫助。",
    expectedAnswer: "けいけん",
    options: ["けいけん", "けいげん", "けえけん", "きけん"],
    explanation: "「経」讀長音「けい」、「験」讀「けん」，故「経験」＝けいけん（經驗）。「けいげん」把「験」誤濁成「げん」；「けえけん」把長音誤寫成「けえ」；「きけん」音節錯誤（近「危険」）。",
    exampleJapanese: "海外で働いた経験が、今の仕事に役立っている。",
    exampleMeaningZh: "在海外工作的經驗，對現在的工作很有幫助。"
  }),
  examQuestion({
    id: "n3-kanji-shinsetsu",
    level: "N3",
    surface: "親切",
    reading: "しんせつ",
    meaningZh: "親切",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "道に迷ったとき、「親切」な人が駅まで案内してくれた。",
    promptContextZh: "迷路的時候，有位親切的人帶我到車站。",
    expectedAnswer: "しんせつ",
    options: ["しんせつ", "じんせつ", "しんぜつ", "じんぜつ"],
    explanation: "「親」讀「しん」、「切」讀「せつ」，故「親切」＝しんせつ（親切）。「じんせつ」把「親」誤濁成「じん」；「しんぜつ」把「切」誤濁成「ぜつ」；「じんぜつ」兩處都錯。",
    exampleJapanese: "道に迷ったとき、親切な人が駅まで案内してくれた。",
    exampleMeaningZh: "迷路的時候，有位親切的人帶我到車站。"
  }),
  examQuestion({
    id: "n3-context-sorede",
    level: "N3",
    surface: "それで",
    reading: "それで",
    meaningZh: "因此、所以",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "朝から大雨が降っていた。 ___ 、今日の試合は中止になった。",
    promptContextZh: "從早上就下著大雨，因此今天的比賽取消了。",
    hintZh: "前句的大雨與後句比賽結果之間的關係。",
    expectedAnswer: "それで",
    options: ["それで", "それに", "ところが", "それとも"],
    explanation: "「それで」承接前因、帶出結果「因此」，本句「一早就下大雨，因此比賽取消了」。「それに」是「而且」（追加）；「ところが」是「然而」（出乎意料）；「それとも」是「或者」（選擇）。表因果，唯「それで」成立。"
  }),
  examQuestion({
    id: "n3-context-tsumari",
    level: "N3",
    surface: "つまり",
    reading: "つまり",
    meaningZh: "也就是說",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "彼は私の母の弟だ。 ___ 、私のおじにあたる。",
    promptContextZh: "他是我媽媽的弟弟，也就是說相當於我的舅舅。",
    hintZh: "後句是對前句的換句話說。",
    expectedAnswer: "つまり",
    options: ["つまり", "しかし", "それで", "たとえば"],
    explanation: "「つまり」用於換句話說、歸結，本句「他是我媽媽的弟弟，也就是說是我舅舅」。「しかし」是「但是」；「それで」是「所以」；「たとえば」是「例如」。表「換言之」，唯「つまり」成立。"
  }),
  examQuestion({
    id: "n3-grammar-naito-name",
    level: "N3",
    surface: "ないと",
    reading: "ないと",
    meaningZh: "如果不…（就會…）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "名前を書か ___ 、誰の提出物か分からない。",
    promptContextZh: "如果不寫名字，就不知道是誰交的東西。",
    hintZh: "沒寫名字會造成的結果。",
    expectedAnswer: "ないと",
    options: ["ないと", "ないで", "なくても", "ないうちに"],
    explanation: "「Vないと、〜」表示如果不做前項就會導致後項結果，本句是不寫名字就分不出是誰交的。「ないで」表示不做某事而…（後接動作，且「分からない」非動作，不順）；「なくても」是「即使不…也…」，會變成「即使不寫也分不出」與原意矛盾；「ないうちに」是「趁還沒…」，皆不合。唯「ないと」成立。"
  }),
  examQuestion({
    id: "n3-grammar-tearu-door",
    level: "N3",
    surface: "てある",
    reading: "てある",
    meaningZh: "（有意做後留下的）狀態",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "会議室のドアがもう開けて ___ 。中に入って大丈夫です。",
    promptContextZh: "會議室的門已經開著了，可以進去。",
    hintZh: "門被打開後一直保持著、可以直接進去。",
    expectedAnswer: "ある",
    options: ["ある", "おく", "いる", "しまう"],
    explanation: "「他動詞て＋ある」表示某人有意做了動作後留下的狀態，本句是門已被打開而開著。「開けておく」需以人為主語表示事先打開，與「ドアが」這個無情物主語不合；「ドアが開けている」他動詞用「が」主語不通；「開けてしまう」偏完成或遺憾，與「中に入って大丈夫」矛盾。唯「ある」成立。"
  }),
  examQuestion({
    id: "n3-grammar-youni-voice",
    level: "N3",
    surface: "ように",
    reading: "ように",
    meaningZh: "為了（達到某狀態）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "後ろの席の人にも聞こえる ___ 、もう少し大きな声で話してください。",
    promptContextZh: "為了讓後排的人也聽得到，請說大聲一點。",
    hintZh: "調整音量所要達到的目標狀態。",
    expectedAnswer: "ように",
    options: ["ように", "ために", "とおりに", "かわりに"],
    explanation: "「V可能形／無意志動詞＋ように」表示目的或目標狀態，本句是為了讓後排也聽得到。「ために」要接意志動詞或名詞目的，「聞こえる」是無意志動詞，「聞こえるために」不自然；「とおりに」是「按照」；「かわりに」是「代替」，皆不合。唯「ように」成立。"
  }),
  examQuestion({
    id: "n3-grammar-kotogaaru-hokkaido",
    level: "N3",
    surface: "たことがある",
    reading: "たことがある",
    meaningZh: "曾經…過（經驗）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "子どものころ、家族で北海道へ行った ___ 。",
    promptContextZh: "小時候曾和家人去過北海道。",
    hintZh: "過去是否有過這樣的經歷。",
    expectedAnswer: "ことがある",
    options: ["ことがある", "ところがある", "はずがある", "つもりがある"],
    explanation: "「Vたことがある」表示曾經有過某經驗，本句是小時候曾和家人去過北海道。「ところがある」不表示經驗；「はずがある」此處不自然；「つもりがある」是「有意願」，不能接過去經驗。唯「ことがある」成立。"
  }),
  examQuestion({
    id: "n3-grammar-kotoninatteiru-library",
    level: "N3",
    surface: "ことになっている",
    reading: "ことになっている",
    meaningZh: "（規定、慣例）規定要…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この図書館では、飲み物はふた付きのものだけ持ち込める ___ 。",
    promptContextZh: "這間圖書館規定只能帶有蓋子的飲料進入。",
    hintZh: "場所內既定的規則或安排。",
    expectedAnswer: "ことになっている",
    options: ["ことになっている", "ことにしている", "ようにしている", "ところだった"],
    explanation: "「Vることになっている」表示規則、安排或慣例，本句是在說圖書館的規定。「ことにしている」「ようにしている」表示個人習慣或自我決定，與設施規則不合；「ところだった」是「正要、差點」，皆不合。唯「ことになっている」成立。"
  }),
  examQuestion({
    id: "n3-vocab-moushikomi-course",
    level: "N3",
    surface: "申し込み",
    reading: "もうしこみ",
    meaningZh: "報名、申請",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "講座に参加したい人は、金曜までに ___ をしてください。",
    promptContextZh: "想參加講座的人，請在週五前完成報名。",
    hintZh: "參加課程前要完成的手續。",
    expectedAnswer: "申し込み",
    options: ["申し込み", "申し訳", "見込み", "思い出"],
    explanation: "講座やイベントへの参加手続きは「申し込み」（報名、申請）。「申し訳」是道歉語；「見込み」是預估或可能性；「思い出」是回憶。與「参加したい人」「金曜までに…をして」的報名語境相配，唯「申し込み」成立。"
  }),
  examQuestion({
    id: "n3-vocab-naosu-kanji",
    level: "N3",
    surface: "直す",
    reading: "なおす",
    meaningZh: "改正、修正",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "名前の漢字が間違っていたので、すぐに ___ もらった。",
    promptContextZh: "名字的漢字寫錯了，所以馬上請對方改正。",
    hintZh: "把寫錯的字加以更正。",
    expectedAnswer: "直して",
    options: ["直して", "治して", "戻して", "返して"],
    explanation: "文字や誤りを改める時は「直す」（改正）。「治す」是治療病傷（同音陷阱，但漢字錯誤不用「治す」）；「戻す」是恢復原狀；「返す」是歸還。與「漢字が間違っていた」的改正語境相配，唯「直して」成立。"
  }),
  examQuestion({
    id: "n3-vocab-nokotte-bag",
    level: "N3",
    surface: "残る",
    reading: "のこる",
    meaningZh: "留下、剩下",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "授業が終わった後も、教室にかばんが一つ ___ いた。",
    promptContextZh: "下課之後，教室裡還留著一個包包。",
    hintZh: "東西沒被帶走，仍在原處。",
    expectedAnswer: "残って",
    options: ["残って", "余って", "残して", "置いて"],
    explanation: "物がその場に残る時は自動詞「残る」（残っている）。「余る」是多出、剩餘，一個包不算「余る」；「残す」是他動詞，主語通常是人（「かばんが残して」不通）；「かばんが置いていた」不自然，應為「置いてあった」。唯「残って」成立。"
  }),
  examQuestion({
    id: "n3-vocab-maniau-train",
    level: "N3",
    surface: "間に合う",
    reading: "まにあう",
    meaningZh: "趕得上、來得及",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "駅まで走ったので、発車時刻に ___ 。",
    promptContextZh: "因為跑到了車站，趕上了發車時刻。",
    hintZh: "在預定時間前順利趕到。",
    expectedAnswer: "間に合った",
    options: ["間に合った", "間違った", "向かった", "追いついた"],
    explanation: "時間に遅れず到着することは「間に合う」（趕得上）。「間違う」是弄錯；「向かう」是前往（尚未到達）；「追いつく」是追上某人或某物，不直接表示趕上發車時刻。與「発車時刻に」搭配，唯「間に合った」成立。"
  }),
  examQuestion({
    id: "n3-vocab-kawaku-shirt",
    level: "N3",
    surface: "乾く",
    reading: "かわく",
    meaningZh: "（物品）變乾、乾燥",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "洗ったシャツがまだ ___ いないので、今日は着られない。",
    promptContextZh: "洗好的襯衫還沒乾，所以今天不能穿。",
    hintZh: "衣服洗完後水分是否消失。",
    expectedAnswer: "乾いて",
    options: ["乾いて", "渇いて", "空いて", "冷えて"],
    explanation: "衣類や物の水分がなくなる時は「乾く」（變乾）。「渇く」是口渴（同音陷阱，喉が渇く）；「空く」是空出；「冷える」是變冷。與「洗ったシャツ」「着られない」搭配，唯「乾いて」成立。"
  }),
  examQuestion({
    id: "n3-vocab-suteru-magazines",
    level: "N3",
    surface: "捨てる",
    reading: "すてる",
    meaningZh: "丟棄、扔掉",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "読まなくなった古い雑誌をまとめて ___ 。",
    promptContextZh: "把不再看的舊雜誌一起丟掉了。",
    hintZh: "不要的雜誌最後如何處理。",
    expectedAnswer: "捨てた",
    options: ["捨てた", "拾った", "渡した", "戻した"],
    explanation: "不要な物を処分する時は「捨てる」（丟棄）。「拾う」是撿起；「渡す」是交給別人；「戻す」是放回或返回。與「読まなくなった古い雑誌」的處分語境相配，唯「捨てた」成立。"
  }),
  examQuestion({
    id: "n3-vocab-erabu-color",
    level: "N3",
    surface: "選ぶ",
    reading: "えらぶ",
    meaningZh: "選擇、挑選",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "三つの中から好きな色を一つ ___ ください。",
    promptContextZh: "請從三個當中挑一個喜歡的顏色。",
    hintZh: "從多個選項中決定一個。",
    expectedAnswer: "選んで",
    options: ["選んで", "比べて", "並べて", "集めて"],
    explanation: "多個選項から一つ決める時は「選ぶ」（選擇）。「比べる」是比較；「並べる」是排列；「集める」是收集，三者都與「一つ…ください」（挑出一個）不合。唯「選んで」成立。"
  }),
  examQuestion({
    id: "n3-kanji-genin",
    level: "N3",
    surface: "原因",
    reading: "げんいん",
    meaningZh: "原因",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "事故の「原因」を調べるため、現場を確認した。",
    promptContextZh: "為了調查事故的原因，確認了現場。",
    expectedAnswer: "げんいん",
    options: ["げんいん", "げいいん", "げんにん", "がんいん"],
    explanation: "「原」讀「げん」、「因」讀「いん」，故「原因」＝げんいん。「げいいん」是把「ん」音脫落的誤讀；「げんにん」與「現任／原人」等別語混同；「がんいん」是語頭母音的誤讀。",
    exampleJapanese: "事故の原因を調べるため、現場を確認した。",
    exampleMeaningZh: "為了調查事故的原因，確認了現場。"
  }),
  examQuestion({
    id: "n3-kanji-koutsuu",
    level: "N3",
    surface: "交通",
    reading: "こうつう",
    meaningZh: "交通",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "雪のため、「交通」が大きく乱れている。",
    promptContextZh: "因為下雪，交通大亂。",
    expectedAnswer: "こうつう",
    options: ["こうつう", "こうずう", "こつう", "こうとう"],
    explanation: "「交」讀長音「こう」、「通」讀「つう」，故「交通」＝こうつう。「こうずう」是把「つ」誤濁成「ず」；「こつう」是長音脫落；「こうとう」是把「通」誤讀成別音（近「高等」）。",
    exampleJapanese: "雪のため、交通が大きく乱れている。",
    exampleMeaningZh: "因為下雪，交通大亂。"
  }),
  examQuestion({
    id: "n3-kanji-shippai",
    level: "N3",
    surface: "失敗",
    reading: "しっぱい",
    meaningZh: "失敗",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "一度の「失敗」であきらめず、もう一度挑戦した。",
    promptContextZh: "沒有因一次失敗就放棄，再挑戰了一次。",
    expectedAnswer: "しっぱい",
    options: ["しっぱい", "しつばい", "しはい", "しっぺい"],
    explanation: "「失」促音化讀「しっ」、「敗」讀「ぱい」，故「失敗」＝しっぱい。「しつばい」是促音與清濁皆誤；「しはい」是音脫落（近「支配」）；「しっぺい」是「疾病」等別語的讀音。",
    exampleJapanese: "一度の失敗であきらめず、もう一度挑戦した。",
    exampleMeaningZh: "沒有因一次失敗就放棄，再挑戰了一次。"
  }),
  examQuestion({
    id: "n3-kanji-yakusoku",
    level: "N3",
    surface: "約束",
    reading: "やくそく",
    meaningZh: "約定、約會",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "友達との「約束」を忘れてしまった。",
    promptContextZh: "把和朋友的約定忘了。",
    expectedAnswer: "やくそく",
    options: ["やくそく", "やくぞく", "よくそく", "やっそく"],
    explanation: "「約」讀「やく」、「束」讀「そく」，故「約束」＝やくそく。「やくぞく」是把「そ」誤濁成「ぞ」；「よくそく」是語頭母音的誤讀；「やっそく」是把「く」誤促音化。",
    exampleJapanese: "友達との約束を忘れてしまった。",
    exampleMeaningZh: "把和朋友的約定忘了。"
  }),
  examQuestion({
    id: "n3-context-tokorode-meeting",
    level: "N3",
    surface: "ところで",
    reading: "ところで",
    meaningZh: "對了、話說回來（轉換話題）",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "明日の発表資料は完成しました。 ___ 、会議は何時からですか。",
    promptContextZh: "明天的發表資料完成了。對了，會議是幾點開始呢？",
    hintZh: "前句話題告一段落後，轉到另一個相關問題。",
    expectedAnswer: "ところで",
    options: ["ところで", "だから", "それでも", "つまり"],
    explanation: "「ところで」用於轉換話題，本句先說資料完成，接著轉問會議時間。「だから」表示所以（因果）；「それでも」表示即使如此（逆接）；「つまり」表示換言之（歸結），皆不適合話題轉換。唯「ところで」成立。"
  }),
  examQuestion({
    id: "reinforce-round2-bayokatta-consult",
    level: "N3",
    surface: "ばよかった",
    reading: "ばよかった",
    meaningZh: "早知道就該…（懊悔）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "こんなに簡単に解決するなら、もっと早く先生に相談 ___。",
    promptContextZh: "早知道這麼容易解決，就該早點找老師商量。",
    hintZh: "事後才覺得當初應該那麼做。",
    expectedAnswer: "すればよかった",
    options: ["すればよかった", "することにした", "しているところだった", "しないわけではない"],
    explanation: "「Vばよかった」表示後悔：如果當時做了就好了。本句是早點問老師就好了。「することにした」表示決定；「しているところだった」正在做；「しないわけではない」並非不做，皆不合。"
  }),
  examQuestion({
    id: "n3-syn-toutou",
    level: "N3",
    surface: "とうとう",
    reading: "とうとう",
    meaningZh: "終於、到最後",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "三時間も待って、バスは「とうとう」来なかった。",
    promptContextZh: "等了三個小時，巴士到最後還是沒來。",
    hintZh: "形容一件事經過漫長過程之後出現的結果。",
    expectedAnswer: "ついに",
    options: ["ついに", "すぐに", "だんだん", "もうすぐ"],
    explanation: "「とうとう」表示經過長時間或過程後最終的結果（此處是最終沒來），≒「ついに」。「すぐに」是「馬上」（無過程）；「だんだん」是「漸漸地」（描述變化過程，不是最終結果）；「もうすぐ」是「快要」（事情尚未發生）。唯「ついに」與「とうとう」同義。",
    exampleJapanese: "三時間も待って、バスはついに来なかった。",
    exampleMeaningZh: "等了三個小時，巴士到最後還是沒來。"
  }),
  examQuestion({
    id: "n3-syn-tashika",
    level: "N3",
    surface: "たしか",
    reading: "たしか",
    meaningZh: "（印象中）好像是、記得是",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "会議は「たしか」三時からだったと思う。",
    promptContextZh: "我記得會議好像是三點開始。",
    hintZh: "說話者憑記憶判斷，語氣帶有不太肯定的味道。",
    expectedAnswer: "おそらく",
    options: ["おそらく", "きっと", "ぜったいに", "やっぱり"],
    explanation: "副詞「たしか」表示憑記憶的不確定推測「記得好像…」，與表推測的「おそらく」相近。「きっと」是「一定」（把握度高）；「ぜったいに」是「絕對」（100% 肯定）；「やっぱり」是「果然」（事後印證）。唯「おそらく」與「たしか」同為不確定的推測語氣。",
    exampleJapanese: "会議はおそらく三時からだったと思う。",
    exampleMeaningZh: "我記得會議好像是三點開始。"
  }),
  examQuestion({
    id: "n3-syn-sassoku",
    level: "N3",
    surface: "さっそく",
    reading: "さっそく",
    meaningZh: "立刻、趕緊（去做）",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "新しい辞書を買って、「さっそく」使ってみた。",
    promptContextZh: "買了新字典，馬上就用用看。",
    hintZh: "拿到東西後不拖延、立即動手的樣子。",
    expectedAnswer: "すぐに",
    options: ["すぐに", "ゆっくり", "あとで", "たまに"],
    explanation: "「さっそく」表示「（得到某物或機會後）立刻著手做」，≒「すぐに」。「ゆっくり」是「慢慢地」（相反）；「あとで」是「待會兒」（延後）；「たまに」是「偶爾」（頻率）。唯「すぐに」與「さっそく」同表立即去做。",
    exampleJapanese: "新しい辞書を買って、すぐに使ってみた。",
    exampleMeaningZh: "買了新字典，馬上就用用看。"
  }),
  examQuestion({
    id: "n3-syn-jouzu",
    level: "N3",
    surface: "上手",
    reading: "じょうず",
    meaningZh: "擅長、拿手",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "姉は料理が「上手」で、いつもおいしい。",
    promptContextZh: "姊姊很會做菜，總是很好吃。",
    hintZh: "形容一個人對某件事做得很好、很在行。",
    expectedAnswer: "得意",
    options: ["得意", "下手", "苦手", "丁寧"],
    explanation: "「上手」表示某事做得好、很在行，≒「得意」（擅長且有自信）。「下手」「苦手」都表示「不擅長」（相反）；「丁寧」是「仔細、有禮」（描述做事態度，不等於擅長）。唯「得意」與「上手」同義。",
    exampleJapanese: "姉は料理が得意で、いつもおいしい。",
    exampleMeaningZh: "姊姊很會做菜，總是很好吃。"
  }),
  examQuestion({
    id: "n3-syn-kichinto",
    level: "N3",
    surface: "きちんと",
    reading: "きちんと",
    meaningZh: "確實地、好好地",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "出かける前に、戸締まりを「きちんと」してください。",
    promptContextZh: "出門前請好好把門窗鎖上。",
    hintZh: "做事不馬虎、按該有的方式仔細完成的樣子。",
    expectedAnswer: "ちゃんと",
    options: ["ちゃんと", "ときどき", "だんだん", "やっと"],
    explanation: "「きちんと」表示「確實、不馬虎地完成」，口語近義詞是「ちゃんと」。「ときどき」是「有時」（頻率）；「だんだん」是「漸漸」（變化）；「やっと」是「好不容易才」（強調費力達成）。唯「ちゃんと」與「きちんと」同表確實做好。",
    exampleJapanese: "出かける前に、戸締まりをちゃんとしてください。",
    exampleMeaningZh: "出門前請好好把門窗鎖上。"
  }),
  examQuestion({
    id: "n3-usage-tsutaeru",
    level: "N3",
    surface: "伝える",
    reading: "つたえる",
    meaningZh: "轉達、傳達話語",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「伝える」の使い方が最も適切なものはどれか。",
    promptContextZh: "「伝える」是把話語或事情傳達給某人。",
    hintZh: "把一件事或一句話讓對方知道的動作。",
    expectedAnswer: "会議が延期になったと、みんなに伝えてください。",
    options: ["会議が延期になったと、みんなに伝えてください。", "風邪を弟に伝えないように、マスクをした。", "仲間にボールを伝えて、ゴールを決めた。", "この病気は親から子へ伝えることがある。"],
    explanation: "「伝える」＝把話語、訊息傳達給人，本句「請向大家轉達會議延期」最自然。把感冒傳染給人用「うつす」；把球傳給隊友用「パスする／渡す」；疾病經由血緣遺傳用「遺伝する」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "会議が延期になったと、みんなに伝えてください。",
    exampleMeaningZh: "請向大家轉達會議延期了。"
  }),
  examQuestion({
    id: "n3-usage-tsukareru",
    level: "N3",
    surface: "疲れる",
    reading: "つかれる",
    meaningZh: "疲累、疲倦",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「疲れる」の使い方が最も適切なものはどれか。",
    promptContextZh: "「疲れる」是身體或精神感到勞累。",
    hintZh: "身體或精神因勞動而感到吃力的狀態。",
    expectedAnswer: "一日中歩いたので、足がとても疲れた。",
    options: ["一日中歩いたので、足がとても疲れた。", "電池が疲れて、時計が止まってしまった。", "夏は食べ物がすぐに疲れるので注意が必要だ。", "水をやらなかったので、花が疲れてしまった。"],
    explanation: "「疲れる」＝（人或身體部位）因勞動而感到勞累，本句「走了一整天，腳很累」最自然。電池沒電用「なくなる／切れる」；食物變質用「腐る」；花枯萎用「枯れる」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "一日中歩いたので、足がとても疲れた。",
    exampleMeaningZh: "走了一整天，腳非常累。"
  }),
  examQuestion({
    id: "n3-usage-tarinai",
    level: "N3",
    surface: "足りない",
    reading: "たりない",
    meaningZh: "不足、不夠",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「足りない」の使い方が最も適切なものはどれか。",
    promptContextZh: "「足りない」是數量或程度不到所需。",
    hintZh: "數量或程度沒有達到需要的量。",
    expectedAnswer: "人手が足りないので、もう一人呼ぶことにした。",
    options: ["人手が足りないので、もう一人呼ぶことにした。", "弟はクラスでいちばん背が足りない。", "勉強しなかったので、試験に足りてしまった。", "急いだのに、電車に足りなくて遅刻した。"],
    explanation: "「足りない」＝數量、程度不夠，本句「人手不夠，所以決定再找一個人」最自然。個子矮用「（背が）低い」；考試不及格用「落ちる」；沒趕上電車用「間に合わない」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "人手が足りないので、もう一人呼ぶことにした。",
    exampleMeaningZh: "因為人手不夠，所以決定再找一個人。"
  }),
  examQuestion({
    id: "n3-usage-kuraberu",
    level: "N3",
    surface: "比べる",
    reading: "くらべる",
    meaningZh: "比較、對比",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「比べる」の使い方が最も適切なものはどれか。",
    promptContextZh: "「比べる」是把兩者放在一起對照。",
    hintZh: "把兩樣東西放在一起看出差別的動作。",
    expectedAnswer: "二つの店の値段を比べてから、買う店を決めた。",
    options: ["二つの店の値段を比べてから、買う店を決めた。", "駅のホームに、たくさんの人が比べて立っていた。", "発表のために、図書館で資料を比べておいた。", "本を大きさの順に、棚に比べてください。"],
    explanation: "「比べる」＝把兩者對照看出差別，本句「比較兩家店的價格後再決定」最自然。並排站立用「並ぶ」；收集資料用「集める」；按順序排放用「並べる」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "二つの店の値段を比べてから、買う店を決めた。",
    exampleMeaningZh: "比較了兩家店的價格後，才決定要買的店。"
  }),
  examQuestion({
    id: "n3-usage-todoku",
    level: "N3",
    surface: "届く",
    reading: "とどく",
    meaningZh: "（物品）送達、寄到",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「届く」の使い方が最も適切なものはどれか。",
    promptContextZh: "「届く」是寄送的物品送到、寄達某處。",
    hintZh: "寄出的東西抵達對方那裡的情形。",
    expectedAnswer: "昨日注文した本が、今日もう届いた。",
    options: ["昨日注文した本が、今日もう届いた。", "急いで走って、なんとか電車に届いた。", "私は約束より早く駅に届いた。", "棚の上の箱に手を届いて、取ろうとした。"],
    explanation: "「届く」＝（寄送的物品）送達、寄到，本句「昨天訂的書今天就寄到了」最自然。趕上電車用「間に合う」；（人）抵達某處用「着く」（届く 用於物品，不用於人到達）；伸手搆到用「手が届く」（自動詞，不可說「手を届く」）。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "昨日注文した本が、今日もう届いた。",
    exampleMeaningZh: "昨天訂的書，今天就已經寄到了。"
  }),
  examQuestion({
    id: "n3-vocab-mamoru",
    level: "N3",
    surface: "守る",
    reading: "まもる",
    meaningZh: "遵守、保護",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "ルールを ___ ことは、みんなが安全に過ごすために大切だ。",
    promptContextZh: "遵守規則對大家安全地生活來說很重要。",
    hintZh: "按照規定去做、不違反。",
    expectedAnswer: "守る",
    options: ["守る", "破る", "作る", "覚える"],
    explanation: "「守る」＝遵守（規則）、保護。「破る」是打破、違反（規則）；「作る」是製作；「覚える」是記住。與「ルールを…ことはみんなが安全に」搭配表遵守規則，唯「守る」成立。"
  }),
  examQuestion({
    id: "n3-vocab-tsutsumu",
    level: "N3",
    surface: "包む",
    reading: "つつむ",
    meaningZh: "包、包裹",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "プレゼントをきれいな紙で ___ 、リボンをつけた。",
    promptContextZh: "用漂亮的紙把禮物包起來，繫上緞帶。",
    hintZh: "用紙張把東西裹在裡面、不外露。",
    expectedAnswer: "包んだ",
    options: ["包んだ", "折った", "結んだ", "混ぜた"],
    explanation: "「包む」＝用紙、布把東西包起來。「折る」是摺疊；「結ぶ」是綁、打結；「混ぜる」是混合。與「紙で…リボンをつけた」搭配把禮物整個包覆，唯「包んだ」成立。"
  }),
  examQuestion({
    id: "n3-vocab-sugosu",
    level: "N3",
    surface: "過ごす",
    reading: "すごす",
    meaningZh: "度過、消磨",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "夏休みの一週間を、家族と田舎で楽しく ___ 。",
    promptContextZh: "暑假的一週，和家人在鄉下愉快地度過。",
    hintZh: "把一段日子用某種方式經歷、打發。",
    expectedAnswer: "過ごした",
    options: ["過ごした", "暮らした", "通った", "続いた"],
    explanation: "「過ごす」＝度過（一段時間），可接「一週間を」這類時間受詞。「暮らす」是（長期）生活、居住（自動詞，不接「一週間を」）；「通う」是往返、通勤；「続く」是持續（自動詞）。與「夏休みの一週間を…楽しく」搭配，唯「過ごした」成立。"
  }),
  examQuestion({
    id: "n3-vocab-tameru",
    level: "N3",
    surface: "貯める",
    reading: "ためる",
    meaningZh: "儲存、積攢",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "留学のために、毎月少しずつお金を ___ いる。",
    promptContextZh: "為了留學，每個月一點一點地存錢。",
    hintZh: "為了將來把錢一點一點留下來。",
    expectedAnswer: "貯めて",
    options: ["貯めて", "数えて", "払って", "借りて"],
    explanation: "「貯める」＝把錢儲存、積攢起來。「数える」是計算數量；「払う」是支付；「借りる」是借入。與「毎月少しずつお金を…いる」搭配表存錢，唯「貯めて」成立。"
  }),
  examQuestion({
    id: "n3-vocab-kazaru",
    level: "N3",
    surface: "飾る",
    reading: "かざる",
    meaningZh: "裝飾、擺飾",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "部屋の壁に、旅行で撮った写真を ___ 。",
    promptContextZh: "在房間的牆上裝飾旅行時拍的照片。",
    hintZh: "把東西擺出來讓空間更好看。",
    expectedAnswer: "飾った",
    options: ["飾った", "並べた", "重ねた", "配った"],
    explanation: "「飾る」＝為了美觀而裝飾、擺飾。「並べる」是（在平面上）排列；「重ねる」是疊放；「配る」是分發。與「壁に写真を」搭配表裝飾牆面，唯「飾った」成立。"
  }),
  examQuestion({
    id: "n3-vocab-akirameru",
    level: "N3",
    surface: "諦める",
    reading: "あきらめる",
    meaningZh: "放棄、死心",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "雨がひどかったので、今日の登山は ___ ことにした。",
    promptContextZh: "因為雨太大，決定放棄今天的登山。",
    hintZh: "因情況不允許而打消原本的念頭。",
    expectedAnswer: "諦める",
    options: ["諦める", "続ける", "始める", "決める"],
    explanation: "「諦める」＝放棄、死心。「続ける」是繼續；「始める」是開始；「決める」是決定。因「雨がひどかった」而打消登山計畫，唯「諦める」與「ことにした」搭配成立。"
  }),
  examQuestion({
    id: "n3-vocab-rusu",
    level: "N3",
    surface: "留守",
    reading: "るす",
    meaningZh: "不在家、看家",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "母は買い物に出かけていて、今は ___ です。",
    promptContextZh: "媽媽出門買東西了，現在不在家。",
    hintZh: "家裡沒人，主人外出了。",
    expectedAnswer: "留守",
    options: ["留守", "欠席", "留学", "休憩"],
    explanation: "「留守」＝（人外出）不在家。「欠席」是（會議、課程）缺席；「留学」是去外國求學；「休憩」是休息。與「買い物に出かけていて、今は…です」搭配表不在家，唯「留守」成立。"
  }),
  examQuestion({
    id: "n3-vocab-juutai",
    level: "N3",
    surface: "渋滞",
    reading: "じゅうたい",
    meaningZh: "塞車、交通壅塞",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "事故のせいで、高速道路がひどく ___ している。",
    promptContextZh: "因為車禍，高速公路嚴重塞車。",
    hintZh: "路上車太多、走不動的狀況。",
    expectedAnswer: "渋滞",
    options: ["渋滞", "故障", "満員", "停電"],
    explanation: "「渋滞」＝道路車多壅塞、塞車。「故障」是（機器、車輛）故障；「満員」是（人）擠滿、客滿；「停電」是停電。與「高速道路がひどく…している」搭配，唯「渋滞」成立。"
  }),
  examQuestion({
    id: "n3-vocab-kyuuryou",
    level: "N3",
    surface: "給料",
    reading: "きゅうりょう",
    meaningZh: "薪水、工資",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "今の会社は、仕事は大変だが ___ がいい。",
    promptContextZh: "現在的公司雖然工作辛苦，但薪水不錯。",
    hintZh: "公司每月發給員工的報酬。",
    expectedAnswer: "給料",
    options: ["給料", "料金", "値段", "代金"],
    explanation: "「給料」＝公司付給員工的薪水。「料金」是使用服務的費用；「値段」是商品的價格；「代金」是買東西要付的貨款。三者都是「要付出的錢」，與「仕事は大変だが…がいい」（領得多）不符，唯「給料」成立。"
  }),
  examQuestion({
    id: "n3-vocab-gaman",
    level: "N3",
    surface: "我慢",
    reading: "がまん",
    meaningZh: "忍耐、忍住",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "電車の中だったので、笑いたい気持ちを ___ した。",
    promptContextZh: "因為在電車裡，忍住了想笑的衝動。",
    hintZh: "把情緒或慾望壓下來不表現出。",
    expectedAnswer: "我慢",
    options: ["我慢", "遠慮", "心配", "緊張"],
    explanation: "「我慢」＝忍耐、把情緒或慾望壓住，可接「気持ちを」。「遠慮」是（顧及他人而）客氣、謝絕；「心配」是擔心；「緊張」是緊張。與「笑いたい気持ちを…した」（忍住笑）搭配，唯「我慢」成立。"
  }),
  examQuestion({
    id: "n3-vocab-junban",
    level: "N3",
    surface: "順番",
    reading: "じゅんばん",
    meaningZh: "順序、次序",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "受付で番号札を取って、自分の ___ が来るまで待つ。",
    promptContextZh: "在櫃台抽號碼牌，等到輪到自己為止。",
    hintZh: "排隊時輪到自己的先後位置。",
    expectedAnswer: "順番",
    options: ["順番", "場所", "時間", "予定"],
    explanation: "「順番」＝順序、輪到的次序。「場所」是地點；「時間」是時間；「予定」是預定計畫。與「番号札を取って、自分の…が来るまで待つ」（等輪到自己）搭配，唯「順番」成立。"
  }),
  examQuestion({
    id: "n3-vocab-kibishii",
    level: "N3",
    surface: "厳しい",
    reading: "きびしい",
    meaningZh: "嚴格、嚴厲",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あの先生は時間に ___ から、遅刻は絶対にできない。",
    promptContextZh: "那位老師對時間很嚴格，絕對不能遲到。",
    hintZh: "對規矩或要求毫不放鬆。",
    expectedAnswer: "厳しい",
    options: ["厳しい", "優しい", "詳しい", "正しい"],
    explanation: "「厳しい」＝嚴格、嚴厲。「優しい」是溫柔；「詳しい」是熟悉、詳盡；「正しい」是正確。與「時間に…から遅刻は絶対にできない」（對時間嚴格）搭配，唯「厳しい」成立。"
  }),
  examQuestion({
    id: "n3-vocab-komakai",
    level: "N3",
    surface: "細かい",
    reading: "こまかい",
    meaningZh: "細小、瑣細",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この作業は ___ ところまで注意が必要で、とても疲れる。",
    promptContextZh: "這項作業連細節都得注意，非常累人。",
    hintZh: "連很小的部分都不忽略。",
    expectedAnswer: "細かい",
    options: ["細かい", "深い", "高い", "広い"],
    explanation: "「細かい」＝細小、瑣細，「細かいところまで」表示連細節都顧到。「深い」是深；「高い」是高；「広い」是寬廣。與「作業は…ところまで注意が必要」（注意細節）搭配，唯「細かい」成立。"
  }),
  examQuestion({
    id: "n3-vocab-majime",
    level: "N3",
    surface: "真面目",
    reading: "まじめ",
    meaningZh: "認真、踏實",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "彼は毎日きちんと予習する、とても ___ な学生だ。",
    promptContextZh: "他每天都確實預習，是非常認真的學生。",
    hintZh: "做事一絲不苟、不偷懶。",
    expectedAnswer: "真面目",
    options: ["真面目", "派手", "得意", "苦手"],
    explanation: "「真面目」＝認真、踏實。「派手」是花俏、招搖；「得意」是擅長；「苦手」是不擅長。與「毎日きちんと予習する…な学生」（用功）搭配，唯「真面目」成立。"
  }),
  examQuestion({
    id: "n3-vocab-taikutsu",
    level: "N3",
    surface: "退屈",
    reading: "たいくつ",
    meaningZh: "無聊、無趣",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "話がつまらなくて、聞いているうちに ___ になってきた。",
    promptContextZh: "話題很無趣，聽著聽著就開始覺得無聊了。",
    hintZh: "因為沒意思而坐不住、提不起勁。",
    expectedAnswer: "退屈",
    options: ["退屈", "満足", "心配", "元気"],
    explanation: "「退屈」＝無聊、悶。「満足」是滿足；「心配」是擔心；「元気」是有精神。與「話がつまらなくて…になってきた」（覺得無聊）搭配，唯「退屈」成立。"
  })
];
