import type { PracticeQuestion } from "../../types";
import { examQuestion } from "../helpers";

export const n4Items: PracticeQuestion[] = [
  examQuestion({
    id: "n4-grammar-takotogaaru-fuji",
    level: "N4",
    surface: "たことがある",
    reading: "たことがある",
    meaningZh: "曾經…過（經驗）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "私は富士山に登っ ___ があります。",
    promptContextZh: "我曾經爬過富士山。",
    hintZh: "表達過去做過某件事。",
    expectedAnswer: "たこと",
    options: ["たこと", "ること", "ないこと", "るところ"],
    explanation: "「Vたことがある」表示過去的經驗，「登ったことがあります」＝曾經爬過。「ること」「ないこと」與「があります」無法構成『經驗』之意；「るところ」是「正要…」。表經驗唯「たこと」成立。"
  }),
  examQuestion({
    id: "n4-grammar-nakereba-shiken",
    level: "N4",
    surface: "なければならない",
    reading: "なければならない",
    meaningZh: "必須…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "明日は試験だから、今夜は勉強し ___ 。",
    promptContextZh: "因為明天考試，今晚必須讀書。",
    hintZh: "因為明天考試，今晚對讀書的必要性。",
    expectedAnswer: "なければならない",
    options: ["なければならない", "てもいい", "なくてもいい", "ないでください"],
    explanation: "「Vなければならない」表示義務、非做不可，「勉強しなければならない」＝必須讀書。「てもいい」是「可以…」；「なくてもいい」是「不必…」（相反）；「ないでください」是「請不要…」。配合「試験だから」的必要性，唯「なければならない」成立。"
  }),
  examQuestion({
    id: "n4-grammar-tahougaii-kaze",
    level: "N4",
    surface: "たほうがいい",
    reading: "たほうがいい",
    meaningZh: "最好…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "かぜの ときは、早く 寝た ___ が いいです。",
    promptContextZh: "感冒的時候，最好早點睡。",
    hintZh: "感冒時，關於睡覺給出的建議。",
    expectedAnswer: "ほう",
    options: ["ほう", "こと", "つもり", "はず"],
    explanation: "「Vたほうがいい」是給建議的固定句型「最好…」，「早く寝たほうがいい」＝最好早點睡。「こと」「つもり」「はず」都無法與「〜た___がいい」構成此建議句型。唯「ほう」成立。"
  }),
  examQuestion({
    id: "n4-vocab-abunai-michi",
    level: "N4",
    surface: "危ない",
    reading: "あぶない",
    meaningZh: "危險的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この道は車が多くて ___ ので、気をつけてください。",
    promptContextZh: "這條路車很多很危險，請小心。",
    hintZh: "車多、要小心，這條路給人的感覺。",
    expectedAnswer: "危ない",
    options: ["危ない", "明るい", "新しい", "暖かい"],
    explanation: "「危ない」是「危險的」，本句「車多很危險，請小心」即此。「明るい」是「明亮」；「新しい」是「新」；「暖かい」是「溫暖」。與「車が多くて…気をつけて」搭配，唯「危ない」成立。"
  }),
  examQuestion({
    id: "n4-kanji-keizai",
    level: "N4",
    surface: "経済",
    reading: "けいざい",
    meaningZh: "經濟",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "毎朝、新聞で「経済」のニュースを読みます。",
    promptContextZh: "每天早上看報紙的經濟新聞。",
    expectedAnswer: "けいざい",
    options: ["けいざい", "けいさい", "きょうざい", "けえざい"],
    explanation: "「経」讀長音「けい」、「済」濁化讀「ざい」，故「経済」＝けいざい。「けいさい」沒把「済」讀濁音；「きょうざい」誤把「経」讀「きょう」；「けえざい」把長音誤寫成「けえ」。",
    exampleJapanese: "毎朝、新聞で経済のニュースを読みます。",
    exampleMeaningZh: "每天早上看報紙的經濟新聞。"
  }),
  examQuestion({
    id: "n4-grammar-kanou-ryouri",
    level: "N4",
    surface: "可能形",
    reading: "つくれる",
    meaningZh: "會做、能做（可能形）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "毎日 練習したので、今では 一人で カレーが ___ ようになった。",
    promptContextZh: "因為每天練習，現在已經會一個人做咖哩了。",
    hintZh: "每天練習後，在下廚這件事上的轉變。",
    expectedAnswer: "作れる",
    options: ["作れる", "作る", "作られる", "作らせる"],
    explanation: "「Vようになった」前面要接表示能力的可能形，本句是「練習後變得會做咖哩」。「作れる」是「作る」的可能形「會做」，與「ようになった」搭配成立。「作る」是辭書形，缺少「從不會到會」的能力義；「作られる」此處是被動／尊敬，主語自己做咖哩用被動不通；「作らせる」是使役「讓別人做」，與「一人で」矛盾。唯「作れる」成立。"
  }),
  examQuestion({
    id: "n4-grammar-saseru-sensei",
    level: "N4",
    surface: "使役（させる）",
    reading: "かかせる",
    meaningZh: "讓／使（某人）做",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "先生は 学生に 作文を ___ 、一人ずつ 読ませた。",
    promptContextZh: "老師讓學生寫作文，再讓他們一個一個唸出來。",
    hintZh: "老師對學生下達的指示，後面又叫他們唸。",
    expectedAnswer: "書かせて",
    options: ["書かせて", "書かれて", "書けて", "書いて"],
    explanation: "句中「学生に〜、読ませた」是使役句，老師讓學生做動作，前項也應為使役「書かせて」（讓學生寫）。「書かれて」是被動／尊敬，與「学生に」的使役對象不合；「書けて」是可能形「會寫」，與後句「讓他們唸」的使役脈絡不一致；「書いて」是單純て形，少了「讓學生做」的使役義。唯「書かせて」與「学生に…読ませた」前後一致成立。"
  }),
  examQuestion({
    id: "n4-grammar-to-shizen",
    level: "N4",
    surface: "〜と（自然結果）",
    reading: "と",
    meaningZh: "一…就…（必然結果）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この ボタンを ___ 、切符が 出てきます。",
    promptContextZh: "一按這個按鈕，車票就會跑出來。",
    hintZh: "每次操作這個按鈕後固定會發生的事。",
    expectedAnswer: "押すと",
    options: ["押すと", "押すなら", "押しながら", "押しても"],
    explanation: "「Vと、〜」表示前項一發生就必然導致後項，常用於機械操作、自然規律，本句「按按鈕車票就出來」即此。「なら」是承接話題提建議，不表機械必然；「ながら」是「一邊…一邊…」同時進行，「押しながら切符が出てくる」語意不合（出票不是與按鈕同主語的同時動作）；「ても」是「即使按也…」，與「車票會出來」的正向結果矛盾。表固定因果唯「押すと」成立。"
  }),
  examQuestion({
    id: "n4-grammar-temo-ame",
    level: "N4",
    surface: "〜ても",
    reading: "ても",
    meaningZh: "即使…也…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "明日 雨が ___ 、試合は 行います。",
    promptContextZh: "明天就算下雨，比賽也照常舉行。",
    hintZh: "下不下雨與比賽是否舉行之間的關係。",
    expectedAnswer: "降っても",
    options: ["降っても", "降ったら", "降ると", "降るので"],
    explanation: "後句「試合は行います」是不受前項影響的決定，須用逆接條件「ても」（即使…也…）。「降っても行います」表示「就算下雨也辦」。「たら」「と」都是順接條件，會變成「下雨→辦比賽」的因果，與『下雨通常該停辦』的常識矛盾、不自然；「ので」是「因為」，「因為下雨所以舉行」邏輯不通。唯「降っても」表達讓步、成立。"
  }),
  examQuestion({
    id: "n4-grammar-souda-oishi",
    level: "N4",
    surface: "〜そう（樣態）",
    reading: "そう",
    meaningZh: "看起來…（樣態）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "わあ、この ケーキ、とても ___ ですね。一つ ください。",
    promptContextZh: "哇，這個蛋糕看起來好好吃喔，請給我一個。",
    hintZh: "看著蛋糕外觀、還沒吃時所做的判斷。",
    expectedAnswer: "おいしそう",
    options: ["おいしそう", "おいしいそう", "おいしいらしい", "おいしいよう"],
    explanation: "樣態「そう」表示「看起來…」，接い形容詞時要去掉「い」直接加「そう」，故「おいしい→おいしそう」。本句是看著蛋糕外觀做的判斷，用「おいしそう」。「おいしいそう」是傳聞用法（聽說很好吃），與『眼前親眼看到』的語境不合，且形態上傳聞需「おいしいそうだ」；「おいしいらしい」是根據傳聞／間接資訊推測，非眼前所見；「おいしいよう」語感是間接推斷且「ようですね」較生硬。唯眼見其貌的「おいしそう」成立。"
  }),
  examQuestion({
    id: "n4-grammar-rashii-denbun",
    level: "N4",
    surface: "〜らしい（傳聞）",
    reading: "らしい",
    meaningZh: "聽說、好像…（傳聞）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "ニュースに よると、来週は とても 寒く なる ___ です。",
    promptContextZh: "根據新聞報導，下週好像會變得很冷。",
    hintZh: "句首「根據新聞」提示了這個說法的來源。",
    expectedAnswer: "らしい",
    options: ["らしい", "つもり", "ながら", "そうな"],
    explanation: "句首「ニュースによると」（根據新聞）提示資訊來自外部來源，後面要用傳聞表現「らしい」（聽說／好像），本句「聽說下週會很冷」。「つもり」是說話者主觀打算，天氣非人能打算；「ながら」是「一邊…一邊…」，接續與語意皆不合；「そうな」樣態要接ます形或形容詞語幹（寒そう），不能接「なる」的辭書形成「なるそうな」，且樣態是眼前徵兆而非『根據新聞』。唯與「〜によると」呼應的傳聞「らしい」成立。"
  }),
  examQuestion({
    id: "n4-grammar-tsumori-eiga",
    level: "N4",
    surface: "〜つもり",
    reading: "つもり",
    meaningZh: "打算…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "私は 週末、家で ゆっくり 映画を 見る ___ です。",
    promptContextZh: "我打算週末在家悠閒地看電影。",
    hintZh: "說話者對週末的個人計畫。",
    expectedAnswer: "つもり",
    options: ["つもり", "らしい", "そう", "ながら"],
    explanation: "「Vる＋つもりだ」表示說話者主觀的打算，本句以句首「私は」點明是自己的計畫「打算週末在家看電影」。「らしい」是傳聞／推測別人的事，與「私は」自述矛盾；「そう」（樣態）需接ます形（見そう），接辭書形「見るそう」會變傳聞，同樣與「私は」不合；「ながら」是「一邊…一邊…」，「見るながら」接續也不對。唯表個人意圖的「つもり」成立。"
  }),
  examQuestion({
    id: "n4-grammar-nagara-aruki",
    level: "N4",
    surface: "〜ながら",
    reading: "ながら",
    meaningZh: "一邊…一邊…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "道を ___ スマホを 見るのは 危ないので、やめましょう。",
    promptContextZh: "邊走路邊看手機很危險，別這麼做吧。",
    hintZh: "走路和看手機這兩個動作同時進行。",
    expectedAnswer: "歩きながら",
    options: ["歩きながら", "歩いたら", "歩くなら", "歩くので"],
    explanation: "「Vます形＋ながら」表示同一個人同時做兩件事，本句是「邊走邊看手機」。「歩きながら見る」即「一邊走一邊看」。「歩いたら」是「走了之後／如果走」的條件，非同時；「歩くなら」是「如果要走的話」承接話題；「歩くので」是「因為走路」的原因，皆無法表達『同時進行』。唯接ます形的「歩きながら」成立。"
  }),
  examQuestion({
    id: "n4-grammar-noni-benkyou",
    level: "N4",
    surface: "〜のに",
    reading: "のに",
    meaningZh: "明明…卻…（逆接、不滿）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "弟は まだ 子ども ___ 、私より 漢字を よく 知って いる。",
    promptContextZh: "弟弟明明還是個小孩，卻比我還懂漢字。",
    hintZh: "弟弟的年紀和他懂的漢字量之間的反差。",
    expectedAnswer: "なのに",
    options: ["なのに", "なので", "だから", "なら"],
    explanation: "前後是「還是小孩」與「比我懂漢字」的意外反差，要用逆接「のに」，名詞後接「な＋のに」故為「なのに」。「なので」是「因為是小孩」的順接，會變『因為是小孩所以比我懂漢字』邏輯矛盾；「だから」同樣是順接因果，矛盾；「なら」是「如果是小孩的話」的條件，與既成事實不合。唯表逆接、帶意外語氣的「なのに」成立。"
  }),
  examQuestion({
    id: "n4-vocab-tsutaeru-message",
    level: "N4",
    surface: "伝える",
    reading: "つたえる",
    meaningZh: "傳達、轉告",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "田中さんが 来たら、「会議は 三時から」と ___ ください。",
    promptContextZh: "田中先生來的話，請轉告他「會議三點開始」。",
    hintZh: "把一段話的內容帶話給某個人。",
    expectedAnswer: "伝えて",
    options: ["伝えて", "答えて", "読んで", "聞いて"],
    explanation: "「伝える」指把訊息／話語轉告給某人，本句是請對方把「會議三點開始」帶給田中先生，與「と〜てください」的引用轉告句式最搭。「答える」是「回答（問題）」，此處沒有提問，不合；「読む」是「朗讀／閱讀」，與轉達口信無關；「聞く」是「聽／問」，方向相反。唯「伝えて」成立。"
  }),
  examQuestion({
    id: "n4-vocab-yoyaku-seki",
    level: "N4",
    surface: "予約",
    reading: "よやく",
    meaningZh: "預約",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "週末の レストランは 込むので、電話で 席を ___ して おいた。",
    promptContextZh: "週末的餐廳會很擠，所以先打電話訂了位子。",
    hintZh: "為了確保有位子，事先打電話做的安排。",
    expectedAnswer: "予約",
    options: ["予約", "予定", "用意", "案内"],
    explanation: "「予約」指事先訂位／訂購，本句是打電話「訂位子」，與「席を〜する」搭配成立。「予定」是「預定的計畫／行程」，不能「席を予定する」；「用意」是「準備（物品等）」，餐廳席位由店家保留，顧客是『預約』而非『準備』；「案内」是「帶路／介紹」，語意不合。唯「予約」成立。"
  }),
  examQuestion({
    id: "n4-vocab-kanarazu-yakusoku",
    level: "N4",
    surface: "必ず",
    reading: "かならず",
    meaningZh: "一定、務必",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "これは 大切な 約束だから、明日は ___ 来て ください。",
    promptContextZh: "這是重要的約定，所以明天請務必要來。",
    hintZh: "強調這件事沒有例外、毫無疑問要做到。",
    expectedAnswer: "必ず",
    options: ["必ず", "たぶん", "なかなか", "ぜんぜん"],
    explanation: "「必ず」表示「一定、務必」，與命令／請求「〜てください」搭配，強調無例外地要做到，本句是『務必要來』。「たぶん」是「大概」的推測，與『一定』的強制語氣相反；「なかなか」後多接否定或表「相當不容易」，「なかなか来てください」不通；「ぜんぜん」後接否定（全然…ない），「ぜんぜん来てください」接續錯誤。唯「必ず」成立。"
  }),
  examQuestion({
    id: "n4-vocab-sukkari-wasureru",
    level: "N4",
    surface: "すっかり",
    reading: "すっかり",
    meaningZh: "完全、徹底",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "昨日は 忙しくて、薬を 飲むのを ___ 忘れて いた。",
    promptContextZh: "昨天太忙了，把吃藥的事忘得一乾二淨。",
    hintZh: "強調這件事被忘得一點都不剩。",
    expectedAnswer: "すっかり",
    options: ["すっかり", "そろそろ", "なるべく", "だんだん"],
    explanation: "「すっかり」表示「完全、徹底」，常與「忘れる」搭配成「すっかり忘れる」（忘得一乾二淨），本句即此。「そろそろ」是「差不多該…」表時機，「そろそろ忘れていた」不通；「なるべく」是「盡量」，後多接意志／請求（なるべく早く），不修飾無意的「忘記」；「だんだん」是「漸漸」表逐步變化，「だんだん忘れていた」與『一次性完全忘記』的語意不合。唯「すっかり」成立。"
  }),
  examQuestion({
    id: "n4-kanji-setsumei",
    level: "N4",
    surface: "説明",
    reading: "せつめい",
    meaningZh: "說明",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "先生が 使い方を ていねいに「説明」して くれた。",
    promptContextZh: "老師仔細地說明了使用方法。",
    expectedAnswer: "せつめい",
    options: ["せつめい", "せつめえ", "せきめい", "ぜつめい"],
    explanation: "「説」讀「せつ」、「明」讀長音「めい」，故「説明」＝せつめい。「せつめえ」把長音「めい」誤寫成「めえ」；「せきめい」把「説（せつ）」誤讀成「せき」；「ぜつめい」把語頭「せ」誤濁成「ぜ」（近「絶命」）。唯「せつめい」正確。",
    exampleJapanese: "先生が使い方をていねいに説明してくれた。",
    exampleMeaningZh: "老師仔細地說明了使用方法。"
  }),
  examQuestion({
    id: "n4-kanji-riyou",
    level: "N4",
    surface: "利用",
    reading: "りよう",
    meaningZh: "利用、使用",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "図書館は だれでも 無料で「利用」できます。",
    promptContextZh: "圖書館任何人都可以免費使用。",
    expectedAnswer: "りよう",
    options: ["りよう", "りょう", "りゆう", "りようう"],
    explanation: "「利」讀「り」、「用」讀「よう」，故「利用」＝りよう（三拍：り・よ・う）。「りょう」把「りよ」誤拼成拗音一拍「りょ」（少一拍，近「量／料」）；「りゆう」把「用（よう）」誤讀成「ゆう」（近「理由」）；「りようう」多加一個「う」。唯「りよう」正確。",
    exampleJapanese: "図書館はだれでも無料で利用できます。",
    exampleMeaningZh: "圖書館任何人都可以免費使用。"
  }),
  examQuestion({
    id: "n4-kanji-seiji",
    level: "N4",
    surface: "政治",
    reading: "せいじ",
    meaningZh: "政治",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "若い 人も もっと「政治」に 関心を 持った ほうが いい。",
    promptContextZh: "年輕人也最好多關心政治。",
    expectedAnswer: "せいじ",
    options: ["せいじ", "せいち", "せえじ", "しょうじ"],
    explanation: "「政」讀長音「せい」、「治」在此濁化讀「じ」，故「政治」＝せいじ。「せいち」沒把「治」讀濁音（清音「ち」）；「せえじ」把長音「せい」誤寫成「せえ」；「しょうじ」把「政（せい）」誤讀成「しょう」。唯「せいじ」正確。",
    exampleJapanese: "若い人ももっと政治に関心を持ったほうがいい。",
    exampleMeaningZh: "年輕人也最好多關心政治。"
  }),
  examQuestion({
    id: "n4-kanji-yotei",
    level: "N4",
    surface: "予定",
    reading: "よてい",
    meaningZh: "預定、計畫",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "来月の 旅行の「予定」は もう 決まりました。",
    promptContextZh: "下個月旅行的行程已經定下來了。",
    expectedAnswer: "よてい",
    options: ["よてい", "ようてい", "よてえ", "よでい"],
    explanation: "「予」讀短音「よ」、「定」讀長音「てい」，故「予定」＝よてい。「ようてい」把「予（よ）」誤讀成長音「よう」；「よてえ」把長音「てい」誤寫成「てえ」；「よでい」把「定（てい）」誤濁成「でい」。唯「よてい」正確。",
    exampleJapanese: "来月の旅行の予定はもう決まりました。",
    exampleMeaningZh: "下個月旅行的行程已經定下來了。"
  }),
  examQuestion({
    id: "n4-grammar-tara-jouken",
    level: "N4",
    surface: "〜たら（条件）",
    reading: "たら",
    meaningZh: "如果…的話、…之後",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "もし 明日 雨 ___ 、運動会は 来週に なります。",
    promptContextZh: "如果明天下雨的話，運動會就改到下週。",
    hintZh: "句首「もし」提示這是對明天天氣的一種假設。",
    expectedAnswer: "だったら",
    options: ["だったら", "なのに", "でも", "だから"],
    explanation: "句首「もし」提示假設條件，名詞「雨」後接「だったら」構成「如果是雨（下雨）的話」，與後句「就改到下週」的假設結果相呼應。「なのに」是逆接「明明…卻…」，與『尚未發生的假設』及「もし」矛盾；「でも」此處接名詞會變「雨でも」（即使下雨也…），但後句是改期而非照辦，語意不合；「だから」是「因為是雨所以…」的既成因果，與「もし」的假設語氣衝突。唯與「もし」呼應的假設條件「だったら」成立。"
  }),
  examQuestion({
    id: "n4-grammar-nakutemoii-isogu",
    level: "N4",
    surface: "〜なくてもいい",
    reading: "なくてもいい",
    meaningZh: "不必…、不…也可以",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "まだ 時間が ある から、そんなに 急が ___ よ。",
    promptContextZh: "還有時間，所以不必那麼急喔。",
    hintZh: "因為時間還夠，讓對方寬心、不用趕的說法。",
    expectedAnswer: "なくてもいい",
    options: ["なくてもいい", "なければならない", "てはいけない", "たほうがいい"],
    explanation: "「Vなくてもいい」表示「不必…、不做也沒關係」，本句「還有時間，不必那麼急」。「なければならない」是「必須…」（與不必相反）；「てはいけない」是「不可以…」（禁止語氣，「急いてはいけない」語意也不合）；「たほうがいい」是「最好…（做）」（建議去做，與不必矛盾）。表不必要唯「なくてもいい」成立。"
  }),
  examQuestion({
    id: "n4-grammar-kunaru-samui",
    level: "N4",
    surface: "〜くなる（形容詞變化）",
    reading: "くなる",
    meaningZh: "變得…（形容詞的變化）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "秋に なると、だんだん ___ なって きます。",
    promptContextZh: "一到秋天，天氣就漸漸變冷起來。",
    hintZh: "隨著季節推移，氣溫往低處的轉變。",
    expectedAnswer: "寒く",
    options: ["寒く", "寒い", "寒に", "寒くて"],
    explanation: "い形容詞表示變化時要去「い」改「く」再接「なる」，故「寒い→寒くなる」（變冷）。「寒い」是辭書形，不能直接接「なる」；「寒に」是把い形容詞誤當な形容詞／名詞接「に」，接續錯誤；「寒くて」是て形表並列或原因，「寒くてなる」不成句。配合「だんだん…なってきます」的漸變，唯「寒く」成立。"
  }),
  examQuestion({
    id: "n4-grammar-teshimau-saifu",
    level: "N4",
    surface: "〜てしまう",
    reading: "てしまう",
    meaningZh: "（不小心）…了、完成（含遺憾）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "電車の 中に 財布を ___ 、本当に 困って います。",
    promptContextZh: "把錢包忘在電車裡了，真的很傷腦筋。",
    hintZh: "後句「真的很傷腦筋」透露出對這件事的懊惱。",
    expectedAnswer: "忘れてしまって",
    options: ["忘れてしまって", "忘れておいて", "忘れてあって", "忘れてみて"],
    explanation: "「Vてしまう」可表示「不小心做了而感到遺憾」，本句忘記錢包又「真的很傷腦筋」，正是這種懊惱語氣，故用「忘れてしまって」。「忘れておいて」是「事先忘好」，但「ておく」表為將來的準備，忘東西不可能是有意的準備，語意矛盾；「忘れてあって」的「てある」表人為造成的留存狀態（且須他動詞配出現），「忘れてある」不自然；「忘れてみて」是「試著忘」，刻意嘗試遺忘不合常理。表非故意又懊惱唯「忘れてしまって」成立。"
  }),
  examQuestion({
    id: "n4-grammar-teoku-ryokou",
    level: "N4",
    surface: "〜ておく",
    reading: "ておく",
    meaningZh: "事先做好（為將來準備）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "旅行の 前に、ガイドブックを 読んで 行く 店を 決めて ___ つもりです。",
    promptContextZh: "打算在旅行前先把要去的店決定好。",
    hintZh: "為了之後的旅行，現在先把事情安排妥當。",
    expectedAnswer: "おく",
    options: ["おく", "しまう", "みる", "ある"],
    explanation: "「Vておくつもりだ」表示「打算事先做好準備」，本句「打算旅行前先決定好要去的店」正是事前準備，故「決めておくつもりです」。「しまう」（てしまう）表完成或遺憾，與『有計畫地準備』不合；「みる」（てみる）是「試試看」，句意是把事情敲定而非嘗試；「ある」（てある）是表狀態留存的「てある」，但「てあるつもり」接續不通（つもり 接意志動作、てある 是狀態）。表為將來準備的打算唯「おく」成立。"
  }),
  examQuestion({
    id: "n4-grammar-temiru-ryouri",
    level: "N4",
    surface: "〜てみる",
    reading: "てみる",
    meaningZh: "試試看…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "新しい 料理の 作り方を 習ったので、今夜 家で 作って ___ つもりです。",
    promptContextZh: "學了新菜的做法，所以打算今晚在家試做看看。",
    hintZh: "剛學會做法，想實際動手嘗試一次。",
    expectedAnswer: "みる",
    options: ["みる", "おく", "しまう", "ある"],
    explanation: "「Vてみる」表示「試著做做看」，本句剛學會做法、想實際嘗試，故「作ってみる」。「おく」（ておく）是「事先做好準備」，但句中是想體驗成果而非為日後準備；「しまう」（てしまう）表完成或遺憾，與『躍躍欲試』的語氣不合；「ある」（てある）表狀態留存且要接動作結果，「作ってあるつもり」接續與語意皆不通。表嘗試唯「みる」成立。"
  }),
  examQuestion({
    id: "n4-grammar-tekureru-haha",
    level: "N4",
    surface: "〜てくれる（授受）",
    reading: "てくれる",
    meaningZh: "（別人）為我做…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "私が 病気の とき、母が おいしい おかゆを 作って ___ 。",
    promptContextZh: "我生病的時候，媽媽為我煮了好吃的粥。",
    hintZh: "生病時，母親主動為「我」做的事所帶來的心意。",
    expectedAnswer: "くれました",
    options: ["くれました", "あげました", "もらいました", "おきました"],
    explanation: "授受表現中，「他人為我（或我方）做某事」用「Vてくれる」，本句是『母親為我煮粥』，受益者是我，故「作ってくれました」。「あげました」（てあげる）是「我為別人做」，方向相反（變成我為媽媽煮）；「もらいました」（てもらう）雖也表受益，但句中主語是「母が」（が表動作者），須搭配「くれる」；若用「もらう」主語應是受益的我並以「に」標示母親，與「母が」不合；「おきました」（ておく）是「事先做好」，無『施惠於我』之意。表他人施惠且主語為施予者唯「くれました」成立。"
  }),
  examQuestion({
    id: "n4-grammar-ukemi-densha",
    level: "N4",
    surface: "受身（られる）",
    reading: "られる",
    meaningZh: "被…（被動）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "込んで いる 電車の 中で、誰かに 足を ___ 、とても 痛かった。",
    promptContextZh: "在擁擠的電車裡，被某人踩到腳，非常痛。",
    hintZh: "在人擠人的車廂裡，腳遭遇到的不愉快事情。",
    expectedAnswer: "踏まれて",
    options: ["踏まれて", "踏んで", "踏ませて", "踏めて"],
    explanation: "句中「誰かに足を〜」是受害者視角，他人對我的腳做了動作而我受影響，要用被動「踏まれて」（被踩），與後句「非常痛」呼應。「踏んで」是主動「（我）踩」，與「誰かに」的施動者及『我受害』矛盾；「踏ませて」是使役「讓（某人）踩」，我不會主動讓人踩自己；「踏めて」是可能形「能踩」，與『被踩到很痛』語意不合。表受害被動唯「踏まれて」成立。"
  }),
  examQuestion({
    id: "n4-grammar-kamoshirenai-sora",
    level: "N4",
    surface: "〜かもしれない",
    reading: "かもしれない",
    meaningZh: "也許…、可能…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "空が 暗く なって きた。午後から 雨が 降る ___ から、傘を 持って 行こう。",
    promptContextZh: "天空變暗了。下午也許會下雨，所以帶傘去吧。",
    hintZh: "看著變暗的天空，對下午天氣只是一種沒把握的猜測。",
    expectedAnswer: "かもしれない",
    options: ["かもしれない", "はずがない", "に違いない", "ことにする"],
    explanation: "看天色變暗只能『不確定地推測』可能下雨，用低可能性的推量「かもしれない」（也許），並以此為帶傘的理由。「はずがない」是「不可能…」的強烈否定推測，與『打算帶傘以防下雨』矛盾；「に違いない」是「一定是…」的高度肯定，僅憑天色變暗下此斷言過強，且與『沒把握』的語氣不合；「ことにする」是「決定…」表個人決定，天氣非人能決定。表不確定推測唯「かもしれない」成立。"
  }),
  examQuestion({
    id: "n4-vocab-todoku-nimotsu",
    level: "N4",
    surface: "届く",
    reading: "とどく",
    meaningZh: "送達、寄到",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "先週 注文した 本が、今朝 やっと 家に ___ 。",
    promptContextZh: "上週訂的書，今天早上終於寄到家了。",
    hintZh: "訂購的東西經過運送，最後抵達自己手邊。",
    expectedAnswer: "届きました",
    options: ["届きました", "集めました", "配りました", "送りました"],
    explanation: "「届く」是自動詞，指物品送達、寄到，本句「訂的書寄到家」即此，與「家に〜」（抵達某處）搭配成立。「集めました」是「收集」，及物且方向相反；「配りました」是「分發」，指把東西發給多人，非『寄到我家』；「送りました」是「寄出」，站在寄件方的角度，與『書終於到我這裡』的收件視角不符。表物品送達唯「届きました」成立。",
    exampleJapanese: "先週注文した本が、今朝やっと家に届きました。",
    exampleMeaningZh: "上週訂的書，今天早上終於寄到家了。"
  }),
  examQuestion({
    id: "n4-vocab-komu-densha",
    level: "N4",
    surface: "込む",
    reading: "こむ",
    meaningZh: "擁擠",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "朝の 電車は いつも ___ いて、座る ことが できません。",
    promptContextZh: "早上的電車總是很擠，沒辦法坐下。",
    hintZh: "上班時段車廂裡人多到不行的狀態。",
    expectedAnswer: "込んで",
    options: ["込んで", "並んで", "集まって", "余って"],
    explanation: "「込む」表示場所人多、擁擠，「電車が込んでいる」＝電車很擠，與後句「沒辦法坐下」呼應。「並んで」是「排隊／排列」，指依序站成一排，非『人多擁擠』；「集まって」是「聚集」，強調人們匯聚到一處的動作，不直接表達『滿到坐不下的擁擠狀態』；「余って」是「剩餘」，與『人很多』語意相反。表擁擠唯「込んで」成立。"
  }),
  examQuestion({
    id: "n4-vocab-modoru-wasuremono",
    level: "N4",
    surface: "戻る",
    reading: "もどる",
    meaningZh: "返回、回到",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "かさを 忘れた ことに 気づいて、急いで 教室に ___ 。",
    promptContextZh: "發現忘了帶傘，急忙回到教室。",
    hintZh: "察覺東西沒拿，往原本待過的地方折返。",
    expectedAnswer: "戻りました",
    options: ["戻りました", "通りました", "進みました", "渡りました"],
    explanation: "「戻る」指回到原來的地方，本句發現忘了傘而「回到（剛離開的）教室」即此。「通りました」是「經過、通過」，只是路過某處，非折返原地；「進みました」是「前進」，方向往前與『回去』相反；「渡りました」是「渡過、穿越（馬路等）」，語意不合。表返回原處唯「戻りました」成立。"
  }),
  examQuestion({
    id: "n4-vocab-tanoshimi-ryokou",
    level: "N4",
    surface: "楽しみ",
    reading: "たのしみ",
    meaningZh: "期待、樂趣",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "来月の 旅行が とても ___ で、毎日 ガイドブックを 見て います。",
    promptContextZh: "非常期待下個月的旅行，每天都在看旅遊書。",
    hintZh: "對還沒到來的旅行，心裡那份雀躍盼望的心情。",
    expectedAnswer: "楽しみ",
    options: ["楽しみ", "楽しい", "うれしい", "おもしろい"],
    explanation: "「楽しみ」指對『未來的事』感到期待、盼望，本句是『期待下個月的旅行』、每天看旅遊書，正是這種事前的期待，與「〜が楽しみだ」句型搭配成立。「楽しい」是「（正在進行中而感到）快樂」，多用於體驗當下，旅行還沒開始故不合；「うれしい」是「（因某事而）高興」，偏對已發生之事的喜悅；「おもしろい」是「有趣」，評價事物本身的趣味。表對未來的期待唯「楽しみ」成立。"
  }),
  examQuestion({
    id: "n4-vocab-choudo-jikan",
    level: "N4",
    surface: "ちょうど",
    reading: "ちょうど",
    meaningZh: "正好、恰好",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "駅に 着いた とき、___ 電車が 来た ので、待たずに 乗れた。",
    promptContextZh: "到車站的時候，電車正好來了，所以沒等就搭上了。",
    hintZh: "抵達的瞬間和電車進站的時間剛好對上。",
    expectedAnswer: "ちょうど",
    options: ["ちょうど", "ずっと", "やっと", "もっと"],
    explanation: "「ちょうど」表示「時間／數量剛好吻合」，本句『到站的瞬間電車正好來』、不用等就搭上，正是時間的恰好相合。「ずっと」是「一直、持續」表長時間，與『瞬間吻合』不合；「やっと」是「終於」，含等了很久的語感，但後句明說「沒等就搭上」，矛盾；「もっと」是「更…」表程度增加，語意不合。表時間剛好唯「ちょうど」成立。"
  }),
  examQuestion({
    id: "n4-kanji-ryokou",
    level: "N4",
    surface: "旅行",
    reading: "りょこう",
    meaningZh: "旅行",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "夏休みに 家族で 沖縄へ「旅行」に 行きます。",
    promptContextZh: "暑假要和家人去沖繩旅行。",
    expectedAnswer: "りょこう",
    options: ["りょこう", "りょうこう", "りょこ", "りこう"],
    explanation: "「旅」讀拗音「りょ」（一拍）、「行」讀長音「こう」，故「旅行」＝りょこう。「りょうこう」把「旅（りょ）」誤讀成長音「りょう」；「りょこ」漏掉「行」的長音尾「う」（少一拍）；「りこう」把拗音「りょ」誤讀成直音「り」（近「利口」）。唯「りょこう」正確。",
    exampleJapanese: "夏休みに家族で沖縄へ旅行に行きます。",
    exampleMeaningZh: "暑假要和家人去沖繩旅行。"
  }),
  examQuestion({
    id: "n4-kanji-undou",
    level: "N4",
    surface: "運動",
    reading: "うんどう",
    meaningZh: "運動",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "健康の ために、毎朝 公園で 軽い「運動」を して います。",
    promptContextZh: "為了健康，每天早上在公園做點輕度運動。",
    expectedAnswer: "うんどう",
    options: ["うんどう", "うんとう", "うんど", "うどう"],
    explanation: "「運」讀「うん」、「動」濁化讀長音「どう」，故「運動」＝うんどう。「うんとう」沒把「動」讀濁音（清音「とう」）；「うんど」漏掉「動」的長音尾「う」（少一拍）；「うどう」漏掉「運（うん）」的撥音「ん」。唯「うんどう」正確。",
    exampleJapanese: "健康のために、毎朝公園で軽い運動をしています。",
    exampleMeaningZh: "為了健康，每天早上在公園做點輕度運動。"
  }),
  examQuestion({
    id: "n4-kanji-aji",
    level: "N4",
    surface: "味",
    reading: "あじ",
    meaningZh: "味道",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この スープは すこし うすいので、もう 少し「味」を つけましょう。",
    promptContextZh: "這道湯有點淡，再多調點味道吧。",
    expectedAnswer: "あじ",
    options: ["あじ", "あぢ", "み", "あい"],
    explanation: "「味」單獨作名詞用訓讀「あじ」，本句指食物的味道。「あぢ」是把「じ」誤寫成現代假名遣已不用的「ぢ」；「み」是「味」的音讀，多用於「意味（いみ）／興味（きょうみ）」等詞，單獨指食物滋味要用訓讀「あじ」；「あい」與「味」的讀音無關。指食物味道唯「あじ」正確。",
    exampleJapanese: "このスープはすこしうすいので、もう少し味をつけましょう。",
    exampleMeaningZh: "這道湯有點淡，再多調點味道吧。"
  }),
  examQuestion({
    id: "n4-kanji-kazoku",
    level: "N4",
    surface: "家族",
    reading: "かぞく",
    meaningZh: "家人、家庭",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "日曜日は「家族」と いっしょに 公園で お弁当を 食べました。",
    promptContextZh: "星期天和家人一起在公園吃便當。",
    expectedAnswer: "かぞく",
    options: ["かぞく", "かそく", "けぞく", "かずく"],
    explanation: "「家」讀「か」、「族」濁化讀「ぞく」，故「家族」＝かぞく。「かそく」沒把「族」讀濁音（清音「そく」，近「加速」）；「けぞく」把「家（か）」誤讀成「け」；「かずく」把「ぞ」誤讀成「ず」。唯「かぞく」正確。",
    exampleJapanese: "日曜日は家族といっしょに公園でお弁当を食べました。",
    exampleMeaningZh: "星期天和家人一起在公園吃便當。"
  }),
  examQuestion({
    id: "n4-syn-yatto",
    level: "N4",
    surface: "やっと",
    reading: "やっと",
    meaningZh: "終於、好不容易才",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "三十分も歩いて、「やっと」駅に着いた。",
    promptContextZh: "走了三十分鐘，終於到了車站。",
    hintZh: "經過一番等待或努力之後，事情總算實現了。",
    expectedAnswer: "ようやく",
    options: ["ようやく", "すぐに", "もうすぐ", "ときどき"],
    explanation: "「やっと」表示經過時間或辛苦之後總算達成，≒「ようやく」。「すぐに」是「馬上」（沒有過程）；「もうすぐ」是「快要」（事情還沒發生）；「ときどき」是「有時」（頻率）。唯「ようやく」與「やっと」同表歷經辛苦後終於達成。",
    exampleJapanese: "三十分も歩いて、ようやく駅に着いた。",
    exampleMeaningZh: "走了三十分鐘，終於到了車站。"
  }),
  examQuestion({
    id: "n4-syn-tabun",
    level: "N4",
    surface: "たぶん",
    reading: "たぶん",
    meaningZh: "大概、可能",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "彼は「たぶん」もう家に帰ったでしょう。",
    promptContextZh: "他大概已經回家了吧。",
    hintZh: "說話者沒有十足把握，只是做出推測。",
    expectedAnswer: "おそらく",
    options: ["おそらく", "ぜったいに", "やっぱり", "もちろん"],
    explanation: "「たぶん」表示把握度中等的推測「大概」，≒「おそらく」。「ぜったいに」是「絕對」（100% 肯定）；「やっぱり」是「果然」（事後印證）；「もちろん」是「當然」（理所當然、無疑問）。唯「おそらく」與「たぶん」同為不確定的推測語氣。",
    exampleJapanese: "彼はおそらくもう家に帰ったでしょう。",
    exampleMeaningZh: "他大概已經回家了吧。"
  }),
  examQuestion({
    id: "n4-syn-yuumei",
    level: "N4",
    surface: "有名",
    reading: "ゆうめい",
    meaningZh: "有名、知名",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "この町は古いお寺で「有名」です。",
    promptContextZh: "這個城鎮以古老的寺廟聞名。",
    hintZh: "這個地方廣為人知，很多人都認識。",
    expectedAnswer: "よく知られている",
    options: ["よく知られている", "新しくできた", "とても静かな", "少し珍しい"],
    explanation: "「有名」表示廣為人知，≒「よく知られている」。「新しくできた」是「新建成的」（描述新舊）；「とても静かな」是「很安靜的」（描述氛圍）；「少し珍しい」是「有點稀奇的」（描述稀有度）。三者都不等於「為人所知」，唯「よく知られている」與「有名」同義。",
    exampleJapanese: "この町は古いお寺でよく知られています。",
    exampleMeaningZh: "這個城鎮以古老的寺廟聞名。"
  }),
  examQuestion({
    id: "n4-syn-hajimeni",
    level: "N4",
    surface: "はじめに",
    reading: "はじめに",
    meaningZh: "起初、一開始",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "りょうりを作るとき、「はじめに」野菜を洗います。",
    promptContextZh: "做菜的時候，一開始先洗菜。",
    hintZh: "事情剛開頭的那個階段，還沒進入後面。",
    expectedAnswer: "さいしょに",
    options: ["さいしょに", "さいごに", "すぐに", "たまに"],
    explanation: "「はじめに」表示順序上的「最先、一開始」，≒「さいしょに」。「さいごに」是「最後」（順序相反）；「すぐに」是「馬上」（強調沒有間隔的時間，不是順序的開頭）；「たまに」是「偶爾」（頻率）。唯「さいしょに」與「はじめに」同表順序的開頭。",
    exampleJapanese: "りょうりを作るとき、さいしょに野菜を洗います。",
    exampleMeaningZh: "做菜的時候，一開始先洗菜。"
  }),
  examQuestion({
    id: "n4-usage-naoru",
    level: "N4",
    surface: "治る",
    reading: "なおる",
    meaningZh: "（病、傷）痊癒、好轉",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「治る」の使い方が最も適切なものはどれか。",
    promptContextZh: "「治る」是生病或受傷恢復健康。",
    hintZh: "身體不舒服的狀況恢復到健康的樣子。",
    expectedAnswer: "薬を飲んで休んだら、風邪がすっかり治った。",
    options: ["薬を飲んで休んだら、風邪がすっかり治った。", "こわれた時計を、店の人が治ってくれた。", "へやが暗いので、電気を治ってください。", "道が分からなくて、駅で人に治った。"],
    explanation: "「治る」是自動詞，指生病、受傷恢復健康，本句「吃藥休息後感冒痊癒」最自然。修理壞掉的東西用「直す」（直してくれた）；開電燈用「つける」；向人問路用「聞く／たずねる」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "薬を飲んで休んだら、風邪がすっかり治った。",
    exampleMeaningZh: "吃了藥休息之後，感冒就完全好了。"
  }),
  examQuestion({
    id: "n4-usage-sodateru",
    level: "N4",
    surface: "育てる",
    reading: "そだてる",
    meaningZh: "養育、培育",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「育てる」の使い方が最も適切なものはどれか。",
    promptContextZh: "「育てる」是花心力讓人或動植物成長。",
    hintZh: "花時間照顧讓對象慢慢長大。",
    expectedAnswer: "庭で野菜を育てるのが、父の楽しみだ。",
    options: ["庭で野菜を育てるのが、父の楽しみだ。", "古いビルを育てて、新しい店にした。", "週末は部屋を育ててから出かける。", "重いにもつを二階まで育ててもらった。"],
    explanation: "「育てる」指花心力使人或動植物成長，本句「在院子裡種菜是爸爸的樂趣」最自然。把舊大樓改建用「建て直す」；整理房間用「片付ける」；把行李搬上樓用「運ぶ」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "庭で野菜を育てるのが、父の楽しみだ。",
    exampleMeaningZh: "在院子裡種菜是爸爸的樂趣。"
  }),
  examQuestion({
    id: "n4-usage-kimeru",
    level: "N4",
    surface: "決める",
    reading: "きめる",
    meaningZh: "決定、定下",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「決める」の使い方が最も適切なものはどれか。",
    promptContextZh: "「決める」是做出選擇、把事情定下來。",
    hintZh: "在幾個可能之中挑出要採取的那一個。",
    expectedAnswer: "みんなで相談して、旅行に行く日を決めた。",
    options: ["みんなで相談して、旅行に行く日を決めた。", "へやが暗いので、電気を決めてください。", "駅前で友だちを決めて、いっしょに帰った。", "重いにもつを、一人で二階に決めた。"],
    explanation: "「決める」＝做出選擇、把事情定下來，本句「大家商量後決定旅行的日子」最自然。開電燈用「つける」；和朋友碰面用「会う」；把行李搬上樓用「運ぶ」。三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "みんなで相談して、旅行に行く日を決めた。",
    exampleMeaningZh: "大家商量後，決定了去旅行的日子。"
  }),
  examQuestion({
    id: "n4-usage-nigiyaka",
    level: "N4",
    surface: "にぎやか",
    reading: "にぎやか",
    meaningZh: "熱鬧、繁華",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「にぎやか」の使い方が最も適切なものはどれか。",
    promptContextZh: "「にぎやか」是人多、有活力而熱鬧。",
    hintZh: "人多又有聲音，氣氛很有活力的樣子。",
    expectedAnswer: "お祭りの夜、町はとてもにぎやかだった。",
    options: ["お祭りの夜、町はとてもにぎやかだった。", "このスープは少しにぎやかで、おいしくない。", "みせの前に車がにぎやかにとまっている。", "夜の図書館はにぎやかで、よく眠れる。"],
    explanation: "「にぎやか」形容人多、有活力而熱鬧，本句「祭典的夜晚，街上很熱鬧」最自然。形容湯的味道要用「味が濃い／薄い」；車子停著的狀態不會用「熱鬧」形容；圖書館應是「静か（安靜）」才好睡，「にぎやかでよく眠れる」自相矛盾。三句皆不通，唯第一句成立。",
    exampleJapanese: "お祭りの夜、町はとてもにぎやかだった。",
    exampleMeaningZh: "祭典的夜晚，街上非常熱鬧。"
  }),
  examQuestion({
    id: "n4-context-dakara",
    level: "N4",
    surface: "だから",
    reading: "だから",
    meaningZh: "所以、因此",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "今日は朝からとても暑かった。___、プールはたくさんの人でこんでいた。",
    promptContextZh: "今天從早上就很熱。所以游泳池擠滿了人。",
    hintZh: "前句說明了原因，後句帶出由此產生的結果。",
    expectedAnswer: "だから",
    options: ["だから", "しかし", "それとも", "ところで"],
    explanation: "前句「很熱」是原因，後句「泳池很多人」是結果，用表因果的「だから」（所以）。「しかし」是逆接「但是」（很熱與人多不是相反）；「それとも」是「或者」（選擇）；「ところで」是「對了」（轉換話題）。表因果唯「だから」成立。",
    exampleJapanese: "今日は朝からとても暑かった。だから、プールはたくさんの人でこんでいた。",
    exampleMeaningZh: "今天從早上就很熱。所以游泳池擠滿了人。"
  }),
  examQuestion({
    id: "n4-context-demo",
    level: "N4",
    surface: "でも",
    reading: "でも",
    meaningZh: "可是、不過",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "薬を飲んで早く寝た。___、次の朝も熱は下がらなかった。",
    promptContextZh: "吃了藥早早睡了。可是隔天早上燒還是沒退。",
    hintZh: "後句出現和前句預期相反的情況。",
    expectedAnswer: "でも",
    options: ["でも", "だから", "それで", "そして"],
    explanation: "前句「吃藥早睡」讓人期待會好轉，後句卻是「沒退燒」，前後相反，用逆接的「でも」（可是）。「だから」「それで」都是因果（會變成「所以沒退燒」，邏輯矛盾）；「そして」是並列「然後」，無法表達轉折。表逆接唯「でも」成立。",
    exampleJapanese: "薬を飲んで早く寝た。でも、次の朝も熱は下がらなかった。",
    exampleMeaningZh: "吃了藥早早睡了。可是隔天早上燒還是沒退。"
  }),
  examQuestion({
    id: "n4-context-sonoato",
    level: "N4",
    surface: "その後",
    reading: "そのあと",
    meaningZh: "之後、後來",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "私は十時に駅で友だちに会った。___、いっしょに映画を見に行った。",
    promptContextZh: "我十點在車站和朋友碰面。之後一起去看了電影。",
    hintZh: "用來把前後兩件事按時間先後連起來。",
    expectedAnswer: "その後",
    options: ["その後", "だから", "しかし", "それとも"],
    explanation: "前句「碰面」與後句「去看電影」是依時間先後發生的兩件事，用表時間順序的「その後」（之後）。「だから」是因果（「所以去看電影」不自然）；「しかし」是逆接（前後不相反）；「それとも」是選擇。表時間先後唯「その後」成立。",
    exampleJapanese: "私は十時に駅で友だちに会った。その後、いっしょに映画を見に行った。",
    exampleMeaningZh: "我十點在車站和朋友碰面。之後一起去看了電影。"
  }),
  examQuestion({
    id: "n4-context-mata",
    level: "N4",
    surface: "また",
    reading: "また",
    meaningZh: "另外、還有",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "この店の料理はとてもおいしい。___、ねだんも安い。",
    promptContextZh: "這家店的菜很好吃。另外價錢也便宜。",
    hintZh: "在前面內容之外，再補上一個同方向的項目。",
    expectedAnswer: "また",
    options: ["また", "でも", "だから", "それとも"],
    explanation: "前句「好吃」與後句「便宜」都是優點、同方向，後句再追加一項，用表並列追加的「また」（另外、還有）。「でも」是逆接（好吃與便宜不相反）；「だから」是因果（「所以便宜」不通）；「それとも」是選擇。表同方向追加唯「また」成立。",
    exampleJapanese: "この店の料理はとてもおいしい。また、ねだんも安い。",
    exampleMeaningZh: "這家店的菜很好吃。另外價錢也便宜。"
  })
];
