import type { PracticeQuestion } from "../../types";
import { examQuestion } from "../helpers";

export const n5Items: PracticeQuestion[] = [
  examQuestion({
    id: "n5-grammar-wo-pan",
    level: "N5",
    surface: "を",
    reading: "を",
    meaningZh: "受詞助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "毎朝、パン ___ 食べます。",
    promptContextZh: "每天早上吃麵包。",
    hintZh: "「吃麵包」中，麵包與動詞之間要用的助詞。",
    expectedAnswer: "を",
    options: ["を", "が", "に", "へ"],
    explanation: "他動詞「食べる」的受詞用「を」標記，「パンを食べます」＝吃麵包。「が」標主語、「に」標對象/時間地點、「へ」標方向，都不能標受詞。唯「を」成立。"
  }),
  examQuestion({
    id: "n5-grammar-de-toshokan",
    level: "N5",
    surface: "で",
    reading: "で",
    meaningZh: "動作場所助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "図書館 ___ 本を読みます。",
    promptContextZh: "在圖書館讀書。",
    hintZh: "「讀書」這個動作發生的場所要用的助詞。",
    expectedAnswer: "で",
    options: ["で", "に", "を", "へ"],
    explanation: "動作發生的場所用「で」，「図書館で読みます」＝在圖書館讀。「に」表存在或到達點（如いる/行く）；「を」標受詞；「へ」標方向。表動作場所唯「で」成立。"
  }),
  examQuestion({
    id: "n5-grammar-tekudasai-iu",
    level: "N5",
    surface: "てください",
    reading: "てください",
    meaningZh: "請（做）…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "すみません、もう一度言っ ___ 。",
    promptContextZh: "不好意思，請再說一次。",
    hintZh: "客氣地請對方再做一次的說法。",
    expectedAnswer: "てください",
    options: ["てください", "てから", "ています", "ました"],
    explanation: "「Vてください」表示客氣的請求，「もう一度言ってください」＝請再說一次。「てから」是「做完…之後」；「ています」是「正在…」；「ました」是過去。配合「すみません、もう一度…」的請求語境，唯「てください」成立。"
  }),
  examQuestion({
    id: "n5-grammar-teimasu-shinbun",
    level: "N5",
    surface: "ています",
    reading: "ています",
    meaningZh: "正在（做）…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "今、父は新聞を読ん ___ 。",
    promptContextZh: "現在爸爸正在看報紙。",
    hintZh: "句首的『今』提示動作此刻發生中。",
    expectedAnswer: "でいます",
    options: ["でいます", "でから", "でも", "でした"],
    explanation: "「Vている」表示正在進行，「今…読んでいます」＝現在正在讀。「でから」是「讀完之後」；「でも」是「即使讀」；「でした」非自然接續。配合句首「今」，唯「でいます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-nomimasu-mizu",
    level: "N5",
    surface: "飲む",
    reading: "のむ",
    meaningZh: "喝",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "のどが かわいたので、水を ___ 。",
    promptContextZh: "因為口渴，所以喝水。",
    hintZh: "口渴時對水做的動作。",
    expectedAnswer: "飲みます",
    options: ["飲みます", "食べます", "聞きます", "見ます"],
    explanation: "「水を飲みます」＝喝水。「食べます」是吃（固體）；「聞きます」是聽/問；「見ます」是看。與「のどがかわいた（口渴）…水を」搭配，唯「飲みます」成立。"
  }),
  examQuestion({
    id: "n5-kanji-gakkou",
    level: "N5",
    surface: "学校",
    reading: "がっこう",
    meaningZh: "學校",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "毎日、自転車で「学校」へ行きます。",
    promptContextZh: "每天騎腳踏車去學校。",
    expectedAnswer: "がっこう",
    options: ["がっこう", "がくこう", "がっこ", "かっこう"],
    explanation: "「学」在「校（こう）」前促音化讀「がっ」、「校」讀長音「こう」，故「学校」＝がっこう。「がくこう」沒促音化；「がっこ」漏掉長音；「かっこう」沒把「学」讀濁音「がっ」（且 かっこう＝格好）。",
    exampleJapanese: "毎日、自転車で学校へ行きます。",
    exampleMeaningZh: "每天騎腳踏車去學校。"
  }),
  examQuestion({
    id: "n5-grammar-ha-watashi-gakusei",
    level: "N5",
    surface: "は",
    reading: "は",
    meaningZh: "主題助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "わたし ___ 学生です。",
    promptContextZh: "我是學生。",
    hintZh: "句首點出「自己」這個談論對象時，後面接的那個字。",
    expectedAnswer: "は",
    options: ["は", "を", "で", "へ"],
    explanation: "「Ａは Ｂです」用「は」提示主題，「わたしは学生です」＝我是學生。「を」是受詞助詞、句中沒有動作對象；「で」是場所/手段、此處非場所；「へ」是方向、句中沒有移動。判斷句的主題唯「は」成立。"
  }),
  examQuestion({
    id: "n5-grammar-ga-neko-iru",
    level: "N5",
    surface: "が",
    reading: "が",
    meaningZh: "主格助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あそこに ねこ ___ います。",
    promptContextZh: "那裡有貓。",
    hintZh: "描述某處存在某個動物時，緊接在那個動物後面的字。",
    expectedAnswer: "が",
    options: ["が", "を", "へ", "と"],
    explanation: "存在句「Ｎがいます／あります」用「が」標示存在的主體，「ねこがいます」＝有貓。「を」需要他動詞作受詞、「います」是自動詞不接受詞；「へ」是方向；「と」是「和」。存在句的主體唯「が」成立。"
  }),
  examQuestion({
    id: "n5-grammar-ni-shichiji-okiru",
    level: "N5",
    surface: "に",
    reading: "に",
    meaningZh: "時間點助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "まいあさ 七時 ___ おきます。",
    promptContextZh: "每天早上七點起床。",
    hintZh: "具體鐘點與動作之間，接在鐘點後面的那個字。",
    expectedAnswer: "に",
    options: ["に", "を", "で", "へ"],
    explanation: "具體時刻＋「に」表示動作發生的時間點，「七時に起きます」＝七點起床。「を」是受詞、時刻不是受詞；「で」標示場所或範圍、非時間點；「へ」是方向。鐘點時刻唯「に」成立。"
  }),
  examQuestion({
    id: "n5-grammar-e-kyouto-iku",
    level: "N5",
    surface: "へ",
    reading: "へ",
    meaningZh: "方向助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あした 京都 ___ 行きます。",
    promptContextZh: "明天要去京都。",
    hintZh: "標示「行きます」這個移動所朝向的地點。",
    expectedAnswer: "へ",
    options: ["へ", "を", "が", "は"],
    explanation: "移動動詞「行きます」前用「へ」表示前往的方向，「京都へ行きます」＝去京都。「を」是受詞、地點不是受詞；「が」是主格、京都非主體；「は」是主題、此處要的是方向。移動目的地唯「へ」（或に）成立，選項中只有「へ」。"
  }),
  examQuestion({
    id: "n5-grammar-to-tomodachi-au",
    level: "N5",
    surface: "と",
    reading: "と",
    meaningZh: "共事對象助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "日曜日に ともだち ___ 会います。",
    promptContextZh: "星期天和朋友見面。",
    hintZh: "標示一起進行「見面」這個互動的另一方。",
    expectedAnswer: "と",
    options: ["と", "を", "で", "へ"],
    explanation: "「Ｎと会います」用「と」標示一起見面的對象，「ともだちと会います」＝和朋友見面。「を」是受詞、「会う」在此用「と」不用「を」；「で」是場所；「へ」是方向。互動對象唯「と」成立。"
  }),
  examQuestion({
    id: "n5-grammar-mo-watashi-iku",
    level: "N5",
    surface: "も",
    reading: "も",
    meaningZh: "「也」助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "田中さんは 行きます。わたし ___ 行きます。",
    promptContextZh: "田中先生要去。我也要去。",
    hintZh: "前句已有人要去，後句表達自己同樣如此時接在主語後的字。",
    expectedAnswer: "も",
    options: ["も", "を", "に", "へ"],
    explanation: "前句「田中さんは行きます」已成立，後句用「も」表示「我也一樣」，「わたしも行きます」＝我也去。「を」是受詞；「に」「へ」是時間/方向，都無法表達『同樣、也』。追加同類唯「も」成立。"
  }),
  examQuestion({
    id: "n5-grammar-tai-mizu-nomu",
    level: "N5",
    surface: "たい",
    reading: "たい",
    meaningZh: "想要（做）…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "のどが かわきました。つめたい お茶が 飲み ___ です。",
    promptContextZh: "口渴了。想喝冰涼的茶。",
    hintZh: "口渴時表達自己內心願望的說法。",
    expectedAnswer: "たい",
    options: ["たい", "ました", "ています", "ません"],
    explanation: "「Ｖます形＋たい」表示說話者的願望，「飲みたいです」＝想喝。「ました」是過去、與『現在想要』矛盾；「ています」是正在進行；「ません」是否定、與想喝相反。表達願望唯「たい」成立。"
  }),
  examQuestion({
    id: "n5-grammar-masenka-eiga-miru",
    level: "N5",
    surface: "ませんか",
    reading: "ませんか",
    meaningZh: "要不要一起…（邀約）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "土曜日、いっしょに えいがを 見 ___ 。",
    promptContextZh: "星期六，要不要一起看電影？",
    hintZh: "句中的「いっしょに」提示正在向對方提出邀請的句尾說法。",
    expectedAnswer: "ませんか",
    options: ["ませんか", "ました", "たいです", "ています"],
    explanation: "「Ｖませんか」是邀請對方一起做某事的句型，搭配「いっしょに」很自然，「見ませんか」＝要不要看。「ました」是過去陳述；「たいです」是說自己想看、不是邀約；「ています」是正在進行。邀約唯「ませんか」成立。"
  }),
  examQuestion({
    id: "n5-vocab-iku-kaisha",
    level: "N5",
    surface: "行く",
    reading: "いく",
    meaningZh: "去",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あした、でんしゃで 会社へ ___ 。",
    promptContextZh: "明天搭電車去公司。",
    hintZh: "朝著公司這個目的地移動的動作。",
    expectedAnswer: "行きます",
    options: ["行きます", "来ます", "あります", "います"],
    explanation: "「Ｎへ行きます」表示前往某地，「会社へ行きます」＝去公司。「来ます」是『來』、方向相反；「あります」是無生命物的存在；「います」是有生命物的存在。朝目的地前往唯「行きます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-kuru-tomodachi-ie",
    level: "N5",
    surface: "来る",
    reading: "くる",
    meaningZh: "來",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あした、ともだちが わたしの 家へ ___ 。",
    promptContextZh: "明天朋友會來我家。",
    hintZh: "對方朝著「我家」這邊移動過來的動作。",
    expectedAnswer: "来ます",
    options: ["来ます", "行きます", "食べます", "見ます"],
    explanation: "朋友朝著「わたしの家」這邊移動，用「来ます」＝來。「行きます」是離開說話者方向的『去』、與『來我家』矛盾；「食べます」是吃；「見ます」是看。朝說話者方向移動唯「来ます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-miru-terebi",
    level: "N5",
    surface: "見る",
    reading: "みる",
    meaningZh: "看",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "毎晩、うちで テレビを ___ 。",
    promptContextZh: "每天晚上在家看電視。",
    hintZh: "用眼睛接收電視畫面的動作。",
    expectedAnswer: "見ます",
    options: ["見ます", "聞きます", "話します", "行きます"],
    explanation: "電視以畫面為主，用眼睛接收，搭配「見ます」＝看。「聞きます」是用耳朵『聽』、對象是聲音；「話します」是說；「行きます」是去。看電視唯「見ます」最自然。"
  }),
  examQuestion({
    id: "n5-vocab-ookii-kaban",
    level: "N5",
    surface: "大きい",
    reading: "おおきい",
    meaningZh: "大的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この かばんは たくさん 入るので、とても ___ です。",
    promptContextZh: "這個包包能裝很多東西，所以非常大。",
    hintZh: "因為能裝很多東西，所以對它尺寸的形容。",
    expectedAnswer: "大きい",
    options: ["大きい", "小さい", "新しい", "高い"],
    explanation: "「たくさん入る（裝得多）」對應尺寸大，用「大きい」＝大的。「小さい」是小、與裝得多矛盾；「新しい」是新舊、與容量無關；「高い」是貴/高、與裝得多無關。形容容量大唯「大きい」成立。"
  }),
  examQuestion({
    id: "n5-vocab-jikan-nai",
    level: "N5",
    surface: "時間",
    reading: "じかん",
    meaningZh: "時間",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "いそがしくて、昼ごはんを 食べる ___ が ありません。",
    promptContextZh: "太忙了，沒有吃午餐的空檔。",
    hintZh: "因為忙碌而抽不出來、用來做某事的那段空檔。",
    expectedAnswer: "時間",
    options: ["時間", "お金", "ところ", "ことば"],
    explanation: "「忙碌到沒有做某事的～」指的是時段，用「時間」＝時間，「食べる時間がありません」＝沒有吃的時間。「お金」是錢、與忙碌無關；「ところ」是地點；「ことば」是話語。表抽不出的時段唯「時間」成立。"
  }),
  examQuestion({
    id: "n5-kanji-sensei",
    level: "N5",
    surface: "先生",
    reading: "せんせい",
    meaningZh: "老師",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "山田「先生」は とても やさしいです。",
    promptContextZh: "山田老師非常親切。",
    expectedAnswer: "せんせい",
    options: ["せんせい", "せんせ", "ぜんせい", "せいせい"],
    explanation: "「先」讀「せん」、「生」在此讀長音「せい」，故「先生」＝せんせい。「せんせ」漏掉長音；「ぜんせい」把「先」誤濁音化成「ぜん」；「せいせい」把「先」誤讀成「せい」。",
    exampleJapanese: "山田先生は とても やさしいです。",
    exampleMeaningZh: "山田老師非常親切。"
  }),
  examQuestion({
    id: "n5-kanji-mainichi",
    level: "N5",
    surface: "毎日",
    reading: "まいにち",
    meaningZh: "每天",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "わたしは「毎日」コーヒーを のみます。",
    promptContextZh: "我每天喝咖啡。",
    expectedAnswer: "まいにち",
    options: ["まいにち", "めいにち", "まいひ", "まいにつ"],
    explanation: "「毎」讀「まい」、「日」在此讀「にち」，故「毎日」＝まいにち。「めいにち」把「毎」誤讀成「めい」（那是「命日」的讀音）；「まいひ」把「日」讀成訓讀「ひ」；「まいにつ」把「にち」誤讀成促音「につ」。",
    exampleJapanese: "わたしは 毎日 コーヒーを のみます。",
    exampleMeaningZh: "我每天喝咖啡。"
  }),
  examQuestion({
    id: "n5-kanji-taberu",
    level: "N5",
    surface: "食べる",
    reading: "たべる",
    meaningZh: "吃",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あさ、くだものを「食べます」。",
    promptContextZh: "早上吃水果。",
    expectedAnswer: "たべます",
    options: ["たべます", "だべます", "たへます", "ためます"],
    explanation: "「食」訓讀「た」、送りがな「べます」，故「食べます」＝たべます。「だべます」把「た」誤濁音成「だ」；「たへます」沒把「べ」讀濁音；「ためます」把「べ」誤讀成「め」。",
    exampleJapanese: "あさ、くだものを 食べます。",
    exampleMeaningZh: "早上吃水果。"
  }),
  examQuestion({
    id: "n5-grammar-kara-atama-itai",
    level: "N5",
    surface: "から",
    reading: "から",
    meaningZh: "因為（原因）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あたまが いたい ___、きょうは 休みます。",
    promptContextZh: "因為頭痛，所以今天請假。",
    hintZh: "前半說明狀況、後半說明因此採取的行動，連接兩者的字。",
    expectedAnswer: "から",
    options: ["から", "まで", "より", "だけ"],
    explanation: "「ＡからＢ」用「から」表示原因理由，「あたまがいたいから休みます」＝因為頭痛所以請假。「まで」是「到…為止」（範圍終點）、此處非範圍；「より」是「比…」（比較基準）、句中無比較對象；「だけ」是「只…」（限定）、與因果無關。表原因唯「から」成立。"
  }),
  examQuestion({
    id: "n5-grammar-made-kuji-hataraku",
    level: "N5",
    surface: "まで",
    reading: "まで",
    meaningZh: "到…為止（範圍終點）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "けさは 八時から 九時 ___ はたらきました。",
    promptContextZh: "今天早上從八點工作到九點。",
    hintZh: "標示「工作」這個動作一直持續到的那個終點時刻。",
    expectedAnswer: "まで",
    options: ["まで", "から", "より", "だけ"],
    explanation: "「Ｎまで」表示動作持續到的終點。句中已有起點「八時から」，第二格填「まで」構成「八時から九時まで」＝從八點到九點。「から」是起點、句中起點已是八時、再填會重複矛盾；「より」是「比…」、句中無比較；「だけ」是「只…」、非範圍終點。表終點唯「まで」成立。"
  }),
  examQuestion({
    id: "n5-grammar-yori-densha-hayai",
    level: "N5",
    surface: "より",
    reading: "より",
    meaningZh: "比…（比較基準）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "でんしゃは バス ___ はやいです。",
    promptContextZh: "電車比公車快。",
    hintZh: "兩種交通工具相比時，標示被當作比較對象的那一方。",
    expectedAnswer: "より",
    options: ["より", "まで", "から", "だけ"],
    explanation: "「ＡはＢより〜」用「より」標示比較的基準，「バスよりはやい」＝比公車快。「まで」是「到…為止」（範圍）、此處非範圍；「から」是「從…」（起點）、句中非起點；「だけ」是「只…」（限定）、與比較無關。「はやいです」的比較對象唯「より」成立。"
  }),
  examQuestion({
    id: "n5-grammar-dake-mizu-nomu",
    level: "N5",
    surface: "だけ",
    reading: "だけ",
    meaningZh: "只…（限定）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あさは なにも 食べないで、お水 ___ 飲みます。",
    promptContextZh: "早上什麼都不吃，只喝水。",
    hintZh: "前半說「什麼都不吃」，後半把範圍縮到單一一項時用的字。",
    expectedAnswer: "だけ",
    options: ["だけ", "まで", "から", "より"],
    explanation: "「Ｎだけ」用「だけ」表示限定『只有…』，呼應前半「なにも食べないで」，「お水だけ飲みます」＝只喝水。「まで」是「到…為止」（範圍終點）；「から」是「從…」（起點）；「より」是「比…」（比較）。限定單一項目唯「だけ」成立。"
  }),
  examQuestion({
    id: "n5-grammar-nodesuka-naze-yasumu",
    level: "N5",
    surface: "のですか",
    reading: "のですか",
    meaningZh: "（詢問緣由）是…嗎？",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "かおいろが わるいですね。どこか いたい ___ 。",
    promptContextZh: "你臉色不好耶。是哪裡不舒服嗎？",
    hintZh: "看見對方臉色不好、想關心地追問緣由時的句尾說法。",
    expectedAnswer: "のですか",
    options: ["のですか", "ましょう", "ませんか", "でしょう"],
    explanation: "「い形容詞＋のですか」用來追問眼前情況的緣由，「いたいのですか」＝是哪裡不舒服嗎。「ましょう」是邀約/提議『一起…吧』、無法接い形容詞也非詢問；「ませんか」是邀約『要不要…』、語意不合；「でしょう」是推測『…吧』、不是針對眼前狀況的詢問。關心追問緣由唯「のですか」成立。"
  }),
  examQuestion({
    id: "n5-grammar-ne-tenki-ii",
    level: "N5",
    surface: "ね",
    reading: "ね",
    meaningZh: "…呢（尋求認同）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "きょうは いい てんきです ___ 。「ええ、そうですね。」",
    promptContextZh: "今天天氣真好呢。「嗯，是啊。」",
    hintZh: "後句對方回「是啊」，提示前句正向對方尋求同感的句尾語氣。",
    expectedAnswer: "ね",
    options: ["ね", "よ", "か", "の"],
    explanation: "終助詞「ね」向對方尋求同感、確認共識，後句「そうですね」正是附和，「いいてんきですね」＝天氣真好呢。「よ」是把新資訊告知對方（單向通知）、與徵求同感不同；「か」是疑問、但後句並非回答是非；「の」此處接「です」後不自然。尋求同感且對方附和，唯「ね」成立。"
  }),
  examQuestion({
    id: "n5-grammar-yo-densha-kuru",
    level: "N5",
    surface: "よ",
    reading: "よ",
    meaningZh: "…喔（告知對方）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "「電車が 来ました ___ 。はやく のりましょう。」",
    promptContextZh: "「電車來了喔。快點上車吧。」",
    hintZh: "把對方還沒注意到的事情、要他留意的句尾語氣。",
    expectedAnswer: "よ",
    options: ["よ", "ね", "か", "を"],
    explanation: "終助詞「よ」用來把對方還沒注意到的新資訊告知、提醒，呼應後句「はやくのりましょう」，「来ましたよ」＝電車來了喔。「ね」是尋求同感、但對方尚未察覺無從附和；「か」是疑問、此處是告知非提問；「を」是受詞助詞、不能放句尾。提醒告知唯「よ」成立。"
  }),
  examQuestion({
    id: "n5-grammar-mashou-issho-kaeru",
    level: "N5",
    surface: "ましょう",
    reading: "ましょう",
    meaningZh: "一起…吧（提議）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "もう おそいです。いっしょに 帰り ___ 。",
    promptContextZh: "已經很晚了。一起回去吧。",
    hintZh: "句中的「いっしょに」提示正在邀雙方一同行動的句尾說法。",
    expectedAnswer: "ましょう",
    options: ["ましょう", "ました", "ません", "たいです"],
    explanation: "「Ｖましょう」表示提議一起做某事，搭配「いっしょに」很自然，「帰りましょう」＝一起回去吧。「ました」是過去陳述；「ません」是否定；「たいです」是說自己想做、不是提議邀對方。提議共同行動唯「ましょう」成立。"
  }),
  examQuestion({
    id: "n5-grammar-tekara-te-arau-taberu",
    level: "N5",
    surface: "てから",
    reading: "てから",
    meaningZh: "做完…之後（再）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "うちに かえって 手を あらっ ___ 、ごはんを 食べます。",
    promptContextZh: "回家洗手，洗完之後再吃飯。",
    hintZh: "強調前一個動作結束後、緊接著才做下一個動作的接續說法。",
    expectedAnswer: "てから",
    options: ["てから", "ながら", "たり", "ないで"],
    explanation: "「Ｖてから」表示『做完前項之後再做後項』、有先後順序，「あらってから食べます」＝洗完手再吃。「ながら」是『一邊…一邊…』（同時並行）、洗手和吃不會同時；「たり」需「〜たり〜たり」並列形式、句中只有一個動作；「ないで」是『不做…就…』、與『洗完再吃』相反。表先後順序唯「てから」成立。"
  }),
  examQuestion({
    id: "n5-vocab-kaku-tegami",
    level: "N5",
    surface: "書く",
    reading: "かく",
    meaningZh: "寫",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "ペンで ノートに なまえを ___ 。",
    promptContextZh: "用筆在筆記本上寫名字。",
    hintZh: "拿著筆、把名字記在紙上的動作。",
    expectedAnswer: "書きます",
    options: ["書きます", "読みます", "話します", "聞きます"],
    explanation: "「ペンで…なまえを書きます」＝用筆寫名字，用筆記下文字用「書きます」。「読みます」是『讀』、是看文字不是寫；「話します」是『說』、是出聲不是寫；「聞きます」是『聽/問』。用筆記下文字唯「書きます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-okiru-rokuji",
    level: "N5",
    surface: "起きる",
    reading: "おきる",
    meaningZh: "起床",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "まいあさ 六時に ___、かおを あらいます。",
    promptContextZh: "每天早上六點起床，然後洗臉。",
    hintZh: "早上睡醒、離開被窩開始一天的動作。",
    expectedAnswer: "起きます",
    options: ["起きます", "ねます", "やすみます", "かえります"],
    explanation: "「六時に起きて、かおをあらいます」＝六點起床洗臉，早上睡醒離開被窩用「起きます」。「ねます」是『睡覺』、與早上開始活動相反；「やすみます」是『休息/請假』；「かえります」是『回去』。早上睡醒展開一天唯「起きます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-yasui-mise",
    level: "N5",
    surface: "安い",
    reading: "やすい",
    meaningZh: "便宜的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この みせの やさいは ___ ので、よく かいます。",
    promptContextZh: "這家店的蔬菜很便宜，所以我常買。",
    hintZh: "因為價錢不高、所以願意常去買，對價格的形容。",
    expectedAnswer: "安い",
    options: ["安い", "たかい", "おおい", "とおい"],
    explanation: "「安いので、よくかいます」＝因為便宜所以常買，價錢不高用「安い」。「たかい」是『貴』、貴的話通常不會『常買』、與文脈矛盾；「おおい」是『多』、形容數量不是價格；「とおい」是『遠』、形容距離。形容價格低唯「安い」成立。"
  }),
  examQuestion({
    id: "n5-vocab-atarashii-kaban",
    level: "N5",
    surface: "新しい",
    reading: "あたらしい",
    meaningZh: "新的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "きのう かばんを かいました。とても ___ かばんです。",
    promptContextZh: "昨天買了包包。是個很新的包包。",
    hintZh: "因為昨天才剛買來、還沒用過，對它的形容。",
    expectedAnswer: "新しい",
    options: ["新しい", "ふるい", "おもい", "ながい"],
    explanation: "「きのう かいました…新しいかばん」＝昨天剛買的新包包，剛買來沒用過用「新しい」。「ふるい」是『舊』、與昨天才買矛盾；「おもい」是『重』、形容重量；「ながい」是『長』、形容長度。剛買的全新物品唯「新しい」成立。"
  }),
  examQuestion({
    id: "n5-vocab-tenki-ame",
    level: "N5",
    surface: "天気",
    reading: "てんき",
    meaningZh: "天氣",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あしたの ___ は あめだと テレビで 言って いました。",
    promptContextZh: "電視上說明天的天氣是雨。",
    hintZh: "電視預報所講的、明天會晴或會雨的那種狀況。",
    expectedAnswer: "天気",
    options: ["天気", "げんき", "びょうき", "でんき"],
    explanation: "「あしたの天気はあめ」＝明天的天氣是雨，晴雨等大氣狀況用「天気」。「げんき」是『精神/健康』；「びょうき」是『生病』；「でんき」是『電/電燈』。雖讀音相近，但講晴雨狀況唯「天気」成立。"
  }),
  examQuestion({
    id: "n5-kanji-mizu",
    level: "N5",
    surface: "水",
    reading: "みず",
    meaningZh: "水",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あついので、つめたい「水」を のみます。",
    promptContextZh: "因為很熱，所以喝冰涼的水。",
    expectedAnswer: "みず",
    options: ["みず", "みす", "すい", "みづ"],
    explanation: "「水」單獨當名詞時用訓讀「みず」。「みす」漏掉濁音（ず→す）；「すい」是音讀（用於「水曜日」等複合詞）、單獨的『水』不這樣讀；「みづ」是歷史假名遣的舊寫法、現代標準寫作「みず」。此處單獨名詞唯「みず」成立。",
    exampleJapanese: "あついので、つめたい水を のみます。",
    exampleMeaningZh: "因為很熱，所以喝冰涼的水。"
  }),
  examQuestion({
    id: "n5-kanji-tomodachi",
    level: "N5",
    surface: "友達",
    reading: "ともだち",
    meaningZh: "朋友",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あした「友達」と こうえんで あそびます。",
    promptContextZh: "明天和朋友在公園玩。",
    expectedAnswer: "ともだち",
    options: ["ともだち", "ともたち", "ゆうだち", "とまだち"],
    explanation: "「友」訓讀「とも」、「達」在此讀濁音「だち」，故「友達」＝ともだち。「ともたち」沒把「達」讀濁音（たち→應為だち）；「ゆうだち」把「友」誤用音讀「ゆう」（且 ゆうだち＝夕立、午後雷陣雨）；「とまだち」把「とも」誤讀成「とま」。此處唯「ともだち」成立。",
    exampleJapanese: "あした友達と こうえんで あそびます。",
    exampleMeaningZh: "明天和朋友在公園玩。"
  }),
  examQuestion({
    id: "n5-kanji-yasumu",
    level: "N5",
    surface: "休む",
    reading: "やすむ",
    meaningZh: "休息、請假",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "かぜを ひいたので、きょうは かいしゃを「休みます」。",
    promptContextZh: "因為感冒了，今天向公司請假。",
    expectedAnswer: "やすみます",
    options: ["やすみます", "やしみます", "きゅうみます", "やすめます"],
    explanation: "「休」訓讀「やす」、送りがな「みます」，故「休みます」＝やすみます。「やしみます」把「やす」誤讀成「やし」；「きゅうみます」把「休」誤用音讀「きゅう」（用於「休日」等複合詞）；「やすめます」是可能形/別的活用、與辭書形「休む」的ます形不符。此處唯「やすみます」成立。",
    exampleJapanese: "かぜを ひいたので、きょうは かいしゃを 休みます。",
    exampleMeaningZh: "因為感冒了，今天向公司請假。"
  }),
  examQuestion({
    id: "n5-kanji-ame",
    level: "N5",
    surface: "雨",
    reading: "あめ",
    meaningZh: "雨",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "そとは「雨」なので、かさを もって いきます。",
    promptContextZh: "外面在下雨，所以帶傘出門。",
    expectedAnswer: "あめ",
    options: ["あめ", "あま", "う", "あね"],
    explanation: "「雨」單獨當名詞時用訓讀「あめ」。「あま」是複合詞時的讀法（如「雨水＝あまみず」）、單獨的『雨』不這樣讀；「う」是音讀（用於「雨天」等）、此處非複合詞；「あね」與「雨」無關（あね＝姉、姊姊）。此處單獨名詞唯「あめ」成立。",
    exampleJapanese: "そとは雨なので、かさを もって いきます。",
    exampleMeaningZh: "外面在下雨，所以帶傘出門。"
  }),
  examQuestion({
    id: "n5-syn-takusan",
    level: "N5",
    surface: "たくさん",
    reading: "たくさん",
    meaningZh: "很多",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "日曜日、こうえんに 子どもが 「たくさん」 いました。",
    promptContextZh: "星期天，公園裡有很多小孩。",
    hintZh: "數量上不算少，到了有許多的程度。",
    expectedAnswer: "いっぱい",
    options: ["いっぱい", "すこし", "ぜんぜん", "ときどき"],
    explanation: "「たくさん」表示數量多，本句「公園裡有很多小孩」用「いっぱい」（滿滿、很多）替換後語意相同。「すこし」是『一點點』（量少，相反）；「ぜんぜん」是『完全（不）』（用於否定）；「ときどき」是『有時』（頻率，不是數量）。表數量多唯「いっぱい」與「たくさん」同義。",
    exampleJapanese: "日曜日、こうえんに 子どもが いっぱい いました。",
    exampleMeaningZh: "星期天，公園裡有很多小孩。"
  }),
  examQuestion({
    id: "n5-syn-totemo",
    level: "N5",
    surface: "とても",
    reading: "とても",
    meaningZh: "非常",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "この 本は 「とても」 おもしろいです。",
    promptContextZh: "這本書非常有趣。",
    hintZh: "表示程度很高，不是普通的那種等級。",
    expectedAnswer: "たいへん",
    options: ["たいへん", "あまり", "すこし", "だんだん"],
    explanation: "「とても」修飾形容詞、表示程度很高，本句「這本書非常有趣」用副詞「たいへん」（非常）替換後語意相同。「あまり」是『不太』（用於否定，程度低）；「すこし」是『稍微』（程度低）；「だんだん」是『漸漸』（表變化，不是程度）。表程度高唯「たいへん」與「とても」同義。",
    exampleJapanese: "この 本は たいへん おもしろいです。",
    exampleMeaningZh: "這本書非常有趣。"
  }),
  examQuestion({
    id: "n5-syn-tokidoki",
    level: "N5",
    surface: "ときどき",
    reading: "ときどき",
    meaningZh: "有時、偶爾",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "わたしは 「ときどき」 きっさてんで コーヒーを 飲みます。",
    promptContextZh: "我有時會在咖啡店喝咖啡。",
    hintZh: "次數不多，要隔一段時間才會發生一次。",
    expectedAnswer: "たまに",
    options: ["たまに", "いつも", "すぐに", "だんだん"],
    explanation: "「ときどき」表示頻率不高的「有時」，本句用「たまに」（偶爾）替換後語意相同。「いつも」是『總是』（頻率最高，相反）；「すぐに」是『馬上』（表時間快，不是頻率）；「だんだん」是『漸漸』（表變化）。表頻率中低唯「たまに」與「ときどき」同義。",
    exampleJapanese: "わたしは たまに きっさてんで コーヒーを 飲みます。",
    exampleMeaningZh: "我有時會在咖啡店喝咖啡。"
  }),
  examQuestion({
    id: "n5-syn-kyonen",
    level: "N5",
    surface: "きょねん",
    reading: "きょねん",
    meaningZh: "去年",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "わたしは 「きょねん」 日本へ 行きました。",
    promptContextZh: "我去年去了日本。",
    hintZh: "指現在這一年的前一年。",
    expectedAnswer: "さくねん",
    options: ["さくねん", "らいねん", "ことし", "まいとし"],
    explanation: "「きょねん」與「さくねん」都指『去年』，是同義詞，替換後語意完全相同。「らいねん」是『明年』（還沒到，相反方向）；「ことし」是『今年』（現在這一年）；「まいとし」是『每年』（表頻率，不是特定一年）。指前一年唯「さくねん」與「きょねん」同義。",
    exampleJapanese: "わたしは さくねん 日本へ 行きました。",
    exampleMeaningZh: "我去年去了日本。"
  }),
  examQuestion({
    id: "n5-usage-arau",
    level: "N5",
    surface: "洗う",
    reading: "あらう",
    meaningZh: "洗",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「洗う」の使い方が最も適切なものはどれか。",
    promptContextZh: "「洗う」是用水把東西弄乾淨。",
    hintZh: "用水把髒的地方弄到乾淨。",
    expectedAnswer: "まいあさ おきてから、かおを 洗います。",
    options: ["まいあさ おきてから、かおを 洗います。", "こわれた とけいを、みせの 人が 洗いました。", "へやが くらいので、でんきを 洗って ください。", "えきで ともだちを 洗って、いっしょに 帰りました。"],
    explanation: "「洗う」是用水把東西弄乾淨，本句「每天早上起床後洗臉」最自然。修理壞掉的時鐘要用「直す」（直しました）；開電燈要用「つける」；和朋友碰面要用「会う」。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "まいあさ おきてから、かおを 洗います。",
    exampleMeaningZh: "每天早上起床後洗臉。"
  }),
  examQuestion({
    id: "n5-usage-samui",
    level: "N5",
    surface: "寒い",
    reading: "さむい",
    meaningZh: "（天氣）冷、寒冷",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「寒い」の使い方が最も適切なものはどれか。",
    promptContextZh: "「寒い」用來形容氣溫低、身體覺得冷。",
    hintZh: "氣溫低、身體覺得不暖和的狀態。",
    expectedAnswer: "ふゆは ゆきが ふって、とても 寒いです。",
    options: ["ふゆは ゆきが ふって、とても 寒いです。", "この 水は 寒いので、手が つめたく なりました。", "この もんだいは 寒くて、ぜんぜん わかりません。", "この スープは 寒いので、あたためて ください。"],
    explanation: "「寒い」用來形容氣溫低、身體覺得冷的環境，本句「冬天下雪，非常冷」最自然。摸到的水或湯要用「つめたい」（つめたい水／つめたいスープ）；題目難要用「難しい」，不會用「寒い」形容。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "ふゆは ゆきが ふって、とても 寒いです。",
    exampleMeaningZh: "冬天下雪，非常冷。"
  }),
  examQuestion({
    id: "n5-usage-oyogu",
    level: "N5",
    surface: "泳ぐ",
    reading: "およぐ",
    meaningZh: "游泳",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「泳ぐ」の使い方が最も適切なものはどれか。",
    promptContextZh: "「泳ぐ」是在水裡前進。",
    hintZh: "在水裡用手腳前進。",
    expectedAnswer: "なつに うみで 泳ぐのが すきです。",
    options: ["なつに うみで 泳ぐのが すきです。", "あさ、でんしゃで かいしゃまで 泳ぎます。", "おなかが すいたので、ごはんを 泳ぎます。", "よる、いえで テレビを 泳ぎます。"],
    explanation: "「泳ぐ」是在水裡前進，本句「喜歡夏天在海裡游泳」最自然。搭電車去公司要用「行く」；吃飯要用「食べる」；看電視要用「見る」。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "なつに うみで 泳ぐのが すきです。",
    exampleMeaningZh: "喜歡夏天在海裡游泳。"
  }),
  examQuestion({
    id: "n5-usage-kasu",
    level: "N5",
    surface: "貸す",
    reading: "かす",
    meaningZh: "借出、出借",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「貸す」の使い方が最も適切なものはどれか。",
    promptContextZh: "「貸す」是把自己的東西讓給別人用。",
    hintZh: "把自己的東西暫時讓別人使用。",
    expectedAnswer: "ペンを わすれた ともだちに、ペンを 貸しました。",
    options: ["ペンを わすれた ともだちに、ペンを 貸しました。", "私は 本が よみたくて、としょかんで 貸しました。", "やおやで やさいを たくさん 貸しました。", "おもい にもつを、二かいまで 貸しました。"],
    explanation: "「貸す」是把自己的東西讓給別人用（東西從自己流向對方），本句「把筆借給忘記帶筆的朋友」方向正確、最自然。在圖書館取得書是『借入』，要用「借りる」；在蔬果店取得蔬菜要用「買う」；把行李搬到二樓要用「運ぶ」。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "ペンを わすれた ともだちに、ペンを 貸しました。",
    exampleMeaningZh: "把筆借給忘記帶筆的朋友。"
  }),
  examQuestion({
    id: "n5-context-soshite",
    level: "N5",
    surface: "そして",
    reading: "そして",
    meaningZh: "而且、然後",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "この みせの ケーキは おいしいです。 ___ 、ねだんも 安いです。",
    promptContextZh: "這家店的蛋糕很好吃。而且價錢也便宜。",
    hintZh: "在前面內容之外，再加上一個同方向的優點。",
    expectedAnswer: "そして",
    options: ["そして", "でも", "だから", "それとも"],
    explanation: "前句「好吃」與後句「便宜」都是優點、方向相同，後句再追加一項，用表並列追加的「そして」（而且）。「でも」是逆接『可是』（好吃與便宜不相反）；「だから」是因果『所以』（『所以便宜』不合邏輯）；「それとも」是選擇『還是』。表同方向追加唯「そして」成立。",
    exampleJapanese: "この みせの ケーキは おいしいです。そして、ねだんも 安いです。",
    exampleMeaningZh: "這家店的蛋糕很好吃。而且價錢也便宜。"
  }),
  examQuestion({
    id: "n5-context-sorekara",
    level: "N5",
    surface: "それから",
    reading: "それから",
    meaningZh: "接著、然後",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "あさ おきて、かおを あらいました。 ___ 、あさごはんを 食べました。",
    promptContextZh: "早上起床洗了臉。接著吃了早餐。",
    hintZh: "前一件事做完，緊跟著做下一件事。",
    expectedAnswer: "それから",
    options: ["それから", "しかし", "だから", "それとも"],
    explanation: "前句「洗臉」與後句「吃早餐」是依時間先後發生的兩個動作，用表時間順序的「それから」（接著、然後）。「しかし」是逆接『可是』（前後不相反）；「だから」是因果『所以』（『所以吃早餐』不自然）；「それとも」是選擇『還是』。表時間先後唯「それから」成立。",
    exampleJapanese: "あさ おきて、かおを あらいました。それから、あさごはんを 食べました。",
    exampleMeaningZh: "早上起床洗了臉。接著吃了早餐。"
  }),
  examQuestion({
    id: "n5-context-shikashi",
    level: "N5",
    surface: "しかし",
    reading: "しかし",
    meaningZh: "但是、可是",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "きのうは いい てんきでした。 ___ 、きょうは あさから 雨です。",
    promptContextZh: "昨天是好天氣。但是今天從早上就下雨。",
    hintZh: "後句出現和前句預料相反的情況。",
    expectedAnswer: "しかし",
    options: ["しかし", "だから", "そして", "それから"],
    explanation: "前句「昨天好天氣」讓人期待今天也好，後句卻是「下雨」，前後相反，用逆接的「しかし」（但是）。「だから」是因果『所以』（『所以下雨』邏輯矛盾）；「そして」是並列『而且』（無法表轉折）；「それから」是時間先後『接著』（前後不是順接）。表逆接唯「しかし」成立。",
    exampleJapanese: "きのうは いい てんきでした。しかし、きょうは あさから 雨です。",
    exampleMeaningZh: "昨天是好天氣。但是今天從早上就下雨。"
  }),
  examQuestion({
    id: "n5-context-soretomo",
    level: "N5",
    surface: "それとも",
    reading: "それとも",
    meaningZh: "或者、還是",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "のみものは コーヒーが いいですか。 ___ 、おちゃが いいですか。",
    promptContextZh: "飲料要咖啡好呢？還是茶好呢？",
    hintZh: "在兩件事之間，問對方要挑哪一個。",
    expectedAnswer: "それとも",
    options: ["それとも", "そして", "だから", "しかし"],
    explanation: "前後是「咖啡」與「茶」兩個選項，句子在問對方要二擇一，用表選擇的「それとも」（還是）。「そして」是並列『而且』（不是二擇一）；「だから」是因果『所以』（句中無因果）；「しかし」是逆接『可是』（兩者非相反對立）。表二選一的疑問唯「それとも」成立。",
    exampleJapanese: "のみものは コーヒーが いいですか。それとも、おちゃが いいですか。",
    exampleMeaningZh: "飲料要咖啡好呢？還是茶好呢？"
  }),
  examQuestion({
    id: "n5-kanji-kawa",
    level: "N5",
    surface: "川",
    reading: "かわ",
    meaningZh: "河、河川",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あの「川」で 魚が およいで います。",
    promptContextZh: "那條河裡有魚在游。",
    expectedAnswer: "かわ",
    options: ["かわ", "がわ", "かわあ", "かっわ"],
    explanation: "正解「かわ」：「川」單獨當名詞時讀訓讀 かわ，句中是『那條河』，正確。干擾「がわ」：濁音化只在複合詞（例：かわ→がわ 如 みぎがわ 右側）才發生，單獨的「川」不濁音，此語境不成立。干擾「かわあ」：多了長音，N5 的 川 無長音，發音不對。干擾「かっわ」：插入促音，無此讀法。陷阱類型＝清濁混淆＋長音／促音干擾。",
    exampleJapanese: "あの川で 魚が およいで います。",
    exampleMeaningZh: "那條河裡有魚在游。"
  }),
  examQuestion({
    id: "n5-kanji-yama",
    level: "N5",
    surface: "山",
    reading: "やま",
    meaningZh: "山",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "なつ休みに たかい「山」に のぼりました。",
    promptContextZh: "暑假時爬了高高的山。",
    expectedAnswer: "やま",
    options: ["やま", "さん", "やあま", "やっま"],
    explanation: "正解「やま」：「山」單獨名詞讀訓讀 やま，句中『爬上高山』，正確。干擾「さん」：是音讀，只用於複合詞（如 ふじさん 富士山），此處 山 是單獨名詞、前面被『たかい』修飾，不讀音讀，明確不成立。干擾「やあま」：多了長音，發音不對。干擾「やっま」：插入促音，無此讀法。陷阱類型＝音訓混淆＋長音／促音干擾。",
    exampleJapanese: "なつ休みに たかい山に のぼりました。",
    exampleMeaningZh: "暑假時爬了高高的山。"
  }),
  examQuestion({
    id: "n5-kanji-asa",
    level: "N5",
    surface: "朝",
    reading: "あさ",
    meaningZh: "早上、早晨",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "まいにち「朝」 六じに おきます。",
    promptContextZh: "每天早上六點起床。",
    expectedAnswer: "あさ",
    options: ["あさ", "あざ", "あっさ", "あさあ"],
    explanation: "正解「あさ」：「朝」單獨名詞讀訓讀 あさ，句中『每天早上六點』指時段，正確。干擾「あざ」：把 さ 濁化成 ざ，あざ 是別的詞（瘀青／痣），讀音與語意都不對。干擾「あっさ」：插入促音，無此讀法。干擾「あさあ」：多了長音，發音不對。陷阱類型＝清濁混淆（會變成別的詞）＋促音／長音干擾。",
    exampleJapanese: "まいにち朝 六じに おきます。",
    exampleMeaningZh: "每天早上六點起床。"
  }),
  examQuestion({
    id: "n5-kanji-namae",
    level: "N5",
    surface: "名前",
    reading: "なまえ",
    meaningZh: "名字、姓名",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "ここに あなたの「名前」を かいて ください。",
    promptContextZh: "請在這裡寫上你的名字。",
    expectedAnswer: "なまえ",
    options: ["なまえ", "なまへ", "なめえ", "なっまえ"],
    explanation: "正解「なまえ」：「名前」讀 なまえ（名 な＋前 まえ），句意『請在這裡寫上你的名字』，正確。干擾「なまへ」：把 え 寫成近形假名 へ（讀音為 he），不成立。干擾「なめえ」：把第二拍 ま 誤替換成 め（なめえ），假名拼錯，非此詞讀音。干擾「なっまえ」：多插入促音 っ，無此讀法。陷阱類型＝近形假名（え/へ）＋假名替換錯誤＋促音干擾。",
    exampleJapanese: "ここに あなたの名前を かいて ください。",
    exampleMeaningZh: "請在這裡寫上你的名字。"
  }),
  examQuestion({
    id: "n5-kanji-tatsu",
    level: "N5",
    surface: "立って",
    reading: "たって",
    meaningZh: "站立（て形）",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "せんせいが きょうしつの まえに「立って」います。",
    promptContextZh: "老師站在教室前面。",
    expectedAnswer: "たって",
    options: ["たって", "だって", "たて", "たあって"],
    explanation: "正解「たって」：「立つ」的 て形是 たって（促音便），句中『老師站在前面』，正確。干擾「だって」：把 た 濁化成 だ，だって 是別的詞（接續助詞「可是」），讀音與意思都不對。干擾「たて」：少了促音變成 たて（另是『縱』或命令形語感），與『立って います』的 て形不符，發音也不同。干擾「たあって」：多了長音，發音不對。陷阱類型＝清濁混淆（變別詞）＋促音脫落＋長音干擾。",
    exampleJapanese: "せんせいが きょうしつの まえに 立って います。",
    exampleMeaningZh: "老師站在教室前面。"
  }),
  examQuestion({
    id: "n5-kanji-takai",
    level: "N5",
    surface: "高い",
    reading: "たかい",
    meaningZh: "高的；貴的",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この ビルは とても「高い」です。",
    promptContextZh: "這棟大樓非常高。",
    expectedAnswer: "たかい",
    options: ["たかい", "だかい", "たがい", "たかあい"],
    explanation: "正解「たかい」：「高い」形容詞讀 たかい，句中『大樓非常高』，正確。干擾「だかい」：把開頭 た 濁化成 だ，無此讀法。干擾「たがい」：把 か 濁化成 が，たがい 會聯想到別詞（互い 互相），讀音與意思都不對。干擾「たかあい」：在 か 後加長音，發音不對。陷阱類型＝清濁混淆（兩處）＋長音干擾。",
    exampleJapanese: "この ビルは とても 高いです。",
    exampleMeaningZh: "這棟大樓非常高。"
  }),
  examQuestion({
    id: "n5-vocab-denwa",
    level: "N5",
    surface: "電話",
    reading: "でんわ",
    meaningZh: "電話",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "母に___をかけます。",
    promptContextZh: "打電話給媽媽。",
    hintZh: "想跟遠方的家人聯絡、報平安的時候。",
    expectedAnswer: "電話",
    options: ["電話", "手紙", "写真", "新聞"],
    explanation: "「電話をかける」是固定搭配＝打電話。「手紙（信）」用「書く」、「写真（照片）」用「撮る」、「新聞（報紙）」用「読む」，都不與「かけます」搭配。故唯「電話」成立。"
  }),
  examQuestion({
    id: "n5-vocab-yomu",
    level: "N5",
    surface: "読む",
    reading: "よむ",
    meaningZh: "閱讀、看（書）",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "図書館で本を___。",
    promptContextZh: "在圖書館看書。",
    hintZh: "在安靜的房間裡，手裡拿著一本書，眼睛沿著紙頁移動的時候。",
    expectedAnswer: "読みます",
    options: ["読みます", "聞きます", "話します", "歌います"],
    explanation: "正解「読みます」：對象是「本（書）」，「本を読む」＝看書，在圖書館的語境最自然。干擾「聞きます（聽）」對象應是聲音、音樂或別人說的話，不能「本を聞く」（聽書在 N5 語境不自然）。干擾「話します（說、談）」是開口講話，「本を話す」不成立。干擾「歌います（唱）」對象是歌曲，「本を歌う」明顯錯誤。三個干擾都是動詞、接續成立，但與賓語「本を」搭配只有「読む」對。"
  }),
  examQuestion({
    id: "n5-vocab-atsui",
    level: "N5",
    surface: "暑い",
    reading: "あつい",
    meaningZh: "熱、炎熱（天氣）",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "夏はとても___です。",
    promptContextZh: "夏天非常___。",
    hintZh: "一年裡七、八月那個季節的時候。",
    expectedAnswer: "暑い",
    options: ["暑い", "涼しい", "暖かい", "冷たい"],
    explanation: "正解「暑い」：描述夏天的氣溫，「夏は暑い」＝夏天熱，是固定常識搭配。干擾「涼しい（涼爽）」是秋天的氣候，與「夏」矛盾。干擾「暖かい（溫暖）」是春天的氣候，程度與季節都不對。干擾「冷たい（冰冷）」用於觸感（水、手等具體東西），不用來形容天氣，「夏は冷たい」不成立。三個干擾都是形容詞、接續成立，但被主語「夏は」鎖死方向，只有「暑い」對。"
  }),
  examQuestion({
    id: "n5-vocab-kau",
    level: "N5",
    surface: "買う",
    reading: "かう",
    meaningZh: "買、購買",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "スーパーでりんごを三つ___。",
    promptContextZh: "在超市買了三顆蘋果。",
    hintZh: "想想在超市裡，顧客對商品會做的事。",
    expectedAnswer: "買いました",
    options: ["買いました", "売りました", "作りました", "捨てました"],
    explanation: "正解「買いました」：在超市付錢取得蘋果，「りんごを買う」＝買蘋果，符合顧客在超市的角色。干擾「売りました（賣）」是店家的動作，顧客在超市是買方不是賣方，方向相反。干擾「作りました（製作）」是自己動手做，在超市不會「做蘋果」。干擾「捨てました（丟掉）」是把東西扔掉，與在超市挑選購買矛盾。三個干擾都是動詞且接續成立，但被「スーパーで」的買方語境鎖死，只有「買う」對。"
  }),
  examQuestion({
    id: "n5-vocab-kiku",
    level: "N5",
    surface: "聞く",
    reading: "きく",
    meaningZh: "聽、聆聽",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "毎晩、好きな音楽を___。",
    promptContextZh: "每天晚上聽喜歡的音樂。",
    hintZh: "戴上耳機、放鬆地享受旋律和節奏的時候。",
    expectedAnswer: "聞きます",
    options: ["聞きます", "見ます", "読みます", "弾きます"],
    explanation: "正解「聞きます」：對象是「音楽（音樂）」，「音楽を聞く」＝聽音樂，是固定搭配。干擾「見ます（看）」對象是影像、畫面，「音楽を見る」不成立。干擾「読みます（讀）」對象是文字書報，「音楽を読む」不對。干擾「弾きます（彈奏）」對象是樂器（ピアノ、ギター等），「音楽を弾く」不自然，應是「ピアノを弾く」。三個干擾都是動詞、接續成立，但與賓語「音楽を」搭配只有「聞く」對。"
  }),
  examQuestion({
    id: "n5-vocab-neru",
    level: "N5",
    surface: "寝る",
    reading: "ねる",
    meaningZh: "睡覺",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "ねむく なったので、ベッドで ___ 。",
    promptContextZh: "因為睏了，所以在床上睡覺。",
    hintZh: "覺得睏了、躺到床上閉上眼睛的時候。",
    expectedAnswer: "寝ます",
    options: ["寝ます", "起きます", "あそびます", "あらいます"],
    explanation: "正解「寝ます」：「ねむくなった（睏了）…ベッドで」鎖死方向，躺到床上閉眼休息用「寝ます」＝睡覺，最自然。干擾「起きます（起床）」是離開被窩、醒過來，與『睏了躺到床上』方向完全相反；干擾「あそびます（玩）」與『睏了上床』的場景矛盾，睏了不會去玩；干擾「あらいます（洗）」是用水清洗，賓語應是手或臉、不能搭「ベッドで…」表睡覺。三個干擾都是動詞、接續成立，但被『ねむくなった＋ベッドで』語境鎖死，唯「寝ます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-kaeru",
    level: "N5",
    surface: "帰る",
    reading: "かえる",
    meaningZh: "回去、回家",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "しごとが おわったので、いえに ___ 。",
    promptContextZh: "因為工作結束了，所以回家。",
    hintZh: "一天的工作做完、離開公司往自己住的地方移動的時候。",
    expectedAnswer: "帰ります",
    options: ["帰ります", "来ます", "あります", "います"],
    explanation: "正解「帰ります」：「しごとがおわった…いえに」鎖死方向，工作結束後回到自己家用「帰ります」＝回去，最自然。干擾「来ます（來）」是別人朝說話者這邊移動過來，主詞與方向不合『自己回家』；干擾「あります（在／有）」是無生命物的存在、不能表移動回家，且接「いえに」語意不通；干擾「います（在）」是有生命物的存在、表靜態存在不是移動，『いえにいます』是『在家』而非『回家』。三個干擾接續成立，但被『しごとがおわった＋いえに』的返回語境鎖死，唯「帰ります」成立。"
  }),
  examQuestion({
    id: "n5-vocab-haru",
    level: "N5",
    surface: "春",
    reading: "はる",
    meaningZh: "春天",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "___ に なると、こうえんで さくらが さきます。",
    promptContextZh: "到了春天，公園裡櫻花就會開。",
    hintZh: "一年四季裡，公園的櫻花開花的那個季節。",
    expectedAnswer: "春",
    options: ["春", "夏", "秋", "冬"],
    explanation: "正解「春」：日本櫻花在三、四月盛開，「さくらがさきます（櫻花開）」這個常識把季節鎖死成「春」＝春天。干擾「夏（夏天）」櫻花季已過、夏天是綠葉，櫻花不在夏天開；干擾「秋（秋天）」是楓葉與落葉的季節，櫻花不在秋天開；干擾「冬（冬天）」天氣寒冷、櫻花樹光禿，更不會開花。四個選項都是季節名詞、接續都成立，但被『さくらがさきます』的常識鎖死，唯「春」成立。"
  }),
  examQuestion({
    id: "n5-vocab-heya",
    level: "N5",
    surface: "部屋",
    reading: "へや",
    meaningZh: "房間",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "つかれたので、じぶんの ___ で ゆっくり やすみます。",
    promptContextZh: "因為累了，在自己的房間裡好好休息。",
    hintZh: "在家裡屬於自己、可以獨處睡覺與休息的私人小空間。",
    expectedAnswer: "部屋",
    options: ["部屋", "えき", "がっこう", "びょういん"],
    explanation: "正解「部屋」：「じぶんの…でゆっくりやすみます（在自己的＿好好休息）」指家中私人空間，用「部屋」＝房間，最自然。干擾「えき（車站）」是搭車的公共場所、不是『自己的』地方，無法在那ゆっくり休息；干擾「がっこう（學校）」是上課的場所、也非『自己的』私人空間；干擾「びょういん（醫院）」是看病的場所，與『累了好好休息』的居家語境不合。四個都是場所名詞、接續成立，但被『じぶんの＋ゆっくりやすみます』的私人居家語境鎖死，唯「部屋」成立。"
  }),
  examQuestion({
    id: "n5-vocab-eki",
    level: "N5",
    surface: "駅",
    reading: "えき",
    meaningZh: "車站",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "でんしゃに のるために、あるいて ___ へ いきます。",
    promptContextZh: "為了搭電車，走路去車站。",
    hintZh: "想想要搭電車，必須先走到哪一種設施才能上車。",
    expectedAnswer: "えき",
    options: ["えき", "ぎんこう", "ゆうびんきょく", "としょかん"],
    explanation: "正解「えき（駅）」：「でんしゃにのるために（為了搭電車）」鎖死目的地，搭電車要去「駅」＝車站，最自然。干擾「ぎんこう（銀行）」是存提款的地方、與搭電車無關；干擾「ゆうびんきょく（郵局）」是寄信寄包裹的地方、不是搭車處；干擾「としょかん（圖書館）」是借書讀書的地方、與搭電車無關。四個都是場所名詞、接續成立，但被『でんしゃにのるために』的目的鎖死，唯「えき」成立。"
  }),
  examQuestion({
    id: "n5-vocab-genki",
    level: "N5",
    surface: "元気",
    reading: "げんき",
    meaningZh: "精神好、有活力",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "びょうきが なおって、いまは とても ___ です。",
    promptContextZh: "病好了，現在非常有精神。",
    hintZh: "病已經好了，描述身體恢復、狀況轉好的整體樣子。",
    expectedAnswer: "元気",
    options: ["元気", "ひま", "じょうず", "しずか"],
    explanation: "正解「元気」：「びょうきがなおって（病好了）」鎖死方向，康復後身體有活力、狀況好用「元気」＝有精神，最自然。干擾「ひま（空閒）」形容沒事做的時間狀態、和病好不好沒有關係；干擾「じょうず（擅長）」形容能力高、不能形容病後的身體狀況；干擾「しずか（安靜）」形容聲音小或環境安靜、與『病好了身體變好』無關。四個都是な形容詞、接續成立，但被『びょうきがなおって』的康復語境鎖死，唯「元気」成立。"
  }),
  examQuestion({
    id: "n5-vocab-hanasu",
    level: "N5",
    surface: "話す",
    reading: "はなす",
    meaningZh: "說、講話",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "じゅぎょうちゅうは、ともだちと 大きい声で ___ では いけません。",
    promptContextZh: "上課中不可以和朋友講話。",
    hintZh: "老師正在上課，同學之間不該做的那件事。",
    expectedAnswer: "話して",
    options: ["話して", "あるいて", "ねて", "たべて"],
    explanation: "正解「話して」：「ともだちと…ではいけません（和朋友＿是不行的）」搭配上課中的禁止語境，和朋友開口交談用「話す」＝講話，最自然。干擾「あるいて（走）」是移動、上課中不會說『不可以和朋友走』這種搭配；干擾「ねて（睡）」雖上課睡覺也不好，但『ともだちと寝て』語意怪、不是和朋友一起睡的場景；干擾「たべて（吃）」是『和朋友吃』、但賓語應是食物且場景不合課堂交談。四個都是て形動詞、接續成立，但被『ともだちと＋じゅぎょうちゅう』的交談禁止語境鎖死，唯「話して」成立。"
  }),
  examQuestion({
    id: "n5-kanji-hito",
    level: "N5",
    surface: "人",
    reading: "ひと",
    meaningZh: "人",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あの「人」はわたしの となりに すんでいます。",
    promptContextZh: "那個人住在我的隔壁。",
    expectedAnswer: "ひと",
    options: ["ひと", "びと", "じん", "にん"],
    explanation: "單獨當「人」這個名詞時訓讀「ひと」。「びと」是錯誤地把詞頭濁化（旅人たびびと那種連濁只在複合詞後半才出現，句首單獨的「人」不濁）；「じん」「にん」都是音讀，只用在日本人にほんじん、三人さんにん這類複合詞，單獨指「那個人」不能用。故只有「ひと」成立。",
    exampleJapanese: "あの人はわたしの となりに すんでいます。",
    exampleMeaningZh: "那個人住在我的隔壁。"
  }),
  examQuestion({
    id: "n5-kanji-ue",
    level: "N5",
    surface: "上",
    reading: "うえ",
    meaningZh: "上面、上方",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "つくえの「上」に ねこが います。",
    promptContextZh: "桌子上面有一隻貓。",
    expectedAnswer: "うえ",
    options: ["うえ", "した", "うへ", "じょう"],
    explanation: "表示位置「上面」時訓讀「うえ」。「した」是「下」的讀音、意思相反（下面），語意明確不對；「うへ」把第二拍誤寫成へ，是錯讀；「じょう」是音讀，用在屋上おくじょう這類複合詞，單獨指「桌上」不能用。故只有「うえ」成立。",
    exampleJapanese: "つくえの 上に ねこが います。",
    exampleMeaningZh: "桌子上面有一隻貓。"
  }),
  examQuestion({
    id: "n5-kanji-en",
    level: "N5",
    surface: "円",
    reading: "えん",
    meaningZh: "日圓",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この りんごは ひゃく「円」です。",
    promptContextZh: "這顆蘋果是一百日圓。",
    expectedAnswer: "えん",
    options: ["えん", "けん", "げん", "まる"],
    explanation: "貨幣單位「円」讀「えん」。「けん」是「件」「軒」等別字的讀音；「げん」把えん誤濁化、也不是此字讀音；「まる」是圓圈符號「○」的訓讀，不用在金額。一百圓只能用「えん」，故唯一成立。",
    exampleJapanese: "この りんごは ひゃく円です。",
    exampleMeaningZh: "這顆蘋果是一百日圓。"
  }),
  examQuestion({
    id: "n5-kanji-deru",
    level: "N5",
    surface: "出ます",
    reading: "でます",
    meaningZh: "出去、出來、出發",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "まいあさ 七時に いえを 「出ます」。",
    promptContextZh: "每天早上七點出門。",
    expectedAnswer: "でます",
    options: ["でます", "てます", "だします", "ではます"],
    explanation: "自動詞「出る」的ます形是「でます」（出去、離開）。「てます」漏掉濁點是錯讀；「だします」是他動詞「出す」（拿出、交出）的讀音，需要受詞、和「いえを出る＝離開家」的自動詞用法不同（這裡的を是離開的起點）；「ではます」多塞了は是錯讀。故只有「でます」成立。",
    exampleJapanese: "まいあさ 七時に いえを 出ます。",
    exampleMeaningZh: "每天早上七點出門。"
  }),
  examQuestion({
    id: "n5-kanji-haha",
    level: "N5",
    surface: "母",
    reading: "はは",
    meaningZh: "（自己的）母親、媽媽",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "わたしの 「母」は りょうりが じょうずです。",
    promptContextZh: "我媽媽很會做菜。",
    expectedAnswer: "はは",
    options: ["はは", "ばば", "ちち", "はわ"],
    explanation: "謙稱自己的母親時讀「はは」。「ばば」把詞頭濁化是錯讀（且語感粗俗）；「ちち」是「父」的讀音、指父親、語意相反；「はわ」把第二拍誤寫成わ是錯讀。提到自己的媽媽只能用「はは」，故唯一成立。",
    exampleJapanese: "わたしの 母は りょうりが じょうずです。",
    exampleMeaningZh: "我媽媽很會做菜。"
  }),
  examQuestion({
    id: "n5-kanji-iu",
    level: "N5",
    surface: "言います",
    reading: "いいます",
    meaningZh: "說、講",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あさ あう とき、「おはよう」と 「言います」。",
    promptContextZh: "早上見面時會說「早安」。",
    expectedAnswer: "いいます",
    options: ["いいます", "います", "ゆいます", "いえます"],
    explanation: "「言う」的ます形是「いいます」（說）。「います」漏掉一個い、變成存在動詞「居る」的讀音、意思是「在」、語意不對；「ゆいます」是錯讀（言う口語雖唸ゆう，但ます形寫成讀音時是いいます，ゆいます不成立）；「いえます」是可能形「言える」（能說）的讀音、和原句陳述習慣動作的「言います」不同。故只有「いいます」成立。",
    exampleJapanese: "あさ あう とき、「おはよう」と 言います。",
    exampleMeaningZh: "早上見面時會說「早安」。"
  }),
  examQuestion({
    id: "n5-grammar-ka",
    level: "N5",
    surface: "か",
    reading: "か",
    meaningZh: "疑問助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "すみません、田中さんは 学生です ___ 。",
    promptContextZh: "不好意思，請問田中先生是學生嗎？",
    hintZh: "向對方打聽、不確定對方身分而開口探問時，加在句尾的字。",
    expectedAnswer: "か",
    options: ["か", "ね", "よ", "わ"],
    explanation: "句尾「か」把陳述句變成提問，「学生ですか」＝是學生嗎，搭配「すみません、…」向人探問很自然。「ね」是向對方尋求同意/確認共識（你也覺得吧）、不構成詢問身分的問句；「よ」是把資訊告知對方、是陳述不是提問；「わ」是女性語氣的感嘆、也非疑問。表疑問唯「か」成立。"
  }),
  examQuestion({
    id: "n5-grammar-no",
    level: "N5",
    surface: "の",
    reading: "の",
    meaningZh: "所有助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "これは わたし ___ かさです。",
    promptContextZh: "這是我的傘。",
    hintZh: "說明這把傘屬於自己、把人和物品連起來時夾在中間的字。",
    expectedAnswer: "の",
    options: ["の", "は", "を", "へ"],
    explanation: "「Ａの Ｂ」用「の」表示所屬，「わたしのかさ」＝我的傘。「は」是主題助詞、「わたしはかさです」＝我是傘，語意荒謬；「を」是受詞助詞、句中沒有動作；「へ」是方向、句中沒有移動。名詞接名詞表所有唯「の」成立。"
  }),
  examQuestion({
    id: "n5-grammar-nagara",
    level: "N5",
    surface: "ながら",
    reading: "ながら",
    meaningZh: "一邊…一邊…（同時）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "おんがくを 聞き ___ べんきょうします。",
    promptContextZh: "一邊聽音樂一邊讀書。",
    hintZh: "同一個人在做主要動作時，還順便做著另一件事的說法。",
    expectedAnswer: "ながら",
    options: ["ながら", "たい", "ましょう", "ません"],
    explanation: "「Ｖます形＋ながら」表示同一人同時做兩件事，「聞きながら勉強します」＝邊聽邊讀。「たい」是願望（想聽）、無法把兩動作並接；「ましょう」是邀約/提議；「ません」是否定。連接『同時進行的另一動作』唯「ながら」成立。"
  }),
  examQuestion({
    id: "n5-grammar-na",
    level: "N5",
    surface: "な",
    reading: "な",
    meaningZh: "形容動詞連體形",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "ここは とても しずか ___ こうえんです。",
    promptContextZh: "這裡是非常安靜的公園。",
    hintZh: "把「しずか」拿來修飾後面那個地方時、夾在兩者之間的字。",
    expectedAnswer: "な",
    options: ["な", "に", "で", "の"],
    explanation: "ナ形容詞修飾名詞要用連體形「〜な」，「しずかな公園」＝安靜的公園。「に」是副詞形（しずかに＝安靜地）、修飾動作而非名詞；「で」是中止/接續形、後面要再接述語而非直接接名詞；「の」用於名詞接名詞、「しずか」此處是ナ形容詞不接「の」。ナ形容詞修飾名詞唯「な」成立。"
  }),
  examQuestion({
    id: "n5-usage-matsu",
    level: "N5",
    surface: "待つ",
    reading: "まつ",
    meaningZh: "等、等待",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「待つ」の使い方が最も適切なものはどれか。",
    promptContextZh: "「待つ」是停在原地，直到人或事物到來。",
    hintZh: "人還沒到，停在原地直到對方出現。",
    expectedAnswer: "えきで 友達を 30ぷん 待ちました。",
    options: ["えきで 友達を 30ぷん 待ちました。", "この りんごは あかくて、とても 待ちます。", "つめたい おちゃを コップに 待ちました。", "あさ あたらしい くつを 待って、でかけました。"],
    explanation: "「待つ」是停在原地直到人或事物到來，本句「在車站等了朋友三十分鐘」最自然。第二句形容蘋果又紅，那是描述狀態，要用「おいしい」之類的形容詞，蘋果無法被『等』；第三句把茶倒進杯子要用「入れる」（入れました）；第四句早上穿上新鞋要用「はく」（はいて）。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "えきで 友達を 30ぷん 待ちました。",
    exampleMeaningZh: "在車站等了朋友三十分鐘。"
  }),
  examQuestion({
    id: "n5-usage-akarui",
    level: "N5",
    surface: "明るい",
    reading: "あかるい",
    meaningZh: "明亮的、光線充足",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「明るい」の使い方が最も適切なものはどれか。",
    promptContextZh: "「明るい」用來形容地方有很多光、看得清楚。",
    hintZh: "房間裡有很多光、看得清楚的狀態。",
    expectedAnswer: "この へやは まどが おおきくて、とても 明るいです。",
    options: ["この へやは まどが おおきくて、とても 明るいです。", "この コーヒーは さとうを いれて、明るいです。", "この もんだいは かんたんで、明るいです。", "この にもつは ちいさくて、明るいです。"],
    explanation: "「明るい」形容地方光線充足、看得清楚，本句「這個房間窗戶很大，非常明亮」最自然。第二句咖啡加了糖是味道甜，要用「あまい」；第三句題目簡單要用「やさしい／かんたん」，無法用『明亮』形容；第四句行李小是體積，要用「ちいさい」，跟『明亮』無關。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "この へやは まどが おおきくて、とても 明るいです。",
    exampleMeaningZh: "這個房間窗戶很大，非常明亮。"
  }),
  examQuestion({
    id: "n5-context-demo",
    level: "N5",
    surface: "でも",
    reading: "でも",
    meaningZh: "可是、不過",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "この りょうりは からいです。 ___ 、ぜんぶ 食べました。",
    promptContextZh: "這道菜很辣。可是還是全部吃完了。",
    hintZh: "後句出現和前句印象相反的評價。",
    expectedAnswer: "でも",
    options: ["でも", "だから", "それから", "そして"],
    explanation: "前句『很辣』與後句『全部吃完了』形成『雖然辣，但還是吃完』的逆接，用「でも」（可是）。「だから（所以）」因果不成立；「それから（然後）」「そして（而且）」是順接/追加，無法表達『辣卻仍吃完』的轉折。唯「でも」成立。"
  }),
  examQuestion({
    id: "n5-context-mata",
    level: "N5",
    surface: "また",
    reading: "また",
    meaningZh: "另外、再者",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "わたしの へやは ひろいです。 ___ 、まどから うみが みえます。",
    promptContextZh: "我的房間很寬敞。另外，從窗戶能看見海。",
    hintZh: "在前句之後，再列出一件同方向的優點。",
    expectedAnswer: "また",
    options: ["また", "でも", "だから", "それとも"],
    explanation: "前句「房間寬敞」與後句「能看見海」都是房間的優點、方向相同，後句再補充一項，用表並列補充的「また」（另外、再者）。「でも」是逆接『可是』（兩者皆優點、不相反）；「だから」是因果『所以』（『寬敞所以看得見海』無因果關係）；「それとも」是選擇『還是』（句中不是要二擇一）。表同方向補充唯「また」成立。"
  }),
  examQuestion({
    id: "n5-grammar-kute",
    level: "N5",
    surface: "くて",
    reading: "くて",
    meaningZh: "（形容詞）並列接續",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "この へやは ひろ ___ あかるいです。",
    promptContextZh: "這個房間又寬敞又明亮。",
    hintZh: "把房間的兩個好處連著講，接在前一個性質後面的形。",
    expectedAnswer: "くて",
    options: ["くて", "かった", "くない", "では"],
    explanation: "イ形容詞用「〜くて」連接後面的形容詞，「広くて明るい」＝又寬又亮。「かった」是過去式、「広かった明るい」無法把兩形容詞接起來；「くない」是否定、「広くない明るい」變成『不寬敞、亮』語意矛盾；「では」用於名詞/ナ形容詞接續、不接イ形容詞語幹。並列兩個イ形容詞唯「くて」成立。"
  }),
  examQuestion({
    id: "n5-usage-hima",
    level: "N5",
    surface: "ひま",
    reading: "ひま",
    meaningZh: "空閒、有空",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「ひま」の使い方が最も適切なものはどれか。",
    promptContextZh: "「ひま」是沒有事情要做、時間很多。",
    hintZh: "沒有工作或約定，時間空著的狀態。",
    expectedAnswer: "きょうは しごとが なくて、とても ひまです。",
    options: ["きょうは しごとが なくて、とても ひまです。", "この みせの ラーメンは とても ひまです。", "あの やまは たかくて、とても ひまです。", "この にもつは おもくて、ひまです。"],
    explanation: "「ひま」是沒有事情要做、時間很多，本句「今天沒有工作，非常有空」最自然。第二句拉麵好吃要用「おいしい」，食物無法用『有空』形容；第三句山很高要用「たかい」，山的高度跟『有空』無關；第四句行李重要用「おもい」本身，重量跟『有空』無關。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "きょうは しごとが なくて、とても ひまです。",
    exampleMeaningZh: "今天沒有工作，非常有空。"
  }),
  examQuestion({
    id: "n5-context-dakara",
    level: "N5",
    surface: "だから",
    reading: "だから",
    meaningZh: "所以、因此",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "あたまが いたいです。 ___ 、きょうは はやく ねます。",
    promptContextZh: "頭很痛。所以今天要早點睡。",
    hintZh: "前句是頭痛的原因，後句是接著決定要做的事。",
    expectedAnswer: "だから",
    options: ["だから", "でも", "それとも", "しかし"],
    explanation: "前句「頭痛」是原因，後句「早點睡」是因應這原因而採取的行動，前後是因果關係，用表結果的「だから」（所以）。「でも」是逆接『可是』（頭痛與早睡不相反，無轉折）；「それとも」是選擇『還是』（句中沒有兩個選項要二擇一）；「しかし」是逆接『但是』（前後非相反）。表因果唯「だから」成立。"
  }),
  examQuestion({
    id: "n5-vocab-yasai",
    level: "N5",
    surface: "やさい",
    reading: "やさい",
    meaningZh: "蔬菜、青菜",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "スーパーで にんじんや トマトなどの ___ を 買いました。",
    promptContextZh: "在超市買了胡蘿蔔、番茄之類的東西。",
    hintZh: "在超市購物，籃子裡放進了紅蘿蔔和番茄這一類東西。",
    expectedAnswer: "やさい",
    options: ["やさい", "にく", "さかな", "くだもの"],
    explanation: "正解 やさい(蔬菜)：にんじん(胡蘿蔔)和トマト(番茄)都是代表性蔬菜，「などの＋類名」要求上位類，唯一吻合。にく(肉)錯，胡蘿蔔番茄不是肉。さかな(魚)錯，二者都不是魚。くだもの(水果)看似接近但トマト和にんじん在日語慣常歸為蔬菜、母語者不會用くだもの概括，語意不成立。"
  }),
  examQuestion({
    id: "n5-vocab-tsumetai",
    level: "N5",
    surface: "つめたい",
    reading: "つめたい",
    meaningZh: "冰涼的、冰冷的（觸感）",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "のどが かわいたので、___ ジュースを 飲みたいです。",
    promptContextZh: "因為口渴，想喝冰冰的果汁。",
    hintZh: "口渴的時候，最想喝下去的那種飲料。",
    expectedAnswer: "つめたい",
    options: ["つめたい", "あかい", "ながい", "まるい"],
    explanation: "正解 つめたい(冰涼)：口渴想喝的飲料自然會想要冰的，與「飲みたい」搭配最貼切，唯一成立。あかい(紅的)錯，口渴與顏色無關、語意不通。ながい(長的)錯，不能形容果汁。まるい(圓的)錯，飲料不用圓形容、且與口渴無關。"
  }),
  examQuestion({
    id: "n5-vocab-omoshiroi",
    level: "N5",
    surface: "おもしろい",
    reading: "おもしろい",
    meaningZh: "有趣的、好玩的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "きのうの えいがは とても ___ から、また 見たいです。",
    promptContextZh: "昨天的電影很有趣，所以還想再看。",
    hintZh: "昨天看了一部片子，看完之後還想再看一次。",
    expectedAnswer: "おもしろかった",
    options: ["おもしろかった", "くらかった", "からかった", "あおかった"],
    explanation: "正解 おもしろかった(很有趣，過去式)：「また見たい(還想再看)」的理由只能是覺得有趣，且配合「きのう」需過去形，唯一成立。くらかった(暗)錯，黑暗不是想再看的理由、語意反。からかった(辣)錯，辣形容食物不形容電影。あおかった(藍)錯，顏色不構成再看的理由。"
  }),
  examQuestion({
    id: "n5-vocab-mijikai",
    level: "N5",
    surface: "みじかい",
    reading: "みじかい",
    meaningZh: "短的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "なつは あついので、かみを ___ きりました。",
    promptContextZh: "因為夏天很熱，把頭髮剪短了。",
    hintZh: "空格要填形容詞的副詞形（～く），用來說明剪頭髮的結果狀態。",
    expectedAnswer: "みじかく",
    options: ["みじかく", "おもく", "ひろく", "つよく"],
    explanation: "正解 みじかく(短)：天熱剪頭髮自然是剪短，「かみをきる」與短搭配且需副詞形，唯一成立。おもく(重)錯，剪頭髮不會說剪重。ひろく(寬)錯，頭髮不用寬窄形容。つよく(強)錯，頭髮不用強弱形容，皆語意不通。"
  }),
  examQuestion({
    id: "n5-vocab-hayaku",
    level: "N5",
    surface: "はやく",
    reading: "はやく",
    meaningZh: "早地、快地",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あした しけんが あるので、今日は ___ ねます。",
    promptContextZh: "因為明天有考試，今天要早點睡。",
    hintZh: "明天有考試，今天的就寢時間要怎麼安排。",
    expectedAnswer: "はやく",
    options: ["はやく", "おそく", "あつく", "くらく"],
    explanation: "正解 はやく(早)：明天有考試、今天要早睡養精神，與『ねます』邏輯一致。おそく(晚)方向相反；あつく(熱地)、くらく(暗地)都無法形容就寢時間，語意不通。唯『はやく』成立。"
  }),
  examQuestion({
    id: "n5-vocab-denki",
    level: "N5",
    surface: "でんき",
    reading: "でんき",
    meaningZh: "電燈、燈",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "へやが くらいので、___ を つけてください。",
    promptContextZh: "因為房間很暗，請把燈打開。",
    hintZh: "房間裡光線不足，看不太清楚，希望能改善一下。",
    expectedAnswer: "でんき",
    options: ["でんき", "まど", "ドア", "いす"],
    explanation: "正解 でんき(電燈)：房間暗時要「つける(開)」的對象是燈，「でんきをつける」是固定搭配，唯一成立。まど(窗)錯，窗用「あける(開啟)」不用「つける」、且夜暗開窗不解決照明。ドア(門)錯，門用「あける」、不與「つける」搭。いす(椅子)錯，椅子不能つける、與房間暗無關。"
  }),
  examQuestion({
    id: "n5-kanji-chichi",
    level: "N5",
    surface: "父",
    reading: "ちち",
    meaningZh: "（自己的）父親、爸爸",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "わたしの「父」は かいしゃいんです。",
    promptContextZh: "我爸爸是上班族。",
    expectedAnswer: "ちち",
    options: ["ちち", "はは", "じじ", "だい"],
    explanation: "謙稱自己的父親時訓讀「ちち」。「はは」是「母」的讀音、指母親、語意相反；「じじ」把詞頭誤濁化（且語感是『老頭』、非父親）；「だい」是無關讀音，與「父」不符。提到自己的爸爸只能用「ちち」，故唯一成立。",
    exampleJapanese: "わたしの父は かいしゃいんです。",
    exampleMeaningZh: "我爸爸是上班族。"
  }),
  examQuestion({
    id: "n5-kanji-inu",
    level: "N5",
    surface: "犬",
    reading: "いぬ",
    meaningZh: "狗",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "にわで しろい「犬」が あそんで います。",
    promptContextZh: "白色的狗在院子裡玩。",
    expectedAnswer: "いぬ",
    options: ["いぬ", "いね", "いの", "えぬ"],
    explanation: "動物「犬」單獨當名詞時訓讀「いぬ」。「いね」（＝稲、稻子）語意不符；「いの」「えぬ」皆為音形錯讀。唯「いぬ」成立。",
    exampleJapanese: "にわで しろい犬が あそんで います。",
    exampleMeaningZh: "白色的狗在院子裡玩。"
  }),
  examQuestion({
    id: "n5-kanji-kuruma",
    level: "N5",
    surface: "車",
    reading: "くるま",
    meaningZh: "車子、汽車",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "ちちは あたらしい「車」を かいました。",
    promptContextZh: "爸爸買了新車。",
    expectedAnswer: "くるま",
    options: ["くるま", "くろま", "くらま", "くりま"],
    explanation: "交通工具「車」單獨當名詞時訓讀「くるま」。「くろま」「くらま」「くりま」皆為母音/音形錯讀，非此字讀音。唯「くるま」成立。",
    exampleJapanese: "ちちは あたらしい車を かいました。",
    exampleMeaningZh: "爸爸買了新車。"
  }),
  examQuestion({
    id: "n5-kanji-shiroi",
    level: "N5",
    surface: "白い",
    reading: "しろい",
    meaningZh: "白色的",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "そらに「白い」くもが あります。",
    promptContextZh: "天空中有白色的雲。",
    expectedAnswer: "しろい",
    options: ["しろい", "じろい", "しるい", "くろい"],
    explanation: "形容詞「白い」訓讀「しろい」。「じろい」把詞頭誤濁化、是錯讀；「しるい」把第二拍ろ誤讀成る、是近形錯讀；「くろい」是「黒い」（黑色的）的讀音、顏色相反、語意明確不對。形容白雲只能用「しろい」，故唯一成立。",
    exampleJapanese: "そらに白い くもが あります。",
    exampleMeaningZh: "天空中有白色的雲。"
  }),
  examQuestion({
    id: "n5-kanji-chiisai",
    level: "N5",
    surface: "小さい",
    reading: "ちいさい",
    meaningZh: "小的",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "この「小さい」かばんは こどもの ものです。",
    promptContextZh: "這個小包包是小孩的東西。",
    expectedAnswer: "ちいさい",
    options: ["ちいさい", "ちさい", "ぢいさい", "こいさい"],
    explanation: "形容詞「小さい」訓讀「ちいさい」（ち＋長音い）。「ちさい」漏掉長音、是錯讀；「ぢいさい」把詞頭誤寫成ぢ（現代標準假名遣寫作ち）、是錯讀；「こいさい」把詞頭誤讀成こ、是近形錯讀。形容包包小只能用「ちいさい」，故唯一成立。",
    exampleJapanese: "この小さい かばんは こどもの ものです。",
    exampleMeaningZh: "這個小包包是小孩的東西。"
  }),
  examQuestion({
    id: "n5-kanji-otoko",
    level: "N5",
    surface: "男",
    reading: "おとこ",
    meaningZh: "男人、男性",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あそこに せの たかい「男」の ひとが います。",
    promptContextZh: "那裡有一個個子高的男人。",
    expectedAnswer: "おとこ",
    options: ["おとこ", "おんな", "おとご", "おどこ"],
    explanation: "「男」單獨指男性時訓讀「おとこ」。「おんな」是「女」的讀音、指女性、語意相反；「おとご」把第三拍こ誤濁化成ご、是錯讀；「おどこ」把第二拍と誤濁化成ど、是錯讀。形容那位男性只能用「おとこ」，故唯一成立。",
    exampleJapanese: "あそこに せの たかい男の ひとが います。",
    exampleMeaningZh: "那裡有一個個子高的男人。"
  }),
  examQuestion({
    id: "n5-grammar-doko",
    level: "N5",
    surface: "どこ",
    reading: "どこ",
    meaningZh: "哪裡、什麼地方",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "すみません、トイレは ___ ですか。",
    promptContextZh: "在車站找洗手間，向站務員詢問位置。",
    hintZh: "向人問路、想知道某個地點在哪邊時用的疑問詞。",
    expectedAnswer: "どこ",
    options: ["どこ", "だれ", "いつ", "なに"],
    explanation: "問「トイレは___ですか」要問場所，「どこ（哪裡）」正解，是問地點的疑問詞。「だれ（誰）」問人，廁所不是人，不成立。「いつ（何時）」問時間，與位置無關，不成立。「なに（什麼）」問事物，「トイレはなにですか」變成問廁所是什麼東西，語意明顯不通。"
  }),
  examQuestion({
    id: "n5-grammar-hoshii",
    level: "N5",
    surface: "ほしい",
    reading: "ほしい",
    meaningZh: "想要（某物）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "わたしは あたらしい かばん ___ ほしいです。",
    promptContextZh: "舊包包壞了，跟家人說自己想要新的包包。",
    hintZh: "說出自己對某個東西的渴望、希望能得到它的時候。",
    expectedAnswer: "が",
    options: ["が", "を", "に", "へ"],
    explanation: "「～がほしい」是表示想要某物的固定句型，對象用助詞「が」標示，故「が」正解。「を」用於動作的受詞（如かばんを買う），但ほしい是形容詞不接を，不成立。「に」表方向或對象、地點，與ほしい的願望對象不搭，不成立。「へ」表移動方向，かばんへ沒有移動意味，明顯不通。"
  }),
  examQuestion({
    id: "n5-grammar-mou",
    level: "N5",
    surface: "もう",
    reading: "もう",
    meaningZh: "已經",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "ひるごはんは ___ たべました。",
    promptContextZh: "朋友問要不要一起吃午餐，但你回答午餐的狀態。",
    hintZh: "回答午餐吃了沒。",
    expectedAnswer: "もう",
    options: ["もう", "よく", "いつも", "ときどき"],
    explanation: "後接肯定過去式『食べました』表動作已完成，用『もう（已經）』最自然。『よく（常常）』『いつも（總是）』『ときどき（有時）』都是頻率副詞，與『午餐吃了沒』的單次完成語意不合。唯『もう』成立。"
  }),
  examQuestion({
    id: "n5-usage-akeru",
    level: "N5",
    surface: "開ける",
    reading: "あける",
    meaningZh: "打開（門、窗等）",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「開ける」の使い方が最も適切なものはどれか。",
    promptContextZh: "選出「開ける」用法最自然的句子。",
    hintZh: "四句裡，哪一句的『開ける』搭配的對象最自然。",
    expectedAnswer: "へやが あついので、まどを 開けます。",
    options: ["へやが あついので、まどを 開けます。", "つめたい ぎゅうにゅうを コップに 開けます。", "あさ 七時に めを さまして、ベッドから 開けます。", "やすみの 日は、こうえんで 子どもと 開けます。"],
    explanation: "正解「まどを 開けます」：房間悶熱、想讓空氣進來，對著窗戶用「開ける」＝打開，方向與搭配都正確。干擾「ぎゅうにゅうを コップに 開けます」：把牛奶倒進杯子要用「入れる」（入れます），液體不能用『打開』；干擾「ベッドから 開けます」：早上睡醒離開床要用「起きる」（起きます），『開ける』不能形容起身；干擾「子どもと 開けます」：和孩子在公園應是『玩』要用「あそぶ」（あそびます），『開ける』不能表示遊玩。四句都含「開ける」，但僅『打開窗戶』的搭配成立。",
    exampleJapanese: "へやが あついので、まどを 開けます。",
    exampleMeaningZh: "因為房間很熱，所以打開窗戶。"
  }),
  examQuestion({
    id: "n5-usage-kirei",
    level: "N5",
    surface: "きれい",
    reading: "きれい",
    meaningZh: "乾淨、漂亮",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「きれい」の使い方が最も適切なものはどれか。",
    promptContextZh: "選出「きれい」用法最自然的句子。",
    hintZh: "四句裡，哪一句的『きれい』用得最自然。",
    expectedAnswer: "そうじを したので、へやが きれいに なりました。",
    options: ["そうじを したので、へやが きれいに なりました。", "この にもつは きれいなので、一人では もてません。", "コーヒーに さとうを 入れて、きれいに のみます。", "けさは さむくて、手が きれいに なりました。"],
    explanation: "正解「へやが きれいに なりました」：打掃過後房間變得乾淨整潔，這種狀態用「きれい」＝乾淨，最自然。干擾「にもつは きれいなので、一人では もてません」：拿不動是因為行李『重』要用「おもい」，『きれい』不能形容重量；干擾「さとうを 入れて、きれいに のみます」：加糖後咖啡是變『甜』要用「あまい」，『きれい』不能形容味道；干擾「手が きれいに なりました」：天冷手是變『冰冷』要用「つめたい」，『きれい』不能表示冷。四句都含「きれい」，但僅『房間變乾淨』的語境成立。",
    exampleJapanese: "そうじを したので、へやが きれいに なりました。",
    exampleMeaningZh: "因為打掃過了，所以房間變乾淨了。"
  }),
  examQuestion({
    id: "n5-usage-wakaru",
    level: "N5",
    surface: "わかる",
    reading: "わかる",
    meaningZh: "懂、明白",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「わかる」の使い方が最も適切なものはどれか。",
    promptContextZh: "選出「わかる」用法最自然的句子。",
    hintZh: "四句裡，哪一句的『わかる』用得最自然。",
    expectedAnswer: "先生に きいたので、もんだいが わかりました。",
    options: ["先生に きいたので、もんだいが わかりました。", "あさごはんに パンと たまごを わかりました。", "つくえの 上に ほんが 三さつ わかって います。", "あした、ともだちと えいがを わかります。"],
    explanation: "「わかる」是『懂、明白』。正解『先生に きいたので、もんだいが わかりました』＝問了老師後就懂了。其餘誤用：『パンとたまごをわかりました』應為『食べました』；『本が三さつわかっています』應為『あります』；『えいがをわかります』應為『見ます』。唯第一句成立。",
    exampleJapanese: "先生に きいたので、もんだいが わかりました。",
    exampleMeaningZh: "因為老師為我說明了，所以題目我懂了。"
  }),
  examQuestion({
    id: "n5-context-sorede",
    level: "N5",
    surface: "それで",
    reading: "それで",
    meaningZh: "於是、因此",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "きのう おそく まで しごとを しました。 ___ 、けさは とても ねむいです。",
    promptContextZh: "昨天工作到很晚。於是今天早上非常睏。",
    hintZh: "看前後兩句的關係，選最自然的接續詞。",
    expectedAnswer: "それで",
    options: ["それで", "でも", "それとも", "また"],
    explanation: "前句「工作到很晚」是原因，後句「今天早上很睏」是順著前句自然產生的結果，用表結果的「それで」（於是、因此）。「でも」是逆接『可是』（工作到很晚而想睡是合理的，前後不相反，無轉折）；「それとも」是選擇『還是』（句中沒有兩個選項要二擇一）；「また」是並列追加『另外』（後句不是再補一項同方向的事物，而是前句造成的結果）。表自然結果唯「それで」成立。"
  }),
  examQuestion({
    id: "n5-context-jaa",
    level: "N5",
    surface: "じゃあ",
    reading: "じゃあ",
    meaningZh: "那麼、那就",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "そとは さむいですね。 ___ 、まどを しめましょう。",
    promptContextZh: "外面好冷呢。那就把窗戶關上吧。",
    hintZh: "看前後兩句的關係，選最自然的接續詞。",
    expectedAnswer: "じゃあ",
    options: ["じゃあ", "でも", "それとも", "しかし"],
    explanation: "前句「外面好冷」是一個狀況，後句承接這個狀況提出「關窗吧」的對應提議，用表承接前提作回應的「じゃあ」（那麼、那就）。「でも」是逆接『可是』（因為冷而關窗是合理的因應，前後不相反）；「それとも」是選擇『還是』（句中沒有兩個選項要二擇一）；「しかし」是逆接『但是』（前後並非相反對立）。承接前提作出回應唯「じゃあ」成立。"
  }),
  examQuestion({
    id: "n5-vocab-oishii",
    level: "N5",
    surface: "おいしい",
    reading: "おいしい",
    meaningZh: "好吃、美味",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "一口食べて、このケーキはとても ___ です。",
    promptContextZh: "嘗了一口蛋糕之後說出的感想。",
    hintZh: "夾了一口蛋糕放進嘴裡，正在說對它的感想。",
    expectedAnswer: "おいしい",
    options: ["おいしい", "おもい", "ながい", "ふるい"],
    explanation: "句中「一口食べて（嘗了一口）」鎖定味覺評價，正解おいしい(好吃)修飾食物味道，「このケーキはとても おいしいです」自然成立。おもい(重)用於物品重量，嘗一口談的是味道而非重量，語意不合。ながい(長)指長度，不能形容嘗到的味道。ふるい(舊/老)指物品陳舊，剛吃一口在評味道、與「とても」搭配說蛋糕「很舊」明顯不對。四個皆為い形容詞、接續都成立，但只有おいしい合「嘗味道」的語境。"
  }),
  examQuestion({
    id: "n5-vocab-jouzu",
    level: "N5",
    surface: "上手",
    reading: "じょうず",
    meaningZh: "擅長、拿手",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "妹は うたを 歌うのが とても ___ です。",
    promptContextZh: "妹妹唱歌唱得很好，大家都稱讚她。",
    hintZh: "在說妹妹唱歌這件事做得怎麼樣，旁人都很佩服。",
    expectedAnswer: "じょうず",
    options: ["じょうず", "しずか", "げんき", "ゆうめい"],
    explanation: "句型「〜のが じょうず」是表達「擅長做某事」的固定搭配，「うたを 歌うのが じょうず」＝很會唱歌，語境成立。しずか(安靜)形容環境或人安靜，「歌うのが しずか」說不通。げんき(有精神)指身體狀態，與技能高低無關。ゆうめい(有名)指出名，但「〜のが ゆうめい」不成搭配，且這裡講的是妹妹唱歌的「能力」而非名氣，表能力時母語者只會用じょうず。四者皆な形容詞，僅じょうず能自然接「〜のが」表擅長。"
  }),
  examQuestion({
    id: "n5-vocab-ginkou",
    level: "N5",
    surface: "銀行",
    reading: "ぎんこう",
    meaningZh: "銀行",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "おかねを おろしに ___ へ いきます。",
    promptContextZh: "想去某個地方把錢領出來。",
    hintZh: "要去某個地方辦理跟金錢有關的事情。",
    expectedAnswer: "ぎんこう",
    options: ["ぎんこう", "びょういん", "としょかん", "こうえん"],
    explanation: "正解ぎんこう(銀行)是領錢(おかねを おろす)的場所，「おかねを おろしに ぎんこうへ いきます」自然成立。びょういん(醫院)是看病的地方，不在那裡領錢。としょかん(圖書館)是借書讀書的地方，與領錢無關。こうえん(公園)是散步休憩的地方，根本不能領錢，搭配「おろしに」完全不成立。四者皆為場所名詞、接「へ いきます」接續一致，僅ぎんこう能領錢，唯一鎖定。"
  }),
  examQuestion({
    id: "n5-vocab-yukkuri",
    level: "N5",
    surface: "ゆっくり",
    reading: "ゆっくり",
    meaningZh: "慢慢地、緩慢地",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "せんせい、___ はなして ください。",
    promptContextZh: "聽不太懂老師說話，希望老師講慢一點。",
    hintZh: "對方說話時你跟不上，想拜託對方調整方式。",
    expectedAnswer: "ゆっくり",
    options: ["ゆっくり", "ちょっと", "あまり", "ぜんぜん"],
    explanation: "正解ゆっくり(慢慢地)修飾はなす(說話)，「ゆっくり はなして ください」＝請說慢一點，自然成立。ちょっと(稍微/一下)常配否定或表少量，「ちょっと はなして」變成「稍微說一下」語意偏離「想聽懂」的情境。あまり(不太)須與否定呼應，「あまり はなして ください」文法上不成立。ぜんぜん(完全)同樣須接否定，「ぜんぜん はなして ください」不成立。四者皆為副詞，但只有ゆっくり能在肯定的請求句中自然修飾說話速度。"
  }),
  examQuestion({
    id: "n5-kanji-hidari",
    level: "N5",
    surface: "左",
    reading: "ひだり",
    meaningZh: "左、左邊",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "「銀行は駅の左にあります。」",
    promptContextZh: "向別人說明銀行的位置。",
    expectedAnswer: "ひだり",
    options: ["ひだり", "びだり", "ひたり", "ひだと"],
    explanation: "「左」讀作「ひだり」，意為左邊，正解。「びだり」把字首濁音化（ひ→び），不存在這個讀音。「ひたり」把第二音「だ」誤讀成清音「た」，不成立。「ひだと」把詞尾「り」誤成「と」，亦非「左」的讀音。四選項只有「ひだり」成立。",
    exampleJapanese: "銀行は駅の左にあります。",
    exampleMeaningZh: "銀行在車站的左邊。"
  }),
  examQuestion({
    id: "n5-kanji-kane",
    level: "N5",
    surface: "お金",
    reading: "おかね",
    meaningZh: "錢、金錢",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "「財布にお金がありません。」",
    promptContextZh: "打開錢包後發現的狀況。",
    expectedAnswer: "おかね",
    options: ["おかね", "おがね", "おかれ", "おっかね"],
    explanation: "「お金」讀作「おかね」，意為錢，正解。「おがね」把「か」濁化成「が」，不是正確讀音。「おかれ」把詞尾「ね」誤成形近的「れ」，不成立。「おっかね」多了促音「っ」，並無此讀法。只有「おかね」成立。",
    exampleJapanese: "財布にお金がありません。",
    exampleMeaningZh: "錢包裡沒有錢。"
  }),
  examQuestion({
    id: "n5-kanji-ashita",
    level: "N5",
    surface: "明日",
    reading: "あした",
    meaningZh: "明天",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "「明日、図書館へ行きます。」",
    promptContextZh: "說明隔天的安排。",
    expectedAnswer: "あした",
    options: ["あした", "あしだ", "あった", "あさた"],
    explanation: "「明日」在日常口語常讀作「あした」，意為明天，正解。「あしだ」把詞尾「た」濁化成「だ」，不成立。「あった」把「し」誤成促音「っ」，並非此詞讀音。「あさた」把「し」誤成形近的「さ」，亦不成立。四選項僅「あした」成立。",
    exampleJapanese: "明日、図書館へ行きます。",
    exampleMeaningZh: "明天要去圖書館。"
  }),
  examQuestion({
    id: "n5-kanji-eki-no-mae",
    level: "N5",
    surface: "前",
    reading: "まえ",
    meaningZh: "前、前面",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "「コンビニは駅の前にあります。」",
    promptContextZh: "告訴朋友便利商店在哪裡。",
    expectedAnswer: "まえ",
    options: ["まえ", "まへ", "なえ", "まいえ"],
    explanation: "「前」讀作「まえ」，意為前面，正解。「まへ」把「え」寫成歷史假名「へ」，現代讀音不採用，不成立。「なえ」把字首「ま」誤成形近的「な」，並非此字讀音。「まいえ」多插了一個「い」，無此讀法。只有「まえ」成立。",
    exampleJapanese: "コンビニは駅の前にあります。",
    exampleMeaningZh: "便利商店在車站前面。"
  }),
  examQuestion({
    id: "n5-syn-isogashii",
    level: "N5",
    surface: "いそがしい",
    reading: "いそがしい",
    meaningZh: "忙碌、繁忙",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "今週はしごとで「いそがしい」です。",
    promptContextZh: "說明這一週的工作狀況。",
    hintZh: "談本週工作排得很滿的狀態。",
    expectedAnswer: "することが多い",
    options: ["することが多い", "ひまだ", "おもしろい", "つかれない"],
    explanation: "正解「することが多い」（要做的事很多）與「いそがしい」（忙碌）意思最接近，代回「今週はしごとで することが多いです」自然成立，兩者都表沒有空閒、事情多。干擾「ひまだ」是「いそがしい」的反義（空閒），明確不成立；「おもしろい」（有趣）描述趣味而非忙碌程度，語意不對；「つかれない」（不累）方向相反且與忙碌無關，皆不可接受。",
    exampleJapanese: "今週はしごとで することが多いです。",
    exampleMeaningZh: "這一週工作要做的事很多。"
  }),
  examQuestion({
    id: "n5-syn-taihen",
    level: "N5",
    surface: "たいへん",
    reading: "たいへん",
    meaningZh: "辛苦、費力、不容易",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "ひとりでこのしごとをするのは「たいへん」です。",
    promptContextZh: "說一個人做這份工作的感受。",
    hintZh: "講獨自承擔一份工作時的吃力感受。",
    expectedAnswer: "とてもむずかしい",
    options: ["とてもむずかしい", "かんたん", "うれしい", "しずか"],
    explanation: "正解「とてもむずかしい」（很難、很吃力）與「たいへん」（辛苦、不容易）意思最接近。干擾「かんたん」（簡單）是反義，明確不成立；「うれしい」（高興）是情緒，與辛苦程度無關；「しずか」（安靜）描述環境聲音，語意完全不對，皆不可接受。",
    exampleJapanese: "ひとりでこのしごとをするのはとてもむずかしいです。",
    exampleMeaningZh: "一個人做這份工作很難、很吃力。"
  }),
  examQuestion({
    id: "n5-syn-kitanai",
    level: "N5",
    surface: "きたない",
    reading: "きたない",
    meaningZh: "髒、不乾淨",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "このへやはそうじをしていないので、とても「きたない」です。",
    promptContextZh: "描述一間沒打掃過的房間。",
    hintZh: "說一間久未整理的房間給人的印象。",
    expectedAnswer: "よごれている",
    options: ["よごれている", "ひろい", "あたらしい", "あかるい"],
    explanation: "正解「よごれている」（弄髒了、不乾淨）與「きたない」（髒）意思最接近。干擾「ひろい」（寬敞）講空間大小，與乾淨與否無關；「あたらしい」（新的）講新舊，且髒亂房間多半不新，方向不對；「あかるい」（明亮）講光線，皆與髒乾淨無關，不可接受。",
    exampleJapanese: "このへやはそうじをしていないので、とてもよごれています。",
    exampleMeaningZh: "這個房間沒有打掃，所以非常髒。"
  }),
  examQuestion({
    id: "n5-usage-amai",
    level: "N5",
    surface: "あまい",
    reading: "あまい",
    meaningZh: "甜的",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「あまい」の使い方が最も適切なものはどれか。",
    promptContextZh: "形容味道的形容詞用法。",
    hintZh: "形容食物或飲料嚐起來的味道。",
    expectedAnswer: "このケーキはとてもあまいです。",
    options: ["このケーキはとてもあまいです。", "このコーヒーはとてもあまい音です。", "きょうはあまいですから、まどをしめます。", "そのかばんはあまいですね。"],
    explanation: "正解：「このケーキはとてもあまいです」——蛋糕甜，符合「あまい＝甜」的味覺形容用法。其餘干擾搭配不成立：「コーヒーはとてもあまい音です（咖啡是很甜的聲音）」把味覺的「あまい」硬接到「音（聲音）」上，語意完全錯亂，聲音不能用甜形容；「きょうはあまいですから、まどをしめます（因為今天很甜所以關窗）」天氣不能用甜形容，應是「さむい(冷)」之類；「そのかばんはあまいですね（那個包包很甜）」包包不是可嚐味道的東西，搭配不成立。",
    exampleJapanese: "このケーキはとてもあまいです。",
    exampleMeaningZh: "這個蛋糕非常甜。"
  })
];
