import type { PracticeQuestion } from "../../types";
import { examQuestion } from "../helpers";

export const n5Items: PracticeQuestion[] = [
  examQuestion({
    id: "n5-grammar-wo-pan",
    level: "N5",
    surface: "を",
    reading: "を",
    meaningZh: "受詞助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "毎朝、パン ___ 食べます。",
    promptContextZh: "每天早上吃麵包。",
    hintZh: "「吃麵包」中，麵包與動詞之間要用的助詞。",
    expectedAnswer: "を",
    options: ["を", "が", "に", "へ"],
    explanation: "他動詞「食べる」的受詞用「を」標記，「パンを食べます」＝吃麵包。「が」標主語、「に」標對象/時間地點、「へ」標方向，都不能標受詞。唯「を」成立。"
  }),
  examQuestion({
    id: "n5-grammar-de-toshokan",
    level: "N5",
    surface: "で",
    reading: "で",
    meaningZh: "動作場所助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "図書館 ___ 本を読みます。",
    promptContextZh: "在圖書館讀書。",
    hintZh: "「讀書」這個動作發生的場所要用的助詞。",
    expectedAnswer: "で",
    options: ["で", "に", "を", "へ"],
    explanation: "動作發生的場所用「で」，「図書館で読みます」＝在圖書館讀。「に」表存在或到達點（如いる/行く）；「を」標受詞；「へ」標方向。表動作場所唯「で」成立。"
  }),
  examQuestion({
    id: "n5-grammar-tekudasai-iu",
    level: "N5",
    surface: "てください",
    reading: "てください",
    meaningZh: "請（做）…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "すみません、もう一度言っ ___ 。",
    promptContextZh: "不好意思，請再說一次。",
    hintZh: "客氣地請對方再做一次的說法。",
    expectedAnswer: "てください",
    options: ["てください", "てから", "ています", "ました"],
    explanation: "「Vてください」表示客氣的請求，「もう一度言ってください」＝請再說一次。「てから」是「做完…之後」；「ています」是「正在…」；「ました」是過去。配合「すみません、もう一度…」的請求語境，唯「てください」成立。"
  }),
  examQuestion({
    id: "n5-grammar-teimasu-shinbun",
    level: "N5",
    surface: "ています",
    reading: "ています",
    meaningZh: "正在（做）…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "今、父は新聞を読ん ___ 。",
    promptContextZh: "現在爸爸正在看報紙。",
    hintZh: "句首的『今』提示動作此刻發生中。",
    expectedAnswer: "でいます",
    options: ["でいます", "でから", "でも", "でした"],
    explanation: "「Vている」表示正在進行，「今…読んでいます」＝現在正在讀。「でから」是「讀完之後」；「でも」是「即使讀」；「でした」非自然接續。配合句首「今」，唯「でいます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-nomimasu-mizu",
    level: "N5",
    surface: "飲む",
    reading: "のむ",
    meaningZh: "喝",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "のどが かわいたので、水を ___ 。",
    promptContextZh: "因為口渴，所以喝水。",
    hintZh: "口渴時對水做的動作。",
    expectedAnswer: "飲みます",
    options: ["飲みます", "食べます", "聞きます", "見ます"],
    explanation: "「水を飲みます」＝喝水。「食べます」是吃（固體）；「聞きます」是聽/問；「見ます」是看。與「のどがかわいた（口渴）…水を」搭配，唯「飲みます」成立。"
  }),
  examQuestion({
    id: "n5-kanji-gakkou",
    level: "N5",
    surface: "学校",
    reading: "がっこう",
    meaningZh: "學校",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "毎日、自転車で「学校」へ行きます。",
    promptContextZh: "每天騎腳踏車去學校。",
    expectedAnswer: "がっこう",
    options: ["がっこう", "がくこう", "がっこ", "かっこう"],
    explanation: "「学」在「校（こう）」前促音化讀「がっ」、「校」讀長音「こう」，故「学校」＝がっこう。「がくこう」沒促音化；「がっこ」漏掉長音；「かっこう」沒把「学」讀濁音「がっ」（且 かっこう＝格好）。",
    exampleJapanese: "毎日、自転車で学校へ行きます。",
    exampleMeaningZh: "每天騎腳踏車去學校。"
  }),
  examQuestion({
    id: "n5-grammar-ha-watashi-gakusei",
    level: "N5",
    surface: "は",
    reading: "は",
    meaningZh: "主題助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "わたし ___ 学生です。",
    promptContextZh: "我是學生。",
    hintZh: "句首點出「自己」這個談論對象時，後面接的那個字。",
    expectedAnswer: "は",
    options: ["は", "を", "で", "へ"],
    explanation: "「Ａは Ｂです」用「は」提示主題，「わたしは学生です」＝我是學生。「を」是受詞助詞、句中沒有動作對象；「で」是場所/手段、此處非場所；「へ」是方向、句中沒有移動。判斷句的主題唯「は」成立。"
  }),
  examQuestion({
    id: "n5-grammar-ga-neko-iru",
    level: "N5",
    surface: "が",
    reading: "が",
    meaningZh: "主格助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あそこに ねこ ___ います。",
    promptContextZh: "那裡有貓。",
    hintZh: "描述某處存在某個動物時，緊接在那個動物後面的字。",
    expectedAnswer: "が",
    options: ["が", "を", "へ", "と"],
    explanation: "存在句「Ｎがいます／あります」用「が」標示存在的主體，「ねこがいます」＝有貓。「を」需要他動詞作受詞、「います」是自動詞不接受詞；「へ」是方向；「と」是「和」。存在句的主體唯「が」成立。"
  }),
  examQuestion({
    id: "n5-grammar-ni-shichiji-okiru",
    level: "N5",
    surface: "に",
    reading: "に",
    meaningZh: "時間點助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "まいあさ 七時 ___ おきます。",
    promptContextZh: "每天早上七點起床。",
    hintZh: "具體鐘點與動作之間，接在鐘點後面的那個字。",
    expectedAnswer: "に",
    options: ["に", "を", "で", "へ"],
    explanation: "具體時刻＋「に」表示動作發生的時間點，「七時に起きます」＝七點起床。「を」是受詞、時刻不是受詞；「で」標示場所或範圍、非時間點；「へ」是方向。鐘點時刻唯「に」成立。"
  }),
  examQuestion({
    id: "n5-grammar-e-kyouto-iku",
    level: "N5",
    surface: "へ",
    reading: "へ",
    meaningZh: "方向助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あした 京都 ___ 行きます。",
    promptContextZh: "明天要去京都。",
    hintZh: "標示「行きます」這個移動所朝向的地點。",
    expectedAnswer: "へ",
    options: ["へ", "を", "が", "は"],
    explanation: "移動動詞「行きます」前用「へ」表示前往的方向，「京都へ行きます」＝去京都。「を」是受詞、地點不是受詞；「が」是主格、京都非主體；「は」是主題、此處要的是方向。移動目的地唯「へ」（或に）成立，選項中只有「へ」。"
  }),
  examQuestion({
    id: "n5-grammar-to-tomodachi-au",
    level: "N5",
    surface: "と",
    reading: "と",
    meaningZh: "共事對象助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "日曜日に ともだち ___ 会います。",
    promptContextZh: "星期天和朋友見面。",
    hintZh: "標示一起進行「見面」這個互動的另一方。",
    expectedAnswer: "と",
    options: ["と", "を", "で", "へ"],
    explanation: "「Ｎと会います」用「と」標示一起見面的對象，「ともだちと会います」＝和朋友見面。「を」是受詞、「会う」在此用「と」不用「を」；「で」是場所；「へ」是方向。互動對象唯「と」成立。"
  }),
  examQuestion({
    id: "n5-grammar-mo-watashi-iku",
    level: "N5",
    surface: "も",
    reading: "も",
    meaningZh: "「也」助詞",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "田中さんは 行きます。わたし ___ 行きます。",
    promptContextZh: "田中先生要去。我也要去。",
    hintZh: "前句已有人要去，後句表達自己同樣如此時接在主語後的字。",
    expectedAnswer: "も",
    options: ["も", "を", "に", "へ"],
    explanation: "前句「田中さんは行きます」已成立，後句用「も」表示「我也一樣」，「わたしも行きます」＝我也去。「を」是受詞；「に」「へ」是時間/方向，都無法表達『同樣、也』。追加同類唯「も」成立。"
  }),
  examQuestion({
    id: "n5-grammar-tai-mizu-nomu",
    level: "N5",
    surface: "たい",
    reading: "たい",
    meaningZh: "想要（做）…",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "のどが かわきました。つめたい お茶が 飲み ___ です。",
    promptContextZh: "口渴了。想喝冰涼的茶。",
    hintZh: "口渴時表達自己內心願望的說法。",
    expectedAnswer: "たい",
    options: ["たい", "ました", "ています", "ません"],
    explanation: "「Ｖます形＋たい」表示說話者的願望，「飲みたいです」＝想喝。「ました」是過去、與『現在想要』矛盾；「ています」是正在進行；「ません」是否定、與想喝相反。表達願望唯「たい」成立。"
  }),
  examQuestion({
    id: "n5-grammar-masenka-eiga-miru",
    level: "N5",
    surface: "ませんか",
    reading: "ませんか",
    meaningZh: "要不要一起…（邀約）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "土曜日、いっしょに えいがを 見 ___ 。",
    promptContextZh: "星期六，要不要一起看電影？",
    hintZh: "句中的「いっしょに」提示正在向對方提出邀請的句尾說法。",
    expectedAnswer: "ませんか",
    options: ["ませんか", "ました", "たいです", "ています"],
    explanation: "「Ｖませんか」是邀請對方一起做某事的句型，搭配「いっしょに」很自然，「見ませんか」＝要不要看。「ました」是過去陳述；「たいです」是說自己想看、不是邀約；「ています」是正在進行。邀約唯「ませんか」成立。"
  }),
  examQuestion({
    id: "n5-vocab-iku-kaisha",
    level: "N5",
    surface: "行く",
    reading: "いく",
    meaningZh: "去",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あした、でんしゃで 会社へ ___ 。",
    promptContextZh: "明天搭電車去公司。",
    hintZh: "朝著公司這個目的地移動的動作。",
    expectedAnswer: "行きます",
    options: ["行きます", "来ます", "あります", "います"],
    explanation: "「Ｎへ行きます」表示前往某地，「会社へ行きます」＝去公司。「来ます」是『來』、方向相反；「あります」是無生命物的存在；「います」是有生命物的存在。朝目的地前往唯「行きます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-kuru-tomodachi-ie",
    level: "N5",
    surface: "来る",
    reading: "くる",
    meaningZh: "來",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あした、ともだちが わたしの 家へ ___ 。",
    promptContextZh: "明天朋友會來我家。",
    hintZh: "對方朝著「我家」這邊移動過來的動作。",
    expectedAnswer: "来ます",
    options: ["来ます", "行きます", "食べます", "見ます"],
    explanation: "朋友朝著「わたしの家」這邊移動，用「来ます」＝來。「行きます」是離開說話者方向的『去』、與『來我家』矛盾；「食べます」是吃；「見ます」是看。朝說話者方向移動唯「来ます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-miru-terebi",
    level: "N5",
    surface: "見る",
    reading: "みる",
    meaningZh: "看",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "毎晩、うちで テレビを ___ 。",
    promptContextZh: "每天晚上在家看電視。",
    hintZh: "用眼睛接收電視畫面的動作。",
    expectedAnswer: "見ます",
    options: ["見ます", "聞きます", "話します", "行きます"],
    explanation: "電視以畫面為主，用眼睛接收，搭配「見ます」＝看。「聞きます」是用耳朵『聽』、對象是聲音；「話します」是說；「行きます」是去。看電視唯「見ます」最自然。"
  }),
  examQuestion({
    id: "n5-vocab-ookii-kaban",
    level: "N5",
    surface: "大きい",
    reading: "おおきい",
    meaningZh: "大的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この かばんは たくさん 入るので、とても ___ です。",
    promptContextZh: "這個包包能裝很多東西，所以非常大。",
    hintZh: "因為能裝很多東西，所以對它尺寸的形容。",
    expectedAnswer: "大きい",
    options: ["大きい", "小さい", "新しい", "高い"],
    explanation: "「たくさん入る（裝得多）」對應尺寸大，用「大きい」＝大的。「小さい」是小、與裝得多矛盾；「新しい」是新舊、與容量無關；「高い」是貴/高、與裝得多無關。形容容量大唯「大きい」成立。"
  }),
  examQuestion({
    id: "n5-vocab-jikan-nai",
    level: "N5",
    surface: "時間",
    reading: "じかん",
    meaningZh: "時間",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "いそがしくて、昼ごはんを 食べる ___ が ありません。",
    promptContextZh: "太忙了，沒有吃午餐的空檔。",
    hintZh: "因為忙碌而抽不出來、用來做某事的那段空檔。",
    expectedAnswer: "時間",
    options: ["時間", "お金", "ところ", "ことば"],
    explanation: "「忙碌到沒有做某事的～」指的是時段，用「時間」＝時間，「食べる時間がありません」＝沒有吃的時間。「お金」是錢、與忙碌無關；「ところ」是地點；「ことば」是話語。表抽不出的時段唯「時間」成立。"
  }),
  examQuestion({
    id: "n5-kanji-sensei",
    level: "N5",
    surface: "先生",
    reading: "せんせい",
    meaningZh: "老師",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "山田「先生」は とても やさしいです。",
    promptContextZh: "山田老師非常親切。",
    expectedAnswer: "せんせい",
    options: ["せんせい", "せんせ", "ぜんせい", "せいせい"],
    explanation: "「先」讀「せん」、「生」在此讀長音「せい」，故「先生」＝せんせい。「せんせ」漏掉長音；「ぜんせい」把「先」誤濁音化成「ぜん」；「せいせい」把「先」誤讀成「せい」。",
    exampleJapanese: "山田先生は とても やさしいです。",
    exampleMeaningZh: "山田老師非常親切。"
  }),
  examQuestion({
    id: "n5-kanji-mainichi",
    level: "N5",
    surface: "毎日",
    reading: "まいにち",
    meaningZh: "每天",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "わたしは「毎日」コーヒーを のみます。",
    promptContextZh: "我每天喝咖啡。",
    expectedAnswer: "まいにち",
    options: ["まいにち", "めいにち", "まいひ", "まいにつ"],
    explanation: "「毎」讀「まい」、「日」在此讀「にち」，故「毎日」＝まいにち。「めいにち」把「毎」誤讀成「めい」（那是「命日」的讀音）；「まいひ」把「日」讀成訓讀「ひ」；「まいにつ」把「にち」誤讀成促音「につ」。",
    exampleJapanese: "わたしは 毎日 コーヒーを のみます。",
    exampleMeaningZh: "我每天喝咖啡。"
  }),
  examQuestion({
    id: "n5-kanji-taberu",
    level: "N5",
    surface: "食べる",
    reading: "たべる",
    meaningZh: "吃",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あさ、くだものを「食べます」。",
    promptContextZh: "早上吃水果。",
    expectedAnswer: "たべます",
    options: ["たべます", "だべます", "たへます", "ためます"],
    explanation: "「食」訓讀「た」、送りがな「べます」，故「食べます」＝たべます。「だべます」把「た」誤濁音成「だ」；「たへます」沒把「べ」讀濁音；「ためます」把「べ」誤讀成「め」。",
    exampleJapanese: "あさ、くだものを 食べます。",
    exampleMeaningZh: "早上吃水果。"
  }),
  examQuestion({
    id: "n5-grammar-kara-atama-itai",
    level: "N5",
    surface: "から",
    reading: "から",
    meaningZh: "因為（原因）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あたまが いたい ___、きょうは 休みます。",
    promptContextZh: "因為頭痛，所以今天請假。",
    hintZh: "前半說明狀況、後半說明因此採取的行動，連接兩者的字。",
    expectedAnswer: "から",
    options: ["から", "まで", "より", "だけ"],
    explanation: "「ＡからＢ」用「から」表示原因理由，「あたまがいたいから休みます」＝因為頭痛所以請假。「まで」是「到…為止」（範圍終點）、此處非範圍；「より」是「比…」（比較基準）、句中無比較對象；「だけ」是「只…」（限定）、與因果無關。表原因唯「から」成立。"
  }),
  examQuestion({
    id: "n5-grammar-made-kuji-hataraku",
    level: "N5",
    surface: "まで",
    reading: "まで",
    meaningZh: "到…為止（範圍終點）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "けさは 八時から 九時 ___ はたらきました。",
    promptContextZh: "今天早上從八點工作到九點。",
    hintZh: "標示「工作」這個動作一直持續到的那個終點時刻。",
    expectedAnswer: "まで",
    options: ["まで", "から", "より", "だけ"],
    explanation: "「Ｎまで」表示動作持續到的終點。句中已有起點「八時から」，第二格填「まで」構成「八時から九時まで」＝從八點到九點。「から」是起點、句中起點已是八時、再填會重複矛盾；「より」是「比…」、句中無比較；「だけ」是「只…」、非範圍終點。表終點唯「まで」成立。"
  }),
  examQuestion({
    id: "n5-grammar-yori-densha-hayai",
    level: "N5",
    surface: "より",
    reading: "より",
    meaningZh: "比…（比較基準）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "でんしゃは バス ___ はやいです。",
    promptContextZh: "電車比公車快。",
    hintZh: "兩種交通工具相比時，標示被當作比較對象的那一方。",
    expectedAnswer: "より",
    options: ["より", "まで", "から", "だけ"],
    explanation: "「ＡはＢより〜」用「より」標示比較的基準，「バスよりはやい」＝比公車快。「まで」是「到…為止」（範圍）、此處非範圍；「から」是「從…」（起點）、句中非起點；「だけ」是「只…」（限定）、與比較無關。「はやいです」的比較對象唯「より」成立。"
  }),
  examQuestion({
    id: "n5-grammar-dake-mizu-nomu",
    level: "N5",
    surface: "だけ",
    reading: "だけ",
    meaningZh: "只…（限定）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "あさは なにも 食べないで、お水 ___ 飲みます。",
    promptContextZh: "早上什麼都不吃，只喝水。",
    hintZh: "前半說「什麼都不吃」，後半把範圍縮到單一一項時用的字。",
    expectedAnswer: "だけ",
    options: ["だけ", "まで", "から", "より"],
    explanation: "「Ｎだけ」用「だけ」表示限定『只有…』，呼應前半「なにも食べないで」，「お水だけ飲みます」＝只喝水。「まで」是「到…為止」（範圍終點）；「から」是「從…」（起點）；「より」是「比…」（比較）。限定單一項目唯「だけ」成立。"
  }),
  examQuestion({
    id: "n5-grammar-nodesuka-naze-yasumu",
    level: "N5",
    surface: "のですか",
    reading: "のですか",
    meaningZh: "（詢問緣由）是…嗎？",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "かおいろが わるいですね。どこか いたい ___ 。",
    promptContextZh: "你臉色不好耶。是哪裡不舒服嗎？",
    hintZh: "看見對方臉色不好、想關心地追問緣由時的句尾說法。",
    expectedAnswer: "のですか",
    options: ["のですか", "ましょう", "ませんか", "でしょう"],
    explanation: "「い形容詞＋のですか」用來追問眼前情況的緣由，「いたいのですか」＝是哪裡不舒服嗎。「ましょう」是邀約/提議『一起…吧』、無法接い形容詞也非詢問；「ませんか」是邀約『要不要…』、語意不合；「でしょう」是推測『…吧』、不是針對眼前狀況的詢問。關心追問緣由唯「のですか」成立。"
  }),
  examQuestion({
    id: "n5-grammar-ne-tenki-ii",
    level: "N5",
    surface: "ね",
    reading: "ね",
    meaningZh: "…呢（尋求認同）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "きょうは いい てんきです ___ 。「ええ、そうですね。」",
    promptContextZh: "今天天氣真好呢。「嗯，是啊。」",
    hintZh: "後句對方回「是啊」，提示前句正向對方尋求同感的句尾語氣。",
    expectedAnswer: "ね",
    options: ["ね", "よ", "か", "の"],
    explanation: "終助詞「ね」向對方尋求同感、確認共識，後句「そうですね」正是附和，「いいてんきですね」＝天氣真好呢。「よ」是把新資訊告知對方（單向通知）、與徵求同感不同；「か」是疑問、但後句並非回答是非；「の」此處接「です」後不自然。尋求同感且對方附和，唯「ね」成立。"
  }),
  examQuestion({
    id: "n5-grammar-yo-densha-kuru",
    level: "N5",
    surface: "よ",
    reading: "よ",
    meaningZh: "…喔（告知對方）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "「電車が 来ました ___ 。はやく のりましょう。」",
    promptContextZh: "「電車來了喔。快點上車吧。」",
    hintZh: "把對方還沒注意到的事情、要他留意的句尾語氣。",
    expectedAnswer: "よ",
    options: ["よ", "ね", "か", "を"],
    explanation: "終助詞「よ」用來把對方還沒注意到的新資訊告知、提醒，呼應後句「はやくのりましょう」，「来ましたよ」＝電車來了喔。「ね」是尋求同感、但對方尚未察覺無從附和；「か」是疑問、此處是告知非提問；「を」是受詞助詞、不能放句尾。提醒告知唯「よ」成立。"
  }),
  examQuestion({
    id: "n5-grammar-mashou-issho-kaeru",
    level: "N5",
    surface: "ましょう",
    reading: "ましょう",
    meaningZh: "一起…吧（提議）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "もう おそいです。いっしょに 帰り ___ 。",
    promptContextZh: "已經很晚了。一起回去吧。",
    hintZh: "句中的「いっしょに」提示正在邀雙方一同行動的句尾說法。",
    expectedAnswer: "ましょう",
    options: ["ましょう", "ました", "ません", "たいです"],
    explanation: "「Ｖましょう」表示提議一起做某事，搭配「いっしょに」很自然，「帰りましょう」＝一起回去吧。「ました」是過去陳述；「ません」是否定；「たいです」是說自己想做、不是提議邀對方。提議共同行動唯「ましょう」成立。"
  }),
  examQuestion({
    id: "n5-grammar-tekara-te-arau-taberu",
    level: "N5",
    surface: "てから",
    reading: "てから",
    meaningZh: "做完…之後（再）",
    promptLabel: "文法形式選擇",
    instructionZh: "句中填空：依文脈選最自然的文法。",
    promptText: "うちに かえって 手を あらっ ___ 、ごはんを 食べます。",
    promptContextZh: "回家洗手，洗完之後再吃飯。",
    hintZh: "強調前一個動作結束後、緊接著才做下一個動作的接續說法。",
    expectedAnswer: "てから",
    options: ["てから", "ながら", "たり", "ないで"],
    explanation: "「Ｖてから」表示『做完前項之後再做後項』、有先後順序，「あらってから食べます」＝洗完手再吃。「ながら」是『一邊…一邊…』（同時並行）、洗手和吃不會同時；「たり」需「〜たり〜たり」並列形式、句中只有一個動作；「ないで」是『不做…就…』、與『洗完再吃』相反。表先後順序唯「てから」成立。"
  }),
  examQuestion({
    id: "n5-vocab-kaku-tegami",
    level: "N5",
    surface: "書く",
    reading: "かく",
    meaningZh: "寫",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "ペンで ノートに なまえを ___ 。",
    promptContextZh: "用筆在筆記本上寫名字。",
    hintZh: "拿著筆、把名字記在紙上的動作。",
    expectedAnswer: "書きます",
    options: ["書きます", "読みます", "話します", "聞きます"],
    explanation: "「ペンで…なまえを書きます」＝用筆寫名字，用筆記下文字用「書きます」。「読みます」是『讀』、是看文字不是寫；「話します」是『說』、是出聲不是寫；「聞きます」是『聽/問』。用筆記下文字唯「書きます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-okiru-rokuji",
    level: "N5",
    surface: "起きる",
    reading: "おきる",
    meaningZh: "起床",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "まいあさ 六時に ___、かおを あらいます。",
    promptContextZh: "每天早上六點起床，然後洗臉。",
    hintZh: "早上睡醒、離開被窩開始一天的動作。",
    expectedAnswer: "起きます",
    options: ["起きます", "ねます", "やすみます", "かえります"],
    explanation: "「六時に起きて、かおをあらいます」＝六點起床洗臉，早上睡醒離開被窩用「起きます」。「ねます」是『睡覺』、與早上開始活動相反；「やすみます」是『休息/請假』；「かえります」是『回去』。早上睡醒展開一天唯「起きます」成立。"
  }),
  examQuestion({
    id: "n5-vocab-yasui-mise",
    level: "N5",
    surface: "安い",
    reading: "やすい",
    meaningZh: "便宜的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "この みせの やさいは ___ ので、よく かいます。",
    promptContextZh: "這家店的蔬菜很便宜，所以我常買。",
    hintZh: "因為價錢不高、所以願意常去買，對價格的形容。",
    expectedAnswer: "安い",
    options: ["安い", "たかい", "おおい", "とおい"],
    explanation: "「安いので、よくかいます」＝因為便宜所以常買，價錢不高用「安い」。「たかい」是『貴』、貴的話通常不會『常買』、與文脈矛盾；「おおい」是『多』、形容數量不是價格；「とおい」是『遠』、形容距離。形容價格低唯「安い」成立。"
  }),
  examQuestion({
    id: "n5-vocab-atarashii-kaban",
    level: "N5",
    surface: "新しい",
    reading: "あたらしい",
    meaningZh: "新的",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "きのう かばんを かいました。とても ___ かばんです。",
    promptContextZh: "昨天買了包包。是個很新的包包。",
    hintZh: "因為昨天才剛買來、還沒用過，對它的形容。",
    expectedAnswer: "新しい",
    options: ["新しい", "ふるい", "おもい", "ながい"],
    explanation: "「きのう かいました…新しいかばん」＝昨天剛買的新包包，剛買來沒用過用「新しい」。「ふるい」是『舊』、與昨天才買矛盾；「おもい」是『重』、形容重量；「ながい」是『長』、形容長度。剛買的全新物品唯「新しい」成立。"
  }),
  examQuestion({
    id: "n5-vocab-tenki-ame",
    level: "N5",
    surface: "天気",
    reading: "てんき",
    meaningZh: "天氣",
    promptLabel: "詞彙填空",
    instructionZh: "句中填空：選最自然的詞語。",
    promptText: "あしたの ___ は あめだと テレビで 言って いました。",
    promptContextZh: "電視上說明天的天氣是雨。",
    hintZh: "電視預報所講的、明天會晴或會雨的那種狀況。",
    expectedAnswer: "天気",
    options: ["天気", "げんき", "びょうき", "でんき"],
    explanation: "「あしたの天気はあめ」＝明天的天氣是雨，晴雨等大氣狀況用「天気」。「げんき」是『精神/健康』；「びょうき」是『生病』；「でんき」是『電/電燈』。雖讀音相近，但講晴雨狀況唯「天気」成立。"
  }),
  examQuestion({
    id: "n5-kanji-mizu",
    level: "N5",
    surface: "水",
    reading: "みず",
    meaningZh: "水",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あついので、つめたい「水」を のみます。",
    promptContextZh: "因為很熱，所以喝冰涼的水。",
    expectedAnswer: "みず",
    options: ["みず", "みす", "すい", "みづ"],
    explanation: "「水」單獨當名詞時用訓讀「みず」。「みす」漏掉濁音（ず→す）；「すい」是音讀（用於「水曜日」等複合詞）、單獨的『水』不這樣讀；「みづ」是歷史假名遣的舊寫法、現代標準寫作「みず」。此處單獨名詞唯「みず」成立。",
    exampleJapanese: "あついので、つめたい水を のみます。",
    exampleMeaningZh: "因為很熱，所以喝冰涼的水。"
  }),
  examQuestion({
    id: "n5-kanji-tomodachi",
    level: "N5",
    surface: "友達",
    reading: "ともだち",
    meaningZh: "朋友",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "あした「友達」と こうえんで あそびます。",
    promptContextZh: "明天和朋友在公園玩。",
    expectedAnswer: "ともだち",
    options: ["ともだち", "ともたち", "ゆうだち", "とまだち"],
    explanation: "「友」訓讀「とも」、「達」在此讀濁音「だち」，故「友達」＝ともだち。「ともたち」沒把「達」讀濁音（たち→應為だち）；「ゆうだち」把「友」誤用音讀「ゆう」（且 ゆうだち＝夕立、午後雷陣雨）；「とまだち」把「とも」誤讀成「とま」。此處唯「ともだち」成立。",
    exampleJapanese: "あした友達と こうえんで あそびます。",
    exampleMeaningZh: "明天和朋友在公園玩。"
  }),
  examQuestion({
    id: "n5-kanji-yasumu",
    level: "N5",
    surface: "休む",
    reading: "やすむ",
    meaningZh: "休息、請假",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "かぜを ひいたので、きょうは かいしゃを「休みます」。",
    promptContextZh: "因為感冒了，今天向公司請假。",
    expectedAnswer: "やすみます",
    options: ["やすみます", "やしみます", "きゅうみます", "やすめます"],
    explanation: "「休」訓讀「やす」、送りがな「みます」，故「休みます」＝やすみます。「やしみます」把「やす」誤讀成「やし」；「きゅうみます」把「休」誤用音讀「きゅう」（用於「休日」等複合詞）；「やすめます」是可能形/別的活用、與辭書形「休む」的ます形不符。此處唯「やすみます」成立。",
    exampleJapanese: "かぜを ひいたので、きょうは かいしゃを 休みます。",
    exampleMeaningZh: "因為感冒了，今天向公司請假。"
  }),
  examQuestion({
    id: "n5-kanji-ame",
    level: "N5",
    surface: "雨",
    reading: "あめ",
    meaningZh: "雨",
    promptLabel: "漢字読み",
    instructionZh: "選出底線詞語的正確讀音。",
    promptText: "そとは「雨」なので、かさを もって いきます。",
    promptContextZh: "外面在下雨，所以帶傘出門。",
    expectedAnswer: "あめ",
    options: ["あめ", "あま", "う", "あね"],
    explanation: "「雨」單獨當名詞時用訓讀「あめ」。「あま」是複合詞時的讀法（如「雨水＝あまみず」）、單獨的『雨』不這樣讀；「う」是音讀（用於「雨天」等）、此處非複合詞；「あね」與「雨」無關（あね＝姉、姊姊）。此處單獨名詞唯「あめ」成立。",
    exampleJapanese: "そとは雨なので、かさを もって いきます。",
    exampleMeaningZh: "外面在下雨，所以帶傘出門。"
  }),
  examQuestion({
    id: "n5-syn-takusan",
    level: "N5",
    surface: "たくさん",
    reading: "たくさん",
    meaningZh: "很多",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "日曜日、こうえんに 子どもが 「たくさん」 いました。",
    promptContextZh: "星期天，公園裡有很多小孩。",
    hintZh: "數量上不算少，到了有許多的程度。",
    expectedAnswer: "いっぱい",
    options: ["いっぱい", "すこし", "ぜんぜん", "ときどき"],
    explanation: "「たくさん」表示數量多，本句「公園裡有很多小孩」用「いっぱい」（滿滿、很多）替換後語意相同。「すこし」是『一點點』（量少，相反）；「ぜんぜん」是『完全（不）』（用於否定）；「ときどき」是『有時』（頻率，不是數量）。表數量多唯「いっぱい」與「たくさん」同義。",
    exampleJapanese: "日曜日、こうえんに 子どもが いっぱい いました。",
    exampleMeaningZh: "星期天，公園裡有很多小孩。"
  }),
  examQuestion({
    id: "n5-syn-totemo",
    level: "N5",
    surface: "とても",
    reading: "とても",
    meaningZh: "非常",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "この 本は 「とても」 おもしろいです。",
    promptContextZh: "這本書非常有趣。",
    hintZh: "表示程度很高，不是普通的那種等級。",
    expectedAnswer: "たいへん",
    options: ["たいへん", "あまり", "すこし", "だんだん"],
    explanation: "「とても」修飾形容詞、表示程度很高，本句「這本書非常有趣」用副詞「たいへん」（非常）替換後語意相同。「あまり」是『不太』（用於否定，程度低）；「すこし」是『稍微』（程度低）；「だんだん」是『漸漸』（表變化，不是程度）。表程度高唯「たいへん」與「とても」同義。",
    exampleJapanese: "この 本は たいへん おもしろいです。",
    exampleMeaningZh: "這本書非常有趣。"
  }),
  examQuestion({
    id: "n5-syn-tokidoki",
    level: "N5",
    surface: "ときどき",
    reading: "ときどき",
    meaningZh: "有時、偶爾",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "わたしは 「ときどき」 きっさてんで コーヒーを 飲みます。",
    promptContextZh: "我有時會在咖啡店喝咖啡。",
    hintZh: "次數不多，要隔一段時間才會發生一次。",
    expectedAnswer: "たまに",
    options: ["たまに", "いつも", "すぐに", "だんだん"],
    explanation: "「ときどき」表示頻率不高的「有時」，本句用「たまに」（偶爾）替換後語意相同。「いつも」是『總是』（頻率最高，相反）；「すぐに」是『馬上』（表時間快，不是頻率）；「だんだん」是『漸漸』（表變化）。表頻率中低唯「たまに」與「ときどき」同義。",
    exampleJapanese: "わたしは たまに きっさてんで コーヒーを 飲みます。",
    exampleMeaningZh: "我有時會在咖啡店喝咖啡。"
  }),
  examQuestion({
    id: "n5-syn-kyonen",
    level: "N5",
    surface: "きょねん",
    reading: "きょねん",
    meaningZh: "去年",
    promptLabel: "類義替換",
    instructionZh: "選與「」中詞語意思最接近的選項。",
    promptText: "わたしは 「きょねん」 日本へ 行きました。",
    promptContextZh: "我去年去了日本。",
    hintZh: "指現在這一年的前一年。",
    expectedAnswer: "さくねん",
    options: ["さくねん", "らいねん", "ことし", "まいとし"],
    explanation: "「きょねん」與「さくねん」都指『去年』，是同義詞，替換後語意完全相同。「らいねん」是『明年』（還沒到，相反方向）；「ことし」是『今年』（現在這一年）；「まいとし」是『每年』（表頻率，不是特定一年）。指前一年唯「さくねん」與「きょねん」同義。",
    exampleJapanese: "わたしは さくねん 日本へ 行きました。",
    exampleMeaningZh: "我去年去了日本。"
  }),
  examQuestion({
    id: "n5-usage-arau",
    level: "N5",
    surface: "洗う",
    reading: "あらう",
    meaningZh: "洗",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「洗う」の使い方が最も適切なものはどれか。",
    promptContextZh: "「洗う」是用水把東西弄乾淨。",
    hintZh: "用水把髒的地方弄到乾淨。",
    expectedAnswer: "まいあさ おきてから、かおを 洗います。",
    options: ["まいあさ おきてから、かおを 洗います。", "こわれた とけいを、みせの 人が 洗いました。", "へやが くらいので、でんきを 洗って ください。", "えきで ともだちを 洗って、いっしょに 帰りました。"],
    explanation: "「洗う」是用水把東西弄乾淨，本句「每天早上起床後洗臉」最自然。修理壞掉的時鐘要用「直す」（直しました）；開電燈要用「つける」；和朋友碰面要用「会う」。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "まいあさ おきてから、かおを 洗います。",
    exampleMeaningZh: "每天早上起床後洗臉。"
  }),
  examQuestion({
    id: "n5-usage-samui",
    level: "N5",
    surface: "寒い",
    reading: "さむい",
    meaningZh: "（天氣）冷、寒冷",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「寒い」の使い方が最も適切なものはどれか。",
    promptContextZh: "「寒い」用來形容氣溫低、身體覺得冷。",
    hintZh: "氣溫低、身體覺得不暖和的狀態。",
    expectedAnswer: "ふゆは ゆきが ふって、とても 寒いです。",
    options: ["ふゆは ゆきが ふって、とても 寒いです。", "この 水は 寒いので、手が つめたく なりました。", "この みせは 人が おおくて、とても 寒いです。", "この スープは 寒いので、あたためて ください。"],
    explanation: "「寒い」用來形容氣溫低、身體覺得冷的環境，本句「冬天下雪，非常冷」最自然。摸到的水或湯要用「つめたい」（つめたい水／つめたいスープ）；店裡人多應該用「にぎやか」，不會用「寒い」形容。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "ふゆは ゆきが ふって、とても 寒いです。",
    exampleMeaningZh: "冬天下雪，非常冷。"
  }),
  examQuestion({
    id: "n5-usage-oyogu",
    level: "N5",
    surface: "泳ぐ",
    reading: "およぐ",
    meaningZh: "游泳",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「泳ぐ」の使い方が最も適切なものはどれか。",
    promptContextZh: "「泳ぐ」是在水裡前進。",
    hintZh: "在水裡用手腳前進。",
    expectedAnswer: "なつに うみで 泳ぐのが すきです。",
    options: ["なつに うみで 泳ぐのが すきです。", "あさ、でんしゃで かいしゃまで 泳ぎます。", "おなかが すいたので、ごはんを 泳ぎます。", "よる、いえで テレビを 泳ぎます。"],
    explanation: "「泳ぐ」是在水裡前進，本句「喜歡夏天在海裡游泳」最自然。搭電車去公司要用「行く」；吃飯要用「食べる」；看電視要用「見る」。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "なつに うみで 泳ぐのが すきです。",
    exampleMeaningZh: "喜歡夏天在海裡游泳。"
  }),
  examQuestion({
    id: "n5-usage-kasu",
    level: "N5",
    surface: "貸す",
    reading: "かす",
    meaningZh: "借出、出借",
    promptLabel: "詞彙用法",
    instructionZh: "選出該詞語使用最自然的句子。",
    promptText: "次の文のうち、「貸す」の使い方が最も適切なものはどれか。",
    promptContextZh: "「貸す」是把自己的東西讓給別人用。",
    hintZh: "把自己的東西暫時讓別人使用。",
    expectedAnswer: "ペンを わすれた ともだちに、ペンを 貸しました。",
    options: ["ペンを わすれた ともだちに、ペンを 貸しました。", "としょかんで おもしろい 本を 貸しました。", "やおやで やさいを たくさん 貸しました。", "おもい にもつを、二かいまで 貸しました。"],
    explanation: "「貸す」是把自己的東西讓給別人用（東西從自己流向對方），本句「把筆借給忘記帶筆的朋友」方向正確、最自然。在圖書館取得書是『借入』，要用「借りる」；在蔬果店取得蔬菜要用「買う」；把行李搬到二樓要用「運ぶ」。後三句搭配皆不通，唯第一句成立。",
    exampleJapanese: "ペンを わすれた ともだちに、ペンを 貸しました。",
    exampleMeaningZh: "把筆借給忘記帶筆的朋友。"
  }),
  examQuestion({
    id: "n5-context-soshite",
    level: "N5",
    surface: "そして",
    reading: "そして",
    meaningZh: "而且、然後",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "この みせの ケーキは おいしいです。 ___ 、ねだんも 安いです。",
    promptContextZh: "這家店的蛋糕很好吃。而且價錢也便宜。",
    hintZh: "在前面內容之外，再加上一個同方向的優點。",
    expectedAnswer: "そして",
    options: ["そして", "でも", "だから", "それとも"],
    explanation: "前句「好吃」與後句「便宜」都是優點、方向相同，後句再追加一項，用表並列追加的「そして」（而且）。「でも」是逆接『可是』（好吃與便宜不相反）；「だから」是因果『所以』（『所以便宜』不合邏輯）；「それとも」是選擇『還是』。表同方向追加唯「そして」成立。",
    exampleJapanese: "この みせの ケーキは おいしいです。そして、ねだんも 安いです。",
    exampleMeaningZh: "這家店的蛋糕很好吃。而且價錢也便宜。"
  }),
  examQuestion({
    id: "n5-context-sorekara",
    level: "N5",
    surface: "それから",
    reading: "それから",
    meaningZh: "接著、然後",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "あさ おきて、かおを あらいました。 ___ 、あさごはんを 食べました。",
    promptContextZh: "早上起床洗了臉。接著吃了早餐。",
    hintZh: "前一件事做完，緊跟著做下一件事。",
    expectedAnswer: "それから",
    options: ["それから", "しかし", "だから", "それとも"],
    explanation: "前句「洗臉」與後句「吃早餐」是依時間先後發生的兩個動作，用表時間順序的「それから」（接著、然後）。「しかし」是逆接『可是』（前後不相反）；「だから」是因果『所以』（『所以吃早餐』不自然）；「それとも」是選擇『還是』。表時間先後唯「それから」成立。",
    exampleJapanese: "あさ おきて、かおを あらいました。それから、あさごはんを 食べました。",
    exampleMeaningZh: "早上起床洗了臉。接著吃了早餐。"
  }),
  examQuestion({
    id: "n5-context-shikashi",
    level: "N5",
    surface: "しかし",
    reading: "しかし",
    meaningZh: "但是、可是",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "きのうは いい てんきでした。 ___ 、きょうは あさから 雨です。",
    promptContextZh: "昨天是好天氣。但是今天從早上就下雨。",
    hintZh: "後句出現和前句預料相反的情況。",
    expectedAnswer: "しかし",
    options: ["しかし", "だから", "そして", "それから"],
    explanation: "前句「昨天好天氣」讓人期待今天也好，後句卻是「下雨」，前後相反，用逆接的「しかし」（但是）。「だから」是因果『所以』（『所以下雨』邏輯矛盾）；「そして」是並列『而且』（無法表轉折）；「それから」是時間先後『接著』（前後不是順接）。表逆接唯「しかし」成立。",
    exampleJapanese: "きのうは いい てんきでした。しかし、きょうは あさから 雨です。",
    exampleMeaningZh: "昨天是好天氣。但是今天從早上就下雨。"
  }),
  examQuestion({
    id: "n5-context-soretomo",
    level: "N5",
    surface: "それとも",
    reading: "それとも",
    meaningZh: "或者、還是",
    promptLabel: "文章脈絡",
    instructionZh: "短文脈絡：選能讓文章流向自然的接續表現。",
    promptText: "のみものは コーヒーが いいですか。 ___ 、おちゃが いいですか。",
    promptContextZh: "飲料要咖啡好呢？還是茶好呢？",
    hintZh: "在兩件事之間，問對方要挑哪一個。",
    expectedAnswer: "それとも",
    options: ["それとも", "そして", "だから", "しかし"],
    explanation: "前後是「咖啡」與「茶」兩個選項，句子在問對方要二擇一，用表選擇的「それとも」（還是）。「そして」是並列『而且』（不是二擇一）；「だから」是因果『所以』（句中無因果）；「しかし」是逆接『可是』（兩者非相反對立）。表二選一的疑問唯「それとも」成立。",
    exampleJapanese: "のみものは コーヒーが いいですか。それとも、おちゃが いいですか。",
    exampleMeaningZh: "飲料要咖啡好呢？還是茶好呢？"
  })
];
